import { CREDENTIAL_MESSAGES, type CredentialMessageId, type CredentialTokenHint } from './credential-token.js';

/** Shared Tovu copy for server cards and admin hooks, covering every offered admin locale. */
export const CREDENTIAL_COPY = {
  "es": {
    "showSecret": "Mostrar",
    "hideSecret": "Ocultar",

    "generationUnavailable": "La generación aún no está disponible para este proveedor.",
    "secretValue": "Valor secreto",
    "saveSecret": "Guardar secreto",
    "cancel": "Cancelar",
    "secretForm": "Introduce el valor en este formulario seguro.",

    "blank": "Introduce un token. Los espacios solos no son un token.",
    "limit": "El token supera el límite de 8192 caracteres. Copia solo el token.",
    "ascii": "Los tokens alojados deben usar caracteres ASCII visibles (0x21–0x7E).",
    "control": "El token contiene un carácter de control no válido.",
    "plain": "Introduce las credenciales en el campo secreto, no en este campo.",
    "saved": "Guardado, sin probar.",
    "connected": "Conectado.",
    "auth": "El servidor rechazó este token.",
    "timeout": "La conexión agotó el tiempo de espera.",
    "unreachable": "No se pudo contactar con el servidor.",
    "chars": "{length} caracteres",
    "env": "Introduce variables de entorno como líneas NAME=VALUE o un objeto JSON de cadenas.",
    "url": "La URL del servidor debe ser una URL absoluta válida.",
    "set": "Token de acceso guardado",
    "storage": "No se pudo guardar o desbloquear la credencial. Revisa el almacén de credenciales del sitio.",
    "savedTitle": "Guardado."
  },
  "id": {
    "showSecret": "Tampilkan",
    "hideSecret": "Sembunyikan",

    "generationUnavailable": "Pembuatan belum tersedia untuk penyedia ini.",
    "secretValue": "Nilai rahasia",
    "saveSecret": "Simpan rahasia",
    "cancel": "Batal",
    "secretForm": "Masukkan nilainya di formulir aman ini.",

    "blank": "Masukkan token. Spasi saja bukan token.",
    "limit": "Token melebihi batas 8192 karakter. Salin hanya token.",
    "ascii": "Token hosted harus memakai karakter ASCII terlihat (0x21–0x7E).",
    "control": "Token berisi karakter kontrol tidak valid.",
    "plain": "Masukkan kredensial di kolom rahasia, bukan di kolom ini.",
    "saved": "Disimpan, belum diuji.",
    "connected": "Terhubung.",
    "auth": "Server menolak token ini.",
    "timeout": "Koneksi kehabisan waktu.",
    "unreachable": "Tidak dapat menghubungi server.",
    "chars": "{length} karakter",
    "env": "Masukkan variabel lingkungan sebagai baris NAME=VALUE atau objek JSON berisi string.",
    "url": "URL server harus berupa URL absolut yang valid.",
    "set": "Token akses tersimpan",
    "storage": "Kredensial tidak dapat disimpan atau dibuka. Periksa penyimpanan kredensial situs.",
    "savedTitle": "Disimpan."
  },
  "de": {
    "showSecret": "Anzeigen",
    "hideSecret": "Ausblenden",

    "generationUnavailable": "Generierung ist für diesen Anbieter noch nicht verfügbar.",
    "secretValue": "Geheimer Wert",
    "saveSecret": "Geheimnis speichern",
    "cancel": "Abbrechen",
    "secretForm": "Gib den Wert in dieses sichere Formular ein.",

    "blank": "Gib ein Token ein. Nur Leerzeichen sind kein Token.",
    "limit": "Das Token überschreitet die Grenze von 8192 Zeichen. Kopiere nur das Token.",
    "ascii": "Gehostete Tokens müssen sichtbare ASCII-Zeichen verwenden (0x21–0x7E).",
    "control": "Das Token enthält ein ungültiges Steuerzeichen.",
    "plain": "Trage Zugangsdaten in das geheime Feld ein, nicht in dieses Feld.",
    "saved": "Gespeichert, nicht getestet.",
    "connected": "Verbunden.",
    "auth": "Der Server hat dieses Token abgelehnt.",
    "timeout": "Zeitüberschreitung der Verbindung.",
    "unreachable": "Der Server ist nicht erreichbar.",
    "chars": "{length} Zeichen",
    "env": "Gib Umgebungsvariablen als NAME=VALUE-Zeilen oder JSON-Objekt mit Zeichenfolgen ein.",
    "url": "Die Server-URL muss eine gültige absolute URL sein.",
    "set": "Zugriffstoken gespeichert",
    "storage": "Die Zugangsdaten konnten nicht gespeichert oder entsperrt werden. Prüfe den Zugangsdaten-Speicher der Website.",
    "savedTitle": "Gespeichert."
  },
  "zh-CN": {
    "showSecret": "显示",
    "hideSecret": "隐藏",

    "generationUnavailable": "此提供商暂不支持生成。",
    "secretValue": "密钥值",
    "saveSecret": "保存密钥",
    "cancel": "取消",
    "secretForm": "请在此安全表单中输入值。",

    "blank": "请输入令牌。只有空白不算令牌。",
    "limit": "令牌超过8192字符限制。请仅复制令牌。",
    "ascii": "托管令牌必须使用可见ASCII字符（0x21–0x7E）。",
    "control": "令牌包含无效控制字符。",
    "plain": "请将凭据填入秘密字段，而非此字段。",
    "saved": "已保存，未测试。",
    "connected": "已连接。",
    "auth": "服务器拒绝了此令牌。",
    "timeout": "连接超时。",
    "unreachable": "无法连接服务器。",
    "chars": "{length} 字符",
    "env": "请以NAME=VALUE行或字符串JSON对象输入环境变量。",
    "url": "服务器URL必须是有效的绝对URL。",
    "set": "已设置访问令牌",
    "storage": "无法保存或解锁凭据。请检查站点凭据存储。",
    "savedTitle": "已保存。"
  },
  "zh-TW": {
    "showSecret": "顯示",
    "hideSecret": "隱藏",

    "generationUnavailable": "此供應商尚不支援生成。",
    "secretValue": "密鑰值",
    "saveSecret": "儲存密鑰",
    "cancel": "取消",
    "secretForm": "請在此安全表單中輸入值。",

    "blank": "請輸入權杖。只有空白不算權杖。",
    "limit": "權杖超過8192字元限制。請僅複製權杖。",
    "ascii": "託管權杖必須使用可見ASCII字元（0x21–0x7E）。",
    "control": "權杖包含無效控制字元。",
    "plain": "請將憑證填入秘密欄位，而非此欄位。",
    "saved": "已儲存，未測試。",
    "connected": "已連線。",
    "auth": "伺服器拒絕了此權杖。",
    "timeout": "連線逾時。",
    "unreachable": "無法連線至伺服器。",
    "chars": "{length} 字元",
    "env": "請以NAME=VALUE行或字串JSON物件輸入環境變數。",
    "url": "伺服器URL必須是有效的絕對URL。",
    "set": "已設定存取權杖",
    "storage": "無法儲存或解鎖憑證。請檢查網站憑證儲存。",
    "savedTitle": "已儲存。"
  },
  "pt-BR": {
    "showSecret": "Mostrar",
    "hideSecret": "Ocultar",

    "generationUnavailable": "A geração ainda não está disponível para este provedor.",
    "secretValue": "Valor secreto",
    "saveSecret": "Salvar segredo",
    "cancel": "Cancelar",
    "secretForm": "Digite o valor neste formulário seguro.",

    "blank": "Insira um token. Apenas espaços não são um token.",
    "limit": "O token excede o limite de 8192 caracteres. Copie apenas o token.",
    "ascii": "Tokens hospedados devem usar caracteres ASCII visíveis (0x21–0x7E).",
    "control": "O token contém um caractere de controle inválido.",
    "plain": "Insira as credenciais no campo secreto, não neste campo.",
    "saved": "Salvo, não testado.",
    "connected": "Conectado.",
    "auth": "O servidor rejeitou este token.",
    "timeout": "A conexão excedeu o tempo limite.",
    "unreachable": "Não foi possível acessar o servidor.",
    "chars": "{length} caracteres",
    "env": "Insira variáveis de ambiente como linhas NAME=VALUE ou um objeto JSON de strings.",
    "url": "A URL do servidor deve ser uma URL absoluta válida.",
    "set": "Token de acesso salvo",
    "storage": "Não foi possível salvar ou desbloquear a credencial. Verifique o armazenamento de credenciais do site.",
    "savedTitle": "Salvo."
  },
  "ru": {
    "showSecret": "Показать",
    "hideSecret": "Скрыть",

    "generationUnavailable": "Генерация для этого провайдера пока недоступна.",
    "secretValue": "Секретное значение",
    "saveSecret": "Сохранить секрет",
    "cancel": "Отмена",
    "secretForm": "Введите значение в этой защищённой форме.",

    "blank": "Введите токен. Одни пробелы не являются токеном.",
    "limit": "Токен превышает лимит 8192 символа. Скопируйте только токен.",
    "ascii": "Токены удалённых серверов должны содержать видимые символы ASCII (0x21–0x7E).",
    "control": "Токен содержит недопустимый управляющий символ.",
    "plain": "Введите учётные данные в секретное поле, а не в это поле.",
    "saved": "Сохранено, не проверено.",
    "connected": "Подключено.",
    "auth": "Сервер отклонил этот токен.",
    "timeout": "Время ожидания подключения истекло.",
    "unreachable": "Не удалось связаться с сервером.",
    "chars": "{length} символов",
    "env": "Введите переменные окружения строками NAME=VALUE или JSON-объектом строк.",
    "url": "URL сервера должен быть допустимым абсолютным URL.",
    "set": "Токен доступа сохранён",
    "storage": "Не удалось сохранить или разблокировать учётные данные. Проверьте хранилище учётных данных сайта.",
    "savedTitle": "Сохранено."
  },
  "fa": {
    "showSecret": "نمایش",
    "hideSecret": "پنهان کردن",

    "generationUnavailable": "تولید برای این ارائه‌دهنده هنوز در دسترس نیست.",
    "secretValue": "مقدار محرمانه",
    "saveSecret": "ذخیره مقدار محرمانه",
    "cancel": "لغو",
    "secretForm": "مقدار را در این فرم امن وارد کنید.",

    "blank": "توکن را وارد کنید. فقط فاصله توکن نیست.",
    "limit": "توکن از محدودیت 8192 نویسه بیشتر است. فقط توکن را کپی کنید.",
    "ascii": "توکن میزبانی‌شده باید از نویسه‌های قابل مشاهده ASCII استفاده کند (0x21–0x7E).",
    "control": "توکن دارای نویسه کنترلی نامعتبر است.",
    "plain": "اطلاعات ورود را در فیلد محرمانه وارد کنید، نه این فیلد.",
    "saved": "ذخیره شد، آزمایش نشده است.",
    "connected": "متصل شد.",
    "auth": "سرور این توکن را رد کرد.",
    "timeout": "مهلت اتصال تمام شد.",
    "unreachable": "اتصال به سرور ممکن نشد.",
    "chars": "{length} نویسه",
    "env": "متغیرهای محیطی را به صورت خطوط NAME=VALUE یا شیء JSON از رشته‌ها وارد کنید.",
    "url": "نشانی سرور باید یک URL مطلق معتبر باشد.",
    "set": "توکن دسترسی تنظیم شد",
    "storage": "ذخیره یا باز کردن اعتبارنامه ممکن نشد. مخزن اعتبارنامه سایت را بررسی کنید.",
    "savedTitle": "ذخیره شد."
  },
  "ar": {
    "showSecret": "إظهار",
    "hideSecret": "إخفاء",

    "generationUnavailable": "التوليد غير متاح بعد لهذا المزوّد.",
    "secretValue": "القيمة السرية",
    "saveSecret": "حفظ السر",
    "cancel": "إلغاء",
    "secretForm": "أدخل القيمة في هذا النموذج الآمن.",

    "blank": "أدخل رمزًا. المسافات وحدها ليست رمزًا.",
    "limit": "يتجاوز الرمز حد 8192 حرفًا. انسخ الرمز فقط.",
    "ascii": "يجب أن تستخدم رموز الخوادم المستضافة أحرف ASCII مرئية (0x21–0x7E).",
    "control": "يحتوي الرمز على حرف تحكم غير صالح.",
    "plain": "أدخل بيانات الاعتماد في الحقل السري، وليس في هذا الحقل.",
    "saved": "تم الحفظ، لم يُختبر.",
    "connected": "متصل.",
    "auth": "رفض الخادم هذا الرمز.",
    "timeout": "انتهت مهلة الاتصال.",
    "unreachable": "تعذر الوصول إلى الخادم.",
    "chars": "{length} حرفًا",
    "env": "أدخل متغيرات البيئة كأسطر NAME=VALUE أو كائن JSON من السلاسل النصية.",
    "url": "يجب أن يكون عنوان الخادم URL مطلقًا صالحًا.",
    "set": "تم ضبط رمز الوصول",
    "storage": "تعذر حفظ بيانات الاعتماد أو فتحها. تحقق من مخزن بيانات اعتماد الموقع.",
    "savedTitle": "تم الحفظ."
  },
  "ja": {
    "showSecret": "表示",
    "hideSecret": "非表示",

    "generationUnavailable": "このプロバイダーでは生成はまだ利用できません。",
    "secretValue": "シークレット値",
    "saveSecret": "シークレットを保存",
    "cancel": "キャンセル",
    "secretForm": "この安全なフォームに値を入力してください。",

    "blank": "トークンを入力してください。空白だけではトークンになりません。",
    "limit": "トークンが8192文字の制限を超えています。トークンだけをコピーしてください。",
    "ascii": "ホスト型トークンには表示可能なASCII文字（0x21–0x7E）が必要です。",
    "control": "トークンに無効な制御文字が含まれています。",
    "plain": "認証情報はこの欄ではなく秘密の欄に入力してください。",
    "saved": "保存済み、未テスト。",
    "connected": "接続済み。",
    "auth": "サーバーがこのトークンを拒否しました。",
    "timeout": "接続がタイムアウトしました。",
    "unreachable": "サーバーに接続できませんでした。",
    "chars": "{length} 文字",
    "env": "環境変数はNAME=VALUEの行または文字列のJSONオブジェクトで入力してください。",
    "url": "サーバーURLは有効な絶対URLである必要があります。",
    "set": "アクセストークン設定済み",
    "storage": "認証情報を保存または解除できませんでした。サイトの認証情報ストアを確認してください。",
    "savedTitle": "保存しました。"
  },
  "ko": {
    "showSecret": "표시",
    "hideSecret": "숨기기",

    "generationUnavailable": "이 제공업체에서는 생성 기능을 아직 사용할 수 없습니다.",
    "secretValue": "비밀 값",
    "saveSecret": "비밀 저장",
    "cancel": "취소",
    "secretForm": "이 보안 양식에 값을 입력하세요.",

    "blank": "토큰을 입력하세요. 공백만으로는 토큰이 될 수 없습니다.",
    "limit": "토큰이 8192자 제한을 초과합니다. 토큰만 복사하세요.",
    "ascii": "호스팅 토큰에는 표시 가능한 ASCII 문자(0x21–0x7E)가 필요합니다.",
    "control": "토큰에 잘못된 제어 문자가 있습니다.",
    "plain": "이 필드 대신 비밀 필드에 자격 증명을 입력하세요.",
    "saved": "저장됨, 테스트하지 않음.",
    "connected": "연결됨.",
    "auth": "서버가 이 토큰을 거부했습니다.",
    "timeout": "연결 시간이 초과되었습니다.",
    "unreachable": "서버에 연결할 수 없습니다.",
    "chars": "{length}자",
    "env": "환경 변수를 NAME=VALUE 줄 또는 문자열 JSON 객체로 입력하세요.",
    "url": "서버 URL은 유효한 절대 URL이어야 합니다.",
    "set": "액세스 토큰 설정됨",
    "storage": "자격 증명을 저장하거나 잠금 해제할 수 없습니다. 사이트 자격 증명 저장소를 확인하세요.",
    "savedTitle": "저장됨."
  },
  "pl": {
    "showSecret": "Pokaż",
    "hideSecret": "Ukryj",

    "generationUnavailable": "Generowanie nie jest jeszcze dostępne u tego dostawcy.",
    "secretValue": "Tajna wartość",
    "saveSecret": "Zapisz sekret",
    "cancel": "Anuluj",
    "secretForm": "Wprowadź wartość w tym bezpiecznym formularzu.",

    "blank": "Wpisz token. Same spacje nie są tokenem.",
    "limit": "Token przekracza limit 8192 znaków. Skopiuj tylko token.",
    "ascii": "Tokeny hostowane muszą używać widocznych znaków ASCII (0x21–0x7E).",
    "control": "Token zawiera nieprawidłowy znak sterujący.",
    "plain": "Wpisz dane uwierzytelniające w polu tajnym, nie w tym polu.",
    "saved": "Zapisano, nie przetestowano.",
    "connected": "Połączono.",
    "auth": "Serwer odrzucił ten token.",
    "timeout": "Przekroczono czas połączenia.",
    "unreachable": "Nie można połączyć się z serwerem.",
    "chars": "{length} znaków",
    "env": "Wpisz zmienne środowiskowe jako wiersze NAME=VALUE lub obiekt JSON z ciągami znaków.",
    "url": "URL serwera musi być prawidłowym bezwzględnym adresem URL.",
    "set": "Token dostępu zapisany",
    "storage": "Nie można zapisać ani odblokować danych logowania. Sprawdź magazyn danych logowania witryny.",
    "savedTitle": "Zapisano."
  },
  "hu": {
    "showSecret": "Megjelenítés",
    "hideSecret": "Elrejtés",

    "generationUnavailable": "Ennél a szolgáltatónál a generálás még nem érhető el.",
    "secretValue": "Titkos érték",
    "saveSecret": "Titok mentése",
    "cancel": "Mégse",
    "secretForm": "Add meg az értéket ebben a biztonságos űrlapban.",

    "blank": "Adj meg egy tokent. A szóközök önmagukban nem tokenek.",
    "limit": "A token túllépi a 8192 karakteres korlátot. Csak a tokent másold.",
    "ascii": "A távoli tokenek csak látható ASCII-karaktereket használhatnak (0x21–0x7E).",
    "control": "A token érvénytelen vezérlőkaraktert tartalmaz.",
    "plain": "A hitelesítő adatokat a titkos mezőbe írd, ne ebbe.",
    "saved": "Mentve, nem tesztelve.",
    "connected": "Csatlakoztatva.",
    "auth": "A szerver elutasította ezt a tokent.",
    "timeout": "A kapcsolat időtúllépés miatt megszakadt.",
    "unreachable": "A szerver nem érhető el.",
    "chars": "{length} karakter",
    "env": "A környezeti változókat NAME=VALUE sorokként vagy karakterláncokat tartalmazó JSON-objektumként add meg.",
    "url": "A szerver URL-jének érvényes abszolút URL-nek kell lennie.",
    "set": "Hozzáférési token beállítva",
    "storage": "A hitelesítő adat nem menthető vagy oldható fel. Ellenőrizd a webhely hitelesítőadat-tárát.",
    "savedTitle": "Mentve."
  },
  "fr": {
    "showSecret": "Afficher",
    "hideSecret": "Masquer",

    "generationUnavailable": "La génération n’est pas encore disponible pour ce fournisseur.",
    "secretValue": "Valeur secrète",
    "saveSecret": "Enregistrer le secret",
    "cancel": "Annuler",
    "secretForm": "Saisissez la valeur dans ce formulaire sécurisé.",

    "blank": "Saisissez un jeton. Des espaces seuls ne sont pas un jeton.",
    "limit": "Le jeton dépasse la limite de 8192 caractères. Copiez uniquement le jeton.",
    "ascii": "Les jetons hébergés doivent utiliser des caractères ASCII visibles (0x21–0x7E).",
    "control": "Le jeton contient un caractère de contrôle invalide.",
    "plain": "Saisissez les identifiants dans le champ secret, pas dans ce champ.",
    "saved": "Enregistré, non testé.",
    "connected": "Connecté.",
    "auth": "Le serveur a refusé ce jeton.",
    "timeout": "La connexion a expiré.",
    "unreachable": "Impossible de joindre le serveur.",
    "chars": "{length} caractères",
    "env": "Saisissez les variables d’environnement sous forme de lignes NAME=VALUE ou d’un objet JSON de chaînes.",
    "url": "L’URL du serveur doit être une URL absolue valide.",
    "set": "Jeton d’accès enregistré",
    "storage": "Impossible d’enregistrer ou de déverrouiller les identifiants. Vérifiez le stockage des identifiants du site.",
    "savedTitle": "Enregistré."
  },
  "uk": {
    "showSecret": "Показати",
    "hideSecret": "Приховати",

    "generationUnavailable": "Генерація для цього провайдера ще недоступна.",
    "secretValue": "Секретне значення",
    "saveSecret": "Зберегти секрет",
    "cancel": "Скасувати",
    "secretForm": "Введіть значення в цій захищеній формі.",

    "blank": "Введіть токен. Самі пробіли не є токеном.",
    "limit": "Токен перевищує ліміт 8192 символи. Скопіюйте лише токен.",
    "ascii": "Токени віддалених серверів мають містити видимі символи ASCII (0x21–0x7E).",
    "control": "Токен містить недопустимий керівний символ.",
    "plain": "Введіть облікові дані в секретне поле, а не в це поле.",
    "saved": "Збережено, не перевірено.",
    "connected": "Підключено.",
    "auth": "Сервер відхилив цей токен.",
    "timeout": "Час очікування підключення минув.",
    "unreachable": "Не вдалося з’єднатися із сервером.",
    "chars": "{length} символів",
    "env": "Введіть змінні середовища рядками NAME=VALUE або JSON-об’єктом рядків.",
    "url": "URL сервера має бути дійсною абсолютною URL-адресою.",
    "set": "Токен доступу збережено",
    "storage": "Не вдалося зберегти або розблокувати облікові дані. Перевірте сховище облікових даних сайту.",
    "savedTitle": "Збережено."
  },
  "tr": {
    "showSecret": "Göster",
    "hideSecret": "Gizle",

    "generationUnavailable": "Bu sağlayıcı için oluşturma henüz kullanılamıyor.",
    "secretValue": "Gizli değer",
    "saveSecret": "Gizli değeri kaydet",
    "cancel": "İptal",
    "secretForm": "Değeri bu güvenli forma girin.",

    "blank": "Bir token girin. Yalnızca boşluklar token değildir.",
    "limit": "Token 8192 karakter sınırını aşıyor. Yalnızca tokeni kopyalayın.",
    "ascii": "Barındırılan tokenler görünür ASCII karakterleri kullanmalıdır (0x21–0x7E).",
    "control": "Token geçersiz bir kontrol karakteri içeriyor.",
    "plain": "Kimlik bilgilerini bu alana değil, gizli alana girin.",
    "saved": "Kaydedildi, test edilmedi.",
    "connected": "Bağlandı.",
    "auth": "Sunucu bu tokeni reddetti.",
    "timeout": "Bağlantı zaman aşımına uğradı.",
    "unreachable": "Sunucuya ulaşılamadı.",
    "chars": "{length} karakter",
    "env": "Ortam değişkenlerini NAME=VALUE satırları veya dizelerden oluşan bir JSON nesnesi olarak girin.",
    "url": "Sunucu URL’si geçerli bir mutlak URL olmalıdır.",
    "set": "Erişim tokeni kaydedildi",
    "storage": "Kimlik bilgisi kaydedilemedi veya açılamadı. Sitenin kimlik bilgisi deposunu kontrol edin.",
    "savedTitle": "Kaydedildi."
  },
  "th": {
    "showSecret": "แสดง",
    "hideSecret": "ซ่อน",

    "generationUnavailable": "ยังไม่สามารถสร้างด้วยผู้ให้บริการนี้ได้",
    "secretValue": "ค่าความลับ",
    "saveSecret": "บันทึกความลับ",
    "cancel": "ยกเลิก",
    "secretForm": "ป้อนค่าในแบบฟอร์มที่ปลอดภัยนี้",

    "blank": "ป้อนโทเค็น ช่องว่างเพียงอย่างเดียวไม่ใช่โทเค็น",
    "limit": "โทเค็นเกินขีดจำกัด 8192 อักขระ คัดลอกเฉพาะโทเค็น",
    "ascii": "โทเค็นบนเซิร์ฟเวอร์ต้องใช้ตัวอักษร ASCII ที่มองเห็นได้ (0x21–0x7E)",
    "control": "โทเค็นมีอักขระควบคุมที่ไม่ถูกต้อง",
    "plain": "ป้อนข้อมูลรับรองในช่องลับ ไม่ใช่ช่องนี้",
    "saved": "บันทึกแล้ว ยังไม่ได้ทดสอบ",
    "connected": "เชื่อมต่อแล้ว",
    "auth": "เซิร์ฟเวอร์ปฏิเสธโทเค็นนี้",
    "timeout": "การเชื่อมต่อหมดเวลา",
    "unreachable": "ไม่สามารถเข้าถึงเซิร์ฟเวอร์ได้",
    "chars": "{length} อักขระ",
    "env": "ป้อนตัวแปรสภาพแวดล้อมเป็นบรรทัด NAME=VALUE หรือวัตถุ JSON ของสตริง",
    "url": "URL เซิร์ฟเวอร์ต้องเป็น URL แบบเต็มที่ถูกต้อง",
    "set": "ตั้งค่าโทเค็นการเข้าถึงแล้ว",
    "storage": "ไม่สามารถบันทึกหรือปลดล็อกข้อมูลรับรองได้ ตรวจสอบที่เก็บข้อมูลรับรองของเว็บไซต์",
    "savedTitle": "บันทึกแล้ว"
  },
  "it": {
    "showSecret": "Mostra",
    "hideSecret": "Nascondi",

    "generationUnavailable": "La generazione non è ancora disponibile per questo fornitore.",
    "secretValue": "Valore segreto",
    "saveSecret": "Salva segreto",
    "cancel": "Annulla",
    "secretForm": "Inserisci il valore in questo modulo sicuro.",

    "blank": "Inserisci un token. Gli spazi da soli non sono un token.",
    "limit": "Il token supera il limite di 8192 caratteri. Copia solo il token.",
    "ascii": "I token ospitati devono usare caratteri ASCII visibili (0x21–0x7E).",
    "control": "Il token contiene un carattere di controllo non valido.",
    "plain": "Inserisci le credenziali nel campo segreto, non in questo campo.",
    "saved": "Salvato, non testato.",
    "connected": "Connesso.",
    "auth": "Il server ha rifiutato questo token.",
    "timeout": "La connessione è scaduta.",
    "unreachable": "Impossibile raggiungere il server.",
    "chars": "{length} caratteri",
    "env": "Inserisci le variabili d’ambiente come righe NAME=VALUE o come oggetto JSON di stringhe.",
    "url": "L’URL del server deve essere un URL assoluto valido.",
    "set": "Token di accesso impostato",
    "storage": "Impossibile salvare o sbloccare le credenziali. Controlla l’archivio credenziali del sito.",
    "savedTitle": "Salvato."
  },
  "hi": {
    "showSecret": "दिखाएं",
    "hideSecret": "छिपाएं",

    "generationUnavailable": "इस प्रदाता के लिए जनरेशन अभी उपलब्ध नहीं है।",
    "secretValue": "गुप्त मान",
    "saveSecret": "गुप्त मान सहेजें",
    "cancel": "रद्द करें",
    "secretForm": "इस सुरक्षित फ़ॉर्म में मान दर्ज करें।",

    "blank": "टोकन दर्ज करें। केवल खाली जगह टोकन नहीं है।",
    "limit": "टोकन 8192 वर्णों की सीमा से अधिक है। केवल टोकन कॉपी करें।",
    "ascii": "होस्ट किए गए टोकन में दृश्य ASCII वर्ण होने चाहिए (0x21–0x7E)।",
    "control": "टोकन में अमान्य नियंत्रण वर्ण है।",
    "plain": "प्रमाण-पत्र इस फ़ील्ड के बजाय गुप्त फ़ील्ड में दर्ज करें।",
    "saved": "सहेजा गया, परीक्षण नहीं हुआ।",
    "connected": "जुड़ा हुआ।",
    "auth": "सर्वर ने यह टोकन अस्वीकार कर दिया।",
    "timeout": "कनेक्शन का समय समाप्त हो गया।",
    "unreachable": "सर्वर से संपर्क नहीं हो सका।",
    "chars": "{length} वर्ण",
    "env": "पर्यावरण चर NAME=VALUE पंक्तियों या स्ट्रिंग के JSON ऑब्जेक्ट के रूप में दर्ज करें।",
    "url": "सर्वर URL एक मान्य पूर्ण URL होना चाहिए।",
    "set": "एक्सेस टोकन सेट है",
    "storage": "क्रेडेंशियल सहेजा या अनलॉक नहीं किया जा सका। साइट का क्रेडेंशियल स्टोर जाँचें।",
    "savedTitle": "सहेजा गया।"
  },
  "ur": {
    "showSecret": "دکھائیں",
    "hideSecret": "چھپائیں",

    "generationUnavailable": "اس فراہم کنندہ کے لیے تخلیق ابھی دستیاب نہیں ہے۔",
    "secretValue": "خفیہ قدر",
    "saveSecret": "خفیہ قدر محفوظ کریں",
    "cancel": "منسوخ کریں",
    "secretForm": "اس محفوظ فارم میں قدر درج کریں۔",

    "blank": "ٹوکن درج کریں۔ صرف خالی جگہ ٹوکن نہیں ہے۔",
    "limit": "ٹوکن 8192 حروف کی حد سے زیادہ ہے۔ صرف ٹوکن کاپی کریں۔",
    "ascii": "میزبانی والے ٹوکن میں نظر آنے والے ASCII حروف ہونے چاہئیں (0x21–0x7E)۔",
    "control": "ٹوکن میں غلط کنٹرول حرف ہے۔",
    "plain": "اس خانے کے بجائے خفیہ خانے میں اسناد درج کریں۔",
    "saved": "محفوظ، جانچا نہیں گیا۔",
    "connected": "منسلک۔",
    "auth": "سرور نے یہ ٹوکن مسترد کر دیا۔",
    "timeout": "کنکشن کا وقت ختم ہو گیا۔",
    "unreachable": "سرور تک رسائی ممکن نہیں ہوئی۔",
    "chars": "{length} حروف",
    "env": "ماحولیاتی متغیرات NAME=VALUE سطروں یا سٹرنگز کے JSON آبجیکٹ کے طور پر درج کریں۔",
    "url": "سرور URL ایک درست مکمل URL ہونا چاہیے۔",
    "set": "رسائی ٹوکن محفوظ ہے",
    "storage": "اسناد محفوظ یا ان لاک نہیں ہو سکیں۔ سائٹ کا اسناد کا ذخیرہ چیک کریں۔",
    "savedTitle": "محفوظ ہو گیا۔"
  },
  "bn": {
    "showSecret": "দেখান",
    "hideSecret": "লুকান",

    "generationUnavailable": "এই প্রদানকারীর জন্য তৈরি করা এখনো উপলব্ধ নয়।",
    "secretValue": "গোপন মান",
    "saveSecret": "গোপন মান সংরক্ষণ করুন",
    "cancel": "বাতিল",
    "secretForm": "এই নিরাপদ ফর্মে মান লিখুন।",

    "blank": "টোকেন লিখুন। শুধু ফাঁকা স্থান টোকেন নয়।",
    "limit": "টোকেন 8192 অক্ষরের সীমা ছাড়িয়েছে। শুধু টোকেন কপি করুন।",
    "ascii": "হোস্ট করা টোকেনে দৃশ্যমান ASCII অক্ষর থাকতে হবে (0x21–0x7E)।",
    "control": "টোকেনে অবৈধ নিয়ন্ত্রণ অক্ষর আছে।",
    "plain": "এই ঘরের বদলে গোপন ঘরে পরিচয়পত্র লিখুন।",
    "saved": "সংরক্ষিত, পরীক্ষা করা হয়নি।",
    "connected": "সংযুক্ত।",
    "auth": "সার্ভার এই টোকেন প্রত্যাখ্যান করেছে।",
    "timeout": "সংযোগের সময় শেষ হয়েছে।",
    "unreachable": "সার্ভারে পৌঁছানো যায়নি।",
    "chars": "{length} অক্ষর",
    "env": "পরিবেশ চলক NAME=VALUE লাইনে বা স্ট্রিংয়ের JSON অবজেক্ট হিসেবে লিখুন।",
    "url": "সার্ভার URL অবশ্যই বৈধ সম্পূর্ণ URL হতে হবে।",
    "set": "অ্যাক্সেস টোকেন সেট করা হয়েছে",
    "storage": "শংসাপত্র সংরক্ষণ বা আনলক করা যায়নি। সাইটের শংসাপত্রের ভাণ্ডার পরীক্ষা করুন।",
    "savedTitle": "সংরক্ষিত।"
  }
} as const;
const dictionary = Object.fromEntries(Object.entries(CREDENTIAL_COPY).map(([locale, values]) => [locale,
  Object.fromEntries(Object.entries(values).map(([id, text]) => [CREDENTIAL_MESSAGES[id as CredentialMessageId], text])),
]));
export function credentialText({ id, locale = 'en' }: { id: CredentialMessageId; locale?: string }, _optional = {}): string {
  return dictionary[locale]?.[CREDENTIAL_MESSAGES[id]] ?? CREDENTIAL_MESSAGES[id];
}
export function formatCredentialHint({ hint, locale = 'en' }: { hint: CredentialTokenHint | null | undefined; locale?: string }, _optional = {}): string {
  if (!hint) return '';
  const length = new Intl.NumberFormat(locale).format(hint.length);
  const chars = credentialText({ id: 'chars', locale }).replace('{length}', length);
  return `${hint.last4 === null ? '' : `…${hint.last4}, `}${chars}`;
}

/** Only known, fixed policy messages are translated; unknown exceptions never gain display permission. */
export function translateCredentialMessage({ message, locale = 'en' }: { message: string; locale?: string }, _optional = {}): string {
  const id = (Object.keys(CREDENTIAL_MESSAGES) as CredentialMessageId[]).find(id => CREDENTIAL_MESSAGES[id] === message);
  return id ? credentialText({ id, locale }) : message;
}

/** Variable names are already public metadata; values are server-derived hints only. */
export function formatCredentialHints(
  { hints, locale = 'en' }: { hints?: Readonly<Record<string, CredentialTokenHint>>; locale?: string },
  _optional = {},
): string {
  return Object.entries(hints ?? {}).map(([name, hint]) => `${name}: ${formatCredentialHint({ hint, locale })}`).join(' · ');
}
