import { createDictionaryTranslator } from "../../lib/dictionary-translator";

const PLAYGROUND_DICT: Record<string, Record<string, string>> = {
  en: { Studio: "Studio", Playground: "Playground", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.", Canvas: "Canvas", "Nothing drawn yet — ask the assistant.": "Nothing drawn yet — ask the assistant." },
  es: { Studio: "Estudio", Playground: "Zona de pruebas", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Pide al asistente que cree cualquier cosa; prueba “Muestra un gráfico circular de mis publicaciones frente a mis páginas”. Ya tiene disponibles todos los componentes reales.", Canvas: "Lienzo", "Nothing drawn yet — ask the assistant.": "Aún no hay nada dibujado; pregúntale al asistente." },
  id: { Studio: "Studio", Playground: "Area percobaan", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Minta asisten membuat apa saja — coba “Tampilkan diagram pai postingan saya dibanding halaman saya”. Semua komponen nyata sudah tersedia untuknya.", Canvas: "Kanvas", "Nothing drawn yet — ask the assistant.": "Belum ada yang digambar — tanyakan kepada asisten." },
  de: { Studio: "Studio", Playground: "Spielplatz", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Bitten Sie den Assistenten, etwas zu erstellen — etwa „Zeige ein Kreisdiagramm meiner Beiträge gegenüber meinen Seiten“. Alle echten Komponenten stehen ihm bereits zur Verfügung.", Canvas: "Arbeitsfläche", "Nothing drawn yet — ask the assistant.": "Noch nichts gezeichnet — fragen Sie den Assistenten." },
  fr: { Studio: "Studio", Playground: "Aire de jeu", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Demandez à l’assistant de créer n’importe quoi — essayez « Affiche un graphique circulaire de mes articles par rapport à mes pages ». Tous les composants réels sont déjà à sa disposition.", Canvas: "Canevas", "Nothing drawn yet — ask the assistant.": "Rien n’est encore dessiné — demandez à l’assistant." },
  it: { Studio: "Studio", Playground: "Area di prova", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Chiedi all’assistente di creare qualsiasi cosa — prova “Mostra un grafico a torta dei miei post rispetto alle mie pagine”. Tutti i componenti reali sono già disponibili.", Canvas: "Area di disegno", "Nothing drawn yet — ask the assistant.": "Non è stato ancora disegnato nulla — chiedi all’assistente." },
  "pt-BR": { Studio: "Estúdio", Playground: "Área de testes", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Peça ao assistente para criar qualquer coisa — experimente “Mostre um gráfico de pizza das minhas publicações versus páginas”. Todos os componentes reais já estão disponíveis para ele.", Canvas: "Tela", "Nothing drawn yet — ask the assistant.": "Ainda não há nada desenhado — peça ao assistente." },
  pl: { Studio: "Studio", Playground: "Plac zabaw", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Poproś asystenta o stworzenie czegokolwiek — spróbuj „Pokaż wykres kołowy moich postów i stron”. Wszystkie rzeczywiste komponenty są już dostępne.", Canvas: "Płótno", "Nothing drawn yet — ask the assistant.": "Nic jeszcze nie narysowano — zapytaj asystenta." },
  tr: { Studio: "Stüdyo", Playground: "Deneme alanı", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Asistandan herhangi bir şey oluşturmasını isteyin — “Gönderilerime karşı sayfalarımın pasta grafiğini göster” demeyi deneyin. Tüm gerçek bileşenler zaten kullanılabilir.", Canvas: "Tuval", "Nothing drawn yet — ask the assistant.": "Henüz hiçbir şey çizilmedi — asistana sorun." },
  hu: { Studio: "Stúdió", Playground: "Játszótér", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Kérje meg az asszisztenst bármi elkészítésére — például: „Mutass kördiagramot a bejegyzéseimről és oldalaimról”. Minden valódi összetevő már rendelkezésére áll.", Canvas: "Vászon", "Nothing drawn yet — ask the assistant.": "Még nincs rajz — kérdezze meg az asszisztenst." },
  ru: { Studio: "Студия", Playground: "Песочница", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Попросите ассистента создать что угодно — например: «Покажи круговую диаграмму моих записей и страниц». Все реальные компоненты уже доступны ему.", Canvas: "Холст", "Nothing drawn yet — ask the assistant.": "Пока ничего не нарисовано — спросите ассистента." },
  uk: { Studio: "Студія", Playground: "Пісочниця", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "Попросіть помічника створити будь-що — спробуйте «Покажи кругову діаграму моїх дописів і сторінок». Усі справжні компоненти вже доступні.", Canvas: "Полотно", "Nothing drawn yet — ask the assistant.": "Ще нічого не намальовано — запитайте помічника." },
  ar: { Studio: "الاستوديو", Playground: "ساحة التجربة", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "اطلب من المساعد إنشاء أي شيء — جرّب «اعرض مخططًا دائريًا لمنشوراتي مقابل صفحاتي». جميع المكونات الفعلية متاحة له بالفعل.", Canvas: "لوحة الرسم", "Nothing drawn yet — ask the assistant.": "لم يُرسم شيء بعد — اسأل المساعد." },
  fa: { Studio: "استودیو", Playground: "محیط آزمایش", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "از دستیار بخواهید هر چیزی بسازد — مثلاً «نمودار دایره‌ای پست‌ها در برابر صفحه‌هایم را نشان بده». همهٔ مؤلفه‌های واقعی از قبل در دسترس او هستند.", Canvas: "بوم", "Nothing drawn yet — ask the assistant.": "هنوز چیزی رسم نشده است — از دستیار بپرسید." },
  ur: { Studio: "اسٹوڈیو", Playground: "تجربہ گاہ", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "اسسٹنٹ سے کچھ بھی بنانے کو کہیں — مثلاً «میری پوسٹس اور صفحات کا پائی چارٹ دکھاؤ»۔ تمام حقیقی اجزا پہلے ہی دستیاب ہیں۔", Canvas: "کینوس", "Nothing drawn yet — ask the assistant.": "ابھی کچھ نہیں بنایا گیا — اسسٹنٹ سے پوچھیں۔" },
  hi: { Studio: "स्टूडियो", Playground: "प्रयोगशाला", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "सहायक से कुछ भी बनाने को कहें — “मेरी पोस्ट और पेज का पाई चार्ट दिखाओ” आज़माएँ। सभी वास्तविक घटक उसके लिए पहले से उपलब्ध हैं।", Canvas: "कैनवास", "Nothing drawn yet — ask the assistant.": "अभी कुछ नहीं बनाया गया — सहायक से पूछें।" },
  bn: { Studio: "স্টুডিও", Playground: "পরীক্ষার ক্ষেত্র", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "সহকারীকে যেকোনো কিছু তৈরি করতে বলুন — “আমার পোস্ট ও পেজের পাই চার্ট দেখাও” চেষ্টা করুন। সব বাস্তব উপাদান তার কাছে আগে থেকেই আছে।", Canvas: "ক্যানভাস", "Nothing drawn yet — ask the assistant.": "এখনও কিছু আঁকা হয়নি — সহকারীকে বলুন।" },
  th: { Studio: "สตูดิโอ", Playground: "พื้นที่ทดลอง", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "ขอให้ผู้ช่วยสร้างอะไรก็ได้ — ลอง “แสดงแผนภูมิวงกลมของโพสต์เทียบกับหน้าเว็บของฉัน” องค์ประกอบจริงทั้งหมดพร้อมใช้งานแล้ว", Canvas: "ผืนผ้าใบ", "Nothing drawn yet — ask the assistant.": "ยังไม่มีสิ่งใดถูกวาด — ถามผู้ช่วยได้เลย" },
  ja: { Studio: "スタジオ", Playground: "プレイグラウンド", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "アシスタントに何でも作成させましょう。たとえば「投稿とページの円グラフを表示して」と頼めます。実際のコンポーネントはすべて利用可能です。", Canvas: "キャンバス", "Nothing drawn yet — ask the assistant.": "まだ何も描かれていません。アシスタントに頼んでください。" },
  ko: { Studio: "스튜디오", Playground: "플레이그라운드", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "도우미에게 무엇이든 만들도록 요청하세요. “게시물과 페이지의 파이 차트를 보여 줘”라고 해 보세요. 모든 실제 구성 요소를 이미 사용할 수 있습니다.", Canvas: "캔버스", "Nothing drawn yet — ask the assistant.": "아직 그려진 것이 없습니다. 도우미에게 요청하세요." },
  "zh-CN": { Studio: "工作室", Playground: "实验场", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "请助手构建任何内容——试试“显示我的文章与页面的饼图”。所有真实组件都已可供它使用。", Canvas: "画布", "Nothing drawn yet — ask the assistant.": "尚未绘制任何内容——请询问助手。" },
  "zh-TW": { Studio: "工作室", Playground: "遊樂場", "Ask the assistant to build anything — try “Show a pie chart of my posts vs pages.” Every real component is already available to it.": "請助理建立任何內容——試試「顯示我的文章與頁面的圓餅圖」。所有真實元件都已可供使用。", Canvas: "畫布", "Nothing drawn yet — ask the assistant.": "尚未繪製任何內容——請詢問助理。" },
};

export const t = createDictionaryTranslator(PLAYGROUND_DICT);
