import { AesGcmSecretSealer as JiniSecretSealer } from "@jini-ai/platform/secrets";
import type { KeyringPort, SiteKeyHandle, SecretSealerPort } from "./ports.js";
import type { SealedSecret } from "@jini-ai/platform/secrets";

/** Host port adapter preserving the existing sealed wire format and open(input.aad) contract.
 *
 * Contract rationale for the Jini implementation and this host boundary:
 *
 * @file `SecretSealerPort`'s first real implementation (ADR-058) — the seam ADR-036 §8 named and
 * deferred ("the recoverable secret-store ADR") when it shipped `integration_secrets`/`SealedSecret`
 * as a table shape with no adapter behind it.
 *
 * How it relates to the project:
 * AES-256-GCM via bare `node:crypto` (no new dependency, matching every other crypto use in this
 * codebase — `keyring.env.ts`, `daemon-auth.ts`, `lipay-gateway.ts` are all already bare
 * `node:crypto`). The AES key is never held or generated by this class directly — it is re-derived
 * on every `seal`/`open` call from an injected `KeyringPort` (ADR-024 §3 by-handle discipline: raw
 * root-key bytes never cross this class's own boundary, only the `RootKeyHandle`'s `keyId` does).
 * `purpose: "secret-sealer.v1"` binds the derivation into its own HKDF domain, separate from
 * webhook-signing (`deriveSigningSecret`) and newsletter-token derivation that share the same root
 * key elsewhere in this codebase (ADR-036 Round-3 fold: `purpose` MUST be a real separation
 * boundary, not decorative).
 *
 * One shared sealing capability app-wide, not one key per tenant: `deriveAesKey` derives a SINGLE
 * AES key per root-key generation (`key.keyId`), the same key for every workspace and every record.
 * Multi-tenant separation is a property of the DATA layer (each row carries its own `workspace_id`
 * — see `site-credential-store.ts`), not of the encryption key, which is standard envelope
 * encryption and matches `SealedSecret.keyId`'s own doc ("names the root-key generation the value
 * was wrapped under" — one generation identity for the whole store, not per-consumer).
 *
 * `aad` (2026-08-15, `publish_credential_sets` hardening): the shared-key design above means the KEY
 * alone does not separate one row's ciphertext from another's — a ciphertext sealed for workspace A
 * would decrypt cleanly under workspace B's key derivation too, since it is the SAME derivation for
 * both. `SecretSealerPort.seal`/`open`'s optional `aad` parameter closes that gap per-CALL rather
 * than per-key: when a caller supplies `aad`, it is bound into the AES-GCM authentication tag via
 * `cipher.setAAD`/`decipher.setAAD` (Node's `crypto` binding of the GCM AAD input, RFC 5116 §5.1) —
 * opening with a different (or absent) `aad` than the one used to seal fails auth-tag verification
 * exactly like a tampered ciphertext would. Optional and additive: every existing call site that
 * never passes `aad` behaves byte-for-byte as before (this adapter supplies zero AAD bytes to Jini, which produces the same GCM tag), so
 * `site_assistant_credentials`/`admin_execution_credentials` rows sealed before this change keep
 * opening with no changes at either the call site or the stored row.
 *
 * Rule-of-two (ADR-006): this is the "real adapter" half. There is deliberately no separate
 * plaintext-passthrough test double for `SecretSealerPort` itself — a fake that skips encryption
 * would defeat the one thing worth testing (that a value round-trips through REAL AES-GCM). The
 * lightweight test path is this same class backed by `KeyringPort`'s own existing in-memory adapter
 * (`InMemoryKeyring`), which is already fast, hermetic, and deterministic per process.
 *
 * Fixed `KeyringPort.derive()` workspace-scope label for the sealer's OWN key derivation — see
 *  this file's header on why one shared key, not one per tenant.
 *
 * AES-256-GCM `SecretSealerPort` adapter over a `KeyringPort`.
 *
 * @overallScore 100
 *
 * Encrypts `input.plaintext` under a key derived from `input.key` (the caller's current
 * `RootKeyHandle`, typically `keyring.activeKey()`).
 *
 * @param input.aad - Optional AES-GCM additional authenticated data (see this file's header). When
 *   supplied, `open()` must be called with the byte-identical string or the auth tag fails to
 *   verify. Zero AAD bytes when `input.aad` is undefined — a plain seal exactly
 *   like every pre-existing call site performs.
 * @returns `{keyId, ciphertext, nonce, alg}` — `ciphertext` is base64(AEAD ciphertext || 16-byte
 *   GCM auth tag), `nonce` is base64(12-byte IV). A fresh random IV every call — GCM's security
 *   property depends on never reusing an IV under the same key. `aad` itself is NOT part of the
 *   returned shape — GCM authenticates it but never encrypts or stores it, so a caller must be able
 *   to re-derive the same string from context at open time (see this file's header).
 * @throws Whatever `KeyringPort.derive()` throws (e.g. a missing root key) — propagated, never
 *   swallowed into a plaintext fallback (ADR-058 §4: this feature's callers convert that into a
 *   distinct `SECRET_STORE_UNCONFIGURED` error, they do not catch it here).
 * @complexity O(n) in `plaintext` length — one cipher pass, no loops over caller-controlled
 *   collections.
 * @overallScore 100
 *
 * Reverses {@link seal}. Re-derives the AES key from `input.sealed.keyId` (not from
 * `keyring.activeKey()` — a sealed row wrapped under an older root-key generation must still open
 * under that generation's own derivation, the seam `keyId` exists for).
 *
 * @param input.aad - Must be the byte-identical string passed to the {@link seal} call that
 *   produced `input.sealed`, or omitted iff `seal` was also called with no `aad`. Any nonempty AAD mismatch
 *   (wrong string, or nonempty/absent asymmetry in either direction) fails auth-tag verification —
 *   see this file's header.
 * @throws If `input.sealed.alg` is not `"aes-256-gcm"`, if the ciphertext is malformed/too short to
 *   contain an auth tag, if the auth tag fails to verify (tampered ciphertext, wrong key, or a
 *   mismatched/missing `aad`), or whatever `KeyringPort.derive()` throws. Never returns a partial or
 *   best-guess plaintext.
 * @complexity O(n) in ciphertext length.
 * @overallScore 100
 */
export class AesGcmSecretSealer implements SecretSealerPort {
  private readonly sealer: JiniSecretSealer;

  constructor(keyring: KeyringPort) {
    this.sealer = new JiniSecretSealer({ keyring: {
      activeKey: () => keyring.activeKey(),
      derive: (input) => keyring.derive(input),
      deriveSigningSecret: (input) => keyring.deriveSigningSecret(input),
    } });
  }

  /** Real stores provide their row AAD. Empty AAD retains the historical unbound host-port format;
   * GCM with zero AAD bytes produces the same tag as the original omitted-AAD implementation.
   * Fields are forwarded explicitly, not spread, so `check:seal-aad`'s AST scan can see this
   * delegation's `aad` (a spread is fail-closed as unresolved there) and nothing beyond the port's
   * own three fields ever reaches Jini.
   * @complexity O(plaintext bytes), delegated to Jini AES-GCM.
   */
  seal(input: { plaintext: string; key: SiteKeyHandle; aad?: string }): Promise<SealedSecret> {
    return this.sealer.seal({ plaintext: input.plaintext, key: input.key, aad: input.aad ?? "" });
  }

  /** Move the host AAD field into Jini's optional object; absent AAD opens historical records.
   * @throws Authentication errors for wrong keys, changed AAD or malformed envelopes.
   * @complexity O(ciphertext bytes), delegated to Jini AES-GCM.
   */
  open(input: { sealed: SealedSecret; aad?: string }): Promise<string> {
    return this.sealer.open({ sealed: input.sealed }, input.aad !== undefined ? { aad: input.aad } : {});
  }
}
// Shared-key/AAD rationale: Jini/packages/platform/src/secrets/secret-sealer.aesgcm.ts (ADR-058).
