import {
  createMediaDispatchEngine,
  findMediaModel,
  findProvider,
  resolveProviderCredentialsFromEnv,
  PROVIDER_CREDENTIAL_ENV_VARS,
  type MediaGenerationRequest,
  type MediaGenerationResult,
  type ProviderCredentials,
} from "@jini-ai/integrations/media-providers";
import {
  buildDomainRegistrations,
  indexCatalogById,
  optionalBoolean,
  optionalString,
  requireInputRecord,
  requireString,
  requireToolPermission,
  withSchemaOnRejection,
  type AgentToolSideEffect,
  type DerivedRiskByToolId,
  type ToolHandler,
  type ToolRegistration,
} from "@jini-ai/cms/core";

import type { AuthorizeFn } from "../../contracts/core/commands/index.js";
import type { ToolContributor } from "#src/assistant/index";
import type { SecretSealerPort } from "../webhooks/index.js";
import {
  resolveMediaProviderCredential,
  sniffContentType,
  uploadMedia,
  type AssetBlobRepoPort,
  type AssetRenditionRepoPort,
  type BlobStorePort,
  type MediaProviderCredentialRepoPort,
  type MediaRepoPort,
  type TransformDefinitionRepoPort,
} from "../media/index.js";
import type { MediaContentTypeStorePort } from "../media/content-type-store.js";
import { resolveMediaPublicUrls } from "../media/tool-registrations.js";
import { mediaGenerationAgentToolCatalog, IMAGE_MODEL_IDS } from "./agent-tools.js";

/**
 * @file Wires `agent-tools.ts`'s one-tool catalog onto the real pipeline: resolve a credential for
 * the SELECTED MODEL'S VENDOR -> generate one image through the vendor dispatch engine
 * (`@jini-ai/integrations/media-providers`'s `createMediaDispatchEngine`, previously imported
 * nowhere under `apps/`) -> upload the generated bytes through the SAME `uploadMedia` service
 * `media_upload_asset` (`@jini-ai/cms/media`) already calls, so a generated asset is
 * indistinguishable in the media library from a human-uploaded one.
 *
 * 2026-09-02 follow-up dispatch: the first landed slice resolved ONLY a saved OpenAI credential
 * (`features/media/provider-credential-store.ts`'s `resolveMediaProviderCredential`), which meant
 * `media_generate_asset` could never generate anything on a machine (or workspace) with a different
 * vendor's key and no saved OpenAI row — exactly this machine's situation (`GEMINI_API_KEY` set, no
 * `OPENAI_API_KEY`, and zero rows in `media_provider_credentials`). {@link resolveCredentialForProvider}
 * is the fix: per the model's resolved `providerId` (see `agent-tools.ts`'s `IMAGE_MODEL_IDS`), try
 * the saved workspace credential first (the real multi-tenant production path — unchanged, still
 * wins whenever it exists), then fall back to `resolveProviderCredentialsFromEnv` (an opt-in
 * reference resolver `@jini-ai/integrations/media-providers` itself ships, documented there as the
 * intended path for a host willing to read plain env vars) ONLY when nothing is saved at all. A
 * saved row that exists but fails to DECRYPT is a different failure entirely — `resolveMediaProviderCredential`
 * throws its own `MediaProviderCredentialSecretStoreUnconfiguredError` for that, and this file
 * deliberately does not catch it, so it is never mistaken for "nothing saved" and never falls through
 * to env.
 *
 * A brand-new domain rather than a 5th entry on `media`'s existing catalog — see this dispatch's own
 * design note: media's 4-tool catalog is `@jini-ai/cms`-owned (shared across every host of that
 * package) with its own "wire the ENTIRE catalog" tripwire test on both sides; this tool's whole
 * pipeline (Tovu's credential store, the dispatch engine, Tovu's ADR-027 URL contract) is genuinely
 * host-specific glue, the same category `custom-credentials`/`site-inspection`/`site-evidence`
 * already established as their own small standalone domains rather than bolt-ons to an existing one.
 *
 * `media.upload`-gated — the same permission `media_upload_asset` uses, not a new
 * `media.generate`/etc. permission: what this tool actually DOES, durably, is create exactly the
 * kind of row a human upload creates (`mediaDerivedRisk`'s own "classify from what is actually
 * called" discipline, mirrored here) — the only difference is the byte source. Reusing the existing
 * permission also means no seed/role change is needed for the owner's existing wildcard grant to
 * cover it immediately.
 */

export interface MediaGenerationToolDeps {
  authorize: AuthorizeFn;
  workspaceId: string;
  clock: { nowIso(): string };
  idGen: { newId(): string };
  mediaRepo: MediaRepoPort;
  assetBlobRepo: AssetBlobRepoPort;
  assetRenditionRepo: AssetRenditionRepoPort;
  blobStore: BlobStorePort;
  mediaContentTypeStore: MediaContentTypeStorePort;
  transformDefinitionRepo: TransformDefinitionRepoPort;
  mediaProviderCredentialRepo: MediaProviderCredentialRepoPort;
  /** Same field name `RouteDeps` (and `CustomCredentialsToolDeps`) already uses for this shared
   *  sealer instance — see `provider-credential-store.ts`'s own header for why this store seals
   *  with no `aad`, the one respect in which its usage here differs from `custom-credentials`'s. */
  siteAssistantSecretSealer: SecretSealerPort;
  /**
   * The testability seam for the one real external I/O this domain performs (the 5a1 pre-check this
   * skill's workflow requires before writing the handler): a paid, non-deterministic third-party
   * call has no business running inside a unit test. Defaults to a thin wrapper over
   * `@jini-ai/integrations/media-providers`'s real `createMediaDispatchEngine` — see
   * {@link defaultGenerateMedia} — so production wiring supplies nothing extra; a test overrides
   * this with a fake that returns fixed bytes with no network access at all. `options.providerId`
   * (resolved from the selected `model` — see `agent-tools.ts`'s `IMAGE_MODEL_IDS`) replaces the old
   * hardcoded OpenAI-only provider id; `options.allowStubFallback` threads the caller's explicit
   * opt-in (see `GENERATE_SCHEMA`'s `allowStubFallback` field) into the engine's own stub-fallback
   * gate (`MediaDispatchEngineOptions.allowStubFallback`) — never enabled unless the caller asked.
   */
  generateMedia?: (
    request: MediaGenerationRequest,
    credentials: ProviderCredentials,
    options: { providerId: string; allowStubFallback: boolean }
  ) => Promise<MediaGenerationResult>;
  /**
   * The credential-env lookup table {@link resolveCredentialForProvider}'s env fallback reads from.
   * Defaults to the real `process.env` in production — the composition root passes nothing and gets
   * this machine's actual environment, which is the whole point (see this file's own module doc for
   * why that fallback exists). Tests inject a fixed map (`{}` included) so a regression run's
   * pass/fail can never depend on which environment variables happen to be set on the machine that
   * happens to run it.
   */
  env?: NodeJS.ProcessEnv;
}

/** `media_generate_asset`'s default model when `model` is omitted — OpenAI's current flagship image
 *  model (`@jini-ai/integrations/media-providers`'s `IMAGE_MODELS`, `default: true`). Still OpenAI:
 *  only the DEFAULT changed meaning (from "the only option" to "the fallback when the caller has no
 *  preference"), not the choice of default itself. */
const DEFAULT_MODEL = "gpt-image-2";

/** {@link MediaGenerationToolDeps.generateMedia}'s real, production implementation — a fresh engine
 *  per call because credentials are resolved fresh per call too (a rotated key must never reuse a
 *  stale boot-time singleton's credentials). `createMediaDispatchEngine` itself does no I/O to
 *  construct — only `.generate()` does — so building one per call costs nothing measurable. */
async function defaultGenerateMedia(
  request: MediaGenerationRequest,
  credentials: ProviderCredentials,
  options: { providerId: string; allowStubFallback: boolean }
): Promise<MediaGenerationResult> {
  const engine = createMediaDispatchEngine({
    credentials: { [options.providerId]: credentials },
    allowStubFallback: options.allowStubFallback,
  });
  return engine.generate(request);
}

/**
 * Resolves usable credentials for `providerId` — the saved workspace credential
 * ({@link resolveMediaProviderCredential}) first, falling through to
 * {@link resolveProviderCredentialsFromEnv} ONLY when nothing is saved at all (no row, or a row with
 * no key yet — both `null` from that function's own documented contract). A saved row that exists
 * but fails to DECRYPT throws `MediaProviderCredentialSecretStoreUnconfiguredError` from
 * `resolveMediaProviderCredential` itself and is deliberately NOT caught here — that is a broken
 * credential, not an absent one, and must surface as its own loud error rather than silently trying
 * the environment instead (see this file's own module doc).
 *
 * @returns `null` when neither source has anything usable — an absent/blank env value never counts
 *   as found (see `resolveProviderCredentialsFromEnv`'s own "`{}` when nothing set" contract).
 * @complexity O(1) beyond {@link resolveMediaProviderCredential}'s own cost (one workspace-scoped
 *   credential-row read, plus a decrypt only when a key is present).
 */
async function resolveCredentialForProvider(routeDeps: MediaGenerationToolDeps, providerId: string): Promise<ProviderCredentials | null> {
  const saved = await resolveMediaProviderCredential(
    { repo: routeDeps.mediaProviderCredentialRepo, sealer: routeDeps.siteAssistantSecretSealer },
    { workspaceId: routeDeps.workspaceId, providerId }
  );
  if (saved) {
    return { apiKey: saved.apiKey, ...(saved.baseUrl ? { baseUrl: saved.baseUrl } : {}) };
  }
  const fromEnv = resolveProviderCredentialsFromEnv(providerId, routeDeps.env ?? process.env);
  return fromEnv.apiKey ? fromEnv : null;
}

const CATALOG_BY_ID = indexCatalogById(mediaGenerationAgentToolCatalog);

const DOMAIN = "media-generation";

/**
 * This wiring layer's OWN risk classification, authored from what the one handler below actually
 * calls — see `DerivedRiskByToolId` in the kit for why it is independent of the catalog's own
 * `sideEffects` declaration.
 */
export const mediaGenerationDerivedRisk: DerivedRiskByToolId = new Map<string, AgentToolSideEffect>([
  // -> resolveMediaProviderCredential (a decrypting read) + one outbound generation call to the
  // vendor's API + uploadMedia (mediaRepo.save/blobRepo.save/renditionRepo.save) +
  // mediaContentTypeStore.set. A genuine durable Tovu-side write, same classification
  // media_upload_asset's own entry carries.
  ["media_generate_asset", "mutates-durable-state"],
]);

/**
 * Builds a filename for the generated asset from its prompt, so the uploaded asset's title
 * (`uploadMedia`'s own `deriveTitleFromFilename`, which strips the extension) reflects what was
 * actually generated rather than a generic placeholder. Bounded and sanitized: only
 * alphanumerics/spaces/hyphens survive, collapsed and trimmed, so a prompt containing path
 * separators, control characters, or pathological punctuation can never produce a surprising
 * filename — this value only ever reaches `uploadMedia`'s title-derivation, never a filesystem path.
 *
 * @complexity O(n) in `prompt.length`, once.
 */
function buildGeneratedFilename(prompt: string): string {
  const slug = prompt
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60);
  return `${slug || "generated-image"}.png`;
}

/** The only rejection worth decorating with the published schema — a caller-supplied `model` outside
 *  {@link IMAGE_MODEL_IDS}, which a DIFFERENT input would fix. Everything else this handler can
 *  throw (no credential configured, a vendor/network failure, an upload validation failure) is not a
 *  shape problem and is deliberately NOT wrapped in this class. */
export class MediaGenerationValidationError extends Error {}

/**
 * Validates the optional `model` field against the published, catalog-derived enum — the
 * handler-level enforcement the published schema's own `enum` cannot itself guarantee (see
 * `agent-tools.ts`'s `IMAGE_MODEL_IDS` doc for why). `undefined` defaults to {@link DEFAULT_MODEL},
 * matching the catalog description's own documented default.
 *
 * @throws {MediaGenerationValidationError} `raw` is present but not one of `IMAGE_MODEL_IDS`.
 * @complexity O(n) in `IMAGE_MODEL_IDS.length` (a fixed, catalog-bounded set) — a simple membership
 *   check, not worth a Set for a list this size.
 */
function requireImageModel(raw: string | undefined): string {
  if (raw === undefined) return DEFAULT_MODEL;
  if (!IMAGE_MODEL_IDS.includes(raw)) {
    throw new MediaGenerationValidationError(
      `'model' must be a registered image model — got '${raw}'. See this tool's own schema for the full list of ${IMAGE_MODEL_IDS.length} supported ids across every configured vendor.`
    );
  }
  return raw;
}

/**
 * Builds the "no credential configured" rejection for `providerId` — NOT a shape problem (retrying
 * the identical input can never fix it), so this is a plain `Error`, never schema-decorated, pointing
 * the caller at the one place a human can actually fix it. Names the vendor's own catalogue label
 * (e.g. "OpenAI", "Nano Banana") so the message stays meaningful for any provider, not just the one
 * this tool used to hardcode.
 *
 * @complexity O(1).
 */
function buildNoCredentialError(providerId: string): Error {
  const label = findProvider(providerId)?.label ?? providerId;
  const envCandidates = PROVIDER_CREDENTIAL_ENV_VARS[providerId] ?? [];
  const envNote = envCandidates.length > 0 ? ` (also checked ${envCandidates.join(", ")} in this process's environment — none were set)` : "";
  return new Error(
    `media_generate_asset: no ${label} media-provider credential is configured for this workspace${envNote}. ` +
      "An operator must add one in the admin under Media -> \"Media providers\" (Access Tokens' " +
      "counterpart for generation vendors) before this tool can generate an image with this model. Do not retry — " +
      "this will not resolve without that credential being added."
  );
}

/** What `media_generate_asset` returns — the SAME shape `media_upload_asset`/`media_list_assets`
 *  return (id/title/alt/caption/credit/sha256/status/version/publicUrl), so the model can chain
 *  straight into `media_update_metadata`/`media_trash_asset` off the returned `id` with no separate
 *  lookup, and use `publicUrl` to embed the image immediately. Declared locally rather than imported:
 *  `@jini-ai/cms/media/tool-registrations.ts`'s own equivalent view type is not part of that
 *  package's public surface (an internal projection, not a contract this domain depends on). */
interface GeneratedMediaView {
  id: string;
  title: string;
  alt: string;
  caption: string;
  credit: string;
  sha256: string;
  status: string;
  version: number;
  publicUrl: string | null;
  /** `true` only when the engine's own stub fallback rendered a deterministic placeholder instead of
   *  a real image (`MediaGenerationResult.usedStubFallback`, only reachable with `allowStubFallback`
   *  explicitly set — see `GENERATE_SCHEMA`). A placeholder must never be mistaken for a real
   *  generation, so this travels on every response rather than being omitted on the common path. */
  placeholder: boolean;
}

export function buildMediaGenerationRegistrations(routeDeps: MediaGenerationToolDeps): ToolRegistration[] {
  const handlers: Record<string, ToolHandler> = {
    media_generate_asset: async (ctx): Promise<{ media: GeneratedMediaView }> => {
      const input = requireInputRecord(ctx.input);
      const prompt = requireString(input, "prompt");
      await requireToolPermission(routeDeps, { principalId: ctx.principal.id, permission: "media.upload", entityType: "media" });

      return withSchemaOnRejection(
        { toolId: "media_generate_asset", catalog: CATALOG_BY_ID, isShapeRejection: (error) => error instanceof MediaGenerationValidationError },
        async () => {
          const model = requireImageModel(optionalString(input, "model"));
          const allowStubFallback = optionalBoolean(input, "allowStubFallback") ?? false;
          // Guaranteed non-null: `model` was just validated against `IMAGE_MODEL_IDS`, itself
          // derived from this same catalogue (`agent-tools.ts`'s own doc for both).
          const providerId = findMediaModel(model)!.provider;

          const credential = await resolveCredentialForProvider(routeDeps, providerId);
          if (!credential && !allowStubFallback) {
            throw buildNoCredentialError(providerId);
          }

          const generate = routeDeps.generateMedia ?? defaultGenerateMedia;
          const generated = await generate({ surface: "image", model, prompt }, credential ?? {}, { providerId, allowStubFallback });

          // A best-effort initial guess, corrected immediately below by a real sniff of the actual
          // bytes — most registered vendors return PNG (`dispatch/stub.ts`'s placeholder included),
          // but this is no longer an OpenAI-specific fact now that `model` can select any vendor.
          const contentType = "image/png";
          const { media } = await uploadMedia({
            deps: {
              clock: routeDeps.clock,
              idGen: routeDeps.idGen,
              mediaRepo: routeDeps.mediaRepo,
              blobRepo: routeDeps.assetBlobRepo,
              renditionRepo: routeDeps.assetRenditionRepo,
              blobStore: routeDeps.blobStore,
            },
            input: {
              workspaceId: routeDeps.workspaceId,
              bytes: generated.bytes,
              filename: buildGeneratedFilename(prompt),
              contentType,
              alt: optionalString(input, "alt"),
              caption: optionalString(input, "caption"),
              credit: optionalString(input, "credit"),
              createdByPrincipal: ctx.principal.id,
            },
          });

          // Same "record what the bytes actually are" write `routes/admin/media/upload.ts` performs
          // after every human upload — see that route's own doc for why this is sniffed rather than
          // trusted from the (here, fixed) `contentType` string.
          const sniffed = sniffContentType(generated.bytes);
          await routeDeps.mediaContentTypeStore.set({ workspaceId: routeDeps.workspaceId, sha256: media.source.sha256, contentType: sniffed });

          const urls = await resolveMediaPublicUrls(routeDeps, [media]);
          return {
            media: {
              id: media.id,
              title: media.title,
              alt: media.alt,
              caption: media.caption,
              credit: media.credit,
              sha256: media.source.sha256,
              status: media.status,
              version: media.version,
              publicUrl: urls.get(media.id) ?? null,
              placeholder: generated.usedStubFallback,
            },
          };
        }
      );
    },
  };

  return buildDomainRegistrations({
    domain: DOMAIN,
    catalogModule: "features/media-generation/agent-tools.ts",
    catalog: CATALOG_BY_ID,
    handlers,
    derivedRisk: mediaGenerationDerivedRisk,
  });
}

/**
 * Contributes `media-generation`'s AI tools to the assistant's catalog — called once by
 * `server/runtime/composition/tool-catalog-manifest.ts`'s `installFirstPartyToolContributors()`,
 * not by importing this module.
 */
export function contributeMediaGenerationTools(): ToolContributor {
  return { domain: DOMAIN, build: buildMediaGenerationRegistrations, risk: mediaGenerationDerivedRisk };
}
