import { createMediaDispatchEngine, type MediaGenerationRequest, type MediaGenerationResult, type ProviderCredentials } from "@jini-ai/integrations/media-providers";
import {
  buildDomainRegistrations,
  indexCatalogById,
  optionalString,
  requireInputRecord,
  requireString,
  requireToolPermission,
  withSchemaOnRejection,
  type AgentToolSideEffect,
  type DerivedRiskByToolId,
  type ToolHandler,
  type ToolRegistration,
} from "@jini-ai/cms/core";

import type { AuthorizeFn } from "../../contracts/core/commands/index.js";
import type { ToolContributor } from "#src/assistant/index";
import type { SecretSealerPort } from "../webhooks/index.js";
import {
  resolveMediaProviderCredential,
  sniffContentType,
  uploadMedia,
  type AssetBlobRepoPort,
  type AssetRenditionRepoPort,
  type BlobStorePort,
  type MediaProviderCredentialRepoPort,
  type MediaRepoPort,
  type TransformDefinitionRepoPort,
} from "../media/index.js";
import type { MediaContentTypeStorePort } from "../media/content-type-store.js";
import { resolveMediaPublicUrls } from "../media/tool-registrations.js";
import { mediaGenerationAgentToolCatalog, OPENAI_IMAGE_MODELS } from "./agent-tools.js";

/**
 * @file Wires `agent-tools.ts`'s one-tool catalog onto the real pipeline: decrypt the workspace's
 * saved OpenAI media-provider credential
 * (`features/media/provider-credential-store.ts`'s `resolveMediaProviderCredential`, added
 * alongside this file specifically for this call) -> generate one image through the vendor dispatch
 * engine (`@jini-ai/integrations/media-providers`'s `createMediaDispatchEngine`, previously imported
 * nowhere under `apps/`) -> upload the generated bytes through the SAME `uploadMedia` service
 * `media_upload_asset` (`@jini-ai/cms/media`) already calls, so a generated asset is
 * indistinguishable in the media library from a human-uploaded one.
 *
 * A brand-new domain rather than a 5th entry on `media`'s existing catalog — see this dispatch's own
 * design note: media's 4-tool catalog is `@jini-ai/cms`-owned (shared across every host of that
 * package) with its own "wire the ENTIRE catalog" tripwire test on both sides; this tool's whole
 * pipeline (Tovu's credential store, the dispatch engine, Tovu's ADR-027 URL contract) is genuinely
 * host-specific glue, the same category `custom-credentials`/`site-inspection`/`site-evidence`
 * already established as their own small standalone domains rather than bolt-ons to an existing one.
 *
 * `media.upload`-gated — the same permission `media_upload_asset` uses, not a new
 * `media.generate`/etc. permission: what this tool actually DOES, durably, is create exactly the
 * kind of row a human upload creates (`mediaDerivedRisk`'s own "classify from what is actually
 * called" discipline, mirrored here) — the only difference is the byte source. Reusing the existing
 * permission also means no seed/role change is needed for the owner's existing wildcard grant to
 * cover it immediately.
 */

export interface MediaGenerationToolDeps {
  authorize: AuthorizeFn;
  workspaceId: string;
  clock: { nowIso(): string };
  idGen: { newId(): string };
  mediaRepo: MediaRepoPort;
  assetBlobRepo: AssetBlobRepoPort;
  assetRenditionRepo: AssetRenditionRepoPort;
  blobStore: BlobStorePort;
  mediaContentTypeStore: MediaContentTypeStorePort;
  transformDefinitionRepo: TransformDefinitionRepoPort;
  mediaProviderCredentialRepo: MediaProviderCredentialRepoPort;
  /** Same field name `RouteDeps` (and `CustomCredentialsToolDeps`) already uses for this shared
   *  sealer instance — see `provider-credential-store.ts`'s own header for why this store seals
   *  with no `aad`, the one respect in which its usage here differs from `custom-credentials`'s. */
  siteAssistantSecretSealer: SecretSealerPort;
  /**
   * The testability seam for the one real external I/O this domain performs (the 5a1 pre-check this
   * skill's workflow requires before writing the handler): a paid, non-deterministic third-party
   * call has no business running inside a unit test. Defaults to a thin wrapper over
   * `@jini-ai/integrations/media-providers`'s real `createMediaDispatchEngine` — see
   * {@link defaultGenerateMedia} — so production wiring supplies nothing extra; a test overrides
   * this with a fake that returns fixed bytes with no network access at all.
   */
  generateMedia?: (request: MediaGenerationRequest, credentials: ProviderCredentials) => Promise<MediaGenerationResult>;
}

/** The one OpenAI provider id this tool resolves a credential for — the engine-canonical id
 *  `@jini-ai/integrations/media-providers`'s catalogue and `provider-credential-store.ts`'s
 *  `KNOWN_PROVIDER_IDS` both use. */
const OPENAI_PROVIDER_ID = "openai";

/** `media_generate_asset`'s default model when `model` is omitted — OpenAI's current flagship image
 *  model (`@jini-ai/integrations/media-providers`'s `IMAGE_MODELS`, `default: true`). */
const DEFAULT_MODEL = "gpt-image-2";

/** {@link MediaGenerationToolDeps.generateMedia}'s real, production implementation — a fresh engine
 *  per call because credentials are resolved fresh per call too (a rotated key must never reuse a
 *  stale boot-time singleton's credentials). `createMediaDispatchEngine` itself does no I/O to
 *  construct — only `.generate()` does — so building one per call costs nothing measurable. */
async function defaultGenerateMedia(request: MediaGenerationRequest, credentials: ProviderCredentials): Promise<MediaGenerationResult> {
  const engine = createMediaDispatchEngine({ credentials: { [OPENAI_PROVIDER_ID]: credentials } });
  return engine.generate(request);
}

const CATALOG_BY_ID = indexCatalogById(mediaGenerationAgentToolCatalog);

const DOMAIN = "media-generation";

/**
 * This wiring layer's OWN risk classification, authored from what the one handler below actually
 * calls — see `DerivedRiskByToolId` in the kit for why it is independent of the catalog's own
 * `sideEffects` declaration.
 */
export const mediaGenerationDerivedRisk: DerivedRiskByToolId = new Map<string, AgentToolSideEffect>([
  // -> resolveMediaProviderCredential (a decrypting read) + one outbound generation call to the
  // vendor's API + uploadMedia (mediaRepo.save/blobRepo.save/renditionRepo.save) +
  // mediaContentTypeStore.set. A genuine durable Tovu-side write, same classification
  // media_upload_asset's own entry carries.
  ["media_generate_asset", "mutates-durable-state"],
]);

/**
 * Builds a filename for the generated asset from its prompt, so the uploaded asset's title
 * (`uploadMedia`'s own `deriveTitleFromFilename`, which strips the extension) reflects what was
 * actually generated rather than a generic placeholder. Bounded and sanitized: only
 * alphanumerics/spaces/hyphens survive, collapsed and trimmed, so a prompt containing path
 * separators, control characters, or pathological punctuation can never produce a surprising
 * filename — this value only ever reaches `uploadMedia`'s title-derivation, never a filesystem path.
 *
 * @complexity O(n) in `prompt.length`, once.
 */
function buildGeneratedFilename(prompt: string): string {
  const slug = prompt
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60);
  return `${slug || "generated-image"}.png`;
}

/** The only rejection worth decorating with the published schema — a caller-supplied `model` outside
 *  {@link OPENAI_IMAGE_MODELS}, which a DIFFERENT input would fix. Everything else this handler can
 *  throw (no credential configured, a vendor/network failure, an upload validation failure) is not a
 *  shape problem and is deliberately NOT wrapped in this class. */
export class MediaGenerationValidationError extends Error {}

/**
 * Validates the optional `model` field against the fixed, published enum — the handler-level
 * enforcement the published schema's own `enum` cannot itself guarantee (see
 * `agent-tools.ts`'s `OPENAI_IMAGE_MODELS` doc for why). `undefined` defaults to
 * {@link DEFAULT_MODEL}, matching the catalog description's own documented default.
 *
 * @throws {MediaGenerationValidationError} `raw` is present but not one of `OPENAI_IMAGE_MODELS`.
 * @complexity O(1) — a fixed 3-entry set membership check.
 */
function requireOpenAiImageModel(raw: string | undefined): string {
  if (raw === undefined) return DEFAULT_MODEL;
  if (!(OPENAI_IMAGE_MODELS as readonly string[]).includes(raw)) {
    throw new MediaGenerationValidationError(`'model' must be one of ${OPENAI_IMAGE_MODELS.join(", ")} — got '${raw}'`);
  }
  return raw;
}

/**
 * Builds the "no credential configured" rejection — NOT a shape problem (retrying the identical
 * input can never fix it), so this is a plain `Error`, never schema-decorated, pointing the caller
 * at the one place a human can actually fix it.
 *
 * @complexity O(1).
 */
function buildNoCredentialError(): Error {
  return new Error(
    "media_generate_asset: no OpenAI media-provider credential is configured for this workspace. " +
      "An operator must add one in the admin under Media -> \"Media providers\" (Access Tokens' " +
      "counterpart for generation vendors) before this tool can generate an image. Do not retry — " +
      "this will not resolve without that credential being added."
  );
}

/** What `media_generate_asset` returns — the SAME shape `media_upload_asset`/`media_list_assets`
 *  return (id/title/alt/caption/credit/sha256/status/version/publicUrl), so the model can chain
 *  straight into `media_update_metadata`/`media_trash_asset` off the returned `id` with no separate
 *  lookup, and use `publicUrl` to embed the image immediately. Declared locally rather than imported:
 *  `@jini-ai/cms/media/tool-registrations.ts`'s own equivalent view type is not part of that
 *  package's public surface (an internal projection, not a contract this domain depends on). */
interface GeneratedMediaView {
  id: string;
  title: string;
  alt: string;
  caption: string;
  credit: string;
  sha256: string;
  status: string;
  version: number;
  publicUrl: string | null;
}

export function buildMediaGenerationRegistrations(routeDeps: MediaGenerationToolDeps): ToolRegistration[] {
  const handlers: Record<string, ToolHandler> = {
    media_generate_asset: async (ctx): Promise<{ media: GeneratedMediaView }> => {
      const input = requireInputRecord(ctx.input);
      const prompt = requireString(input, "prompt");
      await requireToolPermission(routeDeps, { principalId: ctx.principal.id, permission: "media.upload", entityType: "media" });

      return withSchemaOnRejection(
        { toolId: "media_generate_asset", catalog: CATALOG_BY_ID, isShapeRejection: (error) => error instanceof MediaGenerationValidationError },
        async () => {
          const model = requireOpenAiImageModel(optionalString(input, "model"));

          const credential = await resolveMediaProviderCredential(
            { repo: routeDeps.mediaProviderCredentialRepo, sealer: routeDeps.siteAssistantSecretSealer },
            { workspaceId: routeDeps.workspaceId, providerId: OPENAI_PROVIDER_ID }
          );
          if (!credential) {
            throw buildNoCredentialError();
          }

          const generate = routeDeps.generateMedia ?? defaultGenerateMedia;
          const generated = await generate(
            { surface: "image", model, prompt },
            { apiKey: credential.apiKey, ...(credential.baseUrl ? { baseUrl: credential.baseUrl } : {}) }
          );

          const contentType = "image/png"; // Every OpenAI image adapter response is PNG bytes — `dispatch/providers/openai.ts`'s own `suggestedExt: '.png'`.
          const { media } = await uploadMedia({
            deps: {
              clock: routeDeps.clock,
              idGen: routeDeps.idGen,
              mediaRepo: routeDeps.mediaRepo,
              blobRepo: routeDeps.assetBlobRepo,
              renditionRepo: routeDeps.assetRenditionRepo,
              blobStore: routeDeps.blobStore,
            },
            input: {
              workspaceId: routeDeps.workspaceId,
              bytes: generated.bytes,
              filename: buildGeneratedFilename(prompt),
              contentType,
              alt: optionalString(input, "alt"),
              caption: optionalString(input, "caption"),
              credit: optionalString(input, "credit"),
              createdByPrincipal: ctx.principal.id,
            },
          });

          // Same "record what the bytes actually are" write `routes/admin/media/upload.ts` performs
          // after every human upload — see that route's own doc for why this is sniffed rather than
          // trusted from the (here, fixed) `contentType` string.
          const sniffed = sniffContentType(generated.bytes);
          await routeDeps.mediaContentTypeStore.set({ workspaceId: routeDeps.workspaceId, sha256: media.source.sha256, contentType: sniffed });

          const urls = await resolveMediaPublicUrls(routeDeps, [media]);
          return {
            media: {
              id: media.id,
              title: media.title,
              alt: media.alt,
              caption: media.caption,
              credit: media.credit,
              sha256: media.source.sha256,
              status: media.status,
              version: media.version,
              publicUrl: urls.get(media.id) ?? null,
            },
          };
        }
      );
    },
  };

  return buildDomainRegistrations({
    domain: DOMAIN,
    catalogModule: "features/media-generation/agent-tools.ts",
    catalog: CATALOG_BY_ID,
    handlers,
    derivedRisk: mediaGenerationDerivedRisk,
  });
}

/**
 * Contributes `media-generation`'s AI tools to the assistant's catalog — called once by
 * `server/runtime/composition/tool-catalog-manifest.ts`'s `installFirstPartyToolContributors()`,
 * not by importing this module.
 */
export function contributeMediaGenerationTools(): ToolContributor {
  return { domain: DOMAIN, build: buildMediaGenerationRegistrations, risk: mediaGenerationDerivedRisk };
}
