import assert from "node:assert/strict";
import test from "node:test";

import { checkBuiltThemeConformance } from "../build-conformance";
import { planAssetRelocation, rewriteBundlerHtml } from "../code-tier-asset-normalizer";
import { TOKEN_STYLESHEET_SENTINEL } from "../static-asset-contract";

/**
 * @file Unit coverage for `code-tier-asset-normalizer.ts`'s pure planning/rewriting core, plus one
 * fixture-based end-to-end test rooted in a REAL Angular build.
 *
 * `REAL_ANGULAR_INDEX_HTML` below is not hand-authored fixture markup — it is the verbatim `index.html`
 * a real `ng build` (Angular CLI 21.2.21, `@angular/build:application`, `outputHashing: "none"`,
 * `optimization.styles.inlineCritical: false`) produced, captured during
 * `ADS-memory/reports/spikes/20260812-angular-code-tier-build-output-verification.md`'s Phase 1
 * verification. It is frozen here rather than regenerated by a live `ng build` subprocess (the way
 * `astro-real-bundler-conformance.test.ts` runs a real `astro build`) because Angular is not a
 * devDependency of this repo — that is a pending cost/benefit decision (see this module's own file
 * header and the spike doc), not an oversight. This test is real-bundler-DERIVED evidence, but it cannot
 * catch a future Angular version changing its output shape the way a live-build test would; treat it as
 * weaker than the Astro precedent until/unless Angular is added as a devDependency and this is upgraded
 * to a live build.
 */

const REAL_ANGULAR_INDEX_HTML =
  '<!doctype html>\n' +
  '<html lang="en">\n' +
  "<head>\n" +
  '  <meta charset="utf-8">\n' +
  "  <title>ProbeApp</title>\n" +
  '  <base href="/">\n' +
  '  <meta name="viewport" content="width=device-width, initial-scale=1">\n' +
  '  <link rel="icon" type="image/x-icon" href="favicon.ico">\n' +
  '<link rel="stylesheet" href="styles.css"></head>\n' +
  "<body>\n" +
  "  <app-root></app-root>\n" +
  '<script src="main.js" type="module"></script></body>\n' +
  "</html>\n";

const REAL_ANGULAR_OUTPUT_FILES = ["index.html", "favicon.ico", "main.js", "styles.css"];

test("planAssetRelocation moves top-level .css to css/ and .js/.mjs to js/, leaving everything else alone", () => {
  const plan = planAssetRelocation({ fileNames: ["index.html", "favicon.ico", "main.js", "styles.css", "polyfills.mjs"] });

  assert.deepEqual(
    [...plan.relocations].sort((a, b) => a.from.localeCompare(b.from)),
    [
      { from: "main.js", to: "js/main.js" },
      { from: "polyfills.mjs", to: "js/polyfills.mjs" },
      { from: "styles.css", to: "css/styles.css" },
    ]
  );
});

test("planAssetRelocation rejects a fileName that is already nested -- flat output is the precondition, not something to silently tolerate", () => {
  assert.throws(() => planAssetRelocation({ fileNames: ["css/already-nested.css"] }), RangeError);
});

test("rewriteBundlerHtml replaces the plain build-output stylesheet tag with the EXACT sentinel constant, not a hand-reconstructed copy", () => {
  const plan = planAssetRelocation({ fileNames: ["styles.css"] });
  const html = '<head><link rel="stylesheet" href="styles.css"></head>';

  const rewritten = rewriteBundlerHtml({ html, plan, primaryStylesheetFile: "styles.css" });

  assert.equal(rewritten, `<head>${TOKEN_STYLESHEET_SENTINEL}</head>`);
});

test("rewriteBundlerHtml rewrites a script src to the ../js/ form while preserving other attributes on the tag", () => {
  const plan = planAssetRelocation({ fileNames: ["styles.css", "main.js"] });
  const html = '<link rel="stylesheet" href="styles.css"><script src="main.js" type="module"></script>';

  const rewritten = rewriteBundlerHtml({ html, plan, primaryStylesheetFile: "styles.css" });

  assert.ok(rewritten.includes('<script src="../js/main.js" type="module"></script>'), rewritten);
});

test("rewriteBundlerHtml anchors on the FULL attribute value -- 'main.js' does not falsely match inside 'vendor-main.js'", () => {
  const plan = planAssetRelocation({ fileNames: ["styles.css", "main.js"] });
  const html = '<link rel="stylesheet" href="styles.css"><script src="vendor-main.js"></script><script src="main.js"></script>';

  const rewritten = rewriteBundlerHtml({ html, plan, primaryStylesheetFile: "styles.css" });

  assert.ok(rewritten.includes('src="vendor-main.js"'), "unrelated similarly-named file must be left untouched");
  assert.ok(rewritten.includes('src="../js/main.js"'), "the exact-match file must still be rewritten");
});

test("rewriteBundlerHtml throws when primaryStylesheetFile is not among the plan's relocated CSS files", () => {
  const plan = planAssetRelocation({ fileNames: ["main.js"] }); // no CSS at all
  assert.throws(
    () => rewriteBundlerHtml({ html: "<html></html>", plan, primaryStylesheetFile: "styles.css" }),
    /not among the plan's relocated CSS files/
  );
});

test("rewriteBundlerHtml throws loudly, not silently, when the plain tag shape is missing (e.g. Beasties left enabled)", () => {
  const plan = planAssetRelocation({ fileNames: ["styles.css"] });
  // Beasties' critical-CSS inlining shape (see this module's file header, finding 4) -- not the plain tag.
  const html =
    '<style>body{margin:0}</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media=\'all\'">';

  assert.throws(
    () => rewriteBundlerHtml({ html, plan, primaryStylesheetFile: "styles.css" }),
    /expected the plain build-output tag/
  );
});

test("end-to-end: normalizing a REAL Angular build's index.html produces output the actual conformance gate accepts cleanly", () => {
  const plan = planAssetRelocation({ fileNames: REAL_ANGULAR_OUTPUT_FILES });
  const normalized = rewriteBundlerHtml({ html: REAL_ANGULAR_INDEX_HTML, plan, primaryStylesheetFile: "styles.css" });

  // Exactly one sentinel occurrence, and the script tag correctly relocated.
  assert.equal(normalized.split(TOKEN_STYLESHEET_SENTINEL).length - 1, 1);
  assert.ok(normalized.includes('<script src="../js/main.js" type="module">'));

  // Feed the normalized page through the REAL, imported checkBuiltThemeConformance -- not a
  // reimplementation. checkArtifactHashes reads real bytes off disk via themeDir, which this
  // pure-function test does not provide, so this scopes its assertion to the two rules a page's raw
  // HTML can actually be checked against without a real on-disk tree (stylesheet-sentinel, asset-path) --
  // matching how `astro-real-bundler-conformance.test.ts` reasons about the same two rules.
  const issues = checkBuiltThemeConformance({
    themeId: "angular-probe",
    themeDir: "/nonexistent-for-this-html-only-check",
    pages: { index: normalized },
    partials: {},
    artifactHashes: {},
  });

  const relevantIssues = issues.filter((issue) => issue.rule === "stylesheet-sentinel" || issue.rule === "asset-path");
  assert.deepEqual(relevantIssues, []);
});
