import assert from "node:assert/strict";
import test from "node:test";

import { constraintSql, createTableSql, fitIdentifier, indexSql, qualified, quoteIdent, quoteLiteral, reseedIdentitySql } from "../postgres-ddl.js";
import type { TransferTable } from "../table-catalog.js";

const table = (overrides: Partial<TransferTable> = {}): TransferTable => ({ name: "items", columns: [{ name: "parent_id", sqlType: "bigint", notNull: false }, { name: "code", sqlType: "text", notNull: false }], primaryKey: [], indexes: [], foreignKeys: [], checks: [], ...overrides });
const parentColumns = [{ name: "id", sqlType: "bigint", notNull: true }, { name: "code", sqlType: "text", notNull: false }];

test("SQL quoting doubles identifier quotes and literal apostrophes", () => {
  assert.equal(quoteIdent('a"b'), '"a""b"');
  assert.equal(quoteLiteral("O'Brien"), "'O''Brien'");
  assert.equal(qualified('site"a', "order"), '"site""a"."order"');
});

test("identifiers fit the 63-byte limit and retain an independently pinned digest beyond the boundary", () => {
  // F1.1/F4.1: SHA-256 pins computed independently of fitIdentifier; byte, not character, boundary.
  assert.equal(fitIdentifier("a".repeat(63)), "a".repeat(63));
  assert.equal(fitIdentifier("a".repeat(64)), `${"a".repeat(54)}_ffe054fe`);
  assert.equal(fitIdentifier("é".repeat(40)), `${"é".repeat(27)}_84fe2e03`);
  assert.equal(fitIdentifier(`${"a".repeat(63)}b`), `${"a".repeat(54)}_97aa7c54`);
  assert.equal(fitIdentifier(`${"a".repeat(63)}c`), `${"a".repeat(54)}_36fc0615`);
});

test("DDL carries composite primary keys, identity, defaults and both unique and ordinary indexes", () => {
  const t = table({ columns: [{ name: "id", sqlType: "bigint", notNull: true, identity: "BY DEFAULT" }, { name: "label", sqlType: "text", notNull: false, default: "'new'" }], primaryKey: ["id", "label"], indexes: [{ name: "label_key", columns: ["label"], unique: true }, { name: "id_idx", columns: ["id"], unique: false }] });
  assert.equal(createTableSql("copy", t), 'CREATE TABLE "copy"."items" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "label" text DEFAULT \'new\', PRIMARY KEY ("id", "label"));\n');
  assert.equal(indexSql("copy", t), 'CREATE UNIQUE INDEX "label_key" ON "copy"."items" ("label");\nCREATE INDEX "id_idx" ON "copy"."items" ("id");\n');
  assert.equal(reseedIdentitySql("copy", t), 'DO $tovu$ BEGIN PERFORM setval(pg_get_serial_sequence(\'"copy"."items"\', \'id\'), GREATEST(COALESCE((SELECT max("id") FROM "copy"."items"), 0), 1), COALESCE((SELECT max("id") FROM "copy"."items"), 0) >= 1); END $tovu$;\n');
  assert.equal(reseedIdentitySql("copy", table()), "");
});

test("foreign keys are omitted for excluded parents, non-unique columns and mismatched arity", () => {
  // F4.4: the mismatched pair is unique, so only the arity guard can reject it.
  const parent = table({ name: "parent", columns: parentColumns, primaryKey: ["id"], indexes: [{ name: "code_idx", columns: ["code"], unique: false }, { name: "pair_key", columns: ["id", "code"], unique: true }] });
  for (const [foreignTable, foreignColumns] of [["missing", ["id"]], ["parent", ["code"]], ["parent", ["id", "code"]]] as const) {
    const child = table({ foreignKeys: [{ name: "fk", columns: ["parent_id"], foreignTable, foreignColumns, onDelete: "cascade", onUpdate: "restrict" }] });
    assert.equal(constraintSql("copy", [parent, child]), "CREATE TEMP TABLE _tovu_unvalidated (name text NOT NULL) ON COMMIT DROP;\n");
  }
});

test("unique-parent and implicit-primary-key references are accepted; unsafe actions default to NO ACTION", () => {
  const parent = table({ name: "parent", columns: parentColumns, primaryKey: ["id"], indexes: [{ name: "code_key", columns: ["code"], unique: true }] });
  const child = table({ foreignKeys: [
    { name: "by_code", columns: ["code"], foreignTable: "parent", foreignColumns: ["code"], onDelete: "set null", onUpdate: "not SQL" },
    { name: "by_id", columns: ["parent_id"], foreignTable: "parent", foreignColumns: null, onDelete: "cascade", onUpdate: "restrict" },
  ] });
  assert.equal(constraintSql("copy", [parent, child]),
    'CREATE TEMP TABLE _tovu_unvalidated (name text NOT NULL) ON COMMIT DROP;\n' +
    'ALTER TABLE "copy"."items" ADD CONSTRAINT "by_code" FOREIGN KEY ("code") REFERENCES "copy"."parent" ("code") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;\n' +
    'ALTER TABLE "copy"."items" ADD CONSTRAINT "by_id" FOREIGN KEY ("parent_id") REFERENCES "copy"."parent" ("id") ON DELETE CASCADE ON UPDATE RESTRICT NOT VALID;\n' +
    'DO $tovu$ BEGIN\n' +
    '  BEGIN ALTER TABLE "copy"."items" VALIDATE CONSTRAINT "by_code";\n  EXCEPTION WHEN foreign_key_violation OR check_violation THEN INSERT INTO pg_temp._tovu_unvalidated VALUES (\'items.by_code\'); END;\n' +
    '  BEGIN ALTER TABLE "copy"."items" VALIDATE CONSTRAINT "by_id";\n  EXCEPTION WHEN foreign_key_violation OR check_violation THEN INSERT INTO pg_temp._tovu_unvalidated VALUES (\'items.by_id\'); END;\nEND $tovu$;\n');
});
