import type { DbMessages, DbTransferMessages } from "@jini-ai/db/tools";

/**
 * @file Tovu's copy for the `@jini-ai/db/tools` transfer tools. Jini's defaults speak of "the
 * source"; a Tovu site's transfer tools have always said "this site", and the four descriptions are
 * the bytes `features/database/__tests__/db-tool-descriptors.snapshot.unit.test.ts` pins from the
 * pre-extraction catalog. `plan` names the real schemas from `TRANSFER_NAMING` ('tovu', 'tovu_').
 */
export const TOVU_TRANSFER_MESSAGES: DbTransferMessages & Pick<DbMessages, "privateAreasTaken" | "noDestination" | "uncheckedLinks" | "destinationSaved" | "missingSourceTable" | "missingSourceColumn"> = {
  planIdDescription: "The planId database_transfer_plan returned. Single-use; valid for 10 minutes.",
  plan: ({ naming }) => `Plans a COPY of this site's data into a Postgres database (for example 'move/transfer/copy my data to Postgres'). The site keeps running on its built-in storage; this only makes a copy, into the site's own private area (Postgres schema) on that database: '${naming.defaultSchema}' for the first site copied there, '${naming.schemaPrefix}<site name>' for any other, and always the same one for this site afterwards. Several sites can share one database; each copy replaces only its own area. Read-only: it snapshots the site database, connects to the saved destination, and counts what would be copied. Logins, saved keys and secret settings are never copied; photos and files stay where they are. No input: the destination is the one the human saved with database_transfer_set_destination. Returns {planned: true, planId, expiresAt, destination: {host, port, database, user}, area (the schema), snapshotAt, tableCount, rowCount, replaces (the earlier copy's time, or null), leftOut, notes, nextStep}, or {planned: false, code, message} (codes: NO_DESTINATION, UNREACHABLE, SERVER_TOO_OLD, NO_CREATE_PERMISSION, TARGET_NOT_OURS, DATABASE_SNAPSHOT_FAILED, SCHEMA_MISMATCH, UNAVAILABLE). Tell the human in plain words what will be copied, then call database_transfer_run with the planId.`,
  setDestination: "Asks the human where a copy of this site's data should go: shows a private form where they paste a Postgres database address. HUMAN-GATED: this one call shows the form and WAITS. You never see the address, and must never ask for it in chat; if the human pastes one into the chat anyway, do not repeat it, call this tool, and suggest they change that database password. Checks that the database can be reached before saving it (one destination per site; saving replaces the earlier one). Returns {saved: true, destination: {host, port, database, user}, replaces (the time of a copy this site already made there, or null)}, {saved: false, code, message} (INVALID_CONNECTION_STRING, UNREACHABLE, SERVER_TOO_OLD, NO_CREATE_PERMISSION, TARGET_NOT_OURS), or {saved: false, reason} (cancelled, expired, abandoned). Then call database_transfer_plan.",
  status: "Reports where this site's data copy goes and how the last copy went ('is my data copied?', 'when was the last copy?'). Read-only. Returns {destination: {host, port, database, user} or null, lastRun: {copied: true, snapshotAt, tableCount, rowCount} or {copied: false, snapshotAt, code, message} or null (since the server started), copyOnDestination: {site, snapshotAt} or null, or {unreachable: message}}.",
  run: "Copies the data planned by database_transfer_plan. A first copy runs immediately without a confirmation card. Replacing an earlier copy permanently deletes its destination schema: this one call shows a Copy/Cancel card and WAITS; there is no second call. On Copy it writes the planned snapshot as one transaction into this site's private area (this site's earlier copy is replaced; other sites' copies and anything else in the database are untouched), checks every table's row count, and returns {copied: true, destination, area, snapshotAt, tableCount, rowCount, tables: [{name, rows}]}. Any failure throws the copy away and keeps the earlier one: {copied: false, cancelled: false, code, message} (TARGET_NOT_OURS, COPY_FAILED, COUNT_MISMATCH, PLAN_NOT_FOUND, PLAN_EXPIRED). Cancel returns {copied: false, cancelled: true}.",
  privateAreasTaken: ({ where }) => `every private area this site could use in ${where} already holds other data. Nothing will be overwritten.`,
  noDestination: "no destination database is saved for this site yet",
  uncheckedLinks: "Some copied rows point at records that no longer exist in this site's data. Those links are kept but marked unchecked on the destination; everything was still copied.",
  destinationSaved: ({ database, host }) => `Copies of this site's data will go to ${database} on ${host}.`,
  missingSourceTable: ({ table }) => `this site's database has no '${table}' table`,
  missingSourceColumn: ({ table, column }) => `this site's database has no '${table}.${column}' column`,
};
