import type { ToolRegistration } from '@jini-ai/core';
/** Owner decision 2026-10-07 supersedes the 09-28 write-shaped-input always-ask rule.
 * ONE reviewed CMS table: read/edit run directly; trash/delete/restore-over-existing/publish ask.
 * Handler entries retain their specific trust, delivery, credential or replacement checks.
 * Each row was checked against its risk declaration and handler (report links the sources).
 * New native registrations fail closed until a row is added here. */
export type ToolApprovalClass = 'read' | 'edit' | 'trash' | 'delete' | 'restore-over-existing' | 'publish' | 'safety';
export interface ToolApprovalPolicy { readonly class: ToolApprovalClass; readonly confirmation: 'direct' | 'policy' | 'handler'; readonly rule?: 'create-status' | 'update-status' | 'duplicate-status' | 'http-method' | 'page-control' | 'export-commit' }
export const TOOL_APPROVAL_POLICY: Readonly<Record<string, ToolApprovalPolicy>> = {
  // The collapsed cards dispatch the original, independently classified read handlers.
  'content_read.backup_restore_point': { class: 'read', confirmation: 'direct' },
  'content_read.collection_content_type': { class: 'read', confirmation: 'direct' },
  'content_read.collection_entry': { class: 'read', confirmation: 'direct' },
  'content_read.comment_moderation_queue': { class: 'read', confirmation: 'direct' },
  'content_read.content_post': { class: 'read', confirmation: 'direct' },
  'content_read.custom_credential': { class: 'read', confirmation: 'direct' },
  'content_read.database_pending_migration': { class: 'read', confirmation: 'direct' },
  'content_read.database_restore_point': { class: 'read', confirmation: 'direct' },
  'content_read.external_mcp': { class: 'read', confirmation: 'direct' },
  'content_read.form_definition': { class: 'read', confirmation: 'direct' },
  'content_read.identity_policy': { class: 'read', confirmation: 'direct' },
  'content_read.identity_role': { class: 'read', confirmation: 'direct' },
  'content_read.identity_user': { class: 'read', confirmation: 'direct' },
  'content_read.media_asset': { class: 'read', confirmation: 'direct' },
  'content_read.member': { class: 'read', confirmation: 'direct' },
  'content_read.menu': { class: 'read', confirmation: 'direct' },
  'content_read.newsletter_campaign': { class: 'read', confirmation: 'direct' },
  'content_read.newsletter_list': { class: 'read', confirmation: 'direct' },
  'content_read.plugin': { class: 'read', confirmation: 'direct' },
  'content_read.post': { class: 'read', confirmation: 'direct' },
  'content_read.redirect': { class: 'read', confirmation: 'direct' },
  'content_read.seo_entry_meta': { class: 'read', confirmation: 'direct' },
  'content_read.setting_definition': { class: 'read', confirmation: 'direct' },
  'content_read.taxonomy': { class: 'read', confirmation: 'direct' },
  'content_read.theme': { class: 'read', confirmation: 'direct' },
  'content_read.webhook_subscription': { class: 'read', confirmation: 'direct' },
  'content_read.widget_instance': { class: 'read', confirmation: 'direct' },
  'content_read.widget_region': { class: 'read', confirmation: 'direct' },
  'content_read.workspace': { class: 'read', confirmation: 'direct' },
  'page.find_elements': { class: 'read', confirmation: 'direct' },
  'page.highlight': { class: 'read', confirmation: 'direct' },
  'page.scroll_to': { class: 'read', confirmation: 'direct' },
  // A click's effect is opaque. Reviewed ordinary install controls are direct; all other
  // clicks retain explicit consent, including every destructive final-dialog button.
  'page.click': { class: 'safety', confirmation: 'policy', rule: 'page-control' },
  'page.fill': { class: 'edit', confirmation: 'direct' },
  'page.select_option': { class: 'edit', confirmation: 'direct' },
  'page.navigate': { class: 'edit', confirmation: 'direct' },
  'chat.send_message': { class: 'edit', confirmation: 'direct' },
  'chat.set_draft': { class: 'edit', confirmation: 'direct' },
  'chat.select_agent': { class: 'edit', confirmation: 'direct' },
  'chat.cancel_run': { class: 'edit', confirmation: 'direct' },
  // Local view reset keeps stored conversations/messages; it is not a delete.
  'chat.reset_conversation': { class: 'edit', confirmation: 'direct' },
  'chat.set_working_directory': { class: 'edit', confirmation: 'direct' },
  'chat.get_state': { class: 'read', confirmation: 'direct' },
  // Opens the existing Publish dialog; the final submit remains a human control.
  'admin.publish_content': { class: 'edit', confirmation: 'direct' },
  media_promote_chat_attachment: { class: 'edit', confirmation: 'direct' },
  chat_list_pending_attachments: { class: 'read', confirmation: 'direct' },
  'admin.capture_screenshot': { class: 'read', confirmation: 'direct' },

  agent_plugin_connect: { class: 'safety', confirmation: 'handler' },
  agent_plugin_set_access_token: { class: 'safety', confirmation: 'handler' },
  agent_plugin_write_note: { class: 'safety', confirmation: 'handler' },
  agent_plugins_install: { class: 'edit', confirmation: 'direct' },
  analytics_list_recent_hits: { class: 'read', confirmation: 'direct' },
  assistant_admin_screen_link: { class: 'read', confirmation: 'direct' },
  assistant_ask_choice: { class: 'read', confirmation: 'direct' },
  assistant_demo_a2ui: { class: 'read', confirmation: 'direct' },
  assistant_demo_choices: { class: 'read', confirmation: 'direct' },
  assistant_demo_image: { class: 'read', confirmation: 'direct' },
  assistant_render_ui: { class: 'read', confirmation: 'direct' },
  site_backup_plan: { class: 'read', confirmation: 'direct' },
  backup_create_restore_point: { class: 'edit', confirmation: 'direct' },
  backup_execute_restore: { class: 'restore-over-existing', confirmation: 'handler' },
  backup_get_capabilities: { class: 'read', confirmation: 'direct' },
  backup_list_restore_points: { class: 'read', confirmation: 'direct' },
  backup_plan_restore: { class: 'read', confirmation: 'direct' },
  change_sets_list: { class: 'read', confirmation: 'direct' },
  change_sets_revert: { class: 'restore-over-existing', confirmation: 'policy' },
  collections_content_type_define: { class: 'edit', confirmation: 'direct' },
  collections_content_type_deprecate: { class: 'edit', confirmation: 'direct' },
  collections_content_type_list: { class: 'read', confirmation: 'direct' },
  collections_content_type_reactivate: { class: 'edit', confirmation: 'direct' },
  collections_content_type_tombstone: { class: 'trash', confirmation: 'policy' },
  collections_content_type_update_fields: { class: 'edit', confirmation: 'direct' },
  collections_entry_create: { class: 'edit', confirmation: 'direct' },
  collections_entry_list: { class: 'read', confirmation: 'direct' },
  collections_entry_publish: { class: 'publish', confirmation: 'policy' },
  collections_entry_unpublish: { class: 'publish', confirmation: 'policy' },
  collections_entry_update: { class: 'edit', confirmation: 'direct' },
  comments_approve_comment: { class: 'publish', confirmation: 'policy' },
  comments_get_settings: { class: 'read', confirmation: 'direct' },
  comments_list_moderation_queue: { class: 'read', confirmation: 'direct' },
  comments_mark_comment_spam: { class: 'publish', confirmation: 'policy' },
  comments_purge_comment: { class: 'delete', confirmation: 'handler' },
  comments_restore_comment: { class: 'publish', confirmation: 'policy' },
  comments_trash_comment: { class: 'trash', confirmation: 'policy' },
  comments_update_settings: { class: 'edit', confirmation: 'direct' },
  commerce_get_status: { class: 'read', confirmation: 'direct' },
  content_duplicate: { class: 'edit', confirmation: 'direct', rule: 'duplicate-status' },
  content_post_create: { class: 'edit', confirmation: 'direct', rule: 'create-status' },
  content_post_delete: { class: 'trash', confirmation: 'policy' },
  content_post_get: { class: 'read', confirmation: 'direct' },
  content_post_list: { class: 'read', confirmation: 'direct' },
  content_post_preview: { class: 'read', confirmation: 'direct' },
  content_post_search: { class: 'read', confirmation: 'direct' },
  content_post_update: { class: 'edit', confirmation: 'direct', rule: 'update-status' },
  content_stats: { class: 'read', confirmation: 'direct' },
  custom_credential_create: { class: 'safety', confirmation: 'handler' },
  custom_credential_delete: { class: 'delete', confirmation: 'handler' },
  custom_credential_list: { class: 'read', confirmation: 'direct' },
  custom_credential_make_request: { class: 'edit', confirmation: 'handler', rule: 'http-method' },
  custom_credential_set_token: { class: 'safety', confirmation: 'handler' },
  custom_credential_set_username: { class: 'edit', confirmation: 'direct' },
  custom_credential_verify: { class: 'read', confirmation: 'direct' },
  custom_credential_write_files: { class: 'edit', confirmation: 'direct' },
  database_execute_migrate_forward: { class: 'safety', confirmation: 'handler' },
  database_get_health: { class: 'read', confirmation: 'direct' },
  database_get_schema_state: { class: 'read', confirmation: 'direct' },
  database_list_pending_migrations: { class: 'read', confirmation: 'direct' },
  database_list_restore_points: { class: 'read', confirmation: 'direct' },
  database_plan_migrate_forward: { class: 'read', confirmation: 'direct' },
  database_query_timeline: { class: 'read', confirmation: 'direct' },
  database_transfer_plan: { class: 'read', confirmation: 'direct' },
  database_transfer_run: { class: 'safety', confirmation: 'handler' },
  database_transfer_set_destination: { class: 'safety', confirmation: 'handler' },
  database_transfer_status: { class: 'read', confirmation: 'direct' },
  deployment_delete_provider_credential: { class: 'delete', confirmation: 'handler' },
  deployment_execute_static_publish: { class: 'publish', confirmation: 'policy' },
  deployment_generate_bucket_hosting_setup: { class: 'read', confirmation: 'direct' },
  deployment_get_dockerfile: { class: 'read', confirmation: 'direct' },
  deployment_get_export_status: { class: 'read', confirmation: 'direct' },
  deployment_get_static_publish_capabilities: { class: 'read', confirmation: 'direct' },
  deployment_ops_deploy: { class: 'publish', confirmation: 'policy' },
  deployment_ops_list_secrets: { class: 'read', confirmation: 'direct' },
  deployment_ops_list_targets: { class: 'read', confirmation: 'direct' },
  deployment_ops_logs: { class: 'read', confirmation: 'direct' },
  deployment_ops_set_secret: { class: 'safety', confirmation: 'handler' },
  deployment_ops_status: { class: 'read', confirmation: 'direct' },
  deployment_ops_unset_secret: { class: 'delete', confirmation: 'handler' },
  deployment_ops_wait: { class: 'read', confirmation: 'direct' },
  deployment_preview_static_publish: { class: 'read', confirmation: 'direct' },
  deployment_propose_custom_provider_credential: { class: 'safety', confirmation: 'handler' },
  deployment_set_dockerfile: { class: 'edit', confirmation: 'direct' },
  deployment_trigger_export: { class: 'edit', confirmation: 'direct' },
  describe_component: { class: 'read', confirmation: 'direct' },
  domain_check_dns: { class: 'read', confirmation: 'direct' },
  domain_lookup_dns: { class: 'read', confirmation: 'direct' },
  domain_tls_status: { class: 'read', confirmation: 'direct' },
  external_mcp_delete: { class: 'delete', confirmation: 'handler' },
  external_mcp_get_admissions: { class: 'read', confirmation: 'direct' },
  external_mcp_list: { class: 'read', confirmation: 'direct' },
  external_mcp_oauth_connect: { class: 'edit', confirmation: 'direct' },
  external_mcp_oauth_poll_device: { class: 'edit', confirmation: 'direct' },
  external_mcp_probe_connection: { class: 'edit', confirmation: 'direct' },
  external_mcp_reauth_prompt: { class: 'read', confirmation: 'direct' },
  external_mcp_save: { class: 'safety', confirmation: 'handler' },
  external_mcp_test_connection: { class: 'edit', confirmation: 'direct' },
  fetch_live_url: { class: 'read', confirmation: 'direct' },
  fetch_published_page: { class: 'read', confirmation: 'direct' },
  forms_create_definition: { class: 'edit', confirmation: 'direct' },
  forms_get_submission: { class: 'read', confirmation: 'direct' },
  forms_list_definitions: { class: 'read', confirmation: 'direct' },
  forms_list_submissions: { class: 'read', confirmation: 'direct' },
  forms_set_definition_status: { class: 'edit', confirmation: 'direct' },
  forms_update_definition: { class: 'edit', confirmation: 'direct' },
  fs_list_files: { class: 'read', confirmation: 'direct' },
  fs_read_file: { class: 'read', confirmation: 'direct' },
  identity_policy_attach: { class: 'edit', confirmation: 'direct' },
  identity_policy_create: { class: 'edit', confirmation: 'direct' },
  identity_policy_delete: { class: 'delete', confirmation: 'handler' },
  identity_policy_list: { class: 'read', confirmation: 'direct' },
  identity_policy_list_permissions: { class: 'read', confirmation: 'direct' },
  identity_policy_update: { class: 'edit', confirmation: 'direct' },
  identity_role_assign: { class: 'edit', confirmation: 'direct' },
  identity_role_create: { class: 'edit', confirmation: 'direct' },
  identity_role_delete: { class: 'delete', confirmation: 'handler' },
  identity_role_list: { class: 'read', confirmation: 'direct' },
  identity_role_rename: { class: 'edit', confirmation: 'direct' },
  identity_user_create: { class: 'safety', confirmation: 'handler' },
  identity_user_delete: { class: 'delete', confirmation: 'handler' },
  identity_user_disable: { class: 'edit', confirmation: 'direct' },
  identity_user_enable: { class: 'edit', confirmation: 'direct' },
  identity_user_list: { class: 'read', confirmation: 'direct' },
  identity_user_update_email: { class: 'edit', confirmation: 'direct' },
  media_generate_asset: { class: 'edit', confirmation: 'direct' },
  media_import_from_url: { class: 'edit', confirmation: 'direct' },
  media_import_local_file: { class: 'edit', confirmation: 'direct' },
  media_list_assets: { class: 'read', confirmation: 'direct' },
  media_list_providers: { class: 'read', confirmation: 'direct' },
  media_propose_provider_credential: { class: 'safety', confirmation: 'handler' },
  media_purge_asset: { class: 'delete', confirmation: 'handler' },
  media_trash_asset: { class: 'trash', confirmation: 'policy' },
  media_update_metadata: { class: 'edit', confirmation: 'direct' },
  media_upload_asset: { class: 'edit', confirmation: 'direct' },
  media_view_image: { class: 'read', confirmation: 'direct' },
  media_view_video: { class: 'read', confirmation: 'direct' },
  members_disable: { class: 'edit', confirmation: 'direct' },
  members_get_by_id: { class: 'read', confirmation: 'direct' },
  members_list: { class: 'read', confirmation: 'direct' },
  members_request_magic_link: { class: 'edit', confirmation: 'direct' },
  menus_assign_location: { class: 'edit', confirmation: 'direct' },
  menus_create_menu: { class: 'edit', confirmation: 'direct' },
  menus_get_menu: { class: 'read', confirmation: 'direct' },
  menus_list_menus: { class: 'read', confirmation: 'direct' },
  menus_update_menu_tree: { class: 'edit', confirmation: 'direct' },
  newsletter_archive_list: { class: 'edit', confirmation: 'direct' },
  newsletter_cancel_campaign: { class: 'edit', confirmation: 'direct' },
  newsletter_create_campaign: { class: 'edit', confirmation: 'direct' },
  newsletter_create_list: { class: 'edit', confirmation: 'direct' },
  newsletter_create_subscription: { class: 'edit', confirmation: 'direct' },
  newsletter_get_campaign: { class: 'read', confirmation: 'direct' },
  newsletter_list_campaigns: { class: 'read', confirmation: 'direct' },
  newsletter_list_lists: { class: 'read', confirmation: 'direct' },
  newsletter_list_send_log: { class: 'read', confirmation: 'direct' },
  newsletter_list_subscriptions: { class: 'read', confirmation: 'direct' },
  newsletter_pause_campaign: { class: 'edit', confirmation: 'direct' },
  newsletter_remove_subscription: { class: 'edit', confirmation: 'direct' },
  newsletter_resend_confirmation: { class: 'safety', confirmation: 'handler' },
  newsletter_resume_campaign: { class: 'safety', confirmation: 'handler' },
  newsletter_schedule_campaign: { class: 'safety', confirmation: 'handler' },
  newsletter_send_campaign: { class: 'safety', confirmation: 'handler' },
  newsletter_send_test: { class: 'edit', confirmation: 'direct' },
  newsletter_update_campaign: { class: 'edit', confirmation: 'direct' },
  pages_move_region: { class: 'edit', confirmation: 'direct' },
  pages_read_html: { class: 'read', confirmation: 'direct' },
  pages_write_html: { class: 'edit', confirmation: 'direct' },
  pages_write_region: { class: 'edit', confirmation: 'direct' },
  plugins_install: { class: 'edit', confirmation: 'direct' },
  plugins_list: { class: 'read', confirmation: 'direct' },
  plugins_set_enabled: { class: 'safety', confirmation: 'handler' },
  plugins_uninstall: { class: 'trash', confirmation: 'handler' },
  preview_reload: { class: 'edit', confirmation: 'direct' },
  publish_backstop_gaps: { class: 'read', confirmation: 'direct' },
  publish_content_connect: { class: 'edit', confirmation: 'direct' },
  publish_content_disconnect: { class: 'edit', confirmation: 'direct' },
  publish_content_execute_pull: { class: 'restore-over-existing', confirmation: 'handler' },
  publish_content_plan_pull: { class: 'edit', confirmation: 'direct' },
  publish_content_publish: { class: 'publish', confirmation: 'policy' },
  publish_content_status: { class: 'read', confirmation: 'direct' },
  recovery_get_status: { class: 'read', confirmation: 'direct' },
  recovery_resolve_deep_link: { class: 'read', confirmation: 'direct' },
  redirects_create: { class: 'edit', confirmation: 'direct' },
  redirects_get: { class: 'read', confirmation: 'direct' },
  redirects_get_hits: { class: 'read', confirmation: 'direct' },
  redirects_import: { class: 'edit', confirmation: 'direct' },
  redirects_list: { class: 'read', confirmation: 'direct' },
  redirects_tombstone: { class: 'trash', confirmation: 'policy' },
  redirects_update: { class: 'edit', confirmation: 'direct' },
  search_agent_plugin_local: { class: 'read', confirmation: 'direct' },
  search_components: { class: 'read', confirmation: 'direct' },
  seo_analyze_entry: { class: 'read', confirmation: 'direct' },
  seo_get_entry_meta: { class: 'read', confirmation: 'direct' },
  seo_get_settings: { class: 'read', confirmation: 'direct' },
  seo_regenerate_sitemap: { class: 'edit', confirmation: 'direct' },
  seo_set_entry_overrides: { class: 'edit', confirmation: 'direct' },
  seo_set_settings: { class: 'edit', confirmation: 'direct' },
  settings_clear_value: { class: 'safety', confirmation: 'handler' },
  settings_get_effective: { class: 'read', confirmation: 'direct' },
  settings_get_raw: { class: 'read', confirmation: 'direct' },
  settings_list_definitions: { class: 'read', confirmation: 'direct' },
  settings_list_ui_locales: { class: 'read', confirmation: 'direct' },
  settings_set_ui_preference: { class: 'edit', confirmation: 'direct' },
  settings_set_value: { class: 'safety', confirmation: 'handler' },
  site_backup_push: { class: 'edit', confirmation: 'direct' },
  site_collect_page_evidence: { class: 'read', confirmation: 'direct' },
  site_describe_capabilities: { class: 'read', confirmation: 'direct' },
  site_get_profile: { class: 'read', confirmation: 'direct' },
  sites_create_site: { class: 'edit', confirmation: 'direct' },
  sites_duplicate_site: { class: 'edit', confirmation: 'direct' },
  sites_list: { class: 'read', confirmation: 'direct' },
  sites_switch_site: { class: 'edit', confirmation: 'direct' },
  skills_install: { class: 'edit', confirmation: 'direct' },
  source_control_delete_credential: { class: 'delete', confirmation: 'handler' },
  source_control_execute_commit: { class: 'publish', confirmation: 'policy', rule: 'export-commit' },
  source_control_get_capabilities: { class: 'read', confirmation: 'direct' },
  source_control_propose_credential: { class: 'safety', confirmation: 'handler' },
  system_get_mail_status: { class: 'read', confirmation: 'direct' },
  system_read_server_logs: { class: 'read', confirmation: 'direct' },
  taxonomy_assign_terms: { class: 'edit', confirmation: 'direct' },
  taxonomy_create_taxonomy: { class: 'edit', confirmation: 'direct' },
  taxonomy_create_term: { class: 'edit', confirmation: 'direct' },
  taxonomy_execute_merge_term: { class: 'delete', confirmation: 'handler' },
  taxonomy_get_assigned_terms: { class: 'read', confirmation: 'direct' },
  taxonomy_list: { class: 'read', confirmation: 'direct' },
  taxonomy_plan_merge_term: { class: 'read', confirmation: 'direct' },
  taxonomy_rename_term: { class: 'edit', confirmation: 'direct' },
  taxonomy_unassign_terms: { class: 'edit', confirmation: 'direct' },
  theme_copy_file: { class: 'edit', confirmation: 'direct' },
  theme_edit_file: { class: 'edit', confirmation: 'direct' },
  theme_list: { class: 'read', confirmation: 'direct' },
  theme_list_files: { class: 'read', confirmation: 'direct' },
  theme_read_file: { class: 'read', confirmation: 'direct' },
  theme_rename_file: { class: 'edit', confirmation: 'direct' },
  theme_rescan: { class: 'edit', confirmation: 'direct' },
  theme_reset_file: { class: 'restore-over-existing', confirmation: 'policy' },
  theme_restore_trashed_file: { class: 'edit', confirmation: 'direct' },
  theme_set_active: { class: 'edit', confirmation: 'direct' },
  theme_set_page_published: { class: 'publish', confirmation: 'policy' },
  theme_trash_file: { class: 'trash', confirmation: 'policy' },
  theme_write_file: { class: 'edit', confirmation: 'direct' },
  trash_empty: { class: 'delete', confirmation: 'handler' },
  trash_item: { class: 'trash', confirmation: 'policy' },
  trash_list_items: { class: 'read', confirmation: 'direct' },
  trash_purge_item: { class: 'delete', confirmation: 'handler' },
  trash_restore_item: { class: 'edit', confirmation: 'direct' },
  webhooks_create_subscription: { class: 'edit', confirmation: 'direct' },
  webhooks_delete_subscription: { class: 'delete', confirmation: 'handler' },
  webhooks_get_deliveries: { class: 'read', confirmation: 'direct' },
  webhooks_list_subscriptions: { class: 'read', confirmation: 'direct' },
  webhooks_pause_subscription: { class: 'edit', confirmation: 'direct' },
  widgets_bind_region: { class: 'edit', confirmation: 'direct' },
  widgets_create_instance: { class: 'edit', confirmation: 'direct' },
  widgets_get_instance: { class: 'read', confirmation: 'direct' },
  widgets_get_region: { class: 'read', confirmation: 'direct' },
  widgets_insert_embed: { class: 'edit', confirmation: 'direct' },
  widgets_list_instances: { class: 'read', confirmation: 'direct' },
  widgets_list_regions: { class: 'read', confirmation: 'direct' },
  widgets_remove_embed: { class: 'edit', confirmation: 'direct' },
  widgets_reorder_embeds: { class: 'edit', confirmation: 'direct' },
  widgets_set_region_placements: { class: 'edit', confirmation: 'direct' },
  widgets_trash_instance: { class: 'trash', confirmation: 'policy' },
  widgets_update_instance: { class: 'edit', confirmation: 'direct' },
  workspace_get: { class: 'read', confirmation: 'direct' },
  workspace_update: { class: 'edit', confirmation: 'direct' },
};

/** Only parked policy-gated calls can be answered through the MCP-UI callback route. */
export const POLICY_CONFIRMATION_TOOL_IDS: ReadonlySet<string> = new Set(
  Object.entries(TOOL_APPROVAL_POLICY).filter(([, policy]) => policy.confirmation === 'policy' || (policy.rule && policy.confirmation !== 'handler')).map(([id]) => id),
);

/** Behavior-reviewed plugin-add controls: input/disclosure/cancel or installation that stays off.
 * Do not add destructive or publish controls here, including their final confirmation buttons. */
const DIRECT_PAGE_HANDLES: ReadonlySet<string> = new Set([
  'plugins-install-advanced', 'plugins-install-folder', 'plugins-install-folder-upload',
  'plugins-install-zip', 'plugins-install-replace', 'plugins-install-preview',
  'plugins-install-cancel', 'plugins-install-confirm',
  'agent-plugin-add-choose', 'agent-plugin-add-choose-folder', 'agent-plugin-add-replace',
  'agent-plugin-add-install', 'agent-plugin-add-url', 'agent-plugin-add-from-url',
  'skills-add-github-url', 'skills-add-github', 'skills-add-files', 'skills-add-folder',
  'skills-install-cancel', 'skills-install-confirm',
]);
export function directPageAction({ capabilityId, input }: { capabilityId: string; input: unknown }, _optional = {}): boolean {
  if (!Object.hasOwn(TOOL_APPROVAL_POLICY, capabilityId)) throw new Error(`${capabilityId} has no approval classification`);
  if (capabilityId !== 'page.click') return TOOL_APPROVAL_POLICY[capabilityId]!.confirmation === 'direct';
  const handle = input && typeof input === 'object' ? (input as Record<string, unknown>).handle : undefined;
  return typeof handle === 'string' && DIRECT_PAGE_HANDLES.has(handle);
}

/** Data-generated ids are classified by the host factory's behavior, never their names or prose.
 * Memory refresh is a plain text edit; guidance and computed capability results save nothing.
 * NEEDS-JINI: registration classification metadata and the common lookup belong in core. */
export const EXTENSION_TOOL_APPROVAL_POLICY = {
  'installed-guidance': { class: 'read', confirmation: 'direct' },
  'plugin-capability-result': { class: 'read', confirmation: 'direct' },
  'plugin-memory-read': { class: 'read', confirmation: 'direct' },
  'plugin-memory-write': { class: 'edit', confirmation: 'direct' },
} as const satisfies Readonly<Record<string, ToolApprovalPolicy>>;
export const TOOL_APPROVAL_METADATA: unique symbol = Symbol('tovu.toolApprovalPolicy');
type ClassifiedRegistration = ToolRegistration & { readonly [TOOL_APPROVAL_METADATA]?: ToolApprovalPolicy };
export function withExtensionApprovalPolicy(
  { registration, family }: { registration: ToolRegistration; family: keyof typeof EXTENSION_TOOL_APPROVAL_POLICY }, _optional = {},
): ClassifiedRegistration {
  if (!Object.hasOwn(EXTENSION_TOOL_APPROVAL_POLICY, family)) throw new Error(`${registration.descriptor.id} has no approval classification`);
  return { ...registration, [TOOL_APPROVAL_METADATA]: EXTENSION_TOOL_APPROVAL_POLICY[family] };
}
export function toolApprovalPolicyFor({ registration }: { registration: ToolRegistration }, _optional = {}): ToolApprovalPolicy {
  const policy = Object.hasOwn(TOOL_APPROVAL_POLICY, registration.descriptor.id)
    ? TOOL_APPROVAL_POLICY[registration.descriptor.id] : (registration as ClassifiedRegistration)[TOOL_APPROVAL_METADATA];
  if (!policy) throw new Error(`${registration.descriptor.id} has no approval classification`);
  return policy;
}
