/**
 * @file Dead-path sweep — resolves every filesystem path reference in the repo's tooling files and
 * reports the ones that point at nothing.
 *
 * ## Why this exists
 *
 * The `apps/website` restructure (2026-09) moved the source tree but left hardcoded `src/...` paths
 * behind in tooling that nothing exercises. Every instance was invisible until someone happened to
 * run the tool. The six known when this file was written (the first two since repaired, the last
 * four repaired in 921d705f):
 *
 * | file | consequence |
 * |---|---|
 * | `apps/website/src/platform/db/drizzle.config.ts` | `drizzle-kit generate` failed "No schema files found" — NO migration could be generated by anyone |
 * | `apps/website/src/platform/db/drizzle.database-journal.config.ts` | same, for the sidecar `ops/database-journal.db` target |
 * | `development/scripts/generate-seed-content.ts` | `check:seed-content-drift` crashed; CI's `continue-on-error: true` swallowed it |
 * | `development/scripts/list-server-test-files.ts` | prints nothing, so `test:cov:server:{unit,integration}` expand to an EMPTY file list |
 * | `development/scripts/backfill-vendor-credentials.ts` | its test never ran |
 * | `development/scripts/backfill-slug-collision-defaults.ts` | its test never ran |
 *
 * A type-checker cannot see any of them: four are string literals, and the two import cases only
 * fail at module-resolution time in a script `tsc` never loads.
 *
 * ## The two reference classes, and the two different resolution bases
 *
 * 1. **Relative import specifiers** (`./x`, `../y` in `import`/`export ... from`, dynamic
 *    `import()`, `require()`) resolve against the IMPORTING FILE'S directory, with this codebase's
 *    ESM `.js`-written/`.ts`-on-disk extension rewrite applied.
 * 2. **Hardcoded repo-relative path strings** resolve against the CWD the npm script runs in — the
 *    REPO ROOT — not the containing file's directory. `drizzle.config.ts`'s own header comment
 *    documents this explicitly, and it is why that file legitimately reads
 *    `"./apps/website/src/platform/db/schema.sqlite.ts"` from inside `apps/website/src/platform/db/`.
 *    `list-server-test-files.ts`'s `execFileSync("find", ["src/server", ...])` is the same class.
 *
 * Class 2 is the one a naive "check the imports" linter misses entirely, and it is three of those six
 * instances (both drizzle configs and `list-server-test-files.ts`). Across the whole current sweep the
 * split is 15 dead strings to 20 dead imports — neither class is a rounding error.
 *
 * ## Precision over recall, deliberately
 *
 * Scanning string literals for "things that look like paths" over-matches: globs, URLs, mime types,
 * Node package-imports subpath specifiers, npm package names, and prose all contain slashes. Every
 * exclusion below is a NAMED rule (`SkipReason`) reported alongside the finding rather than a silent
 * drop, so a future reader can see exactly what the sweep declines to look at and challenge it. The
 * sweep is allowed to miss a real dead path; it is not allowed to cry wolf, because a guard with
 * false positives gets an allowlist and an allowlist rots.
 */
import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Comment stripping
// ---------------------------------------------------------------------------

/**
 * Replaces every comment in TypeScript/JavaScript source with spaces, preserving byte offsets and
 * line breaks so downstream line numbers stay accurate.
 *
 * Hand-written state machine rather than a regex: a regex cannot tell a `//` inside a string
 * literal from a real comment, and this file's whole job is reading string literals correctly. It
 * tracks single/double-quoted strings, template literals (including nested `${}` interpolation
 * depth), and both comment forms.
 *
 * Regex literals are NOT tracked. A regex containing an unbalanced quote or a `//` sequence would
 * confuse the scanner — accepted deliberately, because a confused scanner produces a spurious
 * finding at a specific line that a human then reads, whereas the alternative (a real JS lexer with
 * ASI-aware regex/division disambiguation) is far more machinery than this guard warrants. No file
 * in the current sweep scope trips it; `sweepFiles` failing loudly on one is the intended outcome.
 *
 * @param source raw file text
 * @returns text of identical length with comment bytes replaced by spaces (newlines kept)
 * @complexity O(n) time in source length, O(1) auxiliary space beyond the output buffer.
 * @tradeoffs Cyclomatic complexity 26, over this repo's ceiling of 9, and deliberately left whole.
 * The branches ARE the state-transition table of a character scanner; splitting them across helpers
 * hides which transitions exist and makes the lexer harder to verify, not easier. Nesting stays at
 * one or two levels throughout. `development/scripts/**` is outside `check:src-complexity-drift`'s
 * scan scope, so this is a disclosed deviation rather than a suppressed gate failure.
 */
export function stripComments(source: string): string {
  const out = source.split("");
  const templateStack: number[] = [];
  let i = 0;
  let state: "code" | "single" | "double" | "template" | "line-comment" | "block-comment" = "code";

  const blank = (from: number, to: number): void => {
    for (let k = from; k < to; k++) if (out[k] !== "\n") out[k] = " ";
  };

  while (i < source.length) {
    const c = source[i];
    const next = source[i + 1];

    if (state === "code") {
      if (c === "/" && next === "/") {
        const start = i;
        while (i < source.length && source[i] !== "\n") i++;
        blank(start, i);
        continue;
      }
      if (c === "/" && next === "*") {
        const start = i;
        i += 2;
        while (i < source.length && !(source[i] === "*" && source[i + 1] === "/")) i++;
        i = Math.min(i + 2, source.length);
        blank(start, i);
        continue;
      }
      if (c === "'") state = "single";
      else if (c === '"') state = "double";
      else if (c === "`") {
        state = "template";
        templateStack.push(0);
      } else if (c === "}" && templateStack.length > 0) {
        // closing a `${ ... }` interpolation returns us to the enclosing template literal
        state = "template";
      }
      i++;
      continue;
    }

    if (c === "\\") {
      i += 2;
      continue;
    }

    if (state === "single" && c === "'") state = "code";
    else if (state === "double" && c === '"') state = "code";
    else if (state === "template") {
      if (c === "`") {
        state = "code";
        templateStack.pop();
      } else if (c === "$" && next === "{") {
        state = "code";
        i += 2;
        continue;
      }
    }
    i++;
  }

  return out.join("");
}

/** 1-based line number of a byte offset. */
function lineOf(source: string, offset: number): number {
  let line = 1;
  for (let i = 0; i < offset && i < source.length; i++) if (source[i] === "\n") line++;
  return line;
}

// ---------------------------------------------------------------------------
// Reference extraction
// ---------------------------------------------------------------------------

export type ReferenceKind = "relative-import" | "repo-relative-string" | "path-join-call";

export interface PathReference {
  /** repo-relative, forward-slash path of the file the reference was written in */
  readonly file: string;
  /** 1-based line number within that file */
  readonly line: number;
  readonly kind: ReferenceKind;
  /** the specifier exactly as written in source */
  readonly specifier: string;
}

export interface DeadPathFinding extends PathReference {
  /** repo-relative candidate targets that were probed, all of which were absent */
  readonly attempted: readonly string[];
}

/**
 * Every named reason the sweep declines to treat a slash-bearing string literal as a filesystem
 * path. Exposed so the test can assert the ruleset by name and so a report can say WHICH rule
 * skipped a given string rather than "it didn't match".
 */
export type SkipReason =
  | "url-scheme"
  | "glob-or-regex-metacharacter"
  | "contains-whitespace"
  | "package-imports-specifier"
  | "scoped-package-specifier"
  | "absolute-or-home-path"
  | "no-path-separator"
  | "colon-bearing-specifier"
  | "parent-relative-outside-repo"
  | "trailing-separator"
  | "own-import-specifier"
  | "not-a-known-repo-segment";

export type StringClassification =
  | { readonly kind: "repo-relative-path"; readonly repoRelative: string }
  | { readonly kind: "skipped"; readonly reason: SkipReason };

export interface StringToken {
  /** the literal's text with the quotes removed and escapes left as written */
  readonly value: string;
  /** 1-based line the literal opens on */
  readonly line: number;
  /** true for a backtick literal (interior never re-scanned; see `tokenizeStringLiterals`) */
  readonly isTemplate: boolean;
  /** code text immediately preceding the opening quote, trimmed — used to tell an import specifier
   *  from any other literal */
  readonly precedingCode: string;
}

/** Matches the tail of the code preceding a string literal when that literal is a module specifier:
 *  `from "x"`, `import "x"`, `import("x")`, `require("x")`. */
const IMPORT_POSITION = /(?:\bfrom|\bimport|\brequire)\s*\(?\s*$/;

/**
 * Splits comment-stripped source into its TOP-LEVEL string literals — literals written in code, not
 * ones nested inside another literal's text.
 *
 * The nesting distinction is the whole reason this is a tokenizer and not a regex. A regex for
 * `from "…"` matches the *text* of `'import { a } from "./a.js";'` and of a template literal holding
 * a source-code fixture, and reports the fixture's paths as real dead imports — which is exactly what
 * a regex-based first draft of this file did to its own test. A literal's interior is consumed whole
 * and never re-scanned, so embedded source code is inert.
 *
 * Template literals are tokenized (so their interiors stay inert) but their `${}` interpolations are
 * skipped along with the rest of the body: a specifier written inside an interpolation would be
 * missed. No file in scope does that, and an interpolated specifier is not a fixed path anyway.
 *
 * @param source raw file text
 * @returns the literals in source order, each with its line and preceding code context
 * @complexity O(n) time in source length.
 * @tradeoffs Cyclomatic complexity 15, over the ceiling of 9, for the same reason as
 * `stripComments`: this is a scanner's transition table, not accidental branching.
 */
export function tokenizeStringLiterals(source: string): readonly StringToken[] {
  const code = stripComments(source);
  const tokens: StringToken[] = [];
  let i = 0;
  let lastCodeEnd = 0;

  while (i < code.length) {
    const quote = code[i];
    if (quote !== "'" && quote !== '"' && quote !== "`") {
      i++;
      continue;
    }
    const open = i;
    i++;
    let depth = 0;
    while (i < code.length) {
      const c = code[i];
      if (c === "\\") {
        i += 2;
        continue;
      }
      if (quote === "`") {
        if (c === "$" && code[i + 1] === "{") {
          depth++;
          i += 2;
          continue;
        }
        if (c === "}" && depth > 0) {
          depth--;
          i++;
          continue;
        }
      } else if (c === "\n") {
        break; // unterminated single/double-quoted literal — do not run past the line
      }
      if (c === quote && depth === 0) break;
      i++;
    }
    const close = i;
    tokens.push({
      value: code.slice(open + 1, close),
      line: lineOf(code, open),
      isTemplate: quote === "`",
      precedingCode: code.slice(lastCodeEnd, open).trimEnd(),
    });
    i = close + 1;
    lastCodeEnd = i;
  }

  return tokens;
}

/**
 * Extracts every relative import specifier (`./…`, `../…`) written in a source file.
 *
 * Bare specifiers (`node:fs`, `drizzle-kit`, `@jini-ai/cms`) are omitted on purpose: those resolve
 * through `node_modules`/`package.json#imports`, not the repo tree, so their existence is npm's
 * problem and not a restructure-rot symptom.
 *
 * @param source raw file text
 * @returns specifier strings paired with the 1-based line they appear on, in source order
 * @complexity O(n) in source length.
 */
export function extractRelativeImportSpecifiers(source: string): readonly { specifier: string; line: number }[] {
  return tokenizeStringLiterals(source)
    .filter((t) => !t.isTemplate)
    .filter((t) => t.value.startsWith("./") || t.value.startsWith("../"))
    .filter((t) => IMPORT_POSITION.test(t.precedingCode))
    .map((t) => ({ specifier: t.value, line: t.line }));
}

/**
 * Extracts every top-level single/double-quoted string literal.
 *
 * Template literals are excluded from the class-2 candidate set: an interpolated one is not a fixed
 * path, and this codebase writes no fixed path with backticks.
 */
export function extractStringLiterals(source: string): readonly { value: string; line: number }[] {
  return tokenizeStringLiterals(source)
    .filter((t) => !t.isTemplate)
    .map((t) => ({ value: t.value, line: t.line }));
}

// ---------------------------------------------------------------------------
// path.join()/path.resolve() call extraction (class 3: computed multi-argument paths)
// ---------------------------------------------------------------------------

export interface PathJoinCandidate {
  /** the trailing string-literal arguments, in call order, e.g. `["..", "..", "src", "server"]`
   *  for `path.resolve(import.meta.dirname, "..", "..", "src", "server")` */
  readonly segments: readonly string[];
  /** 1-based line the call starts on */
  readonly line: number;
}

const PATH_JOIN_CALL = /\bpath\.(?:join|resolve)\s*\(/g;

/**
 * Finds `path.join(...)`/`path.resolve(...)` calls and returns each one's TRAILING run of pure
 * string-literal arguments.
 *
 * This is the gap classes 1 and 2 both miss, found auditing this file against 2026-09-03's
 * `check-outbox-bridge.ts`/`check-capability-inventory.ts` fixes: `path.join(REPO_ROOT, "src")` and
 * `path.resolve(import.meta.dirname, "..", "..", "src", "server")` were both invisible to this sweep
 * — each individual segment string (`"src"`, `"server"`) has no `/` of its own, so class 2's
 * `no-path-separator` skip rule (correct for a genuinely bare word like a directory-name filter)
 * discarded every one of them without ever seeing they were arguments to the SAME call, joined into
 * one real multi-segment path at runtime. Neither instance had a register entry — they were not
 * known-and-tolerated debt, they were structurally unreachable by the classifier that would have
 * found them.
 *
 * The leading argument(s) — almost always a computed base (`import.meta.dirname`, `REPO_ROOT`) —
 * cannot be resolved statically and is not needed to be: the literal segments layered on top of it
 * are what encode the restructure-sensitive part of the path, exactly as class 2 already resolves a
 * hardcoded string against the (also unverifiable-by-this-tool) CWD.
 *
 * The common shape is the TRAILING literal run (`path.join(REPO_ROOT, "src", "server")`), tried
 * first. But a call whose LAST argument is itself non-literal — a computed filename, e.g.
 * `path.join(REPO_ROOT, "src", "server", fileName)` — has no trailing run at all; falling back to
 * "no segments" there would silently drop the literal directory segments before `fileName` along
 * with the one genuinely unresolvable argument. `leadingLiteralRunAfterBase` covers exactly that
 * shape: the literal run starting right after the leading non-literal base(s), stopping at the next
 * non-literal argument (found 2026-09-05, Gemini re-triage finding 14 — no live call site has this
 * shape today; every real trailing argument in this sweep's scan scope is either fully literal or
 * has its variable immediately after the base with no literal in between).
 *
 * @param source raw file text
 * @returns one entry per path.join/path.resolve call whose trailing arguments include at least one
 *          string literal, in source order
 * @complexity O(n) in source length.
 */
export function extractPathJoinSegments(source: string): readonly PathJoinCandidate[] {
  const code = stripComments(source);
  const out: PathJoinCandidate[] = [];

  for (const match of code.matchAll(PATH_JOIN_CALL)) {
    const openParen = match.index! + match[0].length - 1;
    const args = splitCallArguments(code, openParen);
    if (!args) continue;

    const segments = trailingLiteralRun(args) ?? leadingLiteralRunAfterBase(args);
    if (segments.length === 0) continue;

    out.push({ segments, line: lineOf(code, match.index!) });
  }

  return out;
}

/**
 * The run of trailing string-literal arguments, scanning backward from the end.
 *
 * @returns the trailing literals in call order, or `null` if the LAST argument is not itself a
 *          string literal (so there is no trailing run to report at all)
 * @complexity O(k) in the trailing run's length.
 */
function trailingLiteralRun(args: readonly string[]): readonly string[] | null {
  const out: string[] = [];
  for (let i = args.length - 1; i >= 0; i--) {
    const literal = asStringLiteral(args[i]!);
    if (literal === null) break;
    out.unshift(literal);
  }
  return out.length > 0 ? out : null;
}

/**
 * The run of string-literal arguments immediately following the leading non-literal argument(s) —
 * used only when {@link trailingLiteralRun} finds nothing, i.e. the call's last argument is itself
 * non-literal. See {@link extractPathJoinSegments}'s doc comment for why this shape needs its own pass.
 *
 * @returns the literal run in call order; `[]` if the call has no non-literal leading argument
 *          followed by a literal (e.g. every argument is non-literal, or the first is already a
 *          non-trailing literal with no run after it)
 * @complexity O(n) in argument count.
 */
function leadingLiteralRunAfterBase(args: readonly string[]): readonly string[] {
  let i = 0;
  while (i < args.length && asStringLiteral(args[i]!) === null) i++; // skip the leading non-literal base
  const out: string[] = [];
  for (; i < args.length; i++) {
    const literal = asStringLiteral(args[i]!);
    if (literal === null) break;
    out.push(literal);
  }
  return out;
}

/**
 * Splits the argument list of a call whose `(` is at `openParen` into its top-level,
 * comma-separated argument texts (trimmed), respecting nested parens/brackets/braces and quoted
 * strings so a comma or paren inside a string or nested call does not split early.
 *
 * @returns argument texts in call order, or `null` if the call is never closed (malformed/truncated
 *          input — declines to guess rather than report a bogus argument list)
 * @complexity O(n) in the text scanned.
 */
function splitCallArguments(code: string, openParen: number): readonly string[] | null {
  const args: string[] = [];
  let depth = 1;
  let start = openParen + 1;
  let i = start;
  let quote: '"' | "'" | "`" | null = null;

  while (i < code.length && depth > 0) {
    const c = code[i];
    if (quote) {
      if (c === "\\") i += 2;
      else {
        if (c === quote) quote = null;
        i++;
      }
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      quote = c;
      i++;
      continue;
    }
    if (c === "(" || c === "[" || c === "{") {
      depth++;
      i++;
      continue;
    }
    if (c === ")" || c === "]" || c === "}") {
      depth--;
      if (depth === 0) break;
      i++;
      continue;
    }
    if (c === "," && depth === 1) {
      args.push(code.slice(start, i).trim());
      start = i + 1;
      i++;
      continue;
    }
    i++;
  }
  if (depth !== 0) return null;
  const last = code.slice(start, i).trim();
  if (last.length > 0) args.push(last);
  return args;
}

/** `'x'`/`"x"` -> `x`, or `null` if `arg` is not ENTIRELY a single quoted string literal (an
 *  identifier, member expression, template literal, or nested call) — a conservative test, since a
 *  false "yes" here would let a computed value silently pass as a directory-tree literal. */
function asStringLiteral(arg: string): string | null {
  if (arg.length < 2) return null;
  const quote = arg[0];
  if ((quote !== '"' && quote !== "'") || arg[arg.length - 1] !== quote) return null;
  const inner = arg.slice(1, -1);
  if (inner.includes(quote) || inner.includes("\n")) return null;
  return inner;
}

/**
 * Drops a leading run of `".."` segments — parent-directory traversal that resolves relative to
 * whatever the call's non-literal base argument was, and carries no restructure-sensitive
 * information of its own once dropped.
 *
 * When `fileDepth` is supplied, the drop is only trusted when the `".."` run's length matches it
 * EXACTLY. `import.meta.dirname` (this repo's only computed base for these calls, per the 2026-09-05
 * audit) IS the file's own directory, so a run shorter than `fileDepth` lands somewhere between the
 * file and the repo root — the remaining segments would then be relative to THAT directory, not the
 * repo root, and treating them as repo-root-relative would check the wrong location — while a run
 * longer than `fileDepth` escapes above the repo root entirely, where nothing can be "repo-relative"
 * by definition. `fileDepth` is optional (rather than required) so direct unit tests can keep
 * constructing segments without a real file to measure depth from.
 *
 * @param segments the call's trailing literal arguments, in source order
 * @param fileDepth how many directory levels the file containing the call sits below the repo root;
 *        omit to keep the unconditional-strip behavior
 * @returns the segments with their leading ".." run dropped, or `null` if `fileDepth` is given and
 *          the leading ".." count does not exactly match it
 * @complexity O(n) in segment count.
 */
export function dropLeadingParentSegments(segments: readonly string[], fileDepth?: number): readonly string[] | null {
  let i = 0;
  while (i < segments.length && segments[i] === "..") i++;
  if (fileDepth !== undefined && i !== fileDepth) return null;
  return segments.slice(i);
}

/**
 * How many directory levels `repoRelativeFile` sits below the repo root — the count of `".."`
 * segments a `path.resolve(import.meta.dirname, ...)` call in that file would need to reach the root.
 *
 * @param repoRelativeFile a repo-root-relative path with forward slashes
 * @returns 0 for a file directly at the repo root, 1 for one directory down, etc.
 * @complexity O(1).
 */
export function fileDirectoryDepth(repoRelativeFile: string): number {
  const dir = path.posix.dirname(repoRelativeFile);
  return dir === "." ? 0 : dir.split("/").length;
}

// ---------------------------------------------------------------------------
// Classification of hardcoded repo-relative path strings
// ---------------------------------------------------------------------------

export interface ClassifyOptions {
  /** directory names that plausibly begin a repo path (see `collectRepoSegments`) */
  readonly knownRepoSegments: ReadonlySet<string>;
  /** relative import specifiers written in the SAME file, which class 1 already owns */
  readonly ownImportSpecifiers?: ReadonlySet<string>;
}

/**
 * Decides whether a string literal is a repo-root-relative filesystem path this sweep should
 * resolve, or names the rule that excluded it.
 *
 * The load-bearing rule is `knownRepoSegments`. A dead path's whole problem is that its FIRST
 * segment no longer exists at the repo root (`src/server` after `src/` became `apps/website/src/`),
 * so a candidate set derived only from today's root listing is blind to exactly the defect this
 * guard exists to catch. The set is therefore derived from directory names appearing anywhere in
 * the shallow repo tree, not from the root listing alone — `src` still exists as a directory name
 * (at `apps/website/src`), so `"src/server"` is recognized as path-shaped and then correctly fails
 * its existence check. Derived, never hand-listed: a hand-maintained mirror of the tree would drift
 * the first time a directory was added.
 *
 * `ownImportSpecifiers` resolves the one genuinely ambiguous prefix. A leading `./` means
 * repo-root-relative in `drizzle.config.ts` (`"./apps/website/src/..."`, per that file's own header)
 * but file-relative in `check-openapi-contract.ts` (`import ... from "./lib/openapi-operations.js"`).
 * Rather than guess, a literal that is also an import specifier in its own file is handed to class 1,
 * which resolves it against the correct base.
 *
 * @param value the literal's text
 * @param options the derived segment set, plus the file's own import specifiers when available
 * @returns the repo-relative path to probe, or the named `SkipReason` that excluded it
 * @complexity O(1) — a fixed sequence of string tests plus two Set lookups.
 */
interface SkipRule {
  readonly reason: SkipReason;
  readonly rejects: (value: string, options: ClassifyOptions) => boolean;
}

/** Applied to the literal exactly as written. Order matters only where one rule would otherwise
 *  shadow a more specific one: `url-scheme` runs before `colon-bearing-specifier` so an https URL is
 *  reported as a URL rather than as punctuation. */
const RAW_SKIP_RULES: readonly SkipRule[] = [
  { reason: "own-import-specifier", rejects: (v, o) => o.ownImportSpecifiers?.has(v) === true },
  { reason: "url-scheme", rejects: (v) => v.includes("://") },
  { reason: "glob-or-regex-metacharacter", rejects: (v) => /[*?{}[\]!()|^$+\\]/.test(v) },
  { reason: "contains-whitespace", rejects: (v) => /\s/.test(v) },
  { reason: "package-imports-specifier", rejects: (v) => v.startsWith("#") },
  { reason: "scoped-package-specifier", rejects: (v) => v.startsWith("@") },
  { reason: "absolute-or-home-path", rejects: (v) => v.startsWith("/") || v.startsWith("~") },
  // past the scheme test, a `:` means a `node:` specifier, a `key:value` pair, or a Windows drive
  { reason: "colon-bearing-specifier", rejects: (v) => v.includes(":") },
  { reason: "no-path-separator", rejects: (v) => !v.includes("/") },
  // `../x` in a plain string is measured from an unknown base (usually `import.meta.dirname`, which
  // class 1 covers when it is an import); resolving it against the repo root would be wrong
  { reason: "parent-relative-outside-repo", rejects: (v) => v.startsWith("../") },
];

/**
 * Applied after a leading `./` is stripped, to the repo-relative candidate (trailing `/` still
 * attached — `classifyRepoRelativeString` only removes it once these rules have run).
 *
 * `trailing-separator` rejects a value ending in `/` ONLY when removing that one slash leaves a
 * single segment with no separator of its own left (`"src/"` -> `"src"`, `"__tests__/"` ->
 * `"__tests__"`). That single segment is exactly as ambiguous as the same word written with no
 * slash at all (`no-path-separator` already declines to treat a bare `"src"` as a path), and real
 * usage bears this out: `report-churn-hotspots.ts` and its sibling complexity gates write
 * `relPath.includes("__tests__/")` as a directory-NAME filter, never a location to resolve. A
 * MULTI-segment trailing-slash literal is a different animal — `"src/server/"` still names real
 * directory structure once the slash is gone, so it falls through to the same checks below and, if
 * its target is missing, gets reported. This is what closes the escape `route-coverage-lib.ts`'s
 * `isMeasurableRouteFile` used before it was fixed in 678b6464: its `"src/server/routes/"` /
 * `"src/server/inbound/admin-http/routes/"` prefixes were unconditionally exempted here just for
 * ending in `/`, so the sweep never probed them. See the `historical:` tests for that instance.
 */
const NORMALIZED_SKIP_RULES: readonly SkipRule[] = [
  { reason: "trailing-separator", rejects: (v) => v.endsWith("/") && !v.slice(0, -1).includes("/") },
  { reason: "absolute-or-home-path", rejects: (v) => v.split("/")[0]!.length === 0 },
  { reason: "not-a-known-repo-segment", rejects: (v, o) => !o.knownRepoSegments.has(v.split("/")[0]!) },
];

/** Every `SkipReason` the classifier can return, DERIVED from the rule tables rather than mirrored
 *  by hand — a hand-kept second copy of a list is how three registries in this repo drifted in one
 *  day. A test pins this against the `SkipReason` union so neither side can grow alone. */
export const SKIP_REASONS: readonly SkipReason[] = [
  ...new Set([...RAW_SKIP_RULES, ...NORMALIZED_SKIP_RULES].map((r) => r.reason)),
];

export function classifyRepoRelativeString(value: string, options: ClassifyOptions): StringClassification {
  for (const rule of RAW_SKIP_RULES) {
    if (rule.rejects(value, options)) return { kind: "skipped", reason: rule.reason };
  }
  const withoutDot = value.startsWith("./") ? value.slice(2) : value;
  for (const rule of NORMALIZED_SKIP_RULES) {
    if (rule.rejects(withoutDot, options)) return { kind: "skipped", reason: rule.reason };
  }
  const repoRelative = withoutDot.endsWith("/") ? withoutDot.slice(0, -1) : withoutDot;
  return { kind: "repo-relative-path", repoRelative };
}

/**
 * `RAW_SKIP_RULES` minus `no-path-separator`, for classifying the segments joined from a
 * `path.join`/`path.resolve` call (class 3, `classifyPathJoinSegments` below).
 *
 * `no-path-separator` exists to protect class 2 (a bare string literal floating in code, e.g. a mime
 * type or a directory-name filter) from being mistaken for a path — a standalone `"src"` is genuinely
 * ambiguous. A `path.join`/`path.resolve` ARGUMENT is never that: passing a literal to that call is
 * always constructing a path segment, whether the call has one trailing literal (`path.join(REPO_ROOT,
 * "src")`) or several (`path.join(REPO_ROOT, "apps", "website", "src")`). Excluding this one rule is
 * what lets `classifyPathJoinSegments` see the single-segment shape at all; every other rule
 * (glob/regex metacharacters, whitespace, scoped-package/`#`/`:` specifiers, absolute paths, `../`
 * escapes) still applies unchanged, because those describe the LITERAL's shape, not its argument count.
 */
const PATH_JOIN_SKIP_RULES: readonly SkipRule[] = RAW_SKIP_RULES.filter((rule) => rule.reason !== "no-path-separator");

/**
 * Classifies the trailing literal segments of one `path.join`/`path.resolve` call (after
 * `dropLeadingParentSegments`) the same way `classifyRepoRelativeString` classifies a standalone
 * string literal, minus the `no-path-separator` exemption (see `PATH_JOIN_SKIP_RULES`).
 *
 * This is what closes the sweep's disclosed single-segment blind spot (`check-outbox-bridge.ts`'s old
 * `path.join(REPO_ROOT, "src")`, and the still-live `rewrite-deep-imports.ts:50`
 * `path.join(REPO_ROOT, "src")`): a ONE-element segment list is now classified instead of being
 * discarded before classification ever ran. `not-a-known-repo-segment` remains the load-bearing guard
 * against false positives — a single segment that names a real directory somewhere in the tree
 * (`"openapi"`, `"infra"`) still resolves and passes; a single segment that names only a FILE
 * (`"plugin.json"`, `"tsconfig.json"`) is rejected here exactly as it would be as a bare literal,
 * because `collectRepoSegments` only ever collects directory basenames. Pruned directory names
 * (`dist`, `node_modules`, `build`, `coverage`) are never in `knownRepoSegments` either, so a legitimate
 * `path.join(outDir, "dist")`-shaped call is rejected the same way.
 *
 * @param segments the call's trailing literal arguments with any leading `".."` run already dropped
 * @param options the derived segment set, plus the file's own import specifiers when available
 * @returns the repo-relative path to probe, or the named `SkipReason` that excluded it
 * @complexity O(1) — a fixed sequence of string tests plus two Set lookups.
 */
export function classifyPathJoinSegments(segments: readonly string[], options: ClassifyOptions): StringClassification {
  const joined = segments.join("/");
  for (const rule of PATH_JOIN_SKIP_RULES) {
    if (rule.rejects(joined, options)) return { kind: "skipped", reason: rule.reason };
  }
  const withoutDot = joined.startsWith("./") ? joined.slice(2) : joined;
  for (const rule of NORMALIZED_SKIP_RULES) {
    if (rule.rejects(withoutDot, options)) return { kind: "skipped", reason: rule.reason };
  }
  const repoRelative = withoutDot.endsWith("/") ? withoutDot.slice(0, -1) : withoutDot;
  return { kind: "repo-relative-path", repoRelative };
}

const SOURCE_FILE_EXTENSION = /\.(ts|tsx|mts|cts|js|mjs|cjs)$/;

/**
 * The portion of a repo-relative path string whose absence proves the reference is dead.
 *
 * A path naming a SOURCE file must exist in full — a missing `schema.sqlite.ts` is exactly the
 * `drizzle.config.ts` defect. Every other path is checked only down to its parent directory,
 * because a missing leaf under an existing directory is routine and not rot: `check-test-baseline.ts`
 * names `development/coverage/test-results.tap` and `route-coverage-lib.ts` names
 * `development/coverage/lcov.unit.info`, both correct paths to artifacts that only exist after
 * `npm run test:cov` has run. Requiring those to exist would make the guard fail on a clean checkout,
 * which is how a guard gets deleted.
 *
 * The recall this trades away is a non-source leaf that is genuinely misnamed under a directory that
 * does exist. Accepted deliberately: all six known instances of this repo's restructure rot break at
 * a DIRECTORY segment (`src/` moved wholesale to `apps/website/src/`), which this rule still catches.
 *
 * @param repoRelative a repo-root-relative path with no leading `./`
 * @returns the path that must exist for the reference to be live
 * @complexity O(1).
 */
export function pathThatMustExist(repoRelative: string): string {
  if (SOURCE_FILE_EXTENSION.test(repoRelative)) return repoRelative;
  const parent = repoRelative.split("/").slice(0, -1).join("/");
  return parent.length > 0 ? parent : repoRelative;
}

/**
 * Collects the directory names that may legitimately begin a repo-root-relative path, by walking
 * the tree to a shallow depth and taking every directory's basename.
 *
 * Depth 4 is enough to see `apps/website/src` (depth 3) while staying fast. `node_modules`, VCS,
 * build output, and dot-directories are pruned — a name that only exists inside `node_modules` is a
 * package's internal layout, not a repo path.
 *
 * @param repoRoot absolute path to the repository root
 * @param maxDepth how many directory levels below the root to descend
 * @returns the set of directory basenames found
 * @complexity O(d) in the number of directories visited; one `readdirSync` per directory.
 */
export function collectRepoSegments(repoRoot: string, maxDepth = 4): ReadonlySet<string> {
  const pruned = new Set(["node_modules", "dist", "build", "coverage", ".git"]);
  const segments = new Set<string>();

  const walk = (dir: string, depth: number): void => {
    if (depth > maxDepth) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith(".") || pruned.has(entry.name)) continue;
      segments.add(entry.name);
      walk(path.join(dir, entry.name), depth + 1);
    }
  };

  walk(repoRoot, 1);
  return segments;
}

// ---------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------

/**
 * Candidate on-disk targets for one ESM import specifier, applying this codebase's `.js`-written /
 * `.ts`-on-disk extension rewrite.
 *
 * `import "./route-coverage-lib.js"` is satisfied by `route-coverage-lib.ts` under `tsx`, so a
 * resolver that only probed the literal `.js` would report every correct import in the repo as
 * dead. Directory and extensionless forms are probed too, since a few `.mjs` scripts use them.
 *
 * @param importerAbsPath absolute path of the file containing the import
 * @param specifier the relative specifier as written
 * @returns absolute candidate paths, most-likely first
 * @complexity O(1) — a fixed candidate list.
 */
export function resolveImportCandidates(importerAbsPath: string, specifier: string): readonly string[] {
  const base = path.resolve(path.dirname(importerAbsPath), specifier);
  const candidates: string[] = [base];

  const jsLike = /\.(js|mjs|cjs)$/.exec(base);
  if (jsLike) {
    const stem = base.slice(0, -jsLike[0].length);
    candidates.push(`${stem}.ts`, `${stem}.tsx`, `${stem}.mts`, `${stem}.cts`, `${stem}.d.ts`);
  } else if (!path.extname(base)) {
    candidates.push(`${base}.ts`, `${base}.tsx`, `${base}.js`, `${base}.mjs`, `${base}.cjs`);
    candidates.push(path.join(base, "index.ts"), path.join(base, "index.js"), path.join(base, "index.mjs"));
  }
  return candidates;
}

const toRepoRelative = (repoRoot: string, abs: string): string =>
  path.relative(repoRoot, abs).split(path.sep).join("/");

// ---------------------------------------------------------------------------
// The sweep
// ---------------------------------------------------------------------------

export interface SweepOptions {
  readonly repoRoot: string;
  /** repo-relative, forward-slash paths of the files to sweep */
  readonly files: readonly string[];
  /** when false, `repo-relative-string` references are not collected for that file (see
   *  `shouldScanStringsIn` for the rule and its rationale) */
  readonly scanStrings?: (repoRelativeFile: string) => boolean;
  readonly segments?: ReadonlySet<string>;
}

/**
 * Path strings inside a `*.test.ts` / `*.test.mjs` file are FIXTURE DATA, not references the
 * program follows — a coverage-gate test legitimately asserts against `src/contracts/.../marker.ts`
 * that has never existed. Their relative IMPORTS are still swept (class 1), because those really do
 * have to resolve. Stated as a rule rather than left to an allowlist of individual strings.
 */
export function shouldScanStringsIn(repoRelativeFile: string): boolean {
  return !/\.(test|spec)\.(ts|tsx|mts|mjs|cjs|js)$/.test(repoRelativeFile);
}

/**
 * Resolves every path reference in `files` and returns the ones that resolve to nothing.
 *
 * @param options repo root, the file list, and optional overrides for string-scanning and the
 *        derived segment set (the latter injectable so a test can drive the matcher deterministically)
 * @returns findings ordered by file then line; empty means every reference resolves
 * @complexity O(F · n) in file count and file size, plus one `existsSync` per candidate target.
 */
export function sweepFiles(options: SweepOptions): readonly DeadPathFinding[] {
  const { repoRoot, files } = options;
  const scanStrings = options.scanStrings ?? shouldScanStringsIn;
  const segments = options.segments ?? collectRepoSegments(repoRoot);
  const findings: DeadPathFinding[] = [];

  for (const file of files) {
    findings.push(...sweepOneFile(repoRoot, file, segments, scanStrings(file)));
  }

  return findings.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
}

/**
 * All three reference classes for a single file: relative imports, hardcoded repo-relative
 * strings, and (2026-09-03) the trailing literal segments of `path.join`/`path.resolve` calls.
 *
 * @param repoRoot absolute repository root
 * @param file repo-relative path of the file to read
 * @param segments the derived repo-segment set
 * @param scanStrings whether class-2/class-3 hardcoded path references should be collected for
 *        this file (same rationale for both: a test file's fixture data is not a real reference —
 *        see `shouldScanStringsIn`)
 * @returns the dead references found, in the order they were checked
 * @complexity O(n) in file size, plus one `existsSync` per candidate target.
 */
function sweepOneFile(
  repoRoot: string,
  file: string,
  segments: ReadonlySet<string>,
  scanStrings: boolean
): readonly DeadPathFinding[] {
  const abs = path.join(repoRoot, file);
  const source = fs.readFileSync(abs, "utf8");
  const imports = extractRelativeImportSpecifiers(source);
  const findings: DeadPathFinding[] = [];

  for (const { specifier, line } of imports) {
    const candidates = resolveImportCandidates(abs, specifier);
    if (candidates.some((c) => fs.existsSync(c))) continue;
    findings.push({
      file,
      line,
      kind: "relative-import",
      specifier,
      attempted: candidates.map((c) => toRepoRelative(repoRoot, c)),
    });
  }

  if (!scanStrings) return findings;

  const ownImportSpecifiers = new Set(imports.map((i) => i.specifier));
  for (const { value, line } of extractStringLiterals(source)) {
    const classified = classifyRepoRelativeString(value, { knownRepoSegments: segments, ownImportSpecifiers });
    if (classified.kind !== "repo-relative-path") continue;
    const required = pathThatMustExist(classified.repoRelative);
    if (fs.existsSync(path.join(repoRoot, required))) continue;
    findings.push({ file, line, kind: "repo-relative-string", specifier: value, attempted: [required] });
  }

  for (const { segments: rawSegments, line } of extractPathJoinSegments(source)) {
    const meaningful = dropLeadingParentSegments(rawSegments, fileDirectoryDepth(file));
    if (meaningful === null) continue; // ".." count doesn't reach exactly to repo root - can't classify safely
    if (meaningful.length < 1) continue; // nothing left but ".." segments - no target to check
    const classified = classifyPathJoinSegments(meaningful, { knownRepoSegments: segments, ownImportSpecifiers });
    if (classified.kind !== "repo-relative-path") continue;
    const required = pathThatMustExist(classified.repoRelative);
    if (fs.existsSync(path.join(repoRoot, required))) continue;
    findings.push({ file, line, kind: "path-join-call", specifier: classified.repoRelative, attempted: [required] });
  }

  return findings;
}

/** Stable "file:line specifier" key for comparing a finding against the known-broken register. */
export const findingKey = (f: PathReference): string => `${f.file}:${f.specifier}`;

/**
 * Every `*.ts` file under `development/scripts/` and `development/evals/`, plus the `*.config.ts`
 * files in the db tooling directory — the places the restructure left dead paths in (most of the
 * 2026-09-05 breaks lived under `development/evals/`, which this sweep had never covered).
 * Enumerated from disk rather than listed, so a new script or eval is swept the day it lands.
 *
 * @complexity O(d) in files under the three roots.
 */
export function collectSweepTargets(repoRoot: string): readonly string[] {
  const out: string[] = [];

  const walk = (relDir: string): void => {
    const abs = path.join(repoRoot, relDir);
    for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
      if (entry.name.startsWith(".") && entry.name !== "__tests__") continue;
      const rel = `${relDir}/${entry.name}`;
      if (entry.isDirectory()) {
        if (entry.name === "node_modules" || entry.name === "fixtures") continue;
        walk(rel);
      } else if (entry.name.endsWith(".ts")) {
        out.push(rel);
      }
    }
  };

  walk("development/scripts");
  walk("development/evals");

  const dbDir = "apps/website/src/platform/db";
  for (const entry of fs.readdirSync(path.join(repoRoot, dbDir), { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".config.ts")) out.push(`${dbDir}/${entry.name}`);
  }

  return out.sort();
}
