import { createDictionaryTranslator } from "../../lib/dictionary-translator";
import { interpolate } from "../../lib/template-i18n";

const AUTHENTICATION_TRANSLATIONS: Record<string, Record<string, string>> = {
  es: { required: "obligatorio", "Required credentials": "Credenciales obligatorias", "Authentication overview": "Resumen de autenticación", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu inicia sesión de administradores actualmente con un nombre de usuario y una contraseña locales. Aún no están implementados un backend de autenticación de proveedor, un contrato de almacenamiento seguro de credenciales de proveedor, el manejo de devoluciones de llamada ni el ciclo de vida de los tokens.", "Provider setup preview": "Vista previa de la configuración del proveedor", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Abre una pestaña de proveedor para ver las credenciales que necesitará un operador cuando exista la capacidad de backend.", People: "Personas", Authentication: "Autenticación", "Review current sign-in support and future provider requirements.": "Revisa la compatibilidad actual de inicio de sesión y los futuros requisitos de proveedores." },
  id: { required: "wajib", "Required credentials": "Kredensial wajib", "Authentication overview": "Ringkasan autentikasi", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu saat ini membuat administrator masuk dengan nama pengguna dan kata sandi lokal. Backend autentikasi penyedia, kontrak penyimpanan kredensial penyedia yang aman, penanganan callback, dan siklus hidup token belum diterapkan.", "Provider setup preview": "Pratinjau penyiapan penyedia", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Buka tab penyedia untuk melihat kredensial yang akan diperlukan operator setelah kemampuan backend tersedia.", People: "Orang", Authentication: "Autentikasi", "Review current sign-in support and future provider requirements.": "Tinjau dukungan masuk saat ini dan kebutuhan penyedia di masa mendatang." },
  de: { required: "erforderlich", "Required credentials": "Erforderliche Anmeldedaten", "Authentication overview": "Authentifizierungsübersicht", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu meldet Administratoren derzeit mit einem lokalen Benutzernamen und Passwort an. Ein Anbieter-Authentifizierungs-Backend, ein Vertrag für die sichere Speicherung von Anbieter-Anmeldedaten, die Callback-Verarbeitung und der Token-Lebenszyklus sind noch nicht implementiert.", "Provider setup preview": "Vorschau der Anbieter-Einrichtung", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Öffnen Sie einen Anbieter-Tab, um die Anmeldedaten zu sehen, die ein Operator benötigt, sobald die Backend-Funktion verfügbar ist.", People: "Personen", Authentication: "Authentifizierung", "Review current sign-in support and future provider requirements.": "Überprüfen Sie die aktuelle Anmeldeunterstützung und künftige Anbieteranforderungen." },
  "zh-CN": { required: "必填", "Required credentials": "必需凭据", "Authentication overview": "身份验证概览", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu 目前使用本地用户名和密码让管理员登录。提供商身份验证后端、安全的提供商凭据存储协议、回调处理和令牌生命周期尚未实现。", "Provider setup preview": "提供商设置预览", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "打开提供商选项卡，查看后端功能可用后操作员所需的凭据。", People: "人员", Authentication: "身份验证", "Review current sign-in support and future provider requirements.": "查看当前登录支持和未来的提供商要求。" },
  "zh-TW": { required: "必填", "Required credentials": "必要認證", "Authentication overview": "驗證概覽", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu 目前使用本機使用者名稱和密碼讓管理員登入。提供者驗證後端、安全的提供者認證儲存合約、回呼處理和權杖生命週期尚未實作。", "Provider setup preview": "提供者設定預覽", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "開啟提供者分頁，以查看後端功能可用後操作員所需的認證。", People: "人員", Authentication: "驗證", "Review current sign-in support and future provider requirements.": "檢視目前的登入支援和未來的提供者需求。" },
  "pt-BR": { required: "obrigatório", "Required credentials": "Credenciais obrigatórias", "Authentication overview": "Visão geral da autenticação", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Atualmente, o Tovu faz o login dos administradores com um nome de usuário e uma senha locais. Um backend de autenticação de provedor, um contrato de armazenamento seguro de credenciais de provedor, o tratamento de retorno de chamada e o ciclo de vida do token ainda não foram implementados.", "Provider setup preview": "Prévia da configuração do provedor", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Abra uma aba de provedor para ver as credenciais que um operador precisará quando a capacidade de backend existir.", People: "Pessoas", Authentication: "Autenticação", "Review current sign-in support and future provider requirements.": "Revise o suporte atual de login e os futuros requisitos de provedores." },
  ru: { required: "обязательно", "Required credentials": "Обязательные учётные данные", "Authentication overview": "Обзор аутентификации", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Сейчас Tovu выполняет вход администраторов с помощью локальных имени пользователя и пароля. Серверная часть аутентификации поставщика, безопасный контракт хранения учётных данных поставщика, обработка обратных вызовов и жизненный цикл токенов ещё не реализованы.", "Provider setup preview": "Предварительный просмотр настройки поставщика", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Откройте вкладку поставщика, чтобы увидеть учётные данные, которые понадобятся оператору, когда появится возможность серверной части.", People: "Люди", Authentication: "Аутентификация", "Review current sign-in support and future provider requirements.": "Просмотрите текущую поддержку входа и будущие требования к поставщикам." },
  fa: { required: "الزامی", "Required credentials": "اعتبارنامه‌های الزامی", "Authentication overview": "نمای کلی احراز هویت", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu اکنون مدیران را با نام کاربری و گذرواژهٔ محلی وارد می‌کند. بک‌اند احراز هویت ارائه‌دهنده، قرارداد ذخیره‌سازی امن اعتبارنامهٔ ارائه‌دهنده، رسیدگی به بازخوانی و چرخهٔ عمر توکن هنوز پیاده‌سازی نشده‌اند.", "Provider setup preview": "پیش‌نمایش تنظیم ارائه‌دهنده", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "برای دیدن اعتبارنامه‌هایی که پس از فراهم‌شدن قابلیت بک‌اند به آن‌ها نیاز است، زبانهٔ یک ارائه‌دهنده را باز کنید.", People: "افراد", Authentication: "احراز هویت", "Review current sign-in support and future provider requirements.": "پشتیبانی فعلی ورود و نیازهای آیندهٔ ارائه‌دهندگان را بررسی کنید." },
  ar: { required: "مطلوب", "Required credentials": "بيانات الاعتماد المطلوبة", "Authentication overview": "نظرة عامة على المصادقة", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "يسجّل Tovu دخول المسؤولين حاليًا باستخدام اسم مستخدم وكلمة مرور محليين. لم يُنفَّذ بعد نظام مصادقة خلفي لموفّر، أو عقد تخزين آمن لبيانات اعتماد الموفّر، أو معالجة الاستدعاء، أو دورة حياة الرمز المميّز.", "Provider setup preview": "معاينة إعداد الموفّر", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "افتح علامة تبويب لموفّر للاطلاع على بيانات الاعتماد التي سيحتاجها المشغّل عند توفر إمكانات النظام الخلفي.", People: "الأشخاص", Authentication: "المصادقة", "Review current sign-in support and future provider requirements.": "راجع دعم تسجيل الدخول الحالي ومتطلبات الموفّرين المستقبلية." },
  ja: { required: "必須", "Required credentials": "必要な認証情報", "Authentication overview": "認証の概要", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu は現在、ローカルのユーザー名とパスワードで管理者をサインインさせます。プロバイダー認証バックエンド、プロバイダー認証情報の安全な保存契約、コールバック処理、トークンのライフサイクルはまだ実装されていません。", "Provider setup preview": "プロバイダー設定のプレビュー", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "バックエンド機能が利用可能になったときにオペレーターが必要とする認証情報を確認するには、プロバイダーのタブを開きます。", People: "ユーザー", Authentication: "認証", "Review current sign-in support and future provider requirements.": "現在のサインイン対応と今後のプロバイダー要件を確認します。" },
  ko: { required: "필수", "Required credentials": "필수 자격 증명", "Authentication overview": "인증 개요", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu는 현재 로컬 사용자 이름과 비밀번호로 관리자를 로그인합니다. 공급자 인증 백엔드, 안전한 공급자 자격 증명 저장 계약, 콜백 처리 및 토큰 수명 주기는 아직 구현되지 않았습니다.", "Provider setup preview": "공급자 설정 미리 보기", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "백엔드 기능을 사용할 수 있게 되면 운영자에게 필요한 자격 증명을 보려면 공급자 탭을 여세요.", People: "사용자", Authentication: "인증", "Review current sign-in support and future provider requirements.": "현재 로그인 지원 및 향후 공급자 요구 사항을 검토하세요." },
  pl: { required: "wymagane", "Required credentials": "Wymagane poświadczenia", "Authentication overview": "Przegląd uwierzytelniania", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu obecnie loguje administratorów za pomocą lokalnej nazwy użytkownika i hasła. Backend uwierzytelniania dostawcy, umowa bezpiecznego przechowywania poświadczeń dostawcy, obsługa wywołań zwrotnych i cykl życia tokenów nie są jeszcze zaimplementowane.", "Provider setup preview": "Podgląd konfiguracji dostawcy", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Otwórz kartę dostawcy, aby zobaczyć poświadczenia, których operator będzie potrzebować, gdy funkcja backendu będzie dostępna.", People: "Osoby", Authentication: "Uwierzytelnianie", "Review current sign-in support and future provider requirements.": "Przejrzyj bieżącą obsługę logowania i przyszłe wymagania dostawców." },
  hu: { required: "kötelező", "Required credentials": "Kötelező hitelesítő adatok", "Authentication overview": "Hitelesítés áttekintése", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "A Tovu jelenleg helyi felhasználónévvel és jelszóval lépteti be a rendszergazdákat. A szolgáltatói hitelesítési háttérrendszer, a szolgáltatói hitelesítő adatok biztonságos tárolási szerződése, a visszahívás-kezelés és a tokenek életciklusa még nincs megvalósítva.", "Provider setup preview": "Szolgáltatói beállítás előnézete", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Nyisson meg egy szolgáltatói lapot, hogy megtekinthesse azokat a hitelesítő adatokat, amelyekre az üzemeltetőnek szüksége lesz, amikor a háttérrendszer képessége elérhetővé válik.", People: "Személyek", Authentication: "Hitelesítés", "Review current sign-in support and future provider requirements.": "Tekintse át a jelenlegi bejelentkezési támogatást és a jövőbeli szolgáltatói követelményeket." },
  fr: { required: "obligatoire", "Required credentials": "Identifiants requis", "Authentication overview": "Aperçu de l’authentification", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu connecte actuellement les administrateurs avec un nom d’utilisateur et un mot de passe locaux. Un backend d’authentification de fournisseur, un contrat de stockage sécurisé des identifiants de fournisseur, la gestion des retours d’appel et le cycle de vie des jetons ne sont pas encore implémentés.", "Provider setup preview": "Aperçu de la configuration du fournisseur", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Ouvrez un onglet de fournisseur pour voir les identifiants dont un opérateur aura besoin lorsque la fonctionnalité backend existera.", People: "Personnes", Authentication: "Authentification", "Review current sign-in support and future provider requirements.": "Examinez la prise en charge actuelle de la connexion et les futures exigences des fournisseurs." },
  uk: { required: "обов’язково", "Required credentials": "Обов’язкові облікові дані", "Authentication overview": "Огляд автентифікації", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Наразі Tovu виконує вхід адміністраторів за допомогою локальних імені користувача та пароля. Серверна частина автентифікації постачальника, угода про безпечне зберігання облікових даних постачальника, обробка зворотних викликів і життєвий цикл токенів ще не реалізовані.", "Provider setup preview": "Попередній перегляд налаштування постачальника", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Відкрийте вкладку постачальника, щоб переглянути облікові дані, які знадобляться оператору, коли з’явиться можливість серверної частини.", People: "Люди", Authentication: "Автентифікація", "Review current sign-in support and future provider requirements.": "Перегляньте поточну підтримку входу та майбутні вимоги постачальників." },
  tr: { required: "zorunlu", "Required credentials": "Gerekli kimlik bilgileri", "Authentication overview": "Kimlik doğrulamaya genel bakış", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu şu anda yöneticilerin oturumunu yerel kullanıcı adı ve parolayla açar. Sağlayıcı kimlik doğrulama arka ucu, sağlayıcı kimlik bilgileri için güvenli depolama sözleşmesi, geri çağırma işleme ve belirteç yaşam döngüsü henüz uygulanmadı.", "Provider setup preview": "Sağlayıcı kurulumu ön izlemesi", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Arka uç yeteneği kullanılabilir olduğunda operatörün gereksineceği kimlik bilgilerini görmek için bir sağlayıcı sekmesi açın.", People: "Kişiler", Authentication: "Kimlik doğrulama", "Review current sign-in support and future provider requirements.": "Geçerli oturum açma desteğini ve gelecekteki sağlayıcı gereksinimlerini inceleyin." },
  th: { required: "จำเป็น", "Required credentials": "ข้อมูลประจำตัวที่จำเป็น", "Authentication overview": "ภาพรวมการยืนยันตัวตน", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "ขณะนี้ Tovu ให้ผู้ดูแลระบบลงชื่อเข้าใช้ด้วยชื่อผู้ใช้และรหัสผ่านภายในเครื่อง ระบบแบ็กเอนด์การยืนยันตัวตนของผู้ให้บริการ ข้อตกลงการจัดเก็บข้อมูลประจำตัวของผู้ให้บริการอย่างปลอดภัย การจัดการการเรียกกลับ และวงจรชีวิตของโทเค็นยังไม่ได้รับการพัฒนา", "Provider setup preview": "ตัวอย่างการตั้งค่าผู้ให้บริการ", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "เปิดแท็บผู้ให้บริการเพื่อดูข้อมูลประจำตัวที่ผู้ปฏิบัติงานจะต้องใช้เมื่อความสามารถของแบ็กเอนด์พร้อมใช้งาน", People: "บุคคล", Authentication: "การยืนยันตัวตน", "Review current sign-in support and future provider requirements.": "ตรวจสอบการรองรับการลงชื่อเข้าใช้ในปัจจุบันและข้อกำหนดของผู้ให้บริการในอนาคต" },
  it: { required: "obbligatorio", "Required credentials": "Credenziali obbligatorie", "Authentication overview": "Panoramica dell’autenticazione", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu attualmente fa accedere gli amministratori con un nome utente e una password locali. Un backend di autenticazione del provider, un contratto di archiviazione sicura delle credenziali del provider, la gestione dei callback e il ciclo di vita dei token non sono ancora implementati.", "Provider setup preview": "Anteprima della configurazione del provider", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "Apri una scheda del provider per vedere le credenziali di cui un operatore avrà bisogno quando la funzionalità backend sarà disponibile.", People: "Persone", Authentication: "Autenticazione", "Review current sign-in support and future provider requirements.": "Esamina il supporto di accesso attuale e i futuri requisiti dei provider." },
  hi: { required: "आवश्यक", "Required credentials": "आवश्यक क्रेडेंशियल", "Authentication overview": "प्रमाणीकरण अवलोकन", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu वर्तमान में स्थानीय उपयोगकर्ता नाम और पासवर्ड से व्यवस्थापकों को साइन इन कराता है। प्रदाता प्रमाणीकरण बैकएंड, सुरक्षित प्रदाता-क्रेडेंशियल संग्रह अनुबंध, कॉलबैक प्रबंधन और टोकन जीवनचक्र अभी लागू नहीं किए गए हैं।", "Provider setup preview": "प्रदाता सेटअप पूर्वावलोकन", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "बैकएंड क्षमता उपलब्ध होने पर ऑपरेटर को जिन क्रेडेंशियल की आवश्यकता होगी उन्हें देखने के लिए प्रदाता टैब खोलें।", People: "लोग", Authentication: "प्रमाणीकरण", "Review current sign-in support and future provider requirements.": "वर्तमान साइन-इन समर्थन और भविष्य की प्रदाता आवश्यकताओं की समीक्षा करें।" },
  ur: { required: "ضروری", "Required credentials": "ضروری اسناد", "Authentication overview": "تصدیق کا جائزہ", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu فی الحال مقامی صارف نام اور پاس ورڈ سے منتظمین کو سائن اِن کرتا ہے۔ فراہم کنندہ تصدیقی بیک اینڈ، فراہم کنندہ کی اسناد کو محفوظ رکھنے کا معاہدہ، کال بیک ہینڈلنگ اور ٹوکن لائف سائیکل ابھی نافذ نہیں ہیں۔", "Provider setup preview": "فراہم کنندہ سیٹ اپ کا پیش نظارہ", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "بیک اینڈ صلاحیت دستیاب ہونے پر آپریٹر کو درکار اسناد دیکھنے کے لیے فراہم کنندہ کا ٹیب کھولیں۔", People: "افراد", Authentication: "تصدیق", "Review current sign-in support and future provider requirements.": "موجودہ سائن اِن معاونت اور مستقبل کے فراہم کنندہ تقاضوں کا جائزہ لیں۔" },
  bn: { required: "প্রয়োজনীয়", "Required credentials": "প্রয়োজনীয় পরিচয়পত্র", "Authentication overview": "প্রমাণীকরণ সংক্ষিপ্ত বিবরণ", "Tovu currently signs administrators in with a local username and password. A provider authentication backend, secure provider-credential storage contract, callback handling, and token lifecycle are not implemented yet.": "Tovu বর্তমানে স্থানীয় ব্যবহারকারীর নাম ও পাসওয়ার্ড দিয়ে প্রশাসকদের সাইন ইন করায়। প্রদানকারী প্রমাণীকরণ ব্যাকএন্ড, প্রদানকারীর পরিচয়পত্র নিরাপদে সংরক্ষণের চুক্তি, কলব্যাক পরিচালনা এবং টোকেনের জীবনচক্র এখনও বাস্তবায়িত হয়নি।", "Provider setup preview": "প্রদানকারী সেটআপের পূর্বরূপ", "Open a provider tab to see the credentials an operator will need once the backend capability exists.": "ব্যাকএন্ড সুবিধা উপলভ্য হলে অপারেটরের যে পরিচয়পত্র লাগবে তা দেখতে একটি প্রদানকারী ট্যাব খুলুন।", People: "ব্যক্তি", Authentication: "প্রমাণীকরণ", "Review current sign-in support and future provider requirements.": "বর্তমান সাইন-ইন সমর্থন এবং ভবিষ্যতের প্রদানকারী প্রয়োজনীয়তা পর্যালোচনা করুন।" },
};

const PROVIDER_BACKEND_NOTE_TEMPLATE: Record<string, string> = {
  en: "Not connected to a provider authentication backend yet. These required fields are shown for setup planning; Tovu cannot save credentials or enable {provider} sign-in from this screen today.",
  es: "Aún no está conectado a un backend de autenticación de proveedor. Estos campos obligatorios se muestran para planificar la configuración; Tovu no puede guardar credenciales ni habilitar el inicio de sesión con {provider} desde esta pantalla hoy.",
  id: "Belum terhubung ke backend autentikasi penyedia. Kolom wajib ini ditampilkan untuk perencanaan penyiapan; Tovu belum dapat menyimpan kredensial atau mengaktifkan masuk dengan {provider} dari layar ini.",
  de: "Noch nicht mit einem Anbieter-Authentifizierungs-Backend verbunden. Diese erforderlichen Felder werden für die Einrichtungsplanung angezeigt; Tovu kann heute keine Anmeldedaten speichern oder die Anmeldung mit {provider} über diesen Bildschirm aktivieren.",
  "zh-CN": "尚未连接到提供商身份验证后端。这些必填字段用于设置规划；Tovu 目前无法从此屏幕保存凭据或启用 {provider} 登录。",
  "zh-TW": "尚未連線至提供者驗證後端。這些必填欄位用於設定規劃；Tovu 目前無法從此畫面儲存認證或啟用 {provider} 登入。",
  "pt-BR": "Ainda não está conectado a um backend de autenticação de provedor. Estes campos obrigatórios são mostrados para o planejamento da configuração; o Tovu não pode salvar credenciais nem habilitar o login com {provider} nesta tela hoje.",
  ru: "Подключение к серверной части аутентификации поставщика ещё не настроено. Эти обязательные поля показаны для планирования настройки; сегодня Tovu не может сохранять учётные данные или включать вход через {provider} с этого экрана.",
  fa: "هنوز به بک‌اند احراز هویت ارائه‌دهنده متصل نیست. این فیلدهای الزامی برای برنامه‌ریزی راه‌اندازی نمایش داده می‌شوند؛ Tovu امروز نمی‌تواند اعتبارنامه‌ها را ذخیره کند یا ورود با {provider} را از این صفحه فعال کند.",
  ar: "لم يتم الاتصال بعد بنظام مصادقة خلفي لموفّر. تظهر هذه الحقول المطلوبة لتخطيط الإعداد؛ لا يستطيع Tovu اليوم حفظ بيانات الاعتماد أو تمكين تسجيل الدخول عبر {provider} من هذه الشاشة.",
  ja: "プロバイダー認証バックエンドにはまだ接続されていません。これらの必須フィールドは設定計画のために表示されています。Tovu は現在、この画面から認証情報を保存したり、{provider} でのサインインを有効にしたりできません。",
  ko: "아직 공급자 인증 백엔드에 연결되어 있지 않습니다. 이 필수 필드는 설정 계획을 위해 표시됩니다. Tovu는 현재 이 화면에서 자격 증명을 저장하거나 {provider} 로그인을 활성화할 수 없습니다.",
  pl: "Nie połączono jeszcze z backendem uwierzytelniania dostawcy. Te wymagane pola są wyświetlane do planowania konfiguracji; Tovu nie może obecnie zapisywać poświadczeń ani włączać logowania przez {provider} z tego ekranu.",
  hu: "Még nincs kapcsolat a szolgáltatói hitelesítési háttérrendszerrel. Ezek a kötelező mezők a beállítás tervezéséhez jelennek meg; a Tovu jelenleg nem tud hitelesítő adatokat menteni vagy {provider}-bejelentkezést engedélyezni ezen a képernyőn.",
  fr: "Pas encore connecté à un backend d’authentification de fournisseur. Ces champs obligatoires sont affichés pour planifier la configuration ; Tovu ne peut pas encore enregistrer les identifiants ni activer la connexion avec {provider} depuis cet écran.",
  uk: "Ще не підключено до серверної частини автентифікації постачальника. Ці обов’язкові поля показано для планування налаштування; сьогодні Tovu не може зберігати облікові дані або вмикати вхід через {provider} з цього екрана.",
  tr: "Henüz bir sağlayıcı kimlik doğrulama arka ucuna bağlı değil. Bu zorunlu alanlar kurulum planlaması için gösterilir; Tovu bugün bu ekrandan kimlik bilgilerini kaydedemez veya {provider} ile oturum açmayı etkinleştiremez.",
  th: "ยังไม่ได้เชื่อมต่อกับแบ็กเอนด์การยืนยันตัวตนของผู้ให้บริการ ฟิลด์ที่จำเป็นเหล่านี้แสดงไว้เพื่อวางแผนการตั้งค่า โดยขณะนี้ Tovu ไม่สามารถบันทึกข้อมูลประจำตัวหรือเปิดใช้การลงชื่อเข้าใช้ด้วย {provider} จากหน้าจอนี้ได้",
  it: "Non è ancora connesso a un backend di autenticazione del provider. Questi campi obbligatori sono mostrati per pianificare la configurazione; oggi Tovu non può salvare credenziali né abilitare l’accesso con {provider} da questa schermata.",
  hi: "अभी प्रदाता प्रमाणीकरण बैकएंड से कनेक्ट नहीं है। ये आवश्यक फ़ील्ड सेटअप योजना के लिए दिखाए जाते हैं; Tovu आज इस स्क्रीन से क्रेडेंशियल सहेज या {provider} साइन-इन सक्षम नहीं कर सकता।",
  ur: "ابھی فراہم کنندہ تصدیقی بیک اینڈ سے منسلک نہیں ہے۔ یہ ضروری فیلڈز سیٹ اپ کی منصوبہ بندی کے لیے دکھائے جاتے ہیں؛ Tovu آج اس اسکرین سے اسناد محفوظ نہیں کر سکتا یا {provider} سائن اِن فعال نہیں کر سکتا۔",
  bn: "এখনও প্রদানকারী প্রমাণীকরণ ব্যাকএন্ডের সঙ্গে সংযুক্ত নয়। সেটআপ পরিকল্পনার জন্য এই প্রয়োজনীয় ফিল্ডগুলো দেখানো হয়েছে; Tovu আজ এই স্ক্রিন থেকে পরিচয়পত্র সংরক্ষণ বা {provider} সাইন-ইন সক্ষম করতে পারে না।",
};

export const t = createDictionaryTranslator(AUTHENTICATION_TRANSLATIONS);

export function providerBackendNote(locale: string, provider: string): string {
  return interpolate(PROVIDER_BACKEND_NOTE_TEMPLATE[locale] ?? PROVIDER_BACKEND_NOTE_TEMPLATE.en, { provider });
}
