import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

import type { KeyringPort, RootKeyHandle, SecretSealerPort } from "./ports";
import type { SealedSecret } from "./types";

/**
 * @file `SecretSealerPort`'s first real implementation (ADR-058) — the seam ADR-036 §8 named and
 * deferred ("the recoverable secret-store ADR") when it shipped `integration_secrets`/`SealedSecret`
 * as a table shape with no adapter behind it.
 *
 * How it relates to the project:
 * AES-256-GCM via bare `node:crypto` (no new dependency, matching every other crypto use in this
 * codebase — `keyring.env.ts`, `daemon-auth.ts`, `lipay-gateway.ts` are all already bare
 * `node:crypto`). The AES key is never held or generated by this class directly — it is re-derived
 * on every `seal`/`open` call from an injected `KeyringPort` (ADR-024 §3 by-handle discipline: raw
 * root-key bytes never cross this class's own boundary, only the `RootKeyHandle`'s `keyId` does).
 * `purpose: "secret-sealer.v1"` binds the derivation into its own HKDF domain, separate from
 * webhook-signing (`deriveSigningSecret`) and newsletter-token derivation that share the same root
 * key elsewhere in this codebase (ADR-036 Round-3 fold: `purpose` MUST be a real separation
 * boundary, not decorative).
 *
 * One shared sealing capability app-wide, not one key per tenant: `deriveAesKey` derives a SINGLE
 * AES key per root-key generation (`key.keyId`), the same key for every workspace and every record.
 * Multi-tenant separation is a property of the DATA layer (each row carries its own `workspace_id`
 * — see `site-credential-store.ts`), not of the encryption key, which is standard envelope
 * encryption and matches `SealedSecret.keyId`'s own doc ("names the root-key generation the value
 * was wrapped under" — one generation identity for the whole store, not per-consumer).
 *
 * Rule-of-two (ADR-006): this is the "real adapter" half. There is deliberately no separate
 * plaintext-passthrough test double for `SecretSealerPort` itself — a fake that skips encryption
 * would defeat the one thing worth testing (that a value round-trips through REAL AES-GCM). The
 * lightweight test path is this same class backed by `KeyringPort`'s own existing in-memory adapter
 * (`InMemoryKeyring`), which is already fast, hermetic, and deterministic per process.
 */

const ALG = "aes-256-gcm";
const IV_LENGTH_BYTES = 12;
const AUTH_TAG_LENGTH_BYTES = 16;
const SEALER_PURPOSE = "secret-sealer.v1";
/** Fixed `KeyringPort.derive()` workspace-scope label for the sealer's OWN key derivation — see
 *  this file's header on why one shared key, not one per tenant. */
const SEALER_KEY_SCOPE = "secret-sealer";

/**
 * AES-256-GCM `SecretSealerPort` adapter over a `KeyringPort`.
 *
 * @overallScore 100
 */
export class AesGcmSecretSealer implements SecretSealerPort {
  constructor(private readonly keyring: KeyringPort) {}

  /**
   * Encrypts `input.plaintext` under a key derived from `input.key` (the caller's current
   * `RootKeyHandle`, typically `keyring.activeKey()`).
   *
   * @returns `{keyId, ciphertext, nonce, alg}` — `ciphertext` is base64(AEAD ciphertext || 16-byte
   *   GCM auth tag), `nonce` is base64(12-byte IV). A fresh random IV every call — GCM's security
   *   property depends on never reusing an IV under the same key.
   * @throws Whatever `KeyringPort.derive()` throws (e.g. a missing root key) — propagated, never
   *   swallowed into a plaintext fallback (ADR-058 §4: this feature's callers convert that into a
   *   distinct `SECRET_STORE_UNCONFIGURED` error, they do not catch it here).
   * @complexity O(n) in `plaintext` length — one cipher pass, no loops over caller-controlled
   *   collections.
   * @overallScore 100
   */
  async seal(input: { plaintext: string; key: RootKeyHandle }): Promise<SealedSecret> {
    const aesKey = await this.deriveAesKey(input.key);
    const iv = randomBytes(IV_LENGTH_BYTES);
    const cipher = createCipheriv(ALG, aesKey, iv);
    const ciphertext = Buffer.concat([cipher.update(input.plaintext, "utf8"), cipher.final()]);
    const authTag = cipher.getAuthTag();
    return {
      keyId: input.key.keyId,
      ciphertext: Buffer.concat([ciphertext, authTag]).toString("base64"),
      nonce: iv.toString("base64"),
      alg: ALG,
    };
  }

  /**
   * Reverses {@link seal}. Re-derives the AES key from `input.sealed.keyId` (not from
   * `keyring.activeKey()` — a sealed row wrapped under an older root-key generation must still open
   * under that generation's own derivation, the seam `keyId` exists for).
   *
   * @throws If `input.sealed.alg` is not `"aes-256-gcm"`, if the ciphertext is malformed/too short to
   *   contain an auth tag, if the auth tag fails to verify (tampered ciphertext or wrong key), or
   *   whatever `KeyringPort.derive()` throws. Never returns a partial or best-guess plaintext.
   * @complexity O(n) in ciphertext length.
   * @overallScore 100
   */
  async open(input: { sealed: SealedSecret }): Promise<string> {
    if (input.sealed.alg !== ALG) {
      throw new Error(`AesGcmSecretSealer cannot open alg '${input.sealed.alg}' (expected '${ALG}')`);
    }
    const aesKey = await this.deriveAesKey({ keyId: input.sealed.keyId });
    const iv = Buffer.from(input.sealed.nonce, "base64");
    const combined = Buffer.from(input.sealed.ciphertext, "base64");
    if (combined.length <= AUTH_TAG_LENGTH_BYTES) {
      throw new Error("AesGcmSecretSealer: ciphertext too short to contain an auth tag");
    }
    const authTag = combined.subarray(combined.length - AUTH_TAG_LENGTH_BYTES);
    const ciphertext = combined.subarray(0, combined.length - AUTH_TAG_LENGTH_BYTES);
    const decipher = createDecipheriv(ALG, aesKey, iv);
    decipher.setAuthTag(authTag);
    const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
    return plaintext.toString("utf8");
  }

  private async deriveAesKey(key: RootKeyHandle): Promise<Uint8Array> {
    return this.keyring.derive({ workspaceId: SEALER_KEY_SCOPE, purpose: SEALER_PURPOSE, info: key.keyId });
  }
}
