/** Copy for this desktop feature, in every locale supported by Tovu's admin. */
export interface DesktopCopy {
  settings: string;
  automaticUpdates: string;
  saveUpdateError: string;
  restart: string;
  restarting: string;
  siteErrors: { invalid: string; empty: string; incomplete: string; unreadable: string; add: string; start: string };
}
const COPY: Record<string, readonly [string, string, string, string, string]> = {
  en: ['Settings', 'Automatically update Tovu', 'Could not save update preference', 'Restart', 'Restarting…'],
  es: ['Ajustes', 'Actualizar Tovu automáticamente', 'No se pudo guardar la preferencia de actualización', 'Reiniciar', 'Reiniciando…'],
  de: ['Einstellungen', 'Tovu automatisch aktualisieren', 'Update-Einstellung konnte nicht gespeichert werden', 'Neu starten', 'Neustart…'],
  it: ['Impostazioni', 'Aggiorna Tovu automaticamente', 'Impossibile salvare la preferenza di aggiornamento', 'Riavvia', 'Riavvio…'],
  'zh-CN': ['设置', '自动更新 Tovu', '无法保存更新偏好', '重启', '正在重启…'],
  'zh-TW': ['設定', '自動更新 Tovu', '無法儲存更新偏好', '重新啟動', '正在重新啟動…'],
  ar: ['الإعدادات', 'تحديث Tovu تلقائيًا', 'تعذر حفظ تفضيل التحديث', 'إعادة التشغيل', 'جارٍ إعادة التشغيل…'],
  fa: ['تنظیمات', 'به‌روزرسانی خودکار Tovu', 'ذخیرهٔ تنظیم به‌روزرسانی ممکن نشد', 'راه‌اندازی مجدد', 'در حال راه‌اندازی مجدد…'],
  ru: ['Настройки', 'Автоматически обновлять Tovu', 'Не удалось сохранить настройку обновления', 'Перезапустить', 'Перезапуск…'],
  ja: ['設定', 'Tovu を自動更新', '更新設定を保存できませんでした', '再起動', '再起動中…'],
  id: ['Pengaturan', 'Perbarui Tovu secara otomatis', 'Tidak dapat menyimpan preferensi pembaruan', 'Mulai ulang', 'Memulai ulang…'],
  'pt-BR': ['Configurações', 'Atualizar Tovu automaticamente', 'Não foi possível salvar a preferência de atualização', 'Reiniciar', 'Reiniciando…'],
  ko: ['설정', 'Tovu 자동 업데이트', '업데이트 설정을 저장할 수 없습니다', '다시 시작', '다시 시작하는 중…'],
  pl: ['Ustawienia', 'Automatycznie aktualizuj Tovu', 'Nie udało się zapisać ustawienia aktualizacji', 'Uruchom ponownie', 'Ponowne uruchamianie…'],
  hu: ['Beállítások', 'A Tovu automatikus frissítése', 'Nem sikerült menteni a frissítési beállítást', 'Újraindítás', 'Újraindítás…'],
  fr: ['Paramètres', 'Mettre à jour Tovu automatiquement', 'Impossible d’enregistrer la préférence de mise à jour', 'Redémarrer', 'Redémarrage…'],
  uk: ['Налаштування', 'Автоматично оновлювати Tovu', 'Не вдалося зберегти налаштування оновлення', 'Перезапустити', 'Перезапуск…'],
  tr: ['Ayarlar', 'Tovu’yu otomatik güncelle', 'Güncelleme tercihi kaydedilemedi', 'Yeniden başlat', 'Yeniden başlatılıyor…'],
  th: ['การตั้งค่า', 'อัปเดต Tovu โดยอัตโนมัติ', 'ไม่สามารถบันทึกการตั้งค่าการอัปเดตได้', 'เริ่มใหม่', 'กำลังเริ่มใหม่…'],
  hi: ['सेटिंग', 'Tovu को अपने आप अपडेट करें', 'अपडेट की प्राथमिकता सहेजी नहीं जा सकी', 'फिर से शुरू करें', 'फिर से शुरू हो रहा है…'],
  ur: ['ترتیبات', 'Tovu کو خودکار طور پر اپ ڈیٹ کریں', 'اپ ڈیٹ کی ترجیح محفوظ نہیں ہو سکی', 'دوبارہ شروع کریں', 'دوبارہ شروع ہو رہا ہے…'],
  bn: ['সেটিংস', 'Tovu স্বয়ংক্রিয়ভাবে আপডেট করুন', 'আপডেটের পছন্দ সংরক্ষণ করা যায়নি', 'পুনরায় চালু করুন', 'পুনরায় চালু হচ্ছে…'],
};

const SITE_ERROR_COPY: Record<string, readonly [string, string, string, string, string, string]> = {
  en: ['This folder is not a Tovu website. Choose the folder containing your website.', 'No Tovu website was found in this folder. Choose an existing website or use Create website.', 'This Tovu website is incomplete. Choose a complete website folder.', 'Cannot read this website folder. Check that it is available and that Tovu has permission to read it.', 'Could not add this website. Check the folder and try again.', 'Could not start this website. Try again or check its logs.'],
  es: ['Esta carpeta no es un sitio web de Tovu. Elige la carpeta que contiene tu sitio web.', 'No se encontró un sitio web de Tovu en esta carpeta. Elige un sitio existente o usa Crear sitio web.', 'Este sitio web de Tovu está incompleto. Elige la carpeta de un sitio web completo.', 'No se puede leer la carpeta del sitio web. Comprueba que esté disponible y que Tovu tenga permiso para leerla.', 'No se pudo añadir este sitio web. Comprueba la carpeta e inténtalo de nuevo.', 'No se pudo iniciar este sitio web. Inténtalo de nuevo o revisa sus registros.'],
  de: ['Dieser Ordner ist keine Tovu-Website. Wähle den Ordner mit deiner Website.', 'In diesem Ordner wurde keine Tovu-Website gefunden. Wähle eine bestehende Website oder verwende Website erstellen.', 'Diese Tovu-Website ist unvollständig. Wähle einen vollständigen Website-Ordner.', 'Der Website-Ordner kann nicht gelesen werden. Prüfe, ob er verfügbar ist und Tovu Leserechte hat.', 'Diese Website konnte nicht hinzugefügt werden. Prüfe den Ordner und versuche es erneut.', 'Diese Website konnte nicht gestartet werden. Versuche es erneut oder prüfe die Protokolle.'],
  it: ['Questa cartella non è un sito web Tovu. Scegli la cartella che contiene il tuo sito web.', 'Nessun sito web Tovu trovato in questa cartella. Scegli un sito esistente o usa Crea sito web.', 'Questo sito web Tovu è incompleto. Scegli la cartella di un sito web completo.', 'Impossibile leggere la cartella del sito web. Verifica che sia disponibile e che Tovu abbia il permesso di leggerla.', 'Impossibile aggiungere questo sito web. Controlla la cartella e riprova.', 'Impossibile avviare questo sito web. Riprova o controlla i registri.'],
  'zh-CN': ['此文件夹不是 Tovu 网站。请选择包含网站的文件夹。', '此文件夹中未找到 Tovu 网站。请选择现有网站或使用“创建网站”。', '此 Tovu 网站不完整。请选择完整的网站文件夹。', '无法读取此网站文件夹。请检查文件夹是否可用，以及 Tovu 是否有读取权限。', '无法添加此网站。请检查文件夹后重试。', '无法启动此网站。请重试或查看日志。'],
  'zh-TW': ['此資料夾不是 Tovu 網站。請選擇包含網站的資料夾。', '此資料夾中找不到 Tovu 網站。請選擇現有網站或使用「建立網站」。', '此 Tovu 網站不完整。請選擇完整的網站資料夾。', '無法讀取此網站資料夾。請確認資料夾可用，且 Tovu 有讀取權限。', '無法新增此網站。請檢查資料夾後重試。', '無法啟動此網站。請重試或查看記錄。'],
  ar: ['هذا المجلد ليس موقع Tovu. اختر المجلد الذي يحتوي على موقعك.', 'لم يُعثر على موقع Tovu في هذا المجلد. اختر موقعًا موجودًا أو استخدم إنشاء موقع.', 'موقع Tovu هذا غير مكتمل. اختر مجلد موقع مكتمل.', 'تعذرت قراءة مجلد الموقع. تأكد من توفره ومن امتلاك Tovu إذن قراءته.', 'تعذرت إضافة هذا الموقع. تحقق من المجلد وحاول مجددًا.', 'تعذر تشغيل هذا الموقع. حاول مجددًا أو تحقق من سجلاته.'],
  fa: ['این پوشه یک وب‌سایت Tovu نیست. پوشهٔ حاوی وب‌سایت خود را انتخاب کنید.', 'هیچ وب‌سایت Tovu در این پوشه پیدا نشد. یک وب‌سایت موجود انتخاب کنید یا از ایجاد وب‌سایت استفاده کنید.', 'این وب‌سایت Tovu ناقص است. پوشهٔ یک وب‌سایت کامل را انتخاب کنید.', 'خواندن پوشهٔ وب‌سایت ممکن نیست. در دسترس بودن آن و مجوز خواندن Tovu را بررسی کنید.', 'افزودن این وب‌سایت ممکن نشد. پوشه را بررسی و دوباره تلاش کنید.', 'راه‌اندازی این وب‌سایت ممکن نشد. دوباره تلاش کنید یا گزارش‌های آن را بررسی کنید.'],
  ru: ['Эта папка не является сайтом Tovu. Выберите папку, содержащую ваш сайт.', 'В этой папке не найден сайт Tovu. Выберите существующий сайт или используйте Создать сайт.', 'Этот сайт Tovu неполный. Выберите папку полного сайта.', 'Не удалось прочитать папку сайта. Проверьте её доступность и разрешение Tovu на чтение.', 'Не удалось добавить этот сайт. Проверьте папку и повторите попытку.', 'Не удалось запустить этот сайт. Повторите попытку или проверьте журналы.'],
  ja: ['このフォルダーは Tovu のウェブサイトではありません。ウェブサイトを含むフォルダーを選択してください。', 'このフォルダーに Tovu のウェブサイトが見つかりません。既存のサイトを選択するか、ウェブサイトを作成を使用してください。', 'この Tovu ウェブサイトは不完全です。完全なウェブサイトのフォルダーを選択してください。', 'ウェブサイトのフォルダーを読み取れません。利用可能かどうかと Tovu の読み取り権限を確認してください。', 'このウェブサイトを追加できませんでした。フォルダーを確認して再試行してください。', 'このウェブサイトを起動できませんでした。再試行するか、ログを確認してください。'],
  id: ['Folder ini bukan situs web Tovu. Pilih folder yang berisi situs web Anda.', 'Tidak ada situs web Tovu dalam folder ini. Pilih situs yang sudah ada atau gunakan Buat situs web.', 'Situs web Tovu ini tidak lengkap. Pilih folder situs web yang lengkap.', 'Folder situs web tidak dapat dibaca. Pastikan tersedia dan Tovu memiliki izin untuk membacanya.', 'Situs web ini tidak dapat ditambahkan. Periksa folder dan coba lagi.', 'Situs web ini tidak dapat dimulai. Coba lagi atau periksa lognya.'],
  'pt-BR': ['Esta pasta não é um site Tovu. Escolha a pasta que contém seu site.', 'Nenhum site Tovu foi encontrado nesta pasta. Escolha um site existente ou use Criar site.', 'Este site Tovu está incompleto. Escolha a pasta de um site completo.', 'Não é possível ler a pasta do site. Verifique se está disponível e se o Tovu tem permissão de leitura.', 'Não foi possível adicionar este site. Verifique a pasta e tente novamente.', 'Não foi possível iniciar este site. Tente novamente ou verifique os registros.'],
  ko: ['이 폴더는 Tovu 웹사이트가 아닙니다. 웹사이트가 들어 있는 폴더를 선택하세요.', '이 폴더에서 Tovu 웹사이트를 찾지 못했습니다. 기존 웹사이트를 선택하거나 웹사이트 만들기를 사용하세요.', '이 Tovu 웹사이트는 불완전합니다. 완전한 웹사이트 폴더를 선택하세요.', '웹사이트 폴더를 읽을 수 없습니다. 폴더를 사용할 수 있는지와 Tovu의 읽기 권한을 확인하세요.', '이 웹사이트를 추가하지 못했습니다. 폴더를 확인하고 다시 시도하세요.', '이 웹사이트를 시작하지 못했습니다. 다시 시도하거나 로그를 확인하세요.'],
  pl: ['Ten folder nie jest witryną Tovu. Wybierz folder zawierający Twoją witrynę.', 'W tym folderze nie znaleziono witryny Tovu. Wybierz istniejącą witrynę lub użyj Utwórz witrynę.', 'Ta witryna Tovu jest niekompletna. Wybierz folder kompletnej witryny.', 'Nie można odczytać folderu witryny. Sprawdź jego dostępność i uprawnienia Tovu do odczytu.', 'Nie udało się dodać tej witryny. Sprawdź folder i spróbuj ponownie.', 'Nie udało się uruchomić tej witryny. Spróbuj ponownie lub sprawdź dzienniki.'],
  hu: ['Ez a mappa nem Tovu-webhely. Válaszd a webhelyet tartalmazó mappát.', 'Ebben a mappában nem található Tovu-webhely. Válassz meglévő webhelyet, vagy használd a Webhely létrehozása lehetőséget.', 'Ez a Tovu-webhely hiányos. Válassz teljes webhelymappát.', 'A webhely mappája nem olvasható. Ellenőrizd az elérhetőségét és a Tovu olvasási jogosultságát.', 'A webhelyet nem sikerült hozzáadni. Ellenőrizd a mappát, és próbáld újra.', 'A webhelyet nem sikerült elindítani. Próbáld újra, vagy ellenőrizd a naplókat.'],
  fr: ['Ce dossier n’est pas un site Tovu. Choisissez le dossier contenant votre site.', 'Aucun site Tovu n’a été trouvé dans ce dossier. Choisissez un site existant ou utilisez Créer un site.', 'Ce site Tovu est incomplet. Choisissez le dossier d’un site complet.', 'Impossible de lire le dossier du site. Vérifiez sa disponibilité et les autorisations de lecture de Tovu.', 'Impossible d’ajouter ce site. Vérifiez le dossier et réessayez.', 'Impossible de démarrer ce site. Réessayez ou consultez ses journaux.'],
  uk: ['Ця папка не є сайтом Tovu. Виберіть папку, що містить ваш сайт.', 'У цій папці не знайдено сайт Tovu. Виберіть наявний сайт або скористайтеся Створити сайт.', 'Цей сайт Tovu неповний. Виберіть папку повного сайту.', 'Не вдалося прочитати папку сайту. Перевірте її доступність і дозвіл Tovu на читання.', 'Не вдалося додати цей сайт. Перевірте папку та спробуйте ще раз.', 'Не вдалося запустити цей сайт. Спробуйте ще раз або перевірте журнали.'],
  tr: ['Bu klasör bir Tovu web sitesi değil. Web sitenizi içeren klasörü seçin.', 'Bu klasörde Tovu web sitesi bulunamadı. Mevcut bir site seçin veya Web sitesi oluştur seçeneğini kullanın.', 'Bu Tovu web sitesi eksik. Tam bir web sitesi klasörü seçin.', 'Web sitesi klasörü okunamıyor. Kullanılabilir olduğunu ve Tovu’nun okuma izni bulunduğunu kontrol edin.', 'Bu web sitesi eklenemedi. Klasörü kontrol edip tekrar deneyin.', 'Bu web sitesi başlatılamadı. Tekrar deneyin veya günlüklerini kontrol edin.'],
  th: ['โฟลเดอร์นี้ไม่ใช่เว็บไซต์ Tovu เลือกโฟลเดอร์ที่มีเว็บไซต์ของคุณ', 'ไม่พบเว็บไซต์ Tovu ในโฟลเดอร์นี้ เลือกเว็บไซต์ที่มีอยู่หรือใช้สร้างเว็บไซต์', 'เว็บไซต์ Tovu นี้ไม่สมบูรณ์ เลือกโฟลเดอร์เว็บไซต์ที่สมบูรณ์', 'ไม่สามารถอ่านโฟลเดอร์เว็บไซต์ได้ ตรวจสอบว่าโฟลเดอร์พร้อมใช้งานและ Tovu มีสิทธิ์อ่าน', 'ไม่สามารถเพิ่มเว็บไซต์นี้ได้ ตรวจสอบโฟลเดอร์แล้วลองอีกครั้ง', 'ไม่สามารถเริ่มเว็บไซต์นี้ได้ ลองอีกครั้งหรือตรวจสอบบันทึก'],
  hi: ['यह फ़ोल्डर Tovu वेबसाइट नहीं है। अपनी वेबसाइट वाला फ़ोल्डर चुनें।', 'इस फ़ोल्डर में कोई Tovu वेबसाइट नहीं मिली। मौजूदा वेबसाइट चुनें या वेबसाइट बनाएँ का उपयोग करें।', 'यह Tovu वेबसाइट अधूरी है। पूरी वेबसाइट का फ़ोल्डर चुनें।', 'वेबसाइट का फ़ोल्डर पढ़ा नहीं जा सकता। जाँचें कि वह उपलब्ध है और Tovu को पढ़ने की अनुमति है।', 'यह वेबसाइट जोड़ी नहीं जा सकी। फ़ोल्डर जाँचें और फिर कोशिश करें।', 'यह वेबसाइट शुरू नहीं हो सकी। फिर कोशिश करें या उसके लॉग जाँचें।'],
  ur: ['یہ فولڈر Tovu ویب سائٹ نہیں ہے۔ اپنی ویب سائٹ والا فولڈر منتخب کریں۔', 'اس فولڈر میں کوئی Tovu ویب سائٹ نہیں ملی۔ موجودہ ویب سائٹ منتخب کریں یا ویب سائٹ بنائیں استعمال کریں۔', 'یہ Tovu ویب سائٹ نامکمل ہے۔ مکمل ویب سائٹ کا فولڈر منتخب کریں۔', 'ویب سائٹ کا فولڈر پڑھا نہیں جا سکتا۔ اس کی دستیابی اور Tovu کی پڑھنے کی اجازت جانچیں۔', 'یہ ویب سائٹ شامل نہیں ہو سکی۔ فولڈر جانچیں اور دوبارہ کوشش کریں۔', 'یہ ویب سائٹ شروع نہیں ہو سکی۔ دوبارہ کوشش کریں یا اس کے لاگ جانچیں۔'],
  bn: ['এই ফোল্ডারটি Tovu ওয়েবসাইট নয়। আপনার ওয়েবসাইট থাকা ফোল্ডারটি বেছে নিন।', 'এই ফোল্ডারে কোনো Tovu ওয়েবসাইট পাওয়া যায়নি। বিদ্যমান ওয়েবসাইট বেছে নিন বা ওয়েবসাইট তৈরি করুন ব্যবহার করুন।', 'এই Tovu ওয়েবসাইটটি অসম্পূর্ণ। সম্পূর্ণ ওয়েবসাইটের ফোল্ডার বেছে নিন।', 'ওয়েবসাইটের ফোল্ডার পড়া যাচ্ছে না। এটি উপলব্ধ আছে এবং Tovu-এর পড়ার অনুমতি আছে কিনা দেখুন।', 'এই ওয়েবসাইট যোগ করা যায়নি। ফোল্ডার পরীক্ষা করে আবার চেষ্টা করুন।', 'এই ওয়েবসাইট চালু করা যায়নি। আবার চেষ্টা করুন বা এর লগ পরীক্ষা করুন।'],
};

export function desktopCopy({ locale }: { locale: string }, _optionalArgs = {}): DesktopCopy {
  const normalized = locale.replace(/_/g, '-');
  const key = Object.keys(COPY).find(key => key.toLowerCase() === normalized.toLowerCase())
    ?? (normalized.toLowerCase().startsWith('zh') ? (/tw|hk|hant/i.test(normalized) ? 'zh-TW' : 'zh-CN') : normalized.split('-')[0] ?? 'en');
  const row = COPY[key] ?? COPY.en!;
  const [settings, automaticUpdates, saveUpdateError, restart, restarting] = row;
  const [invalid, empty, incomplete, unreadable, add, start] = SITE_ERROR_COPY[key] ?? SITE_ERROR_COPY.en!;
  return { settings, automaticUpdates, saveUpdateError, restart, restarting, siteErrors: { invalid, empty, incomplete, unreadable, add, start } };
}
