/**
 * @file Coverage for `node-toolchain.ts` — the exact shim texts, the win32/POSIX quoting refusal, and
 * what ends up on disk after a write. Real files in a temp dir for the write path, not a mocked `fs`:
 * the whole point of `writeNodeToolchain` is what a shell finds on disk afterward.
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { execFileSync } from "node:child_process";

import { buildNodeToolchainEnv, buildNodeToolchainShims, writeNodeToolchain } from "./node-toolchain.ts";
import { assertCmdQuotable } from "@jini-ai/desktop-host/node-toolchain";

const ELECTRON = "/Applications/Tovu.app/Contents/MacOS/Tovu";
const NPM_ROOT = "/Applications/Tovu.app/Contents/Resources/npm";

function tempDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "tovu-desktop-node-toolchain-"));
}

test("buildNodeToolchainShims: POSIX node re-execs Electron itself, with ELECTRON_RUN_AS_NODE exported on its own line", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.equal(
    shims.node,
    ["#!/bin/sh", "# Generated by Tovu Desktop — rewritten on every launch. Do not edit.", "ELECTRON_RUN_AS_NODE=1", "export ELECTRON_RUN_AS_NODE", `exec '${ELECTRON}' "$@"`, ""].join(
      "\n",
    ),
  );
});

test("buildNodeToolchainShims: POSIX npm and npx re-exec Electron against the bundled npm's own CLI entry points", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "linux" });
  const header = ["#!/bin/sh", "# Generated by Tovu Desktop — rewritten on every launch. Do not edit.", "ELECTRON_RUN_AS_NODE=1", "export ELECTRON_RUN_AS_NODE"];
  assert.equal(shims.npm, [...header, `exec '${ELECTRON}' '${NPM_ROOT}/bin/npm-cli.js' "$@"`, ""].join("\n"));
  assert.equal(shims.npx, [...header, `exec '${ELECTRON}' '${NPM_ROOT}/bin/npx-cli.js' "$@"`, ""].join("\n"));
});

test("buildNodeToolchainShims: win32 writes .cmd variants with CRLF, @echo off, and set (not export)", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "win32" });
  assert.equal(shims["node.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" %*`, ""].join("\r\n"));
  assert.equal(shims["npm.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" "${path.join(NPM_ROOT, "bin", "npm-cli.js")}" %*`, ""].join("\r\n"));
  assert.equal(shims["npx.cmd"], ["@echo off", "set ELECTRON_RUN_AS_NODE=1", `"${ELECTRON}" "${path.join(NPM_ROOT, "bin", "npx-cli.js")}" %*`, ""].join("\r\n"));
  // win32 never gets the POSIX set, and vice versa — one platform's shims only.
  assert.deepEqual(Object.keys(shims).sort(), ["node.cmd", "npm.cmd", "npx.cmd"]);
});

test("buildNodeToolchainShims: POSIX-only keys on a non-win32 platform", () => {
  const shims = buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.deepEqual(Object.keys(shims).sort(), ["node", "npm", "npx"]);
});

test("buildNodeToolchainShims refuses a POSIX path containing a single quote, before writing anything", () => {
  assert.throws(() => buildNodeToolchainShims({ electronPath: "/Applications/Tov'u.app/Tovu", npmRoot: NPM_ROOT, platform: "darwin" }), /electronPath/);
  assert.throws(() => buildNodeToolchainShims({ electronPath: ELECTRON, npmRoot: "/Resources/np'm", platform: "darwin" }), /npmRoot/);
});

test("buildNodeToolchainShims refuses a win32 path containing % \" ^ or &", () => {
  for (const badChar of ["%", '"', "^", "&"]) {
    const dirty = `C:\\Program Files\\Tovu ${badChar} evil\\Tovu.exe`;
    assert.throws(() => buildNodeToolchainShims({ electronPath: dirty, npmRoot: NPM_ROOT, platform: "win32" }), /electronPath/, `char: ${badChar}`);
  }
});

test("assertCmdQuotable rejects empty/non-string input and every unsafe character, accepts a clean path", () => {
  assert.throws(() => assertCmdQuotable({ value: "", field: "field" }), /must be a non-empty string/);
  assert.throws(() => assertCmdQuotable({ value: undefined, field: "field" }), /must be a non-empty string/);
  for (const bad of ["a%b", 'a"b', "a^b", "a&b", "a\rb", "a\nb"]) {
    assert.throws(() => assertCmdQuotable({ value: bad, field: "field" }), /cannot be used/, `input: ${JSON.stringify(bad)}`);
  }
  assert.equal(assertCmdQuotable({ value: "C:\\Program Files\\Tovu\\Tovu.exe", field: "field" }), "C:\\Program Files\\Tovu\\Tovu.exe");
});

test("writeNodeToolchain writes exactly the three POSIX shims, mode 0o700, with no leftover temp files", () => {
  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");

  assert.deepEqual(fs.readdirSync(paths.binDir).sort(), ["node", "npm", "npx"]);
  for (const name of ["node", "npm", "npx"]) {
    const mode: number = fs.statSync(path.join(paths.binDir, name)).mode & 0o777;
    assert.equal(mode, 0o700, `${name} mode`);
    const header = "#!/bin/sh\n# Generated by Tovu Desktop — rewritten on every launch. Do not edit.\nELECTRON_RUN_AS_NODE=1\nexport ELECTRON_RUN_AS_NODE\n";
    const args = name === "node" ? "" : ` '${NPM_ROOT}/bin/${name}-cli.js'`;
    assert.equal(fs.readFileSync(path.join(paths.binDir, name), "utf8"), `${header}exec '${ELECTRON}'${args} "$@"\n`, `${name} bytes`);
  }
  // The dir holding them is prepended to every child's PATH, so only the owner may add to it —
  // including when it already existed with a looser mode from an earlier launch.
  assert.equal(fs.statSync(paths.binDir).mode & 0o777, 0o700, "bin dir mode");
  fs.chmodSync(paths.binDir, 0o777);
  writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.equal(fs.statSync(paths.binDir).mode & 0o777, 0o700, "bin dir mode after a rewrite");
  assert.ok(fs.statSync(paths.npmCacheDir).isDirectory());
  assert.ok(fs.statSync(paths.npmPrefixDir).isDirectory());
});

test("writeNodeToolchain's returned paths are node-toolchain/{bin,npm-cache,npm-prefix} under userData — literals pinned with the website file", () => {
  // apps/website/src/mcp-federation/stdio-launch-resolver.ts reads TOVU_NODE_TOOLCHAIN_DIR and joins
  // the same three names onto it; a rename on this side without that one silently loses the toolchain
  // rather than failing loudly (plan §2, §3, §6 S3).
  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");
  assert.equal(paths.toolchainDir, path.join(userDataDir, "node-toolchain"));
  assert.equal(paths.binDir, path.join(paths.toolchainDir, "bin"));
  assert.equal(paths.npmCacheDir, path.join(paths.toolchainDir, "npm-cache"));
  assert.equal(paths.npmPrefixDir, path.join(paths.toolchainDir, "npm-prefix"));
});

test("writeNodeToolchain overwrites cleanly on a second call, e.g. after the app moves", () => {
  const userDataDir = tempDir();
  writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });

  const movedElectron = "/Applications/Tovu 2.app/Contents/MacOS/Tovu";
  const paths = writeNodeToolchain({ userDataDir, electronPath: movedElectron, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths, "a durable electronPath always writes the toolchain");

  assert.deepEqual(fs.readdirSync(paths.binDir).sort(), ["node", "npm", "npx"]);
  const nodeShim = fs.readFileSync(path.join(paths.binDir, "node"), "utf8");
  assert.ok(nodeShim.includes(movedElectron), "the second write's electronPath must win");
  assert.ok(!nodeShim.includes(ELECTRON), "the first write's electronPath must not survive");
});

test("buildNodeToolchainEnv returns exactly the two contract keys, nothing else", () => {
  const env = buildNodeToolchainEnv({ toolchainDir: "/Users/someone/Library/Application Support/Tovu/node-toolchain", npmRoot: NPM_ROOT });
  assert.deepEqual(env, {
    TOVU_NODE_TOOLCHAIN_DIR: "/Users/someone/Library/Application Support/Tovu/node-toolchain",
    TOVU_BUNDLED_NPM_ROOT: NPM_ROOT,
  });
  assert.deepEqual(Object.keys(env).sort(), ["TOVU_BUNDLED_NPM_ROOT", "TOVU_NODE_TOOLCHAIN_DIR"]);
});

// --- From a transient location (a mounted disk image, App Translocation) -----------------------
// Same rule as `writeSitesMcpLauncher` (`sites-mcp-registration.ts`, 4828a054a / ae7846c4a): the
// shims live in the shared `userData`, so every other copy of the app — and every stdio MCP server
// any of them launches — would exec a `/Volumes/...` Electron and hold the disk image open.

const DMG_ELECTRON = "/Volumes/Tovu 0.1.7/Tovu.app/Contents/MacOS/Tovu";
const DMG_NPM_ROOT = "/Volumes/Tovu 0.1.7/Tovu.app/Contents/Resources/npm";
const ALL_VOLUMES_READ_ONLY = (): boolean => true;

test("writeNodeToolchain from a disk image with no earlier shims writes none and returns null", () => {
  const userDataDir = tempDir();
  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });
  assert.equal(paths, null);
  assert.equal(fs.existsSync(path.join(userDataDir, "node-toolchain", "bin", "node")), false);
});

test("writeNodeToolchain from a disk image keeps an installed copy's shims untouched and returns their paths", () => {
  const userDataDir = tempDir();
  const installedElectron = path.join(tempDir(), "Tovu");
  fs.writeFileSync(installedElectron, "");
  const installed = writeNodeToolchain({ userDataDir, electronPath: installedElectron, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(installed);
  const before = fs.readFileSync(path.join(installed.binDir, "npx"), "utf8");

  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });

  assert.deepEqual(paths, installed);
  assert.equal(fs.readFileSync(path.join(installed.binDir, "npx"), "utf8"), before);
  for (const name of ["node", "npm", "npx"]) {
    assert.equal(fs.readFileSync(path.join(installed.binDir, name), "utf8").includes("/Volumes/"), false, name);
  }
});

test("writeNodeToolchain from a disk image does not keep shims naming an earlier disk image, and writes no new ones", () => {
  const userDataDir = tempDir();
  // Shims written by a build from before this rule, from another disk image.
  writeNodeToolchain({ userDataDir, electronPath: "/Volumes/Tovu 0.1.6/Tovu.app/Contents/MacOS/Tovu", npmRoot: NPM_ROOT, platform: "darwin", isReadOnlyVolume: () => false });

  const paths = writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });

  assert.equal(paths, null);
  assert.equal(fs.readFileSync(path.join(userDataDir, "node-toolchain", "bin", "node"), "utf8").includes(DMG_ELECTRON), false);
});

test("writeNodeToolchain from App Translocation is transient too", () => {
  const userDataDir = tempDir();
  const translocated = "/private/var/folders/xx/T/AppTranslocation/ABC/d/Tovu.app/Contents/MacOS/Tovu";
  assert.equal(writeNodeToolchain({ userDataDir, electronPath: translocated, npmRoot: NPM_ROOT, platform: "darwin" }), null);
});

test("the next launch from a real install recovers: it rewrites the shims with its own path", () => {
  const userDataDir = tempDir();
  writeNodeToolchain({ userDataDir, electronPath: DMG_ELECTRON, npmRoot: DMG_NPM_ROOT, platform: "darwin", isReadOnlyVolume: ALL_VOLUMES_READ_ONLY });
  const paths = writeNodeToolchain({ userDataDir, electronPath: ELECTRON, npmRoot: NPM_ROOT, platform: "darwin" });
  assert.ok(paths);
  assert.ok(fs.readFileSync(path.join(paths.binDir, "node"), "utf8").includes(ELECTRON));
});

test("written POSIX shims execute scripts with preserved arguments and Electron-as-node env", { skip: process.platform === "win32" }, () => {
  const userDataDir = tempDir();
  const npmRoot = path.join(userDataDir, "bundled npm");
  fs.mkdirSync(path.join(npmRoot, "bin"), { recursive: true });
  for (const command of ["npm", "npx"]) {
    fs.writeFileSync(path.join(npmRoot, "bin", `${command}-cli.js`), `console.log(JSON.stringify({ cli: "${command}", args: process.argv.slice(2), mode: process.env.ELECTRON_RUN_AS_NODE }));`);
  }
  const paths = writeNodeToolchain({ userDataDir, electronPath: process.execPath, npmRoot, platform: process.platform });
  assert.ok(paths);
  try {
    const nodeOutput = execFileSync(path.join(paths.binDir, "node"), ["-e", 'console.log(JSON.stringify({value: 42, mode: process.env.ELECTRON_RUN_AS_NODE}))'], { encoding: "utf8" });
    assert.deepEqual(JSON.parse(nodeOutput), { value: 42, mode: "1" });
    for (const command of ["npm", "npx"]) {
      const output: string = execFileSync(path.join(paths.binDir, command), ["one argument", "--flag"], { encoding: "utf8" });
      assert.deepEqual(JSON.parse(output), { cli: command, args: ["one argument", "--flag"], mode: "1" });
    }
  } finally { fs.rmSync(userDataDir, { recursive: true, force: true }); }
});
