/**
 * @file Tiny `node`/`npm`/`npx` shims written into `userData`, so a bundled npm and Electron's own
 * Node can be found on PATH by any stdio MCP server this app launches — no system Node install
 * required.
 *
 * See `plan-desktop-bundled-npx-2026-09-24.md` §2 ("The injected port") for the website-side half of
 * this contract (`apps/website/src/mcp-federation/stdio-launch-resolver.ts`) and §6 S3 for this
 * slice. That resolver reads `TOVU_NODE_TOOLCHAIN_DIR` / `TOVU_BUNDLED_NPM_ROOT` from the child env
 * this app's own `buildServeEnv` sets; {@link buildNodeToolchainEnv} is the desktop half of that pair.
 *
 * Same launcher shape as `sites-mcp-registration.ts`'s MCP launcher: `ELECTRON_RUN_AS_NODE=1` makes
 * Electron's own binary behave as plain Node instead of opening a second GUI, and every shim is
 * rewritten on every launch because `electronPath` changes when the app is moved or updated.
 */
import fs from "node:fs";
import path from "node:path";

import { assertShellQuotable } from "./sites-mcp-registration.ts";

/** {@link buildNodeToolchainShims}'s input. */
interface BuildNodeToolchainShimsInput {
  electronPath: string;
  npmRoot: string;
  /** Test seam: injects the OS platform this branches on. Defaults to the real `process.platform`;
   *  production never passes this. */
  platform?: NodeJS.Platform;
}

/** {@link writeNodeToolchain}'s input — the same three values, plus where to write them. */
interface WriteNodeToolchainInput {
  userDataDir: string;
  electronPath: string;
  npmRoot: string;
  /** Test seam; see {@link BuildNodeToolchainShimsInput}. */
  platform?: NodeJS.Platform;
}

/** {@link writeNodeToolchain}'s result: the directories the env contract and the resolver need. */
interface NodeToolchainPaths {
  toolchainDir: string;
  binDir: string;
  npmCacheDir: string;
  npmPrefixDir: string;
}

/** {@link buildNodeToolchainEnv}'s input. */
interface BuildNodeToolchainEnvInput {
  toolchainDir: string;
  npmRoot: string;
}

/**
 * Refuse a value a win32 batch file cannot quote safely: inside a `"<value>"` literal, `%` still
 * expands a variable, `"` ends the literal early, `^` escapes the next character, and `&` chains a
 * second command — cmd.exe applies all four before the line is even tokenized the way `sh` would.
 * POSIX's {@link assertShellQuotable} (`sites-mcp-registration.ts`) is reused as-is for the `sh`
 * shims; this is its win32 counterpart, for the same reason: every interpolated value here originates
 * in this shell's own code, so this holds that true by construction rather than by review.
 *
 * @throws {Error} naming the field, never echoing the value.
 * @complexity O(n) in the value's length.
 */
function assertCmdQuotable(value: unknown, field: string): string {
  if (typeof value !== "string" || value === "") {
    throw new Error(`node-toolchain: ${field} must be a non-empty string.`);
  }
  if (/[%"^&\r\n]/.test(value)) {
    throw new Error(`node-toolchain: ${field} contains a character a .cmd launcher cannot quote and cannot be used.`);
  }
  return value;
}

/**
 * The exact contents of every shim this app writes, keyed by filename — `node`/`npm`/`npx` on POSIX,
 * `node.cmd`/`npm.cmd`/`npx.cmd` on win32 ({@link writeNodeToolchain} writes only one set per launch,
 * matching its own platform).
 *
 * `node` re-execs Electron directly; `npm` and `npx` re-exec it against the bundled npm's own CLI
 * entry points (`bin/npm-cli.js`, `bin/npx-cli.js` — the same two files a real npm install exposes).
 * All three set `ELECTRON_RUN_AS_NODE=1` first, so the child sees a plain Node process rather than a
 * second Electron GUI window.
 *
 * @complexity O(1) — three fixed-shape strings.
 */
function buildNodeToolchainShims({ electronPath, npmRoot, platform = process.platform }: BuildNodeToolchainShimsInput): Record<string, string> {
  if (platform === "win32") {
    const exe = assertCmdQuotable(electronPath, "electronPath");
    const npmCli = assertCmdQuotable(path.join(npmRoot, "bin", "npm-cli.js"), "npmRoot");
    const npxCli = assertCmdQuotable(path.join(npmRoot, "bin", "npx-cli.js"), "npmRoot");
    const header = ["@echo off", "set ELECTRON_RUN_AS_NODE=1"];
    const CRLF = "\r\n";
    return {
      "node.cmd": [...header, `"${exe}" %*`, ""].join(CRLF),
      "npm.cmd": [...header, `"${exe}" "${npmCli}" %*`, ""].join(CRLF),
      "npx.cmd": [...header, `"${exe}" "${npxCli}" %*`, ""].join(CRLF),
    };
  }

  const electron = assertShellQuotable(electronPath, "electronPath");
  const npmCli = assertShellQuotable(path.join(npmRoot, "bin", "npm-cli.js"), "npmRoot");
  const npxCli = assertShellQuotable(path.join(npmRoot, "bin", "npx-cli.js"), "npmRoot");
  const header = [
    "#!/bin/sh",
    "# Generated by Tovu Desktop — rewritten on every launch. Do not edit.",
    "ELECTRON_RUN_AS_NODE=1",
    "export ELECTRON_RUN_AS_NODE",
  ];
  return {
    node: [...header, `exec '${electron}' "$@"`, ""].join("\n"),
    npm: [...header, `exec '${electron}' '${npmCli}' "$@"`, ""].join("\n"),
    npx: [...header, `exec '${electron}' '${npxCli}' "$@"`, ""].join("\n"),
  };
}

/**
 * Write every shim into `<userDataDir>/node-toolchain/bin/`, and create the npm cache/prefix
 * directories beside it — `npm-cache` and `npm-prefix`. Those two names, and `bin`, are literals
 * shared with `apps/website/src/mcp-federation/stdio-launch-resolver.ts` (plan §2, §3, §6 S3), which
 * points `npm_config_cache` / `npm_config_prefix` at them; a name changed on one side without the
 * other fails a real npm run rather than a type error, which is why both sides pin it with a test.
 *
 * Atomic per file: a same-directory `<name>.<pid>.tmp` is written first, `chmod`ed `0o700`, then
 * renamed over the real name — the convention `site-config.ts`'s `writeSiteName` and
 * `durable-json-file.ts` already use, so a crash mid-write never leaves a half-written, still-owner-
 * executable shim behind. Rewritten unconditionally on every call, never only when absent: exactly
 * `writeSitesMcpLauncher`'s own reasoning (`sites-mcp-registration.ts`) — `electronPath` goes stale
 * the moment the app is moved or updated.
 *
 * @complexity O(1) — three fixed-size files and two empty directories.
 */
function writeNodeToolchain({ userDataDir, electronPath, npmRoot, platform = process.platform }: WriteNodeToolchainInput): NodeToolchainPaths {
  const toolchainDir = path.join(userDataDir, "node-toolchain");
  const binDir = path.join(toolchainDir, "bin");
  const npmCacheDir = path.join(toolchainDir, "npm-cache");
  const npmPrefixDir = path.join(toolchainDir, "npm-prefix");

  // `bin/` goes first on every stdio child's PATH, so only the owner may write into it; chmod too,
  // since `mkdirSync` leaves an existing dir's mode alone and applies the umask to a new one.
  fs.mkdirSync(binDir, { recursive: true, mode: 0o700 });
  fs.chmodSync(binDir, 0o700);
  fs.mkdirSync(npmCacheDir, { recursive: true });
  fs.mkdirSync(npmPrefixDir, { recursive: true });

  const shims = buildNodeToolchainShims({ electronPath, npmRoot, platform });
  for (const [name, contents] of Object.entries(shims)) {
    const finalPath = path.join(binDir, name);
    const tempPath = `${finalPath}.${process.pid}.tmp`;
    fs.writeFileSync(tempPath, contents, { mode: 0o700 });
    fs.chmodSync(tempPath, 0o700);
    fs.renameSync(tempPath, finalPath);
  }

  return { toolchainDir, binDir, npmCacheDir, npmPrefixDir };
}

/**
 * The env contract's two variables, read by the website's `stdioLaunchResolverFromEnv` (plan §2) and
 * never forwarded to a spawned MCP child (plan §4 — neither name is in `INHERITED_ENV_VARS`). This is
 * the desktop half of the pair; `stdio-launch-resolver.ts` pins the other half. A rename on either
 * side without the other silently falls back to the identity resolver — no bundled npm, no error —
 * rather than failing loudly, which is why both sides carry a test pinning these two literal names.
 *
 * @complexity O(1).
 */
function buildNodeToolchainEnv({ toolchainDir, npmRoot }: BuildNodeToolchainEnvInput): Record<string, string> {
  return {
    TOVU_NODE_TOOLCHAIN_DIR: toolchainDir,
    TOVU_BUNDLED_NPM_ROOT: npmRoot,
  };
}

export { assertCmdQuotable, buildNodeToolchainEnv, buildNodeToolchainShims, writeNodeToolchain };
export type { BuildNodeToolchainEnvInput, BuildNodeToolchainShimsInput, NodeToolchainPaths, WriteNodeToolchainInput };
