/** Tovu toolchain names, native filesystem ports and durable-install policy. */
import fs from "node:fs";
// Launcher rationale: Jini/packages/desktop-host/src/node-toolchain/index.ts.
// node-toolchain/{bin,npm-cache,npm-prefix} and the two TOVU_* env names are a cross-process
// contract with apps/website/src/mcp-federation/stdio-launch-resolver.ts. Renaming one side can
// silently fall back to system tooling; these private env names are not forwarded to MCP children.
import path from "node:path";
import {
  buildNodeToolchainEnv as buildEnvironment,
  buildNodeToolchainShims as buildShims,
  writeNodeToolchain as writeToolchain,
} from "@jini-ai/desktop-host/node-toolchain";
import type { NodeToolchainPaths, ToolchainFilesystemPort } from "@jini-ai/desktop-host/node-toolchain";
import { isReadOnlyVolumeRoot, isTransientAppPath, launcherNamesDurableInstall } from "./sites-mcp-registration.ts";

interface BuildNodeToolchainShimsInput {
  electronPath: string;
  npmRoot: string;
  platform?: NodeJS.Platform;
}
interface WriteNodeToolchainInput extends BuildNodeToolchainShimsInput {
  userDataDir: string;
  isReadOnlyVolume?: (volumeRoot: string) => boolean;
}
interface BuildNodeToolchainEnvInput {
  toolchainDir: string;
  npmRoot: string;
}
const GENERATED_COMMENT = "# Generated by Tovu Desktop — rewritten on every launch. Do not edit.";
const joinPath = ({ parts }: { parts: string[] }) => path.join(...parts);
const filesystem: ToolchainFilesystemPort = {
  mkdirSync: ({ path }, options) => fs.mkdirSync(path, options),
  chmodSync: ({ path, mode }) => fs.chmodSync(path, mode),
  writeFileSync: ({ path, data }, options) => fs.writeFileSync(path, data, options),
  renameSync: ({ oldPath, newPath }) => fs.renameSync(oldPath, newPath),
  unlinkSync: ({ path }) => fs.unlinkSync(path),
};

/** Keep Tovu's generated banner and native path joiner. @complexity O(n) path lengths. */
function buildNodeToolchainShims({ electronPath, npmRoot, platform = process.platform }: BuildNodeToolchainShimsInput): Record<string, string> {
  return buildShims({ electronPath, npmRoot, platform, generatedComment: GENERATED_COMMENT, joinPath });
}

/** Bind existing directory names and transient-install probes; I/O failures propagate. @complexity O(n) shim bytes. */
function writeNodeToolchain({
  userDataDir, electronPath, npmRoot, platform = process.platform, isReadOnlyVolume = isReadOnlyVolumeRoot,
}: WriteNodeToolchainInput): NodeToolchainPaths | null {
  const toolchainDir = path.join(userDataDir, "node-toolchain");
  return writeToolchain({
    electronPath, npmRoot, platform, generatedComment: GENERATED_COMMENT, joinPath,
    paths: {
      toolchainDir,
      binDir: path.join(toolchainDir, "bin"),
      npmCacheDir: path.join(toolchainDir, "npm-cache"),
      npmPrefixDir: path.join(toolchainDir, "npm-prefix"),
    },
    filesystem,
    writerPid: process.pid,
    isTransientPath: ({ executablePath }) => isTransientAppPath(executablePath, { isReadOnlyVolume }),
    launcherNamesDurableInstall: ({ launcherPath }) => launcherNamesDurableInstall(launcherPath, isReadOnlyVolume),
    // The node shim names Electron alone in the MCP launcher's exec form, so that same durable-path
    // parser can inspect it; npm/npx also include their CLI script paths and are not the probe target.
  });
}

/** Preserve the environment names consumed by the website's stdio resolver. @complexity O(n) names. */
function buildNodeToolchainEnv(input: BuildNodeToolchainEnvInput): Record<string, string> {
  return buildEnvironment({ ...input, toolchainEnvName: "TOVU_NODE_TOOLCHAIN_DIR", npmRootEnvName: "TOVU_BUNDLED_NPM_ROOT" });
}

export { buildNodeToolchainEnv, buildNodeToolchainShims, writeNodeToolchain };
export type { BuildNodeToolchainEnvInput, BuildNodeToolchainShimsInput, NodeToolchainPaths, WriteNodeToolchainInput };
