/**
 * @file Coverage for `sites-mcp-registration.js` — the generated launcher and the PUT body.
 *
 * The load-bearing assertions here are all about things that fail SILENTLY in production:
 *
 * - A write tool absent from `writeAllowedToolNames` is refused by `trust.ts:326` and simply does
 *   not appear in the assistant's catalog. Nothing errors.
 * - A `writeAllowedToolNames` that is not a subset of `allowedToolNames` makes the whole PUT 400
 *   (`external-mcp-store.ts:1701`), so every tool disappears at once.
 * - A non-empty `args` string containing a space is silently split into broken argv by
 *   `external-mcp-store.ts:441`'s `parseArgs`, which has no quoting at all.
 * - A launcher that is not owner-only is a local escalation seam into the Tovu daemon.
 *
 * So each is asserted directly rather than trusted to the code that produces it.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  SITES_MCP_LAUNCHER_NAME,
  SITES_MCP_SERVER_ID,
  buildSitesMcpLauncherScript,
  buildSitesMcpRegistration,
  sitesMcpPutPath,
  registerSitesMcpServer,
  writeSitesMcpLauncher,
} from "./sites-mcp-registration.ts";
import { SITES_MCP_TOOLS } from "./sites-mcp-tools.ts";

function tempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "tovu-desktop-mcp-reg-"));
}

const LAUNCHER_INPUT = Object.freeze({
  electronPath: "/Applications/Tovu.app/Contents/MacOS/Tovu",
  bridgePath: "/Applications/Tovu.app/Contents/Resources/app/bin/mcp-bridge.ts",
  // The real one contains a space, which is the entire reason this value cannot travel in `args`.
  userDataDir: "/Users/la/Library/Application Support/tovu-desktop",
});

test("the server id matches trust.ts's connection-id pattern", () => {
  // `trust.ts:165` — lowercase, no underscore, since this id becomes part of every federated tool
  // id and an underscore would blur the `mcp__<connection>__<tool>` separator.
  assert.match(SITES_MCP_SERVER_ID, /^[a-z0-9][a-z0-9-]{0,39}$/);
});

test("the launcher script exports ELECTRON_RUN_AS_NODE and execs the bridge with a quoted userData path", () => {
  const script = buildSitesMcpLauncherScript(LAUNCHER_INPUT);

  assert.equal(
    script,
    [
      "#!/bin/sh",
      "# Generated by Tovu Desktop — rewritten on every launch. Do not edit.",
      "ELECTRON_RUN_AS_NODE=1",
      "export ELECTRON_RUN_AS_NODE",
      "exec '/Applications/Tovu.app/Contents/MacOS/Tovu' '/Applications/Tovu.app/Contents/Resources/app/bin/mcp-bridge.ts' --user-data-dir '/Users/la/Library/Application Support/tovu-desktop' \"$@\"",
      "",
    ].join("\n"),
  );
});

test("the launcher EXPORTS the variable rather than relying on an assignment prefix", () => {
  const script = buildSitesMcpLauncherScript(LAUNCHER_INPUT);

  // `VAR=1 exec cmd` is not portably guaranteed to put VAR in the replacing image's environment,
  // because `exec` is a POSIX special built-in. Without the export this launcher starts a second
  // Electron GUI app instead of a Node script — the exact failure the file exists to prevent.
  assert.match(script, /^export ELECTRON_RUN_AS_NODE$/m);
  assert.match(script, /^exec /m);
});

test("the launcher refuses any interpolated value carrying a quote or a newline", () => {
  for (const field of ["electronPath", "bridgePath", "userDataDir"]) {
    for (const hostile of ["/tmp/a'; rm -rf /; echo '", "/tmp/a\nrm -rf /"]) {
      assert.throws(
        () => buildSitesMcpLauncherScript({ ...LAUNCHER_INPUT, [field]: hostile }),
        /contains a quote or newline/,
        `${field} accepted ${JSON.stringify(hostile)}`,
      );
    }
    assert.throws(() => buildSitesMcpLauncherScript({ ...LAUNCHER_INPUT, [field]: "" }), /must be a non-empty string/);
  }
});

test("writeSitesMcpLauncher writes an owner-only executable", () => {
  const userDataDir = tempDir();

  const launcherPath = writeSitesMcpLauncher({ ...LAUNCHER_INPUT, userDataDir });

  assert.equal(launcherPath, path.join(userDataDir, SITES_MCP_LAUNCHER_NAME));
  // `0o700` exactly: the daemon EXECUTES this file, so group/other write is a local
  // privilege-escalation seam. Asserted on the real mode bits, because `writeFileSync`'s `mode` is
  // only a request — the process umask masks it, which is why the code also chmods.
  assert.equal(fs.statSync(launcherPath).mode & 0o777, 0o700);
  assert.match(fs.readFileSync(launcherPath, "utf8"), /^#!\/bin\/sh$/m);
});

test("writeSitesMcpLauncher rewrites a stale launcher rather than leaving it", () => {
  const userDataDir = tempDir();
  const launcherPath = writeSitesMcpLauncher({ ...LAUNCHER_INPUT, userDataDir, electronPath: "/old/Electron" });

  writeSitesMcpLauncher({ ...LAUNCHER_INPUT, userDataDir });

  const script = fs.readFileSync(launcherPath, "utf8");
  // A launcher naming a moved or upgraded Electron binary fails at connect time with an error that
  // names neither cause, so it is regenerated unconditionally.
  assert.equal(script.includes("/old/Electron"), false);
  assert.ok(script.includes(LAUNCHER_INPUT.electronPath));
});

test("the registration allowlists every published tool", () => {
  const body = buildSitesMcpRegistration({ launcherPath: "/x/launcher.sh" });

  // `trust.ts` R2 is default-deny: a tool missing here is discovered and then refused, with nothing
  // anywhere reporting its absence. Derived from the table so adding a tool cannot ship it dead.
  assert.deepEqual(
    body.allowedToolNames.split(",").sort(),
    SITES_MCP_TOOLS.map((tool) => tool.name).sort(),
  );
});

test("the registration write-authorizes EXACTLY the tools declaring readOnlyHint false", () => {
  const body = buildSitesMcpRegistration({ launcherPath: "/x/launcher.sh" });
  const expected = SITES_MCP_TOOLS.filter((tool) => tool.annotations.readOnlyHint === false).map((tool) => tool.name);

  // Both directions matter. Too few: `trust.ts:326` silently drops the write tool. Too many: a
  // read-only tool carries a write grant it never needed, and the operator's Settings screen
  // reports a privilege that is not real.
  assert.deepEqual(body.writeAllowedToolNames.split(",").filter(Boolean).sort(), expected.sort());
  assert.ok(expected.includes("add_site_pointer"));
  // `reveal_site_folder` IS here, and that is the deliberate choice defended in
  // `sites-mcp-tools.js`'s header: it modifies nothing, but it makes a window appear on the
  // operator's machine, and `readOnlyHint: true` over an action with an effect outside Tovu is the
  // self-declaration `trust.ts` exists to distrust. Pinned so nobody "optimizes" the write grant
  // away by relaxing the hint.
  assert.ok(expected.includes("reveal_site_folder"));
  // The genuinely read-only tool is the only one absent.
  assert.equal(expected.includes("list_sites"), false);
});

test("the write list is a SUBSET of the allowlist, or the whole PUT is rejected", () => {
  const body = buildSitesMcpRegistration({ launcherPath: "/x/launcher.sh" });
  const allowed = new Set(body.allowedToolNames.split(","));

  // `assertWriteAllowlistSubset` (`external-mcp-store.ts:1701`) 400s the save on the first name
  // that fails this — taking every tool down, not just that one.
  for (const name of body.writeAllowedToolNames.split(",").filter(Boolean)) {
    assert.ok(allowed.has(name), `${name} is write-authorized but not allowlisted`);
  }
});

test("the registration sends stdio + authMode none + an EMPTY args string", () => {
  const body = buildSitesMcpRegistration({ launcherPath: "/x/launcher.sh" });

  assert.equal(body.transport, "stdio");
  // Explicit, because `resolveSavedAuthMode` defaults an absent `authMode` to `"static_env"` on a
  // new row — describing this connection as credential-bearing when it has none.
  assert.equal(body.authMode, "none");
  assert.equal(body.enabled, true);
  assert.equal(body.command, "/x/launcher.sh");
  // MUST stay empty. `parseArgs` is `raw.split(/\s+/)` with no quoting, so any path with a space
  // (which the real userData path has) would arrive as several broken arguments.
  assert.equal(body.args, "");
  // Empty string, not omitted: omitted means "keep stored credentials" to the PUT route
  // (`put.ts:88-89`). This connection must never carry any.
  assert.equal(body.env, "");
});

test("the registration never declares destructiveHint anywhere in its payload", () => {
  const body = buildSitesMcpRegistration({ launcherPath: "/x/launcher.sh" });

  assert.equal(JSON.stringify(body).includes("destructiveHint"), false);
});

test("sitesMcpPutPath targets the given workspace and encodes it", () => {
  assert.equal(
    sitesMcpPutPath("workspace-local"),
    "/api/admin/v1/workspaces/workspace-local/mcp-servers/tovu-desktop",
  );
  // Not hard-coded to `workspace-local`: `resolveWorkspace` picks the single or oldest workspace row
  // and `tovu serve --workspace` can name another, so the caller passes what the boot line reported.
  assert.match(sitesMcpPutPath("a b/c"), /workspaces\/a%20b%2Fc\//);
});

/** One entry of {@link fakeNet}'s script. */
interface FakeScriptStep {
  status?: number;
  body?: unknown;
  failWith?: string;
}

/** One request {@link fakeNet} recorded. */
interface FakeCall {
  options: { method: string; url: string; session?: unknown; useSessionCookies?: boolean };
  headers: Record<string, string>;
  body: string;
}

/**
 * A `net` stand-in that answers each request from a scripted queue and records what it was asked.
 *
 * A QUEUE rather than one canned response, because `registerSitesMcpServer` now makes two calls —
 * a GET to read the operator's `enabled` value, then the PUT. A single-response fake would have
 * answered the GET with the PUT's status and hidden the read entirely.
 *
 * @param script one entry per expected request, in order: `{status, body?}` for a reply, or
 *   `{failWith}` for a transport error.
 */
function fakeNet(script: FakeScriptStep[]) {
  const calls: FakeCall[] = [];
  const queue = [...script];
  return {
    calls,
    request(options: FakeCall["options"]) {
      const call: FakeCall = { options, headers: {}, body: "" };
      calls.push(call);
      const step = queue.shift() ?? { status: 500 };
      // `AdminHttpRequest`'s two overloaded `on` signatures ("response" and "error") — a plain
      // object literal cannot declare real overloads, so this registry and both `handler: any`
      // params below stand in for them; the two call sites in `end()` are the actual shapes used.
      const handlers: Record<string, any> = {}; // any: see the reason above
      return {
        setHeader: (name: string, value: string) => {
          call.headers[name] = value;
        },
        write: (chunk: string) => {
          call.body += chunk;
        },
        on: (event: string, handler: any) => {
          // any: see the reason on `handlers` above
          handlers[event] = handler;
        },
        end: () => {
          if (step.failWith) return handlers.error?.(new Error(step.failWith));
          handlers.response?.({
            // every non-failWith script step in this file's own tests supplies `status`;
            // `FakeScriptStep.status` is optional only because a failWith step omits it.
            statusCode: step.status!, // !: see the reason above
            on: (event: string, handler: any) => {
              // any: this inner `on` plays the response body's own emitter, whose "data" listener
              // takes a chunk and whose "end" listener takes nothing — see `end()`'s two branches
              if (event === "data" && step.body !== undefined) handler(JSON.stringify(step.body));
              if (event === "end") handler();
            },
          });
        },
      };
    },
  };
}

/** The GET reply for a site with no desktop-MCP row yet. */
const NO_EXISTING_ROW: FakeScriptStep = { status: 200, body: { servers: [] } };

/** The GET reply for a site where the operator has this connection in a given state. */
function existingRow(enabled: boolean): FakeScriptStep {
  return { status: 200, body: { servers: [{ serverId: "tovu-desktop", enabled }] } };
}

test("registerSitesMcpServer reads the existing row, then PUTs as the site session", async () => {
  const net = fakeNet([NO_EXISTING_ROW, { status: 200 }]);
  const session = { id: "site-session" };

  const result = await registerSitesMcpServer({
    net,
    session,
    adminUrl: "http://127.0.0.1:3601/admin/",
    workspaceId: "ws-7",
    launcherPath: "/x/launcher.sh",
  });

  assert.deepEqual(result, { ok: true, status: 200 });
  const [read, write] = net.calls as [FakeCall, FakeCall];
  assert.equal(read.options.method, "GET");
  assert.equal(read.options.url, "http://127.0.0.1:3601/api/admin/v1/workspaces/ws-7/mcp-servers");
  assert.equal(write.options.method, "PUT");
  assert.equal(write.options.url, "http://127.0.0.1:3601/api/admin/v1/workspaces/ws-7/mcp-servers/tovu-desktop");
  // Both calls carry the session. Without `useSessionCookies` a request sends no cookie and 401s
  // while every other signal still looks healthy — the silent failure `desktop-auth.js` pins a test
  // against.
  for (const call of net.calls) {
    assert.equal(call.options.session, session);
    assert.equal(call.options.useSessionCookies, true);
  }
  assert.equal(write.headers["content-type"], "application/json");
  assert.equal(JSON.parse(write.body).command, "/x/launcher.sh");
});

test("a brand-new row is created ENABLED", async () => {
  const net = fakeNet([NO_EXISTING_ROW, { status: 200 }]);

  await registerSitesMcpServer({
    net,
    session: {},
    adminUrl: "http://127.0.0.1:3601/admin/",
    workspaceId: "ws-7",
    launcherPath: "/x/launcher.sh",
  });

  assert.equal(JSON.parse(net.calls[1]!.body).enabled, true);
});

test("a connection the operator DISABLED stays disabled across a re-assert", async () => {
  const net = fakeNet([existingRow(false), { status: 200 }]);

  await registerSitesMcpServer({
    net,
    session: {},
    adminUrl: "http://127.0.0.1:3601/admin/",
    workspaceId: "ws-7",
    launcherPath: "/x/fresh-launcher.sh",
  });

  const body = JSON.parse(net.calls[1]!.body);
  // THE assertion this read-before-write exists for. Sending `enabled: true` unconditionally made
  // "disabled" last until the next launch and then silently undo itself — a setting reversed with
  // nothing telling the operator.
  assert.equal(body.enabled, false);
  // And the stale-path repair still happens: the point is to fix what goes stale on its own without
  // touching what the operator chose.
  assert.equal(body.command, "/x/fresh-launcher.sh");
});

test("an enabled connection stays enabled", async () => {
  const net = fakeNet([existingRow(true), { status: 200 }]);

  await registerSitesMcpServer({
    net,
    session: {},
    adminUrl: "http://127.0.0.1:3601/admin/",
    workspaceId: "ws-7",
    launcherPath: "/x/launcher.sh",
  });

  assert.equal(JSON.parse(net.calls[1]!.body).enabled, true);
});

test("when the existing state CANNOT be read, nothing is written at all", async () => {
  for (const failedRead of [{ status: 401 }, { status: 500 }, { failWith: "ECONNREFUSED" }, { status: 200, body: { unexpected: true } }]) {
    const net = fakeNet([failedRead, { status: 200 }]);

    const result = await registerSitesMcpServer({
      net,
      session: {},
      adminUrl: "http://127.0.0.1:3601/admin/",
      workspaceId: "ws-7",
      launcherPath: "/x/launcher.sh",
    });

    // Declining is the only answer that cannot override the operator: "no row yet" and "a row they
    // disabled" are indistinguishable from a failed read, and one of the two makes writing wrong.
    assert.equal(result.ok, false, `wrote anyway for ${JSON.stringify(failedRead)}`);
    assert.equal(result.skipped, true);
    assert.equal(net.calls.length, 1, `made a second request for ${JSON.stringify(failedRead)}`);
    assert.match(result.reason!, /nothing was changed/);
  }
});

test("registerSitesMcpServer reports a rejected PUT rather than throwing", async () => {
  for (const status of [401, 403, 404, 400, 500, 503]) {
    const result = await registerSitesMcpServer({
      net: fakeNet([NO_EXISTING_ROW, { status }]),
      session: {},
      adminUrl: "http://127.0.0.1:3601/admin/",
      workspaceId: "ws-7",
      launcherPath: "/x/launcher.sh",
    });

    // A site whose assistant lacks the desktop tools is degraded, not broken, and the operator is
    // mid-launch — so this must never be able to abort opening a window.
    assert.equal(result.ok, false);
    assert.equal(result.status, status);
    assert.match(result.reason!, new RegExp(String(status)));
    // Distinguishable from the declined case above, which a caller may want to report differently.
    assert.equal(result.skipped, undefined);
  }
});

test("registerSitesMcpServer reports a transport error on the PUT rather than throwing", async () => {
  const result = await registerSitesMcpServer({
    net: fakeNet([NO_EXISTING_ROW, { failWith: "EPIPE" }]),
    session: {},
    adminUrl: "http://127.0.0.1:3601/admin/",
    workspaceId: "ws-7",
    launcherPath: "/x/launcher.sh",
  });

  assert.equal(result.ok, false);
  assert.match(result.reason!, /EPIPE/);
});
