/** Owner spec: cov1. No runner execution; graph is supplied in memory. */
import assert from "node:assert/strict";
import test from "node:test";
import { discoverTests, scanModule, resolveLocalImport } from "../coverage-changed-discovery.js";

const file = "apps/website/src/feature/rules.ts";
const importer = "apps/website/src/other/handler.ts";
const direct = "apps/website/src/other/__tests__/handler.test.ts";
const sibling = "apps/website/src/feature/__tests__/edge.unit.test.ts";

test("AST imports include reexports, literal dynamic/require, but exclude type imports and strings", () => {
  const scan = scanModule({ file: importer, source: `import type { X } from './types.js'; import { x } from '../feature/rules.js'; export * from './barrel.js'; const a = import('./dynamic.js'); const b = require('./cjs.cjs'); const falsePositive = "import './fake.js'"; // import './comment.js'\n` });
  assert.deepEqual(scan.imports, ["../feature/rules.js", "./barrel.js", "./dynamic.js", "./cjs.cjs"]);
});

test("module resolution uses exact git file lists, TS extensions/index and configured aliases", () => {
  const files = new Set([file, "apps/admin/src/lib/api.ts", "apps/website/src/contracts/headless/index.ts"]);
  assert.equal(resolveLocalImport({ file: importer, specifier: "../feature/rules.js", files }), file);
  assert.equal(resolveLocalImport({ file: importer, specifier: "#src/feature/rules", files }), file);
  assert.equal(resolveLocalImport({ file: "apps/admin/src/features/widget.ts", specifier: "@/lib/api", files }), "apps/admin/src/lib/api.ts");
  assert.equal(resolveLocalImport({ file: "apps/admin/src/features/widget.ts", specifier: "@tovu/headless", files }, { aliases: [{ pattern: "@tovu/headless", targets: ["apps/website/src/contracts/headless/index.ts"] }] }), "apps/website/src/contracts/headless/index.ts");
});

test("reverse transitive imports, sibling tests and report tests are capped with explicit omissions", () => {
  const modules = new Map([
    [file, scanModule({ file, source: "export const result = 1;" })],
    [importer, scanModule({ file: importer, source: "import '../feature/rules.js';" })],
    [direct, scanModule({ file: direct, source: "import '../handler.js';" })],
    [sibling, scanModule({ file: sibling, source: "import 'node:test';" })],
    ["development/scripts/__tests__/reported.test.ts", scanModule({ file: "development/scripts/__tests__/reported.test.ts", source: "import 'node:test';" })],
  ]);
  const result = discoverTests({ changed: [file], modules, reported: ["development/scripts/__tests__/reported.test.ts"] }, { cap: 1 });
  assert.equal(result.tests.length, 2);
  assert.equal(result.omitted.length, 1);
  assert.ok(result.tests.includes("development/scripts/__tests__/reported.test.ts"));
  assert.ok(result.byFile.get(file)!.includes(direct));
  assert.equal(result.errors.length, 0);
  assert.match(discoverTests({ changed: [file], modules, reported: ["development/scripts/missing.test.ts"] }).errors.join(" "), /missing/i);
});

test("runtime and complexity signals inspect real syntax, not comments/strings", () => {
  const innocent = scanModule({ file, source: '// fetch() electron spawn()\nexport const note = "electron child_process";' });
  assert.deepEqual(innocent.runtimeReasons, []);
  const risky = scanModule({ file, source: "import { BrowserWindow } from 'electron'; export function run() { return fetch('https://example.test'); }" });
  assert.equal(risky.runtimeReasons.length, 2);
  const complex = scanModule({ file, source: `export function decide(x: boolean) { ${"if (x) return 1; ".repeat(10)} return 0; }` });
  assert.equal(complex.complexity, 11);
  const mocked = scanModule({ file: sibling, source: "vi.mock('a'); vi.mock('b'); vi.mock('c'); vi.mock('d');" });
  assert.equal(mocked.mockCount, 4);
  assert.deepEqual(scanModule({ file, source: "export function declared() {} export const arrow = () => 1;" }).declaredFunctions, ["declared", "arrow"]);
  assert.equal(scanModule({ file, source: "/** @generated by schema tooling */\nexport const value = 1;" }).generated, true);
  assert.equal(scanModule({ file, source: "const text = '@generated';" }).generated, false);
});

test("cov2 report, own feature, direct proximity and wider tests rank in that order", () => {
  const changed = "apps/website/src/features/media/nested/rules.ts";
  const reported = "development/scripts/__tests__/reported.test.ts";
  const own = "apps/website/src/features/media/__tests__/rules.test.ts";
  const near = "apps/website/src/features/neighbour/__tests__/rules.test.ts";
  const far = "apps/website/src/aaa/__tests__/rules.test.ts";
  const barrel = "apps/website/src/barrel.ts", wider = "apps/website/src/aaa/__tests__/a-wider.test.ts";
  const modules = new Map([
    [changed, scanModule({ file: changed, source: "export const x = 1" })],
    [reported, scanModule({ file: reported, source: "" })],
    [own, scanModule({ file: own, source: "" })],
    [near, scanModule({ file: near, source: "import '../../media/nested/rules.js'" })],
    [far, scanModule({ file: far, source: "import '../../features/media/nested/rules.js'" })],
    [barrel, scanModule({ file: barrel, source: "export * from './features/media/nested/rules.js'" })],
    [wider, scanModule({ file: wider, source: "import '../../barrel.js'" })],
  ]);
  const result = discoverTests({ changed: [changed], modules, reported: [reported] });
  assert.deepEqual(result.tests, [reported, own, near, far, wider]);
  assert.match(result.picks.find((pick) => pick.test === own)!.reason, /own.*feature/);
  assert.match(result.picks.find((pick) => pick.test === near)!.reason, /direct.*one hop/);
});

test("cov2 per-source cap and total cap serve each file before filling one barrel", () => {
  const second = "apps/website/src/second/rules.ts", secondTest = "apps/website/src/second/__tests__/rules.test.ts";
  const modules = new Map([[file, scanModule({ file, source: "" })], [second, scanModule({ file: second, source: "" })], [secondTest, scanModule({ file: secondTest, source: "" })]]);
  for (const name of ["a", "b", "c"]) {
    const testFile = `apps/website/src/feature/__tests__/${name}.test.ts`;
    modules.set(testFile, scanModule({ file: testFile, source: "" }));
  }
  const result = discoverTests({ changed: [file, second], modules }, { cap: 2, totalCap: 2 });
  assert.deepEqual(result.tests, ["apps/website/src/feature/__tests__/a.test.ts", secondTest]);
  assert.equal(result.omitted.length, 2);
  assert.equal(discoverTests({ changed: [file, second], modules }, { cap: 2 }).tests.length, 3);
  const tooSmall = discoverTests({ changed: [file, second], modules }, { cap: 2, totalCap: 1 });
  assert.match(tooSmall.warnings.join(" "), /no selected tests.*second/);
});

test("cov2 ignored and _tmp tests never enter selection even when reported", () => {
  const ignored = "apps/website/src/feature/__tests__/ignored.test.ts", tmp = "apps/website/src/feature/__tests__/_tmp-full-sweep.test.ts";
  const modules = new Map([file, sibling, ignored, tmp].map((file) => [file, scanModule({ file, source: "" })]));
  const result = discoverTests({ changed: [file], modules, reported: [ignored, tmp], inventory: new Set([file, sibling, tmp]) });
  assert.deepEqual(result.tests, [sibling]);
  assert.match(result.errors.join(" "), /git inventory/);
  assert.match(result.warnings.join(" "), /temporary/);
});

test("cov2 own-directory ties prefer the changed basename over unrelated alphabetical tests", () => {
  const changed = "apps/website/src/platform/db/repos/media-repo.ts";
  const nearest = "apps/website/src/platform/db/repos/__tests__/media-repo.test.ts";
  const unrelated = "apps/website/src/platform/db/repos/__tests__/aaa-credential.test.ts";
  const modules = new Map([changed, nearest, unrelated].map((file) => [file, scanModule({ file, source: "" })]));
  assert.deepEqual(discoverTests({ changed: [changed], modules }, { cap: 1 }).tests, [nearest]);
});
