import assert from "node:assert/strict";
import { test } from "node:test";
import express from "express";
import { startTestServer } from "#src/server/__tests__/helpers/http-test-server";
import { registerAdminMediaUploadRoute } from "../upload.js";
import { registerAdminMediaUpdateRoute } from "../update.js";
import { registerAdminMediaListRoute } from "../list.js";
import type { MediaRouteDeps } from "../deps.js";
import { InMemoryVersionedMediaRepo, InMemoryAssetBlobRepo, InMemoryAssetRenditionRepo,
  InMemoryBlobStore, InMemoryMediaContentTypeStore, InMemoryTransformDefinitionRepo,
  InMemoryImageTransformer } from "#src/features/media/index";

/** Owner dispatch 2026-10-04: authenticated attribution, JSON spoof refusal and read-only edits. */
test("admin upload stamps its actor, PATCH preserves it, and list exposes it", async (t) => {
  let id = 0;
  const deps: MediaRouteDeps = {
    workspaceId: "creator-ws", clock: { nowIso: () => "2026-10-04T00:00:00Z", nowMs: () => Date.parse("2026-10-04T00:00:00Z") },
    idGen: { newId: () => `creator-http-${++id}` }, authorize: async () => ({ allowed: true, reason: "matched" }),
    mediaRepo: new InMemoryVersionedMediaRepo(), assetBlobRepo: new InMemoryAssetBlobRepo({}),
    assetRenditionRepo: new InMemoryAssetRenditionRepo({}), blobStore: new InMemoryBlobStore(),
    mediaContentTypeStore: new InMemoryMediaContentTypeStore(), transformDefinitionRepo: new InMemoryTransformDefinitionRepo({}),
    imageTransformer: new InMemoryImageTransformer(),
    removeMedia: async () => { assert.fail("unexpected removal"); },
    forgetRemovedMedia: async () => { assert.fail("unexpected removal"); },
  };
  const app = express();
  app.use(express.json());
  app.use((_req, res, next) => { res.locals.principal = { id: "authenticated-owner" }; next(); });
  registerAdminMediaUploadRoute(app, deps);
  registerAdminMediaUpdateRoute(app, deps);
  registerAdminMediaListRoute(app, deps);
  const base = await startTestServer(app, t);
  const url = `${base}/api/admin/v1/workspaces/creator-ws/media`;
  const upload = await fetch(url, { method: "POST", headers: { "content-type": "application/json" },
    body: JSON.stringify({ filename: "creator.png", contentType: "image/png",
      dataBase64: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
      credit: "Generated by another producer", createdBy: "forged", createdByPrincipal: "forged" }) });
  assert.equal(upload.status, 201);
  const uploaded = await upload.json() as { media: { id: string; createdBy: string } };
  assert.equal(uploaded.media.createdBy, "authenticated-owner");
  const patch = await fetch(`${url}/${uploaded.media.id}`, { method: "PATCH", headers: { "content-type": "application/json" },
    body: JSON.stringify({ title: "Renamed", credit: "Editable", createdBy: "forged-again" }) });
  assert.equal(patch.status, 200);
  assert.equal((await patch.json() as { media: { createdBy: string } }).media.createdBy, "authenticated-owner");
  const list = await fetch(url);
  assert.equal(list.status, 200);
  const listed = await list.json() as { media: Array<{ id: string; createdBy: string }> };
  assert.equal(listed.media.find(asset => asset.id === uploaded.media.id)?.createdBy, "authenticated-owner");
});
