import { createDictionaryTranslator } from "../../lib/dictionary-translator";

/** Settings → User Interface copy (owner, 2026-10-06), across the same 21 admin locales as `settings-i18n.ts`. */
const INTERFACE_DICT: Record<string, Record<string, string>> = {
  es: { "User Interface": "Interfaz de usuario", "How the admin's controls behave for you. Saved per operator.": "Cómo se comportan para ti los controles del administrador. Se guarda por operador.", "Hide the chat button while the chat is open": "Ocultar el botón del chat mientras el chat está abierto", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Activado: la ✕ del panel del chat lo cierra. Desactivado: el botón sigue visible sobre el panel abierto y lo cierra." },
  id: { "User Interface": "Antarmuka Pengguna", "How the admin's controls behave for you. Saved per operator.": "Cara kontrol admin berperilaku untuk Anda. Disimpan per operator.", "Hide the chat button while the chat is open": "Sembunyikan tombol obrolan saat obrolan terbuka", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Aktif: ✕ di panel obrolan menutupnya. Nonaktif: tombol tetap terlihat di atas panel yang terbuka dan menutupnya." },
  de: { "User Interface": "Benutzeroberfläche", "How the admin's controls behave for you. Saved per operator.": "Wie sich die Bedienelemente des Admin-Bereichs für dich verhalten. Pro Operator gespeichert.", "Hide the chat button while the chat is open": "Chat-Schaltfläche ausblenden, solange der Chat geöffnet ist", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "An: Das ✕ im Chat-Bereich schließt ihn. Aus: Die Schaltfläche bleibt über dem geöffneten Bereich sichtbar und schließt ihn." },
  "zh-CN": { "User Interface": "用户界面", "How the admin's controls behave for you. Saved per operator.": "管理后台控件对你的显示方式。按操作员分别保存。", "Hide the chat button while the chat is open": "聊天打开时隐藏聊天按钮", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "开启：用聊天面板上的 ✕ 关闭它。关闭：按钮保持显示在打开的面板上方，点击即可关闭面板。" },
  "zh-TW": { "User Interface": "使用者介面", "How the admin's controls behave for you. Saved per operator.": "管理後台控制項對你的顯示方式。依操作員分別儲存。", "Hide the chat button while the chat is open": "聊天開啟時隱藏聊天按鈕", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "開啟：用聊天面板上的 ✕ 關閉它。關閉：按鈕持續顯示在開啟的面板上方，點擊即可關閉面板。" },
  "pt-BR": { "User Interface": "Interface do usuário", "How the admin's controls behave for you. Saved per operator.": "Como os controles do admin se comportam para você. Salvo por operador.", "Hide the chat button while the chat is open": "Ocultar o botão do chat enquanto o chat estiver aberto", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Ativado: o ✕ do painel do chat o fecha. Desativado: o botão continua visível sobre o painel aberto e o fecha." },
  ru: { "User Interface": "Интерфейс", "How the admin's controls behave for you. Saved per operator.": "Как ведут себя элементы управления админки для вас. Сохраняется для каждого оператора.", "Hide the chat button while the chat is open": "Скрывать кнопку чата, пока чат открыт", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Вкл.: панель чата закрывается кнопкой ✕. Выкл.: кнопка остаётся на экране поверх открытой панели и закрывает её." },
  fa: { "User Interface": "رابط کاربری", "How the admin's controls behave for you. Saved per operator.": "رفتار کنترل‌های مدیریت برای شما. برای هر اپراتور جداگانه ذخیره می‌شود.", "Hide the chat button while the chat is open": "پنهان کردن دکمه گفتگو وقتی گفتگو باز است", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "روشن: ✕ پنل گفتگو آن را می‌بندد. خاموش: دکمه روی پنل باز روی صفحه می‌ماند و آن را می‌بندد." },
  ar: { "User Interface": "واجهة المستخدم", "How the admin's controls behave for you. Saved per operator.": "كيف تعمل عناصر التحكم في لوحة الإدارة بالنسبة لك. تُحفظ لكل مشغّل.", "Hide the chat button while the chat is open": "إخفاء زر الدردشة أثناء فتح الدردشة", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "تشغيل: يغلق الرمز ✕ في لوحة الدردشة اللوحة. إيقاف: يبقى الزر ظاهرًا فوق اللوحة المفتوحة ويغلقها." },
  ja: { "User Interface": "ユーザーインターフェース", "How the admin's controls behave for you. Saved per operator.": "管理画面のコントロールの動作を設定します。オペレーターごとに保存されます。", "Hide the chat button while the chat is open": "チャットを開いている間はチャットボタンを隠す", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "オン：チャットパネルの ✕ で閉じます。オフ：ボタンは開いたパネルの上に表示されたままになり、押すとパネルを閉じます。" },
  ko: { "User Interface": "사용자 인터페이스", "How the admin's controls behave for you. Saved per operator.": "관리자 화면의 컨트롤이 동작하는 방식입니다. 운영자별로 저장됩니다.", "Hide the chat button while the chat is open": "채팅이 열려 있는 동안 채팅 버튼 숨기기", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "켜짐: 채팅 패널의 ✕로 닫습니다. 꺼짐: 버튼이 열린 패널 위에 계속 표시되며 누르면 패널이 닫힙니다." },
  pl: { "User Interface": "Interfejs użytkownika", "How the admin's controls behave for you. Saved per operator.": "Jak zachowują się dla Ciebie elementy sterujące panelu. Zapisywane dla każdego operatora.", "Hide the chat button while the chat is open": "Ukrywaj przycisk czatu, gdy czat jest otwarty", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Wł.: ✕ w panelu czatu go zamyka. Wył.: przycisk pozostaje widoczny nad otwartym panelem i go zamyka." },
  hu: { "User Interface": "Felhasználói felület", "How the admin's controls behave for you. Saved per operator.": "Az admin vezérlőinek viselkedése az Ön számára. Operátoronként mentve.", "Hide the chat button while the chat is open": "A csevegés gomb elrejtése, amíg a csevegés nyitva van", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Be: a csevegőpanel ✕ gombja zárja be. Ki: a gomb a nyitott panel fölött a képernyőn marad, és bezárja azt." },
  fr: { "User Interface": "Interface utilisateur", "How the admin's controls behave for you. Saved per operator.": "Le comportement des commandes de l'administration pour vous. Enregistré par opérateur.", "Hide the chat button while the chat is open": "Masquer le bouton du chat lorsque le chat est ouvert", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Activé : le ✕ du panneau de chat le ferme. Désactivé : le bouton reste affiché au-dessus du panneau ouvert et le ferme." },
  uk: { "User Interface": "Інтерфейс", "How the admin's controls behave for you. Saved per operator.": "Як для вас поводяться елементи керування адмінки. Зберігається для кожного оператора.", "Hide the chat button while the chat is open": "Приховувати кнопку чату, поки чат відкрито", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Увімк.: панель чату закривається кнопкою ✕. Вимк.: кнопка залишається на екрані над відкритою панеллю й закриває її." },
  tr: { "User Interface": "Kullanıcı Arayüzü", "How the admin's controls behave for you. Saved per operator.": "Yönetim denetimlerinin sizin için nasıl davrandığı. Operatör başına kaydedilir.", "Hide the chat button while the chat is open": "Sohbet açıkken sohbet düğmesini gizle", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Açık: sohbet panelindeki ✕ paneli kapatır. Kapalı: düğme açık panelin üzerinde ekranda kalır ve paneli kapatır." },
  th: { "User Interface": "ส่วนติดต่อผู้ใช้", "How the admin's controls behave for you. Saved per operator.": "การทำงานของตัวควบคุมในหน้าผู้ดูแลสำหรับคุณ บันทึกแยกตามผู้ปฏิบัติงาน", "Hide the chat button while the chat is open": "ซ่อนปุ่มแชทขณะที่แชทเปิดอยู่", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "เปิด: ใช้ ✕ ของแผงแชทเพื่อปิด ปิด: ปุ่มจะยังแสดงอยู่เหนือแผงที่เปิดและกดเพื่อปิดแผงได้" },
  it: { "User Interface": "Interfaccia utente", "How the admin's controls behave for you. Saved per operator.": "Come si comportano per te i controlli dell'amministrazione. Salvato per operatore.", "Hide the chat button while the chat is open": "Nascondi il pulsante della chat mentre la chat è aperta", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "Attivo: la ✕ del pannello della chat lo chiude. Disattivo: il pulsante resta visibile sopra il pannello aperto e lo chiude." },
  hi: { "User Interface": "यूज़र इंटरफ़ेस", "How the admin's controls behave for you. Saved per operator.": "एडमिन के नियंत्रण आपके लिए कैसे काम करते हैं। हर ऑपरेटर के लिए अलग से सहेजा जाता है।", "Hide the chat button while the chat is open": "चैट खुली होने पर चैट बटन छिपाएँ", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "चालू: चैट पैनल का ✕ उसे बंद करता है। बंद: बटन खुले पैनल के ऊपर स्क्रीन पर बना रहता है और उसे बंद करता है।" },
  ur: { "User Interface": "یوزر انٹرفیس", "How the admin's controls behave for you. Saved per operator.": "ایڈمن کے کنٹرول آپ کے لیے کیسے کام کرتے ہیں۔ ہر آپریٹر کے لیے الگ محفوظ ہوتا ہے۔", "Hide the chat button while the chat is open": "چیٹ کھلی ہونے پر چیٹ بٹن چھپائیں", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "آن: چیٹ پینل کا ✕ اسے بند کرتا ہے۔ آف: بٹن کھلے پینل کے اوپر اسکرین پر رہتا ہے اور اسے بند کرتا ہے۔" },
  bn: { "User Interface": "ইউজার ইন্টারফেস", "How the admin's controls behave for you. Saved per operator.": "অ্যাডমিনের নিয়ন্ত্রণগুলো আপনার জন্য কীভাবে কাজ করে। প্রতিটি অপারেটরের জন্য আলাদাভাবে সংরক্ষিত।", "Hide the chat button while the chat is open": "চ্যাট খোলা থাকলে চ্যাট বোতাম লুকান", "On: the chat panel's ✕ closes it. Off: the button stays on screen above the open panel and closes it.": "চালু: চ্যাট প্যানেলের ✕ এটি বন্ধ করে। বন্ধ: বোতামটি খোলা প্যানেলের উপরে স্ক্রিনে থাকে এবং এটি বন্ধ করে।" },
};

export const t = createDictionaryTranslator(INTERFACE_DICT);
