import { createDictionaryTranslator } from "../../lib/dictionary-translator";

/**
 * @file Copy for the Sites admin screen (`/admin/sites`).
 *
 * The English UI copy is the lookup key. Every locale block stays complete for every key it owns;
 * shared admin vocabulary continues to fall through to `COMMON_I18N`.
 *
 * Every string in this screen is chrome/explanatory copy. The data — folder names, display names,
 * absolute paths, and the server's own `restartInstructions` — is rendered verbatim and never
 * translated, matching how `AdminExternalMcpServer.serverId` is handled elsewhere in this app.
 */
const SITES_DICT: Record<string, Record<string, string>> = {
  ar: { "Serve after restart": "التقديم بعد إعادة التشغيل", "No listed sites": "لا توجد مواقع مدرجة", "A folder appears here once Tovu has created it.": "يظهر مجلد هنا بعد أن ينشئه Tovu.", "New site": "موقع جديد", "was created. Activate it to serve after the next restart.": "تم إنشاؤه. فعّله للتقديم بعد إعادة التشغيل التالية.", Sites: "المواقع" },
  bn: { "Serve after restart": "পুনরায় চালুর পরে পরিবেশন করুন", "No listed sites": "কোনো তালিকাভুক্ত সাইট নেই", "A folder appears here once Tovu has created it.": "Tovu তৈরি করলে এখানে একটি ফোল্ডার দেখা যাবে।", "New site": "নতুন সাইট", "was created. Activate it to serve after the next restart.": "তৈরি হয়েছে। পরবর্তী পুনরায় চালুর পরে পরিবেশন করতে এটি সক্রিয় করুন।", Sites: "সাইট" },
  de: { "Serve after restart": "Nach Neustart bereitstellen", "No listed sites": "Keine aufgeführten Websites", "A folder appears here once Tovu has created it.": "Ein Ordner erscheint hier, sobald Tovu ihn erstellt hat.", "New site": "Neue Website", "was created. Activate it to serve after the next restart.": "wurde erstellt. Aktivieren Sie sie, damit sie nach dem nächsten Neustart bereitgestellt wird.", Sites: "Websites" },
  es: { "Serve after restart": "Servir después de reiniciar", "No listed sites": "No hay sitios listados", "A folder appears here once Tovu has created it.": "Aquí aparecerá una carpeta cuando Tovu la haya creado.", "New site": "Nuevo sitio", "was created. Activate it to serve after the next restart.": "se creó. Actívalo para servirlo después del próximo reinicio.", Sites: "Sitios" },
  fa: { "Serve after restart": "پس از راه‌اندازی مجدد ارائه شود", "No listed sites": "سایتی فهرست نشده است", "A folder appears here once Tovu has created it.": "وقتی Tovu آن را ایجاد کند، پوشه‌ای اینجا ظاهر می‌شود.", "New site": "سایت جدید", "was created. Activate it to serve after the next restart.": "ایجاد شد. آن را فعال کنید تا پس از راه‌اندازی مجدد بعدی ارائه شود.", Sites: "سایت‌ها" },
  fr: { "Serve after restart": "Servir après le redémarrage", "No listed sites": "Aucun site répertorié", "A folder appears here once Tovu has created it.": "Un dossier apparaît ici une fois que Tovu l’a créé.", "New site": "Nouveau site", "was created. Activate it to serve after the next restart.": "a été créé. Activez-le pour le servir après le prochain redémarrage.", Sites: "Sites" },
  hi: { "Serve after restart": "रीस्टार्ट के बाद सेवा दें", "No listed sites": "कोई सूचीबद्ध साइट नहीं", "A folder appears here once Tovu has created it.": "Tovu के इसे बनाने पर यहां एक फ़ोल्डर दिखाई देगा।", "New site": "नई साइट", "was created. Activate it to serve after the next restart.": "बनाया गया था। अगले रीस्टार्ट के बाद सेवा देने के लिए इसे सक्रिय करें।", Sites: "साइटें" },
  hu: { "Serve after restart": "Kiszolgálás újraindítás után", "No listed sites": "Nincsenek felsorolt webhelyek", "A folder appears here once Tovu has created it.": "Itt jelenik meg egy mappa, miután a Tovu létrehozta.", "New site": "Új webhely", "was created. Activate it to serve after the next restart.": "létrejött. Aktiválja, hogy a következő újraindítás után kiszolgálható legyen.", Sites: "Webhelyek" },
  id: { "Serve after restart": "Sajikan setelah mulai ulang", "No listed sites": "Tidak ada situs terdaftar", "A folder appears here once Tovu has created it.": "Folder akan muncul di sini setelah Tovu membuatnya.", "New site": "Situs baru", "was created. Activate it to serve after the next restart.": "telah dibuat. Aktifkan untuk disajikan setelah mulai ulang berikutnya.", Sites: "Situs" },
  it: { "Serve after restart": "Servi dopo il riavvio", "No listed sites": "Nessun sito elencato", "A folder appears here once Tovu has created it.": "Qui apparirà una cartella quando Tovu l’avrà creata.", "New site": "Nuovo sito", "was created. Activate it to serve after the next restart.": "è stato creato. Attivalo per servirlo dopo il prossimo riavvio.", Sites: "Siti" },
  ja: { "Serve after restart": "再起動後に公開", "No listed sites": "一覧にサイトがありません", "A folder appears here once Tovu has created it.": "Tovu が作成すると、ここにフォルダーが表示されます。", "New site": "新しいサイト", "was created. Activate it to serve after the next restart.": "が作成されました。次回の再起動後に公開するには有効化してください。", Sites: "サイト" },
  ko: { "Serve after restart": "다시 시작한 후 제공", "No listed sites": "등록된 사이트가 없습니다", "A folder appears here once Tovu has created it.": "Tovu가 만들면 여기에 폴더가 표시됩니다.", "New site": "새 사이트", "was created. Activate it to serve after the next restart.": "생성되었습니다. 다음 다시 시작 후 제공하려면 활성화하세요.", Sites: "사이트" },
  pl: { "Serve after restart": "Udostępnij po ponownym uruchomieniu", "No listed sites": "Brak wymienionych witryn", "A folder appears here once Tovu has created it.": "Folder pojawi się tutaj, gdy Tovu go utworzy.", "New site": "Nowa witryna", "was created. Activate it to serve after the next restart.": "została utworzona. Włącz ją, aby była udostępniana po następnym uruchomieniu.", Sites: "Witryny" },
  "pt-BR": { "Serve after restart": "Servir após reiniciar", "No listed sites": "Nenhum site listado", "A folder appears here once Tovu has created it.": "Uma pasta aparecerá aqui quando o Tovu a criar.", "New site": "Novo site", "was created. Activate it to serve after the next restart.": "foi criado. Ative-o para servi-lo após a próxima reinicialização.", Sites: "Sites" },
  ru: { "Serve after restart": "Обслуживать после перезапуска", "No listed sites": "Нет перечисленных сайтов", "A folder appears here once Tovu has created it.": "Папка появится здесь, когда Tovu её создаст.", "New site": "Новый сайт", "was created. Activate it to serve after the next restart.": "создан. Активируйте его, чтобы обслуживать после следующего перезапуска.", Sites: "Сайты" },
  th: { "Serve after restart": "ให้บริการหลังรีสตาร์ต", "No listed sites": "ไม่มีไซต์ในรายการ", "A folder appears here once Tovu has created it.": "โฟลเดอร์จะปรากฏที่นี่เมื่อ Tovu สร้างแล้ว", "New site": "ไซต์ใหม่", "was created. Activate it to serve after the next restart.": "ถูกสร้างแล้ว เปิดใช้งานเพื่อให้บริการหลังรีสตาร์ตครั้งถัดไป", Sites: "ไซต์" },
  tr: { "Serve after restart": "Yeniden başlatmadan sonra sun", "No listed sites": "Listelenen site yok", "A folder appears here once Tovu has created it.": "Tovu oluşturduğunda burada bir klasör görünür.", "New site": "Yeni site", "was created. Activate it to serve after the next restart.": "oluşturuldu. Sonraki yeniden başlatmadan sonra sunmak için etkinleştirin.", Sites: "Siteler" },
  uk: { "Serve after restart": "Обслуговувати після перезапуску", "No listed sites": "Немає перелічених сайтів", "A folder appears here once Tovu has created it.": "Папка з’явиться тут, коли Tovu її створить.", "New site": "Новий сайт", "was created. Activate it to serve after the next restart.": "створено. Активуйте його, щоб обслуговувати після наступного перезапуску.", Sites: "Сайти" },
  ur: { "Serve after restart": "دوبارہ شروع ہونے کے بعد پیش کریں", "No listed sites": "کوئی درج شدہ سائٹ نہیں", "A folder appears here once Tovu has created it.": "Tovu کے بنانے پر یہاں ایک فولڈر ظاہر ہوگا۔", "New site": "نئی سائٹ", "was created. Activate it to serve after the next restart.": "بن گئی ہے۔ اگلے دوبارہ شروع ہونے کے بعد پیش کرنے کے لیے اسے فعال کریں۔", Sites: "سائٹس" },
  "zh-CN": { "Serve after restart": "重启后提供服务", "No listed sites": "没有列出的网站", "A folder appears here once Tovu has created it.": "Tovu 创建后，文件夹会显示在这里。", "New site": "新网站", "was created. Activate it to serve after the next restart.": "已创建。请启用它，以便在下次重启后提供服务。", Sites: "网站" },
  "zh-TW": { "Serve after restart": "重新啟動後提供服務", "No listed sites": "沒有列出的網站", "A folder appears here once Tovu has created it.": "Tovu 建立後，資料夾會顯示在這裡。", "New site": "新網站", "was created. Activate it to serve after the next restart.": "已建立。請啟用它，以便在下次重新啟動後提供服務。", Sites: "網站" },
};

/** Remaining screen-specific copy. Kept separate from the compact core table above so every
 * locale owns the same keys without making the existing, frequently-touched table unwieldy. */
const SITES_DETAIL_DICT: Record<string, Record<string, string>> = {
  ar: {
    "Supabase project URL": "عنوان URL لمشروع Supabase", "Supabase API key": "مفتاح API لـ Supabase", "Paste your API key": "الصق مفتاح API الخاص بك", "Shown for what's coming. It isn't stored anywhere yet.": "يُعرض لما هو قادم. لا يُخزَّن في أي مكان بعد.", "Provider name": "اسم المزوّد", "e.g. Neon, PlanetScale, Turso": "مثل: Neon وPlanetScale وTurso", "Connection string or API endpoint": "سلسلة الاتصال أو نقطة نهاية API", "Not supported yet": "غير مدعوم بعد", Ready: "جاهز",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite هو الخيار الافتراضي الذي لا يحتاج إلى إعداد. استخدم مزوّداً مستضافاً عندما تحتاج إليه.",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "ينشئ Tovu اليوم قاعدة محتوى كل موقع بصيغة SQLite، لذا لا يمكن اختيار الخيارين الآخرين بعد. تستخدم الدردشات SQLite دائماً في ملف chat.db منفصل — واستعادة المحتوى لا تمس سجل المحادثات أبداً.",
    "Site details": "تفاصيل الموقع", "Name the isolated workspace folder for this site.": "سمِّ مجلد مساحة العمل المعزولة لهذا الموقع.", "Folder name": "اسم المجلد", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "أحرف صغيرة وأرقام وشرطات. سيصبح هذا المجلد ضمن sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "إنشاء موقع لا يبدّل هذا الخادم إليه أبداً. فعّله من كل المواقع، ثم أعد التشغيل.", "Create site": "إنشاء موقع", "Save {name} as the site to serve after the next restart": "احفظ {name} كموقع لتقديمه بعد إعادة التشغيل التالية", "All sites": "كل المواقع", "Default · created inside this site's own folder": "افتراضي · يُنشأ داخل مجلد هذا الموقع", "Hosted · requires a project URL and API key": "مستضاف · يتطلب عنوان URL للمشروع ومفتاح API", "Any vendor · add its endpoint and credential": "أي مزوّد · أضف نقطة النهاية وبيانات الاعتماد", "Custom DB Provider": "مزوّد قاعدة بيانات مخصص",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "تم تعيين TOVU_SITE_DIR في بيئة هذا الخادم. إنه يتجاوز التفعيل — وستستمر إعادة التشغيل في تقديم هذا المجلد حتى يُلغى تعيينه.",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "محفوظ لتقديمه تالياً. لم يتبدل شيء بعد — لا يزال هذا الخادم وخادم الوكيل الخاص به على", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "محفوظ، لكن TOVU_SITE_DIR يتجاوزه، لذا لن تلتقطه إعادة التشغيل. لا يزال هذا الخادم وخادم الوكيل الخاص به على", "Restart the dev server to apply it.": "أعد تشغيل خادم التطوير لتطبيقه.", queued: "في قائمة الانتظار", "won't apply": "لن يُطبَّق",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "إنشاء المواقع وتفعيلها معطّل في هذا النشر. يبدّل Tovu-Runner المواقع بنفسه، ويستخدم التثبيت المستضاف مساحات العمل بدلاً من ذلك. لا يزال الموقع الذي يجري تقديمه معروضاً أعلاه.", "Could not load the site list.": "تعذر تحميل قائمة المواقع.", "Loading sites…": "جارٍ تحميل المواقع…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "لكل موقع ضمن sites/ محتواه وملفاته المرفوعة وسماته الخاصة. يتطلب التبديل بينها إعادة تشغيل.",
  },
  bn: {
    "Supabase project URL": "Supabase প্রকল্পের URL", "Supabase API key": "Supabase API কী", "Paste your API key": "আপনার API কী পেস্ট করুন", "Shown for what's coming. It isn't stored anywhere yet.": "আসন্ন ব্যবহারের জন্য দেখানো হচ্ছে। এটি এখনও কোথাও সংরক্ষিত নয়।", "Provider name": "প্রদানকারীর নাম", "e.g. Neon, PlanetScale, Turso": "যেমন Neon, PlanetScale, Turso", "Connection string or API endpoint": "সংযোগ স্ট্রিং বা API এন্ডপয়েন্ট", "Not supported yet": "এখনও সমর্থিত নয়", Ready: "প্রস্তুত",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite হলো কোনো-কনফিগারেশন ছাড়াই ডিফল্ট। প্রয়োজন হলে একটি হোস্টেড প্রদানকারী ব্যবহার করুন।",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu বর্তমানে প্রতিটি সাইটের কনটেন্ট ডেটাবেস SQLite হিসেবে তৈরি করে, তাই অন্য দুটি এখনও বেছে নেওয়া যায় না। চ্যাট সবসময় আলাদা chat.db-তে SQLite ব্যবহার করে — কনটেন্ট পুনরুদ্ধার কখনও কথোপকথনের ইতিহাস স্পর্শ করে না।",
    "Site details": "সাইটের বিবরণ", "Name the isolated workspace folder for this site.": "এই সাইটের বিচ্ছিন্ন ওয়ার্কস্পেস ফোল্ডারের নাম দিন।", "Folder name": "ফোল্ডারের নাম", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "ছোট হাতের অক্ষর, সংখ্যা ও ড্যাশ। এটি sites/ এর অধীনের ফোল্ডার হবে।", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "সাইট তৈরি করলে এই সার্ভার কখনও তাতে বদলায় না। সব সাইট থেকে এটি সক্রিয় করুন, তারপর পুনরায় চালু করুন।", "Create site": "সাইট তৈরি করুন", "Save {name} as the site to serve after the next restart": "পরবর্তী পুনরায় চালুর পরে পরিবেশনের সাইট হিসেবে {name} সংরক্ষণ করুন", "All sites": "সব সাইট", "Default · created inside this site's own folder": "ডিফল্ট · এই সাইটের নিজস্ব ফোল্ডারে তৈরি", "Hosted · requires a project URL and API key": "হোস্টেড · প্রকল্প URL এবং API কী প্রয়োজন", "Any vendor · add its endpoint and credential": "যে কোনো প্রদানকারী · তার এন্ডপয়েন্ট ও শংসাপত্র যোগ করুন", "Custom DB Provider": "কাস্টম DB প্রদানকারী",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "এই সার্ভারের পরিবেশে TOVU_SITE_DIR সেট করা আছে। এটি সক্রিয়করণকে অগ্রাহ্য করে — সেটিং সরানো না হওয়া পর্যন্ত পুনরায় চালুর পরও এই ফোল্ডার পরিবেশিত হবে।",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "পরের বার পরিবেশনের জন্য সংরক্ষিত। এখনও কিছু বদলায়নি — এই সার্ভার ও এর এজেন্ট ডেমন দুটিই এখনও আছে", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "সংরক্ষিত, কিন্তু TOVU_SITE_DIR এটিকে অগ্রাহ্য করে, তাই পুনরায় চালু করলে এটি নেওয়া হবে না। এই সার্ভার ও এর এজেন্ট ডেমন দুটিই এখনও আছে", "Restart the dev server to apply it.": "এটি প্রয়োগ করতে ডেভ সার্ভার পুনরায় চালু করুন।", queued: "সারিবদ্ধ", "won't apply": "প্রয়োগ হবে না",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "এই ডিপ্লয়মেন্টে সাইট তৈরি ও সক্রিয় করা বন্ধ আছে। Tovu-Runner নিজেই সাইট বদলায় এবং হোস্টেড ইনস্টলেশন তার বদলে ওয়ার্কস্পেস ব্যবহার করে। যে সাইটটি পরিবেশিত হচ্ছে সেটি এখনও উপরে দেখানো আছে।", "Could not load the site list.": "সাইটের তালিকা লোড করা যায়নি।", "Loading sites…": "সাইট লোড হচ্ছে…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ এর অধীনে প্রতিটি সাইটের নিজস্ব কনটেন্ট, আপলোড ও থিম আছে। তাদের মধ্যে বদলাতে পুনরায় চালু করতে হয়।",
  },
  de: {
    "Supabase project URL": "Supabase-Projekt-URL", "Supabase API key": "Supabase-API-Schlüssel", "Paste your API key": "Fügen Sie Ihren API-Schlüssel ein", "Shown for what's coming. It isn't stored anywhere yet.": "Zur Vorschau auf Kommendes angezeigt. Es wird noch nirgends gespeichert.", "Provider name": "Anbietername", "e.g. Neon, PlanetScale, Turso": "z. B. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Verbindungszeichenfolge oder API-Endpunkt", "Not supported yet": "Noch nicht unterstützt", Ready: "Bereit",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite ist die vorkonfigurationsfreie Standardeinstellung. Nutzen Sie bei Bedarf einen gehosteten Anbieter.",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu erstellt die Inhaltsdatenbank jeder Website heute als SQLite, daher können die anderen beiden noch nicht gewählt werden. Chats verwenden immer SQLite in einer separaten chat.db — das Wiederherstellen von Inhalten berührt niemals den Gesprächsverlauf.",
    "Site details": "Website-Details", "Name the isolated workspace folder for this site.": "Benennen Sie den isolierten Arbeitsbereichsordner für diese Website.", "Folder name": "Ordnername", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Kleinbuchstaben, Ziffern und Bindestriche. Dies wird zum Ordner unter sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Das Erstellen einer Website schaltet diesen Server nie darauf um. Aktivieren Sie sie unter Alle Websites und starten Sie dann neu.", "Create site": "Website erstellen", "Save {name} as the site to serve after the next restart": "{name} als nach dem nächsten Neustart bereitzustellende Website speichern", "All sites": "Alle Websites", "Default · created inside this site's own folder": "Standard · im eigenen Ordner dieser Website erstellt", "Hosted · requires a project URL and API key": "Gehostet · erfordert eine Projekt-URL und einen API-Schlüssel", "Any vendor · add its endpoint and credential": "Beliebiger Anbieter · Endpunkt und Zugangsdaten hinzufügen", "Custom DB Provider": "Benutzerdefinierter DB-Anbieter",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR ist in der Umgebung dieses Servers gesetzt. Es überschreibt Aktivieren — nach einem Neustart wird dieser Ordner weiter bereitgestellt, bis die Variable entfernt wird.",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "ist für die nächste Bereitstellung gespeichert. Noch wurde nichts umgeschaltet — dieser Server und sein Agent-Daemon laufen beide noch auf", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "ist gespeichert, aber TOVU_SITE_DIR überschreibt es, sodass ein Neustart es nicht übernimmt. Dieser Server und sein Agent-Daemon laufen beide noch auf", "Restart the dev server to apply it.": "Starten Sie den Entwicklungsserver neu, um dies anzuwenden.", queued: "vorgemerkt", "won't apply": "wird nicht angewendet",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Das Erstellen und Aktivieren von Websites ist bei dieser Bereitstellung deaktiviert. Tovu-Runner wechselt Websites selbst, und eine gehostete Installation verwendet stattdessen Arbeitsbereiche. Die bereitgestellte Website wird oben weiterhin angezeigt.", "Could not load the site list.": "Die Websiteliste konnte nicht geladen werden.", "Loading sites…": "Websites werden geladen…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Jede Website unter sites/ hat eigene Inhalte, Uploads und Themes. Das Wechseln zwischen ihnen erfordert einen Neustart.",
  },
  es: {
    "Supabase project URL": "URL del proyecto de Supabase", "Supabase API key": "Clave de API de Supabase", "Paste your API key": "Pega tu clave de API", "Shown for what's coming. It isn't stored anywhere yet.": "Se muestra para lo que viene. Aún no se guarda en ningún lugar.", "Provider name": "Nombre del proveedor", "e.g. Neon, PlanetScale, Turso": "p. ej., Neon, PlanetScale, Turso", "Connection string or API endpoint": "Cadena de conexión o punto de conexión de API", "Not supported yet": "Aún no compatible", Ready: "Listo",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite es la opción predeterminada sin configuración. Usa un proveedor alojado cuando lo necesites.",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Actualmente Tovu crea la base de datos de contenido de cada sitio como SQLite, por lo que aún no se pueden elegir las otras dos. Los chats siempre usan SQLite, en un chat.db independiente; restaurar contenido nunca afecta al historial de conversaciones.",
    "Site details": "Detalles del sitio", "Name the isolated workspace folder for this site.": "Nombra la carpeta de espacio de trabajo aislado para este sitio.", "Folder name": "Nombre de la carpeta", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Letras minúsculas, dígitos y guiones. Esta será la carpeta dentro de sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Crear un sitio nunca cambia este servidor a él. Actívalo desde Todos los sitios y luego reinicia.", "Create site": "Crear sitio", "Save {name} as the site to serve after the next restart": "Guardar {name} como el sitio que se servirá después del próximo reinicio", "All sites": "Todos los sitios", "Default · created inside this site's own folder": "Predeterminado · creado dentro de la propia carpeta de este sitio", "Hosted · requires a project URL and API key": "Alojado · requiere una URL de proyecto y una clave de API", "Any vendor · add its endpoint and credential": "Cualquier proveedor · añade su punto de conexión y credencial", "Custom DB Provider": "Proveedor de BD personalizado",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR está definido en el entorno de este servidor. Anula Activar: al reiniciar se seguirá sirviendo esta carpeta hasta que se quite.",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "está guardado para servirse a continuación. Aún no ha cambiado nada: este servidor y su demonio de agente siguen en", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "está guardado, pero TOVU_SITE_DIR lo anula, por lo que un reinicio no lo aplicará. Este servidor y su demonio de agente siguen en", "Restart the dev server to apply it.": "Reinicia el servidor de desarrollo para aplicarlo.", queued: "en cola", "won't apply": "no se aplicará",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "La creación y activación de sitios está desactivada en esta implementación. Tovu-Runner cambia los sitios por sí mismo y una instalación alojada usa espacios de trabajo en su lugar. El sitio que se está sirviendo sigue mostrándose arriba.", "Could not load the site list.": "No se pudo cargar la lista de sitios.", "Loading sites…": "Cargando sitios…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Cada sitio bajo sites/ tiene su propio contenido, cargas y temas. Cambiar entre ellos requiere reiniciar.",
  },
  fa: {
    "Supabase project URL": "نشانی URL پروژهٔ Supabase", "Supabase API key": "کلید API ‏Supabase", "Paste your API key": "کلید API خود را جای‌گذاری کنید", "Shown for what's coming. It isn't stored anywhere yet.": "برای قابلیت‌های آینده نمایش داده می‌شود. هنوز جایی ذخیره نمی‌شود.", "Provider name": "نام ارائه‌دهنده", "e.g. Neon, PlanetScale, Turso": "برای نمونه Neon، PlanetScale، Turso", "Connection string or API endpoint": "رشتهٔ اتصال یا نقطهٔ پایانی API", "Not supported yet": "هنوز پشتیبانی نمی‌شود", Ready: "آماده",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite پیش‌فرضِ بدون نیاز به پیکربندی است. هر زمان لازم بود از یک ارائه‌دهندهٔ میزبانی‌شده استفاده کنید.",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu اکنون پایگاه دادهٔ محتوای هر سایت را به‌صورت SQLite می‌سازد؛ بنابراین دو گزینهٔ دیگر هنوز قابل انتخاب نیستند. گفتگوها همیشه از SQLite در chat.db جداگانه استفاده می‌کنند — بازیابی محتوا هرگز تاریخچهٔ گفتگو را تغییر نمی‌دهد.",
    "Site details": "جزئیات سایت", "Name the isolated workspace folder for this site.": "برای این سایت نامی برای پوشهٔ فضای کاری ایزوله انتخاب کنید.", "Folder name": "نام پوشه", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "حروف کوچک، رقم و خط تیره. این نام پوشهٔ زیر sites/ می‌شود.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "ساختن سایت هرگز این سرور را به آن جابه‌جا نمی‌کند. آن را از همهٔ سایت‌ها فعال و سپس راه‌اندازی مجدد کنید.", "Create site": "ساخت سایت", "Save {name} as the site to serve after the next restart": "{name} را به‌عنوان سایت قابل ارائه پس از راه‌اندازی مجدد بعدی ذخیره کنید", "All sites": "همهٔ سایت‌ها", "Default · created inside this site's own folder": "پیش‌فرض · در پوشهٔ خود این سایت ساخته شده", "Hosted · requires a project URL and API key": "میزبانی‌شده · به URL پروژه و کلید API نیاز دارد", "Any vendor · add its endpoint and credential": "هر ارائه‌دهنده · نقطهٔ پایانی و اعتبارنامه‌اش را اضافه کنید", "Custom DB Provider": "ارائه‌دهندهٔ DB سفارشی",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR در محیط این سرور تنظیم شده است. بر فعال‌سازی غلبه می‌کند — تا زمانی که برداشته نشود، راه‌اندازی مجدد همچنان این پوشه را ارائه می‌کند.",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "برای ارائهٔ بعدی ذخیره شده است. هنوز چیزی جابه‌جا نشده — این سرور و شبح‌فرایند عامل آن هر دو همچنان روی", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "ذخیره شده است، اما TOVU_SITE_DIR بر آن غلبه می‌کند؛ بنابراین راه‌اندازی مجدد آن را برنمی‌دارد. این سرور و شبح‌فرایند عامل آن هر دو همچنان روی", "Restart the dev server to apply it.": "برای اعمال آن سرور توسعه را راه‌اندازی مجدد کنید.", queued: "در صف", "won't apply": "اعمال نمی‌شود",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "ساختن و فعال‌سازی سایت‌ها در این استقرار غیرفعال است. Tovu-Runner خود سایت‌ها را جابه‌جا می‌کند و نصب میزبانی‌شده به‌جای آن از فضاهای کاری استفاده می‌کند. سایت در حال ارائه همچنان در بالا نمایش داده می‌شود.", "Could not load the site list.": "بارگیری فهرست سایت‌ها ممکن نشد.", "Loading sites…": "در حال بارگیری سایت‌ها…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "هر سایت زیر sites/ محتوا، بارگذاری‌ها و پوسته‌های خودش را دارد. جابه‌جایی میان آن‌ها نیازمند راه‌اندازی مجدد است.",
  },
  fr: {
    "Supabase project URL": "URL du projet Supabase", "Supabase API key": "Clé API Supabase", "Paste your API key": "Collez votre clé API", "Shown for what's coming. It isn't stored anywhere yet.": "Affiché pour les fonctionnalités à venir. Rien n’est encore enregistré.", "Provider name": "Nom du fournisseur", "e.g. Neon, PlanetScale, Turso": "p. ex. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Chaîne de connexion ou point de terminaison d’API", "Not supported yet": "Pas encore pris en charge", Ready: "Prêt",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite est le choix par défaut sans configuration. Utilisez un fournisseur hébergé lorsque nécessaire.",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Aujourd’hui, Tovu crée la base de contenu de chaque site avec SQLite ; les deux autres options ne sont donc pas encore sélectionnables. Les discussions utilisent toujours SQLite dans un fichier chat.db distinct — restaurer le contenu ne touche jamais l’historique des conversations.",
    "Site details": "Détails du site", "Name the isolated workspace folder for this site.": "Nommez le dossier d’espace de travail isolé pour ce site.", "Folder name": "Nom du dossier", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Lettres minuscules, chiffres et tirets. Cela devient le dossier sous sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Créer un site ne bascule jamais ce serveur dessus. Activez-le dans Tous les sites, puis redémarrez.", "Create site": "Créer le site", "Save {name} as the site to serve after the next restart": "Enregistrer {name} comme site à servir après le prochain redémarrage", "All sites": "Tous les sites", "Default · created inside this site's own folder": "Par défaut · créé dans le propre dossier de ce site", "Hosted · requires a project URL and API key": "Hébergé · nécessite une URL de projet et une clé API", "Any vendor · add its endpoint and credential": "Tout fournisseur · ajoutez son point de terminaison et ses identifiants", "Custom DB Provider": "Fournisseur de BD personnalisé",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR est défini dans l’environnement de ce serveur. Il remplace Activer — après redémarrage, ce dossier continuera d’être servi jusqu’à ce que la variable soit supprimée.",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "est enregistré pour être servi ensuite. Rien n’a encore basculé — ce serveur et son démon d’agent sont toujours sur", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "est enregistré, mais TOVU_SITE_DIR le remplace ; un redémarrage ne le prendra donc pas en compte. Ce serveur et son démon d’agent sont toujours sur", "Restart the dev server to apply it.": "Redémarrez le serveur de développement pour l’appliquer.", queued: "en attente", "won't apply": "ne s’appliquera pas",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "La création et l’activation de sites sont désactivées sur ce déploiement. Tovu-Runner bascule lui-même les sites, et une installation hébergée utilise plutôt des espaces de travail. Le site servi est toujours affiché ci-dessus.", "Could not load the site list.": "Impossible de charger la liste des sites.", "Loading sites…": "Chargement des sites…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Chaque site sous sites/ possède son propre contenu, ses téléversements et ses thèmes. Passer de l’un à l’autre exige un redémarrage.",
  },
  hi: {
    "Supabase project URL": "Supabase प्रोजेक्ट URL", "Supabase API key": "Supabase API कुंजी", "Paste your API key": "अपनी API कुंजी चिपकाएँ", "Shown for what's coming. It isn't stored anywhere yet.": "आने वाली सुविधा के लिए दिखाया गया है। यह अभी कहीं संग्रहीत नहीं है।", "Provider name": "प्रदाता का नाम", "e.g. Neon, PlanetScale, Turso": "जैसे Neon, PlanetScale, Turso", "Connection string or API endpoint": "कनेक्शन स्ट्रिंग या API एंडपॉइंट", "Not supported yet": "अभी समर्थित नहीं", Ready: "तैयार",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite बिना कॉन्फ़िगरेशन वाला डिफ़ॉल्ट है। आवश्यकता होने पर होस्ट किए गए प्रदाता का उपयोग करें।",
    "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu आज हर साइट का सामग्री डेटाबेस SQLite के रूप में बनाता है, इसलिए अन्य दो को अभी नहीं चुना जा सकता। चैट हमेशा अलग chat.db में SQLite का उपयोग करती हैं — सामग्री पुनर्स्थापित करने से बातचीत का इतिहास कभी नहीं बदलता।",
    "Site details": "साइट का विवरण", "Name the isolated workspace folder for this site.": "इस साइट के पृथक कार्यस्थान फ़ोल्डर का नाम दें।", "Folder name": "फ़ोल्डर का नाम", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "छोटे अक्षर, अंक और डैश। यह sites/ के अंतर्गत फ़ोल्डर बनेगा।", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "साइट बनाने से यह सर्वर कभी उस पर स्विच नहीं होता। इसे सभी साइटों से सक्रिय करें, फिर रीस्टार्ट करें।", "Create site": "साइट बनाएँ", "Save {name} as the site to serve after the next restart": "अगले रीस्टार्ट के बाद सेवा देने वाली साइट के रूप में {name} सहेजें", "All sites": "सभी साइटें", "Default · created inside this site's own folder": "डिफ़ॉल्ट · इस साइट के अपने फ़ोल्डर में बनाया गया", "Hosted · requires a project URL and API key": "होस्ट किया गया · प्रोजेक्ट URL और API कुंजी आवश्यक", "Any vendor · add its endpoint and credential": "कोई भी प्रदाता · उसका एंडपॉइंट और क्रेडेंशियल जोड़ें", "Custom DB Provider": "कस्टम DB प्रदाता",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "इस सर्वर के परिवेश में TOVU_SITE_DIR सेट है। यह सक्रिय करें को ओवरराइड करता है — इसे अनसेट करने तक रीस्टार्ट के बाद भी यही फ़ोल्डर सेवा देगा।",
    "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "अगली बार सेवा देने के लिए सहेजा गया है। अभी कुछ भी स्विच नहीं हुआ है — यह सर्वर और इसका एजेंट डेमन दोनों अभी भी इस पर हैं", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "सहेजा गया है, लेकिन TOVU_SITE_DIR इसे ओवरराइड करता है, इसलिए रीस्टार्ट इसे नहीं अपनाएगा। यह सर्वर और इसका एजेंट डेमन दोनों अभी भी इस पर हैं", "Restart the dev server to apply it.": "इसे लागू करने के लिए डेवलपमेंट सर्वर रीस्टार्ट करें।", queued: "कतार में", "won't apply": "लागू नहीं होगा",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "इस परिनियोजन में साइट बनाना और सक्रिय करना बंद है। Tovu-Runner स्वयं साइटें बदलता है और होस्ट किया गया इंस्टॉल इसके बजाय कार्यस्थान उपयोग करता है। जिस साइट को सेवा दी जा रही है वह अभी भी ऊपर दिखाई गई है।", "Could not load the site list.": "साइट सूची लोड नहीं की जा सकी।", "Loading sites…": "साइटें लोड हो रही हैं…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ के अंतर्गत हर साइट की अपनी सामग्री, अपलोड और थीम हैं। उनके बीच स्विच करने के लिए रीस्टार्ट करना पड़ता है।",
  },
  hu: {
    "Supabase project URL": "Supabase-projekt URL-je", "Supabase API key": "Supabase API-kulcs", "Paste your API key": "Illessze be az API-kulcsát", "Shown for what's coming. It isn't stored anywhere yet.": "A közelgő funkcióhoz látható. Még sehol sem tároljuk.", "Provider name": "Szolgáltató neve", "e.g. Neon, PlanetScale, Turso": "pl. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Kapcsolati karakterlánc vagy API-végpont", "Not supported yet": "Még nem támogatott", Ready: "Kész",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "Az SQLite az alapértelmezett, konfiguráció nélküli megoldás. Ha szüksége van rá, használjon hosztolt szolgáltatót.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "A Tovu ma minden webhely tartalmi adatbázisát SQLite-ként hozza létre, ezért a másik kettő még nem választható. A csevegések mindig SQLite-ot használnak külön chat.db fájlban — a tartalom visszaállítása sosem érinti a beszélgetési előzményeket.",
    "Site details": "Webhely részletei", "Name the isolated workspace folder for this site.": "Nevezze el a webhely elkülönített munkaterületmappáját.", "Folder name": "Mappa neve", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Kisbetűk, számok és kötőjelek. Ez lesz a sites/ alatti mappa.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Egy webhely létrehozása sosem váltja át rá ezt a kiszolgálót. Aktiválja a Minden webhely alatt, majd indítsa újra.", "Create site": "Webhely létrehozása", "Save {name} as the site to serve after the next restart": "{name} mentése a következő újraindítás után kiszolgálandó webhelyként", "All sites": "Minden webhely", "Default · created inside this site's own folder": "Alapértelmezett · a webhely saját mappájában jön létre", "Hosted · requires a project URL and API key": "Hosztolt · projekt-URL-t és API-kulcsot igényel", "Any vendor · add its endpoint and credential": "Bármely szolgáltató · adja hozzá a végpontját és hitelesítő adatait", "Custom DB Provider": "Egyéni DB-szolgáltató",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "A TOVU_SITE_DIR be van állítva a kiszolgáló környezetében. Felülírja az Aktiválást — újraindítás után ez a mappa marad kiszolgálva, amíg a változó nincs törölve.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "a következő kiszolgáláshoz van mentve. Még semmi nem váltott — ez a kiszolgáló és az ügynök démonja is még ezen van", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "mentve van, de a TOVU_SITE_DIR felülírja, ezért az újraindítás nem veszi át. Ez a kiszolgáló és az ügynök démonja is még ezen van", "Restart the dev server to apply it.": "Az alkalmazásához indítsa újra a fejlesztői kiszolgálót.", queued: "sorban", "won't apply": "nem lép érvénybe",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "A webhelyek létrehozása és aktiválása ki van kapcsolva ebben a telepítésben. A Tovu-Runner maga vált webhelyet, a hosztolt telepítés pedig munkaterületeket használ. A kiszolgált webhely továbbra is fent látható.", "Could not load the site list.": "A webhelylista nem tölthető be.", "Loading sites…": "Webhelyek betöltése…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "A sites/ alatti minden webhelynek saját tartalma, feltöltései és témái vannak. A köztük való váltáshoz újraindítás kell.",
  },
  id: {
    "Supabase project URL": "URL proyek Supabase", "Supabase API key": "Kunci API Supabase", "Paste your API key": "Tempel kunci API Anda", "Shown for what's coming. It isn't stored anywhere yet.": "Ditampilkan untuk fitur yang akan datang. Belum disimpan di mana pun.", "Provider name": "Nama penyedia", "e.g. Neon, PlanetScale, Turso": "misalnya Neon, PlanetScale, Turso", "Connection string or API endpoint": "String koneksi atau titik akhir API", "Not supported yet": "Belum didukung", Ready: "Siap",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite adalah bawaan tanpa konfigurasi. Gunakan penyedia yang dihosting saat Anda membutuhkannya.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Saat ini Tovu membuat basis data konten setiap situs sebagai SQLite, jadi dua opsi lainnya belum dapat dipilih. Obrolan selalu menggunakan SQLite dalam chat.db terpisah — memulihkan konten tidak pernah menyentuh riwayat percakapan.",
    "Site details": "Detail situs", "Name the isolated workspace folder for this site.": "Beri nama folder ruang kerja terisolasi untuk situs ini.", "Folder name": "Nama folder", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Huruf kecil, angka, dan tanda hubung. Ini menjadi folder di bawah sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Membuat situs tidak pernah mengalihkan server ini ke situs tersebut. Aktifkan dari Semua situs, lalu mulai ulang.", "Create site": "Buat situs", "Save {name} as the site to serve after the next restart": "Simpan {name} sebagai situs yang akan dilayani setelah mulai ulang berikutnya", "All sites": "Semua situs", "Default · created inside this site's own folder": "Bawaan · dibuat di dalam folder situs ini", "Hosted · requires a project URL and API key": "Dihosting · memerlukan URL proyek dan kunci API", "Any vendor · add its endpoint and credential": "Penyedia apa pun · tambahkan titik akhir dan kredensialnya", "Custom DB Provider": "Penyedia DB kustom",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR ditetapkan di lingkungan server ini. Ini menimpa Aktifkan — setelah mulai ulang folder ini akan tetap dilayani hingga nilainya dihapus.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "disimpan untuk dilayani berikutnya. Belum ada yang beralih — server ini dan daemon agennya masih pada", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "disimpan, tetapi TOVU_SITE_DIR menimpanya sehingga mulai ulang tidak akan menerapkannya. Server ini dan daemon agennya masih pada", "Restart the dev server to apply it.": "Mulai ulang server pengembangan untuk menerapkannya.", queued: "dalam antrean", "won't apply": "tidak akan diterapkan",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Pembuatan dan pengaktifan situs dimatikan pada penerapan ini. Tovu-Runner mengganti situs sendiri, dan instalasi yang dihosting memakai ruang kerja. Situs yang sedang dilayani masih ditampilkan di atas.", "Could not load the site list.": "Tidak dapat memuat daftar situs.", "Loading sites…": "Memuat situs…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Setiap situs di bawah sites/ memiliki konten, unggahan, dan temanya sendiri. Beralih di antaranya memerlukan mulai ulang.",
  },
  it: {
    "Supabase project URL": "URL del progetto Supabase", "Supabase API key": "Chiave API Supabase", "Paste your API key": "Incolla la tua chiave API", "Shown for what's coming. It isn't stored anywhere yet.": "Mostrato per ciò che arriverà. Non è ancora memorizzato da nessuna parte.", "Provider name": "Nome del provider", "e.g. Neon, PlanetScale, Turso": "ad es. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Stringa di connessione o endpoint API", "Not supported yet": "Non ancora supportato", Ready: "Pronto",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite è l'impostazione predefinita senza configurazione. Usa un provider ospitato quando necessario.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Oggi Tovu crea il database dei contenuti di ogni sito come SQLite, quindi le altre due opzioni non sono ancora selezionabili. Le chat usano sempre SQLite in un chat.db separato — il ripristino dei contenuti non tocca mai la cronologia delle conversazioni.",
    "Site details": "Dettagli del sito", "Name the isolated workspace folder for this site.": "Assegna un nome alla cartella dello spazio di lavoro isolato per questo sito.", "Folder name": "Nome cartella", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Lettere minuscole, cifre e trattini. Questa diventa la cartella sotto sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "La creazione di un sito non sposta mai questo server su di esso. Attivalo da Tutti i siti, quindi riavvia.", "Create site": "Crea sito", "Save {name} as the site to serve after the next restart": "Salva {name} come sito da servire dopo il prossimo riavvio", "All sites": "Tutti i siti", "Default · created inside this site's own folder": "Predefinito · creato nella cartella del sito", "Hosted · requires a project URL and API key": "Ospitato · richiede un URL di progetto e una chiave API", "Any vendor · add its endpoint and credential": "Qualsiasi provider · aggiungi endpoint e credenziali", "Custom DB Provider": "Provider DB personalizzato",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR è impostato nell'ambiente di questo server. Ignora Attiva — dopo il riavvio questa cartella continuerà a essere servita finché non verrà rimosso.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "è salvato per essere servito successivamente. Non è ancora cambiato nulla — questo server e il relativo demone agente sono ancora su", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "è salvato, ma TOVU_SITE_DIR lo ignora, quindi un riavvio non lo selezionerà. Questo server e il relativo demone agente sono ancora su", "Restart the dev server to apply it.": "Riavvia il server di sviluppo per applicarlo.", queued: "in coda", "won't apply": "non verrà applicato",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "La creazione e l'attivazione di siti sono disattivate in questa distribuzione. Tovu-Runner cambia i siti autonomamente e un'installazione ospitata usa invece gli spazi di lavoro. Il sito servito è ancora mostrato sopra.", "Could not load the site list.": "Impossibile caricare l'elenco dei siti.", "Loading sites…": "Caricamento siti…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Ogni sito sotto sites/ ha i propri contenuti, caricamenti e temi. Il passaggio tra essi richiede un riavvio.",
  },
  ja: {
    "Supabase project URL": "Supabase プロジェクト URL", "Supabase API key": "Supabase API キー", "Paste your API key": "API キーを貼り付け", "Shown for what's coming. It isn't stored anywhere yet.": "今後の機能のために表示しています。まだどこにも保存されません。", "Provider name": "プロバイダー名", "e.g. Neon, PlanetScale, Turso": "例: Neon、PlanetScale、Turso", "Connection string or API endpoint": "接続文字列または API エンドポイント", "Not supported yet": "まだサポートされていません", Ready: "準備完了",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite は設定不要の既定値です。必要な場合はホスト型ベンダーを利用してください。", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "現在、Tovu は各サイトのコンテンツデータベースを SQLite として作成するため、他の 2 つはまだ選択できません。チャットは常に別の chat.db で SQLite を使用します。コンテンツを復元しても会話履歴には決して影響しません。",
    "Site details": "サイトの詳細", "Name the isolated workspace folder for this site.": "このサイト用の分離されたワークスペースフォルダーに名前を付けます。", "Folder name": "フォルダー名", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "小文字、数字、ハイフンを使用します。これが sites/ 配下のフォルダーになります。", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "サイトを作成しても、このサーバーはそのサイトに切り替わりません。すべてのサイトから有効化してから、再起動してください。", "Create site": "サイトを作成", "Save {name} as the site to serve after the next restart": "次回の再起動後に公開するサイトとして {name} を保存", "All sites": "すべてのサイト", "Default · created inside this site's own folder": "既定 · このサイト自身のフォルダー内に作成", "Hosted · requires a project URL and API key": "ホスト型 · プロジェクト URL と API キーが必要", "Any vendor · add its endpoint and credential": "任意のベンダー · エンドポイントと認証情報を追加", "Custom DB Provider": "カスタム DB プロバイダー",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "このサーバーの環境には TOVU_SITE_DIR が設定されています。有効化より優先されるため、設定を解除するまで再起動後もこのフォルダーが公開されます。", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "は次に公開するサイトとして保存されています。まだ何も切り替わっていません。このサーバーとエージェントデーモンはどちらもまだ", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "は保存されていますが、TOVU_SITE_DIR が優先されるため、再起動しても反映されません。このサーバーとエージェントデーモンはどちらもまだ", "Restart the dev server to apply it.": "適用するには開発サーバーを再起動してください。", queued: "待機中", "won't apply": "適用されません",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "このデプロイではサイトの作成と有効化が無効です。Tovu-Runner がサイトを切り替え、ホスト型インストールでは代わりにワークスペースを使用します。公開中のサイトは引き続き上に表示されます。", "Could not load the site list.": "サイト一覧を読み込めませんでした。", "Loading sites…": "サイトを読み込み中…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ 配下の各サイトには、独自のコンテンツ、アップロード、テーマがあります。切り替えには再起動が必要です。",
  },
  ko: {
    "Supabase project URL": "Supabase 프로젝트 URL", "Supabase API key": "Supabase API 키", "Paste your API key": "API 키를 붙여넣으세요", "Shown for what's coming. It isn't stored anywhere yet.": "예정된 기능을 위해 표시됩니다. 아직 어디에도 저장되지 않습니다.", "Provider name": "공급자 이름", "e.g. Neon, PlanetScale, Turso": "예: Neon, PlanetScale, Turso", "Connection string or API endpoint": "연결 문자열 또는 API 엔드포인트", "Not supported yet": "아직 지원되지 않음", Ready: "준비됨",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite는 설정이 필요 없는 기본값입니다. 필요하면 호스팅된 공급자를 사용하세요.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "현재 Tovu는 모든 사이트의 콘텐츠 데이터베이스를 SQLite로 만드므로 다른 두 옵션은 아직 선택할 수 없습니다. 채팅은 별도의 chat.db에서 항상 SQLite를 사용하며, 콘텐츠를 복원해도 대화 기록에는 전혀 영향을 주지 않습니다.",
    "Site details": "사이트 세부 정보", "Name the isolated workspace folder for this site.": "이 사이트의 격리된 작업 공간 폴더 이름을 지정하세요.", "Folder name": "폴더 이름", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "소문자, 숫자, 대시를 사용하세요. sites/ 아래의 폴더가 됩니다.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "사이트를 만들어도 이 서버가 해당 사이트로 전환되지는 않습니다. 모든 사이트에서 활성화한 뒤 다시 시작하세요.", "Create site": "사이트 만들기", "Save {name} as the site to serve after the next restart": "다음 다시 시작 후 제공할 사이트로 {name} 저장", "All sites": "모든 사이트", "Default · created inside this site's own folder": "기본값 · 이 사이트의 자체 폴더 안에 생성됨", "Hosted · requires a project URL and API key": "호스팅됨 · 프로젝트 URL과 API 키 필요", "Any vendor · add its endpoint and credential": "모든 공급자 · 엔드포인트와 자격 증명 추가", "Custom DB Provider": "사용자 지정 DB 공급자",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "이 서버 환경에 TOVU_SITE_DIR가 설정되어 있습니다. 활성화보다 우선하므로, 설정을 해제할 때까지 다시 시작해도 이 폴더가 계속 제공됩니다.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "은(는) 다음에 제공할 사이트로 저장되었습니다. 아직 전환된 것은 없습니다. 이 서버와 해당 에이전트 데몬은 둘 다 아직", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "은(는) 저장되었지만 TOVU_SITE_DIR가 이를 재정의하므로 다시 시작해도 적용되지 않습니다. 이 서버와 해당 에이전트 데몬은 둘 다 아직", "Restart the dev server to apply it.": "적용하려면 개발 서버를 다시 시작하세요.", queued: "대기 중", "won't apply": "적용되지 않음",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "이 배포에서는 사이트 생성과 활성화가 꺼져 있습니다. Tovu-Runner가 직접 사이트를 전환하며, 호스팅 설치는 대신 작업 공간을 사용합니다. 제공 중인 사이트는 위에 계속 표시됩니다.", "Could not load the site list.": "사이트 목록을 불러올 수 없습니다.", "Loading sites…": "사이트 불러오는 중…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ 아래의 각 사이트에는 자체 콘텐츠, 업로드 및 테마가 있습니다. 사이트 간 전환에는 다시 시작이 필요합니다.",
  },
  pl: {
    "Supabase project URL": "URL projektu Supabase", "Supabase API key": "Klucz API Supabase", "Paste your API key": "Wklej klucz API", "Shown for what's coming. It isn't stored anywhere yet.": "Pokazane dla nadchodzących funkcji. Nie jest jeszcze nigdzie przechowywane.", "Provider name": "Nazwa dostawcy", "e.g. Neon, PlanetScale, Turso": "np. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Ciąg połączenia lub punkt końcowy API", "Not supported yet": "Jeszcze nieobsługiwane", Ready: "Gotowe",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite jest domyślnym rozwiązaniem bez konfiguracji. W razie potrzeby użyj hostowanego dostawcy.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu tworzy obecnie bazę treści każdej witryny jako SQLite, więc pozostałych dwóch opcji nie można jeszcze wybrać. Czaty zawsze używają SQLite w osobnym pliku chat.db — przywracanie treści nigdy nie dotyka historii rozmów.",
    "Site details": "Szczegóły witryny", "Name the isolated workspace folder for this site.": "Nadaj nazwę izolowanemu folderowi obszaru roboczego dla tej witryny.", "Folder name": "Nazwa folderu", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Małe litery, cyfry i myślniki. To będzie folder w sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Utworzenie witryny nigdy nie przełącza na nią tego serwera. Aktywuj ją w obszarze Wszystkie witryny, a następnie uruchom ponownie.", "Create site": "Utwórz witrynę", "Save {name} as the site to serve after the next restart": "Zapisz {name} jako witrynę do obsłużenia po następnym uruchomieniu", "All sites": "Wszystkie witryny", "Default · created inside this site's own folder": "Domyślna · utworzona w folderze tej witryny", "Hosted · requires a project URL and API key": "Hostowana · wymaga URL projektu i klucza API", "Any vendor · add its endpoint and credential": "Dowolny dostawca · dodaj jego punkt końcowy i poświadczenia", "Custom DB Provider": "Niestandardowy dostawca DB",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR jest ustawione w środowisku tego serwera. Ma pierwszeństwo przed Aktywuj — po ponownym uruchomieniu ten folder będzie nadal obsługiwany, dopóki zmienna nie zostanie usunięta.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "jest zapisane do obsłużenia jako następne. Nic jeszcze nie zostało przełączone — ten serwer i jego demon agenta nadal działają na", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "jest zapisane, ale TOVU_SITE_DIR je nadpisuje, więc ponowne uruchomienie go nie zastosuje. Ten serwer i jego demon agenta nadal działają na", "Restart the dev server to apply it.": "Uruchom ponownie serwer deweloperski, aby to zastosować.", queued: "w kolejce", "won't apply": "nie zostanie zastosowane",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Tworzenie i aktywowanie witryn jest wyłączone w tym wdrożeniu. Tovu-Runner sam przełącza witryny, a instalacja hostowana używa zamiast tego obszarów roboczych. Obsługiwana witryna nadal jest pokazana powyżej.", "Could not load the site list.": "Nie można wczytać listy witryn.", "Loading sites…": "Wczytywanie witryn…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Każda witryna w sites/ ma własną zawartość, przesłane pliki i motywy. Przełączenie między nimi wymaga ponownego uruchomienia.",
  },
  "pt-BR": {
    "Supabase project URL": "URL do projeto Supabase", "Supabase API key": "Chave de API do Supabase", "Paste your API key": "Cole sua chave de API", "Shown for what's coming. It isn't stored anywhere yet.": "Exibido para o que está por vir. Ainda não é armazenado em lugar algum.", "Provider name": "Nome do provedor", "e.g. Neon, PlanetScale, Turso": "por exemplo, Neon, PlanetScale, Turso", "Connection string or API endpoint": "String de conexão ou endpoint de API", "Not supported yet": "Ainda não compatível", Ready: "Pronto",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite é o padrão sem configuração. Use um fornecedor hospedado quando precisar.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Hoje, o Tovu cria o banco de conteúdo de cada site como SQLite, por isso as outras duas opções ainda não podem ser escolhidas. Os chats sempre usam SQLite em um chat.db separado — restaurar conteúdo nunca afeta o histórico da conversa.",
    "Site details": "Detalhes do site", "Name the isolated workspace folder for this site.": "Dê um nome à pasta de espaço de trabalho isolado deste site.", "Folder name": "Nome da pasta", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Letras minúsculas, números e hífens. Isso se torna a pasta em sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Criar um site nunca muda este servidor para ele. Ative-o em Todos os sites e reinicie.", "Create site": "Criar site", "Save {name} as the site to serve after the next restart": "Salvar {name} como o site a servir após a próxima reinicialização", "All sites": "Todos os sites", "Default · created inside this site's own folder": "Padrão · criado dentro da própria pasta deste site", "Hosted · requires a project URL and API key": "Hospedado · requer URL do projeto e chave de API", "Any vendor · add its endpoint and credential": "Qualquer fornecedor · adicione seu endpoint e credencial", "Custom DB Provider": "Provedor de DB personalizado",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR está definido no ambiente deste servidor. Ele substitui Ativar — ao reiniciar, esta pasta continuará sendo servida até ser removido.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "está salvo para ser servido em seguida. Nada mudou ainda — este servidor e seu daemon de agente continuam em", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "está salvo, mas TOVU_SITE_DIR o substitui, então uma reinicialização não o aplicará. Este servidor e seu daemon de agente continuam em", "Restart the dev server to apply it.": "Reinicie o servidor de desenvolvimento para aplicar.", queued: "na fila", "won't apply": "não será aplicado",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "A criação e a ativação de sites estão desativadas nesta implantação. O Tovu-Runner alterna os sites por conta própria, e uma instalação hospedada usa espaços de trabalho. O site servido ainda é mostrado acima.", "Could not load the site list.": "Não foi possível carregar a lista de sites.", "Loading sites…": "Carregando sites…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Cada site em sites/ tem seu próprio conteúdo, uploads e temas. Alternar entre eles requer uma reinicialização.",
  },
  ru: {
    "Supabase project URL": "URL проекта Supabase", "Supabase API key": "Ключ API Supabase", "Paste your API key": "Вставьте ключ API", "Shown for what's coming. It isn't stored anywhere yet.": "Показано для будущей функции. Пока нигде не сохраняется.", "Provider name": "Имя поставщика", "e.g. Neon, PlanetScale, Turso": "например, Neon, PlanetScale, Turso", "Connection string or API endpoint": "Строка подключения или конечная точка API", "Not supported yet": "Пока не поддерживается", Ready: "Готово",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite — вариант по умолчанию без настройки. При необходимости используйте размещённого поставщика.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Сейчас Tovu создаёт базу содержимого каждого сайта как SQLite, поэтому два других варианта пока нельзя выбрать. Чаты всегда используют SQLite в отдельном chat.db — восстановление содержимого никогда не затрагивает историю разговоров.",
    "Site details": "Сведения о сайте", "Name the isolated workspace folder for this site.": "Назовите изолированную папку рабочего пространства для этого сайта.", "Folder name": "Имя папки", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Строчные буквы, цифры и дефисы. Это станет папкой в sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Создание сайта никогда не переключает этот сервер на него. Активируйте его в разделе Все сайты, затем перезапустите.", "Create site": "Создать сайт", "Save {name} as the site to serve after the next restart": "Сохранить {name} как сайт для обслуживания после следующего перезапуска", "All sites": "Все сайты", "Default · created inside this site's own folder": "По умолчанию · создано в собственной папке сайта", "Hosted · requires a project URL and API key": "Размещённый · требуются URL проекта и ключ API", "Any vendor · add its endpoint and credential": "Любой поставщик · добавьте его конечную точку и учётные данные", "Custom DB Provider": "Пользовательский поставщик DB",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR задан в среде этого сервера. Он переопределяет Активацию — после перезапуска эта папка будет обслуживаться, пока переменная не будет снята.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "сохранён для следующего обслуживания. Пока ничего не переключилось — этот сервер и его демон агента всё ещё работают с", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "сохранён, но TOVU_SITE_DIR его переопределяет, поэтому перезапуск его не подхватит. Этот сервер и его демон агента всё ещё работают с", "Restart the dev server to apply it.": "Перезапустите сервер разработки, чтобы применить изменения.", queued: "в очереди", "won't apply": "не будет применено",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Создание и активация сайтов отключены в этом развёртывании. Tovu-Runner переключает сайты сам, а размещённая установка использует рабочие пространства. Обслуживаемый сайт всё ещё показан выше.", "Could not load the site list.": "Не удалось загрузить список сайтов.", "Loading sites…": "Загрузка сайтов…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "У каждого сайта в sites/ есть собственные содержимое, загрузки и темы. Для переключения между ними требуется перезапуск.",
  },
  th: {
    "Supabase project URL": "URL โครงการ Supabase", "Supabase API key": "คีย์ API ของ Supabase", "Paste your API key": "วางคีย์ API ของคุณ", "Shown for what's coming. It isn't stored anywhere yet.": "แสดงไว้สำหรับสิ่งที่จะมา ยังไม่ได้จัดเก็บไว้ที่ใด", "Provider name": "ชื่อผู้ให้บริการ", "e.g. Neon, PlanetScale, Turso": "เช่น Neon, PlanetScale, Turso", "Connection string or API endpoint": "สตริงการเชื่อมต่อหรือปลายทาง API", "Not supported yet": "ยังไม่รองรับ", Ready: "พร้อม",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite เป็นค่าเริ่มต้นที่ไม่ต้องตั้งค่า ใช้ผู้ให้บริการที่โฮสต์เมื่อจำเป็น.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "ปัจจุบัน Tovu สร้างฐานข้อมูลเนื้อหาของทุกไซต์เป็น SQLite จึงยังเลือกอีกสองตัวไม่ได้ แชตใช้ SQLite เสมอใน chat.db แยกต่างหาก — การกู้คืนเนื้อหาไม่กระทบประวัติการสนทนาเลย",
    "Site details": "รายละเอียดไซต์", "Name the isolated workspace folder for this site.": "ตั้งชื่อโฟลเดอร์พื้นที่ทำงานแยกสำหรับไซต์นี้", "Folder name": "ชื่อโฟลเดอร์", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "ตัวพิมพ์เล็ก ตัวเลข และขีดกลาง ชื่อนี้จะเป็นโฟลเดอร์ใต้ sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "การสร้างไซต์จะไม่สลับเซิร์ฟเวอร์นี้ไปยังไซต์นั้น เปิดใช้จากไซต์ทั้งหมดแล้วรีสตาร์ต", "Create site": "สร้างไซต์", "Save {name} as the site to serve after the next restart": "บันทึก {name} เป็นไซต์ที่จะให้บริการหลังรีสตาร์ตครั้งถัดไป", "All sites": "ทุกไซต์", "Default · created inside this site's own folder": "ค่าเริ่มต้น · สร้างในโฟลเดอร์ของไซต์นี้", "Hosted · requires a project URL and API key": "โฮสต์ · ต้องมี URL โครงการและคีย์ API", "Any vendor · add its endpoint and credential": "ผู้ให้บริการใดก็ได้ · เพิ่มปลายทางและข้อมูลรับรอง", "Custom DB Provider": "ผู้ให้บริการ DB แบบกำหนดเอง",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "ตั้งค่า TOVU_SITE_DIR ในสภาพแวดล้อมของเซิร์ฟเวอร์นี้แล้ว ซึ่งจะแทนที่เปิดใช้ — เมื่อรีสตาร์ตจะยังให้บริการโฟลเดอร์นี้จนกว่าจะยกเลิกการตั้งค่า", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "ถูกบันทึกไว้เพื่อให้บริการถัดไป ยังไม่มีอะไรสลับ — เซิร์ฟเวอร์นี้และดีมอนเอเจนต์ยังคงอยู่ที่", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "ถูกบันทึกไว้ แต่ TOVU_SITE_DIR แทนที่ไว้ ดังนั้นการรีสตาร์ตจะไม่ใช้ค่านี้ เซิร์ฟเวอร์นี้และดีมอนเอเจนต์ยังคงอยู่ที่", "Restart the dev server to apply it.": "รีสตาร์ตเซิร์ฟเวอร์พัฒนาเพื่อใช้การเปลี่ยนแปลง", queued: "อยู่ในคิว", "won't apply": "จะไม่ถูกใช้",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "การสร้างและเปิดใช้ไซต์ถูกปิดสำหรับการปรับใช้นี้ Tovu-Runner สลับไซต์เอง และการติดตั้งแบบโฮสต์ใช้พื้นที่ทำงานแทน ไซต์ที่กำลังให้บริการยังแสดงอยู่ด้านบน", "Could not load the site list.": "ไม่สามารถโหลดรายการไซต์ได้", "Loading sites…": "กำลังโหลดไซต์…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "ทุกไซต์ใต้ sites/ มีเนื้อหา การอัปโหลด และธีมของตนเอง การสลับระหว่างกันต้องรีสตาร์ต",
  },
  tr: {
    "Supabase project URL": "Supabase proje URL'si", "Supabase API key": "Supabase API anahtarı", "Paste your API key": "API anahtarınızı yapıştırın", "Shown for what's coming. It isn't stored anywhere yet.": "Gelecek özellik için gösterilir. Henüz hiçbir yerde saklanmaz.", "Provider name": "Sağlayıcı adı", "e.g. Neon, PlanetScale, Turso": "örn. Neon, PlanetScale, Turso", "Connection string or API endpoint": "Bağlantı dizesi veya API uç noktası", "Not supported yet": "Henüz desteklenmiyor", Ready: "Hazır",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite yapılandırma gerektirmeyen varsayılandır. Gerektiğinde barındırılan bir sağlayıcı kullanın.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu bugün her sitenin içerik veritabanını SQLite olarak oluşturur, bu nedenle diğer ikisi henüz seçilemez. Sohbetler her zaman ayrı bir chat.db içinde SQLite kullanır — içeriği geri yüklemek konuşma geçmişine hiç dokunmaz.",
    "Site details": "Site ayrıntıları", "Name the isolated workspace folder for this site.": "Bu site için yalıtılmış çalışma alanı klasörünü adlandırın.", "Folder name": "Klasör adı", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Küçük harfler, rakamlar ve tireler. Bu, sites/ altındaki klasör olur.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Site oluşturmak bu sunucuyu hiçbir zaman ona geçirmez. Tüm sitelerden etkinleştirin, ardından yeniden başlatın.", "Create site": "Site oluştur", "Save {name} as the site to serve after the next restart": "{name} öğesini sonraki yeniden başlatmadan sonra sunulacak site olarak kaydet", "All sites": "Tüm siteler", "Default · created inside this site's own folder": "Varsayılan · bu sitenin kendi klasöründe oluşturulur", "Hosted · requires a project URL and API key": "Barındırılan · proje URL'si ve API anahtarı gerektirir", "Any vendor · add its endpoint and credential": "Herhangi bir sağlayıcı · uç noktasını ve kimlik bilgilerini ekleyin", "Custom DB Provider": "Özel DB sağlayıcısı",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR bu sunucunun ortamında ayarlı. Etkinleştir'i geçersiz kılar — ayar kaldırılana kadar yeniden başlatma bu klasörü sunmaya devam eder.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "sonraki sunum için kaydedildi. Henüz hiçbir şey değişmedi — bu sunucu ve aracı artalan hizmeti hâlâ şurada", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "kaydedildi, ancak TOVU_SITE_DIR bunu geçersiz kılıyor; dolayısıyla yeniden başlatma bunu almayacak. Bu sunucu ve aracı artalan hizmeti hâlâ şurada", "Restart the dev server to apply it.": "Uygulamak için geliştirme sunucusunu yeniden başlatın.", queued: "kuyrukta", "won't apply": "uygulanmayacak",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Bu dağıtımda site oluşturma ve etkinleştirme kapalıdır. Tovu-Runner siteleri kendisi değiştirir; barındırılan kurulum ise çalışma alanlarını kullanır. Sunulan site yukarıda gösterilmeye devam eder.", "Could not load the site list.": "Site listesi yüklenemedi.", "Loading sites…": "Siteler yükleniyor…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ altındaki her sitenin kendi içeriği, yüklemeleri ve temaları vardır. Aralarında geçiş yapmak yeniden başlatma gerektirir.",
  },
  uk: {
    "Supabase project URL": "URL проєкту Supabase", "Supabase API key": "Ключ API Supabase", "Paste your API key": "Вставте свій ключ API", "Shown for what's coming. It isn't stored anywhere yet.": "Показано для майбутньої функції. Ще ніде не зберігається.", "Provider name": "Назва постачальника", "e.g. Neon, PlanetScale, Turso": "наприклад, Neon, PlanetScale, Turso", "Connection string or API endpoint": "Рядок підключення або кінцева точка API", "Not supported yet": "Ще не підтримується", Ready: "Готово",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite — типовий варіант без налаштування. За потреби використовуйте розміщеного постачальника.", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Наразі Tovu створює базу вмісту кожного сайту як SQLite, тому інші два варіанти ще не можна вибрати. Чати завжди використовують SQLite в окремому chat.db — відновлення вмісту ніколи не торкається історії розмов.",
    "Site details": "Відомості про сайт", "Name the isolated workspace folder for this site.": "Назвіть ізольовану папку робочого простору для цього сайту.", "Folder name": "Назва папки", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "Малі літери, цифри та дефіси. Це стане папкою в sites/.", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "Створення сайту ніколи не перемикає цей сервер на нього. Активуйте його в розділі Усі сайти, а потім перезапустіть.", "Create site": "Створити сайт", "Save {name} as the site to serve after the next restart": "Зберегти {name} як сайт для обслуговування після наступного перезапуску", "All sites": "Усі сайти", "Default · created inside this site's own folder": "Типовий · створено у власній папці цього сайту", "Hosted · requires a project URL and API key": "Розміщений · потребує URL проєкту й ключа API", "Any vendor · add its endpoint and credential": "Будь-який постачальник · додайте його кінцеву точку й облікові дані", "Custom DB Provider": "Власний постачальник DB",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "TOVU_SITE_DIR задано в середовищі цього сервера. Він має перевагу над Активувати — після перезапуску ця папка обслуговуватиметься, доки змінну не буде скасовано.", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "збережено для наступного обслуговування. Ще нічого не перемкнулося — цей сервер і його демон агента все ще працюють на", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "збережено, але TOVU_SITE_DIR має перевагу, тому перезапуск його не застосує. Цей сервер і його демон агента все ще працюють на", "Restart the dev server to apply it.": "Перезапустіть сервер розробки, щоб застосувати зміни.", queued: "у черзі", "won't apply": "не буде застосовано",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "Створення й активацію сайтів вимкнено в цьому розгортанні. Tovu-Runner перемикає сайти сам, а розміщене встановлення використовує робочі простори. Сайт, що обслуговується, усе ще показано вище.", "Could not load the site list.": "Не вдалося завантажити список сайтів.", "Loading sites…": "Завантаження сайтів…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "Кожен сайт у sites/ має власні вміст, завантаження й теми. Для перемикання між ними потрібен перезапуск.",
  },
  ur: {
    "Supabase project URL": "Supabase پروجیکٹ URL", "Supabase API key": "Supabase API کلید", "Paste your API key": "اپنی API کلید چسپاں کریں", "Shown for what's coming. It isn't stored anywhere yet.": "آنے والی خصوصیت کے لیے دکھایا گیا ہے۔ یہ ابھی کہیں محفوظ نہیں ہے۔", "Provider name": "فراہم کنندہ کا نام", "e.g. Neon, PlanetScale, Turso": "مثلاً Neon، PlanetScale، Turso", "Connection string or API endpoint": "کنکشن اسٹرنگ یا API اختتامی نقطہ", "Not supported yet": "ابھی معاونت نہیں", Ready: "تیار",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite بغیر ترتیب والا طے شدہ انتخاب ہے۔ ضرورت ہو تو ہوسٹ شدہ فراہم کنندہ استعمال کریں۔", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "Tovu اس وقت ہر سائٹ کا مواد ڈیٹابیس SQLite کے طور پر بناتا ہے، اس لیے باقی دو ابھی منتخب نہیں کیے جا سکتے۔ چیٹس ہمیشہ الگ chat.db میں SQLite استعمال کرتی ہیں — مواد بحال کرنے سے گفتگو کی تاریخ کبھی متاثر نہیں ہوتی۔",
    "Site details": "سائٹ کی تفصیلات", "Name the isolated workspace folder for this site.": "اس سائٹ کے الگ ورک اسپیس فولڈر کا نام دیں۔", "Folder name": "فولڈر کا نام", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "چھوٹے حروف، اعداد اور ڈیش۔ یہ sites/ کے تحت فولڈر بنے گا۔", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "سائٹ بنانے سے یہ سرور کبھی اس پر منتقل نہیں ہوتا۔ اسے تمام سائٹس سے فعال کریں، پھر دوبارہ شروع کریں۔", "Create site": "سائٹ بنائیں", "Save {name} as the site to serve after the next restart": "{name} کو اگلی بار دوبارہ شروع ہونے کے بعد پیش کرنے والی سائٹ کے طور پر محفوظ کریں", "All sites": "تمام سائٹس", "Default · created inside this site's own folder": "طے شدہ · اس سائٹ کے اپنے فولڈر میں بنایا گیا", "Hosted · requires a project URL and API key": "ہوسٹ شدہ · پروجیکٹ URL اور API کلید درکار ہے", "Any vendor · add its endpoint and credential": "کوئی بھی فراہم کنندہ · اس کا اختتامی نقطہ اور اسناد شامل کریں", "Custom DB Provider": "حسب ضرورت DB فراہم کنندہ",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "اس سرور کے ماحول میں TOVU_SITE_DIR مقرر ہے۔ یہ فعال کرنے کو نظرانداز کرتا ہے — جب تک اسے ہٹایا نہ جائے دوبارہ شروع ہونے پر یہی فولڈر پیش ہوتا رہے گا۔", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "اگلی بار پیش کرنے کے لیے محفوظ ہے۔ ابھی کچھ تبدیل نہیں ہوا — یہ سرور اور اس کا ایجنٹ ڈیمَن دونوں اب بھی", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "محفوظ ہے، لیکن TOVU_SITE_DIR اسے نظرانداز کرتا ہے، اس لیے دوبارہ شروع ہونے پر یہ لاگو نہیں ہوگا۔ یہ سرور اور اس کا ایجنٹ ڈیمَن دونوں اب بھی", "Restart the dev server to apply it.": "لاگو کرنے کے لیے ڈیولپمنٹ سرور دوبارہ شروع کریں۔", queued: "قطار میں", "won't apply": "لاگو نہیں ہوگا",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "اس تعیناتی میں سائٹس بنانا اور فعال کرنا بند ہے۔ Tovu-Runner خود سائٹس بدلتا ہے، اور ہوسٹ شدہ تنصیب اس کے بجائے ورک اسپیس استعمال کرتی ہے۔ پیش کی جانے والی سائٹ اوپر اب بھی دکھائی گئی ہے۔", "Could not load the site list.": "سائٹس کی فہرست لوڈ نہیں ہو سکی۔", "Loading sites…": "سائٹس لوڈ ہو رہی ہیں…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ کے تحت ہر سائٹ کا اپنا مواد، اپ لوڈز اور تھیمز ہے۔ ان کے درمیان تبدیل ہونے کے لیے دوبارہ شروع کرنا ضروری ہے۔",
  },
  "zh-CN": {
    "Supabase project URL": "Supabase 项目 URL", "Supabase API key": "Supabase API 密钥", "Paste your API key": "粘贴您的 API 密钥", "Shown for what's coming. It isn't stored anywhere yet.": "为即将推出的功能显示。尚未存储在任何位置。", "Provider name": "提供商名称", "e.g. Neon, PlanetScale, Turso": "例如 Neon、PlanetScale、Turso", "Connection string or API endpoint": "连接字符串或 API 终结点", "Not supported yet": "尚不支持", Ready: "就绪",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite 是无需配置的默认选项。需要时请使用托管提供商。", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "目前 Tovu 将每个网站的内容数据库创建为 SQLite，因此另外两个选项尚不能选择。聊天始终在独立的 chat.db 中使用 SQLite——恢复内容绝不会影响对话历史。",
    "Site details": "网站详细信息", "Name the isolated workspace folder for this site.": "为这个网站的隔离工作区文件夹命名。", "Folder name": "文件夹名称", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "小写字母、数字和连字符。这将成为 sites/ 下的文件夹。", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "创建网站不会将此服务器切换到该网站。请从所有网站中启用它，然后重启。", "Create site": "创建网站", "Save {name} as the site to serve after the next restart": "将 {name} 保存为下次重启后要提供服务的网站", "All sites": "所有网站", "Default · created inside this site's own folder": "默认 · 在此网站自己的文件夹中创建", "Hosted · requires a project URL and API key": "托管 · 需要项目 URL 和 API 密钥", "Any vendor · add its endpoint and credential": "任意提供商 · 添加其终结点和凭据", "Custom DB Provider": "自定义 DB 提供商",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "此服务器的环境中设置了 TOVU_SITE_DIR。它会覆盖启用操作——在取消设置前，重启后将继续为此文件夹提供服务。", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "已保存为下次要提供服务的网站。尚未发生切换——此服务器及其代理守护程序仍在", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "已保存，但 TOVU_SITE_DIR 会覆盖它，因此重启不会应用它。此服务器及其代理守护程序仍在", "Restart the dev server to apply it.": "重启开发服务器以应用它。", queued: "已排队", "won't apply": "不会应用",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "此部署已关闭创建和启用网站功能。Tovu-Runner 会自行切换网站，托管安装则使用工作区。正在提供服务的网站仍显示在上方。", "Could not load the site list.": "无法加载网站列表。", "Loading sites…": "正在加载网站…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ 下的每个网站都有自己的内容、上传和主题。在它们之间切换需要重启。",
  },
  "zh-TW": {
    "Supabase project URL": "Supabase 專案 URL", "Supabase API key": "Supabase API 金鑰", "Paste your API key": "貼上您的 API 金鑰", "Shown for what's coming. It isn't stored anywhere yet.": "為即將推出的功能顯示。尚未儲存在任何位置。", "Provider name": "提供者名稱", "e.g. Neon, PlanetScale, Turso": "例如 Neon、PlanetScale、Turso", "Connection string or API endpoint": "連線字串或 API 端點", "Not supported yet": "尚未支援", Ready: "就緒",
    "SQLite is the zero-configuration default. Bring a hosted vendor when you need one.": "SQLite 是無需設定的預設選項。需要時請使用託管提供者。", "Tovu creates every site's content database as SQLite today, so the other two can't be chosen yet. Chats always use SQLite, in a separate chat.db — restoring content never touches conversation history.": "目前 Tovu 將每個網站的內容資料庫建立為 SQLite，因此另外兩個選項尚不能選擇。聊天一律在獨立的 chat.db 中使用 SQLite——還原內容絕不會影響對話紀錄。",
    "Site details": "網站詳細資料", "Name the isolated workspace folder for this site.": "為這個網站的隔離工作區資料夾命名。", "Folder name": "資料夾名稱", "Lowercase letters, digits, and dashes. This becomes the folder under sites/.": "小寫字母、數字和連字號。這會成為 sites/ 下的資料夾。", "Creating a site never switches this server onto it. Activate it from All sites, then restart.": "建立網站不會將此伺服器切換到該網站。請從所有網站中啟用它，然後重新啟動。", "Create site": "建立網站", "Save {name} as the site to serve after the next restart": "將 {name} 儲存為下次重新啟動後要提供服務的網站", "All sites": "所有網站", "Default · created inside this site's own folder": "預設 · 在此網站自己的資料夾中建立", "Hosted · requires a project URL and API key": "託管 · 需要專案 URL 和 API 金鑰", "Any vendor · add its endpoint and credential": "任何提供者 · 新增其端點和認證資料", "Custom DB Provider": "自訂 DB 提供者",
    "TOVU_SITE_DIR is set in this server's environment. It overrides Activate — restarting will keep serving this folder until it's unset.": "此伺服器的環境中設定了 TOVU_SITE_DIR。它會覆寫啟用操作——在取消設定前，重新啟動後將繼續為此資料夾提供服務。", "is saved to serve next. Nothing has switched yet — this server and its agent daemon are both still on": "已儲存為下次要提供服務的網站。尚未發生切換——此伺服器及其代理程式精靈仍在", "is saved, but TOVU_SITE_DIR overrides it, so a restart will not pick it up. This server and its agent daemon are both still on": "已儲存，但 TOVU_SITE_DIR 會覆寫它，因此重新啟動不會套用它。此伺服器及其代理程式精靈仍在", "Restart the dev server to apply it.": "重新啟動開發伺服器以套用它。", queued: "已排入佇列", "won't apply": "不會套用",
    "Creating and activating sites is turned off on this deployment. Tovu-Runner switches sites itself, and a hosted install uses workspaces instead. The site being served is still shown above.": "此部署已關閉建立和啟用網站功能。Tovu-Runner 會自行切換網站，託管安裝則使用工作區。正在提供服務的網站仍顯示在上方。", "Could not load the site list.": "無法載入網站清單。", "Loading sites…": "正在載入網站…", "Each site under sites/ has its own content, uploads, and themes. Switching between them takes a restart.": "sites/ 下的每個網站都有自己的內容、上傳和佈景主題。在它們之間切換需要重新啟動。",
  },
};

for (const [locale, detail] of Object.entries(SITES_DETAIL_DICT)) {
  Object.assign(Reflect.get(SITES_DICT, locale), detail);
}

export const t = createDictionaryTranslator(SITES_DICT);
