/**
 * @file Characterization pin for `transitionCampaignStatus` — the EXHAUSTIVE 7x7x4 authority
 * matrix (every `CampaignStatus` pair against every `CampaignActorTier`), asserting both the
 * allow/deny decision AND the exact denial text.
 *
 * Why exhaustive rather than representative: `campaign.ts` documents a precedence-ordered
 * transition-authority table (behavior.spec.md §1.1), and the load-bearing property of a
 * precedence table is that no edge falls through to the wrong rule. A representative sample can
 * stay green while a reordering silently re-homes an edge; the full matrix cannot. Companion to
 * `campaign.test.ts`, which pins the same rules as human-readable intent — this file pins them as
 * a total function, so any behavior-preserving restructuring of the guard is provably equivalent.
 *
 * The expected column was captured from the implementation as it stood before the guard was
 * refactored into named edge predicates, so it is an equivalence proof, not a restatement of the
 * current code's shape.
 */
import assert from "node:assert/strict";
import test from "node:test";

import { transitionCampaignStatus, type CampaignActorTier } from "../campaign.js";
import type { CampaignStatus } from "../types.js";

/** `true` = allowed; a string = denied with exactly that `reason`. */
type ExpectedOutcome = true | string;

const MATRIX: ReadonlyArray<readonly [CampaignStatus, CampaignStatus, CampaignActorTier, ExpectedOutcome]> = [
  ["draft", "draft", "pipeline", "'draft' -> 'draft' is not a transition (no-op)"],
  ["draft", "draft", "send", "'draft' -> 'draft' is not a transition (no-op)"],
  ["draft", "draft", "schedule", "'draft' -> 'draft' is not a transition (no-op)"],
  ["draft", "draft", "compose", "'draft' -> 'draft' is not a transition (no-op)"],
  ["draft", "scheduled", "pipeline", "only 'admin.newsletter.campaign.schedule' may set draft -> scheduled"],
  ["draft", "scheduled", "send", "only 'admin.newsletter.campaign.schedule' may set draft -> scheduled"],
  ["draft", "scheduled", "schedule", true],
  ["draft", "scheduled", "compose", "only 'admin.newsletter.campaign.schedule' may set draft -> scheduled"],
  ["draft", "sending", "pipeline", "'draft' -> 'sending' is not a permitted transition for any actor tier"],
  ["draft", "sending", "send", "'draft' -> 'sending' is not a permitted transition for any actor tier"],
  ["draft", "sending", "schedule", "'draft' -> 'sending' is not a permitted transition for any actor tier"],
  ["draft", "sending", "compose", "'draft' -> 'sending' is not a permitted transition for any actor tier"],
  ["draft", "sent", "pipeline", "'sent' may only be entered from 'sending'"],
  ["draft", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["draft", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["draft", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["draft", "paused", "pipeline", "'draft' -> 'paused' is not a permitted transition for any actor tier"],
  ["draft", "paused", "send", "'draft' -> 'paused' is not a permitted transition for any actor tier"],
  ["draft", "paused", "schedule", "'draft' -> 'paused' is not a permitted transition for any actor tier"],
  ["draft", "paused", "compose", "'draft' -> 'paused' is not a permitted transition for any actor tier"],
  ["draft", "canceled", "pipeline", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["draft", "canceled", "send", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["draft", "canceled", "schedule", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["draft", "canceled", "compose", true],
  ["draft", "failed", "pipeline", "'draft' -> 'failed' is not a permitted transition for any actor tier"],
  ["draft", "failed", "send", "'draft' -> 'failed' is not a permitted transition for any actor tier"],
  ["draft", "failed", "schedule", "'draft' -> 'failed' is not a permitted transition for any actor tier"],
  ["draft", "failed", "compose", "'draft' -> 'failed' is not a permitted transition for any actor tier"],
  ["scheduled", "draft", "pipeline", "'scheduled' -> 'draft' is not a permitted transition for any actor tier"],
  ["scheduled", "draft", "send", "'scheduled' -> 'draft' is not a permitted transition for any actor tier"],
  ["scheduled", "draft", "schedule", "'scheduled' -> 'draft' is not a permitted transition for any actor tier"],
  ["scheduled", "draft", "compose", "'scheduled' -> 'draft' is not a permitted transition for any actor tier"],
  ["scheduled", "scheduled", "pipeline", "'scheduled' -> 'scheduled' is not a transition (no-op)"],
  ["scheduled", "scheduled", "send", "'scheduled' -> 'scheduled' is not a transition (no-op)"],
  ["scheduled", "scheduled", "schedule", "'scheduled' -> 'scheduled' is not a transition (no-op)"],
  ["scheduled", "scheduled", "compose", "'scheduled' -> 'scheduled' is not a transition (no-op)"],
  ["scheduled", "sending", "pipeline", true],
  ["scheduled", "sending", "send", "only the send pipeline may set status to 'sending'"],
  ["scheduled", "sending", "schedule", "only the send pipeline may set status to 'sending'"],
  ["scheduled", "sending", "compose", "only the send pipeline may set status to 'sending'"],
  ["scheduled", "sent", "pipeline", "'sent' may only be entered from 'sending'"],
  ["scheduled", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["scheduled", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["scheduled", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["scheduled", "paused", "pipeline", "'scheduled' -> 'paused' is not a permitted transition for any actor tier"],
  ["scheduled", "paused", "send", "'scheduled' -> 'paused' is not a permitted transition for any actor tier"],
  ["scheduled", "paused", "schedule", "'scheduled' -> 'paused' is not a permitted transition for any actor tier"],
  ["scheduled", "paused", "compose", "'scheduled' -> 'paused' is not a permitted transition for any actor tier"],
  ["scheduled", "canceled", "pipeline", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["scheduled", "canceled", "send", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["scheduled", "canceled", "schedule", "only 'admin.newsletter.campaign.compose' may cancel a campaign"],
  ["scheduled", "canceled", "compose", true],
  ["scheduled", "failed", "pipeline", "'scheduled' -> 'failed' is not a permitted transition for any actor tier"],
  ["scheduled", "failed", "send", "'scheduled' -> 'failed' is not a permitted transition for any actor tier"],
  ["scheduled", "failed", "schedule", "'scheduled' -> 'failed' is not a permitted transition for any actor tier"],
  ["scheduled", "failed", "compose", "'scheduled' -> 'failed' is not a permitted transition for any actor tier"],
  ["sending", "draft", "pipeline", "'sending' -> 'draft' is not a permitted transition for any actor tier"],
  ["sending", "draft", "send", "'sending' -> 'draft' is not a permitted transition for any actor tier"],
  ["sending", "draft", "schedule", "'sending' -> 'draft' is not a permitted transition for any actor tier"],
  ["sending", "draft", "compose", "'sending' -> 'draft' is not a permitted transition for any actor tier"],
  ["sending", "scheduled", "pipeline", "'sending' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sending", "scheduled", "send", "'sending' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sending", "scheduled", "schedule", "'sending' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sending", "scheduled", "compose", "'sending' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sending", "sending", "pipeline", "'sending' -> 'sending' is not a transition (no-op)"],
  ["sending", "sending", "send", "'sending' -> 'sending' is not a transition (no-op)"],
  ["sending", "sending", "schedule", "'sending' -> 'sending' is not a transition (no-op)"],
  ["sending", "sending", "compose", "'sending' -> 'sending' is not a transition (no-op)"],
  ["sending", "sent", "pipeline", true],
  ["sending", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["sending", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["sending", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["sending", "paused", "pipeline", true],
  ["sending", "paused", "send", true],
  ["sending", "paused", "schedule", "only 'admin.newsletter.campaign.send' may transition 'sending' -> 'paused'"],
  ["sending", "paused", "compose", "only 'admin.newsletter.campaign.send' may transition 'sending' -> 'paused'"],
  ["sending", "canceled", "pipeline", "'sending' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sending", "canceled", "send", "'sending' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sending", "canceled", "schedule", "'sending' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sending", "canceled", "compose", "'sending' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sending", "failed", "pipeline", "'sending' -> 'failed' is not a permitted transition for any actor tier"],
  ["sending", "failed", "send", "'sending' -> 'failed' is not a permitted transition for any actor tier"],
  ["sending", "failed", "schedule", "'sending' -> 'failed' is not a permitted transition for any actor tier"],
  ["sending", "failed", "compose", "'sending' -> 'failed' is not a permitted transition for any actor tier"],
  ["sent", "draft", "pipeline", "'sent' -> 'draft' is not a permitted transition for any actor tier"],
  ["sent", "draft", "send", "'sent' -> 'draft' is not a permitted transition for any actor tier"],
  ["sent", "draft", "schedule", "'sent' -> 'draft' is not a permitted transition for any actor tier"],
  ["sent", "draft", "compose", "'sent' -> 'draft' is not a permitted transition for any actor tier"],
  ["sent", "scheduled", "pipeline", "'sent' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sent", "scheduled", "send", "'sent' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sent", "scheduled", "schedule", "'sent' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sent", "scheduled", "compose", "'sent' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["sent", "sending", "pipeline", "'sent' -> 'sending' is not a permitted transition for any actor tier"],
  ["sent", "sending", "send", "'sent' -> 'sending' is not a permitted transition for any actor tier"],
  ["sent", "sending", "schedule", "'sent' -> 'sending' is not a permitted transition for any actor tier"],
  ["sent", "sending", "compose", "'sent' -> 'sending' is not a permitted transition for any actor tier"],
  ["sent", "sent", "pipeline", "'sent' -> 'sent' is not a transition (no-op)"],
  ["sent", "sent", "send", "'sent' -> 'sent' is not a transition (no-op)"],
  ["sent", "sent", "schedule", "'sent' -> 'sent' is not a transition (no-op)"],
  ["sent", "sent", "compose", "'sent' -> 'sent' is not a transition (no-op)"],
  ["sent", "paused", "pipeline", "'sent' -> 'paused' is not a permitted transition for any actor tier"],
  ["sent", "paused", "send", "'sent' -> 'paused' is not a permitted transition for any actor tier"],
  ["sent", "paused", "schedule", "'sent' -> 'paused' is not a permitted transition for any actor tier"],
  ["sent", "paused", "compose", "'sent' -> 'paused' is not a permitted transition for any actor tier"],
  ["sent", "canceled", "pipeline", "'sent' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sent", "canceled", "send", "'sent' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sent", "canceled", "schedule", "'sent' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sent", "canceled", "compose", "'sent' -> 'canceled' is not a permitted transition for any actor tier"],
  ["sent", "failed", "pipeline", "'sent' -> 'failed' is not a permitted transition for any actor tier"],
  ["sent", "failed", "send", "'sent' -> 'failed' is not a permitted transition for any actor tier"],
  ["sent", "failed", "schedule", "'sent' -> 'failed' is not a permitted transition for any actor tier"],
  ["sent", "failed", "compose", "'sent' -> 'failed' is not a permitted transition for any actor tier"],
  ["paused", "draft", "pipeline", "'paused' -> 'draft' is not a permitted transition for any actor tier"],
  ["paused", "draft", "send", "'paused' -> 'draft' is not a permitted transition for any actor tier"],
  ["paused", "draft", "schedule", "'paused' -> 'draft' is not a permitted transition for any actor tier"],
  ["paused", "draft", "compose", "'paused' -> 'draft' is not a permitted transition for any actor tier"],
  ["paused", "scheduled", "pipeline", "'paused' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["paused", "scheduled", "send", "'paused' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["paused", "scheduled", "schedule", "'paused' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["paused", "scheduled", "compose", "'paused' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["paused", "sending", "pipeline", true],
  ["paused", "sending", "send", true],
  ["paused", "sending", "schedule", "only 'admin.newsletter.campaign.send' may transition 'paused' -> 'sending'"],
  ["paused", "sending", "compose", "only 'admin.newsletter.campaign.send' may transition 'paused' -> 'sending'"],
  ["paused", "sent", "pipeline", "'sent' may only be entered from 'sending'"],
  ["paused", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["paused", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["paused", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["paused", "paused", "pipeline", "'paused' -> 'paused' is not a transition (no-op)"],
  ["paused", "paused", "send", "'paused' -> 'paused' is not a transition (no-op)"],
  ["paused", "paused", "schedule", "'paused' -> 'paused' is not a transition (no-op)"],
  ["paused", "paused", "compose", "'paused' -> 'paused' is not a transition (no-op)"],
  ["paused", "canceled", "pipeline", "'paused' -> 'canceled' is not a permitted transition for any actor tier"],
  ["paused", "canceled", "send", "'paused' -> 'canceled' is not a permitted transition for any actor tier"],
  ["paused", "canceled", "schedule", "'paused' -> 'canceled' is not a permitted transition for any actor tier"],
  ["paused", "canceled", "compose", "'paused' -> 'canceled' is not a permitted transition for any actor tier"],
  ["paused", "failed", "pipeline", "'paused' -> 'failed' is not a permitted transition for any actor tier"],
  ["paused", "failed", "send", "'paused' -> 'failed' is not a permitted transition for any actor tier"],
  ["paused", "failed", "schedule", "'paused' -> 'failed' is not a permitted transition for any actor tier"],
  ["paused", "failed", "compose", "'paused' -> 'failed' is not a permitted transition for any actor tier"],
  ["canceled", "draft", "pipeline", "'canceled' -> 'draft' is not a permitted transition for any actor tier"],
  ["canceled", "draft", "send", "'canceled' -> 'draft' is not a permitted transition for any actor tier"],
  ["canceled", "draft", "schedule", "'canceled' -> 'draft' is not a permitted transition for any actor tier"],
  ["canceled", "draft", "compose", "'canceled' -> 'draft' is not a permitted transition for any actor tier"],
  ["canceled", "scheduled", "pipeline", "'canceled' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["canceled", "scheduled", "send", "'canceled' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["canceled", "scheduled", "schedule", "'canceled' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["canceled", "scheduled", "compose", "'canceled' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["canceled", "sending", "pipeline", "'canceled' -> 'sending' is not a permitted transition for any actor tier"],
  ["canceled", "sending", "send", "'canceled' -> 'sending' is not a permitted transition for any actor tier"],
  ["canceled", "sending", "schedule", "'canceled' -> 'sending' is not a permitted transition for any actor tier"],
  ["canceled", "sending", "compose", "'canceled' -> 'sending' is not a permitted transition for any actor tier"],
  ["canceled", "sent", "pipeline", "'sent' may only be entered from 'sending'"],
  ["canceled", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["canceled", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["canceled", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["canceled", "paused", "pipeline", "'canceled' -> 'paused' is not a permitted transition for any actor tier"],
  ["canceled", "paused", "send", "'canceled' -> 'paused' is not a permitted transition for any actor tier"],
  ["canceled", "paused", "schedule", "'canceled' -> 'paused' is not a permitted transition for any actor tier"],
  ["canceled", "paused", "compose", "'canceled' -> 'paused' is not a permitted transition for any actor tier"],
  ["canceled", "canceled", "pipeline", "'canceled' -> 'canceled' is not a transition (no-op)"],
  ["canceled", "canceled", "send", "'canceled' -> 'canceled' is not a transition (no-op)"],
  ["canceled", "canceled", "schedule", "'canceled' -> 'canceled' is not a transition (no-op)"],
  ["canceled", "canceled", "compose", "'canceled' -> 'canceled' is not a transition (no-op)"],
  ["canceled", "failed", "pipeline", "'canceled' -> 'failed' is not a permitted transition for any actor tier"],
  ["canceled", "failed", "send", "'canceled' -> 'failed' is not a permitted transition for any actor tier"],
  ["canceled", "failed", "schedule", "'canceled' -> 'failed' is not a permitted transition for any actor tier"],
  ["canceled", "failed", "compose", "'canceled' -> 'failed' is not a permitted transition for any actor tier"],
  ["failed", "draft", "pipeline", "'failed' -> 'draft' is not a permitted transition for any actor tier"],
  ["failed", "draft", "send", "'failed' -> 'draft' is not a permitted transition for any actor tier"],
  ["failed", "draft", "schedule", "'failed' -> 'draft' is not a permitted transition for any actor tier"],
  ["failed", "draft", "compose", "'failed' -> 'draft' is not a permitted transition for any actor tier"],
  ["failed", "scheduled", "pipeline", "'failed' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["failed", "scheduled", "send", "'failed' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["failed", "scheduled", "schedule", "'failed' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["failed", "scheduled", "compose", "'failed' -> 'scheduled' is not a permitted transition for any actor tier"],
  ["failed", "sending", "pipeline", "'failed' -> 'sending' is not a permitted transition for any actor tier"],
  ["failed", "sending", "send", "'failed' -> 'sending' is not a permitted transition for any actor tier"],
  ["failed", "sending", "schedule", "'failed' -> 'sending' is not a permitted transition for any actor tier"],
  ["failed", "sending", "compose", "'failed' -> 'sending' is not a permitted transition for any actor tier"],
  ["failed", "sent", "pipeline", "'sent' may only be entered from 'sending'"],
  ["failed", "sent", "send", "only the send pipeline may set status to 'sent'"],
  ["failed", "sent", "schedule", "only the send pipeline may set status to 'sent'"],
  ["failed", "sent", "compose", "only the send pipeline may set status to 'sent'"],
  ["failed", "paused", "pipeline", "'failed' -> 'paused' is not a permitted transition for any actor tier"],
  ["failed", "paused", "send", "'failed' -> 'paused' is not a permitted transition for any actor tier"],
  ["failed", "paused", "schedule", "'failed' -> 'paused' is not a permitted transition for any actor tier"],
  ["failed", "paused", "compose", "'failed' -> 'paused' is not a permitted transition for any actor tier"],
  ["failed", "canceled", "pipeline", "'failed' -> 'canceled' is not a permitted transition for any actor tier"],
  ["failed", "canceled", "send", "'failed' -> 'canceled' is not a permitted transition for any actor tier"],
  ["failed", "canceled", "schedule", "'failed' -> 'canceled' is not a permitted transition for any actor tier"],
  ["failed", "canceled", "compose", "'failed' -> 'canceled' is not a permitted transition for any actor tier"],
  ["failed", "failed", "pipeline", "'failed' -> 'failed' is not a transition (no-op)"],
  ["failed", "failed", "send", "'failed' -> 'failed' is not a transition (no-op)"],
  ["failed", "failed", "schedule", "'failed' -> 'failed' is not a transition (no-op)"],
  ["failed", "failed", "compose", "'failed' -> 'failed' is not a transition (no-op)"],
];

test("transitionCampaignStatus: the full 7x7x4 status/tier matrix is unchanged", () => {
  assert.equal(MATRIX.length, 7 * 7 * 4, "matrix must stay exhaustive");

  const mismatches: string[] = [];
  for (const [from, to, actorTier, expected] of MATRIX) {
    const actual = transitionCampaignStatus({ from, to, actorTier });
    const actualOutcome: ExpectedOutcome = actual.allowed ? true : actual.reason;
    if (actualOutcome !== expected) {
      mismatches.push(`${from} -> ${to} as '${actorTier}': expected ${JSON.stringify(expected)}, got ${JSON.stringify(actualOutcome)}`);
    }
  }

  assert.deepEqual(mismatches, [], `transition authority changed:\n${mismatches.join("\n")}`);
});

test("transitionCampaignStatus: exactly nine (from, to, tier) triples are permitted", () => {
  const allowed = MATRIX.filter(([, , , expected]) => expected === true).map(([from, to, tier]) => `${from}->${to}:${tier}`);
  assert.deepEqual(allowed, [
    "draft->scheduled:schedule",
    "draft->canceled:compose",
    "scheduled->sending:pipeline",
    "scheduled->canceled:compose",
    "sending->sent:pipeline",
    "sending->paused:pipeline",
    "sending->paused:send",
    "paused->sending:pipeline",
    "paused->sending:send",
  ]);
});
