/**
 * @file BLIND doc2query output — 5 synthetic questions per tool, generated 2026-08-05 by a fresh
 * subagent (Claude Sonnet 5, general-purpose) given ONLY the 131-tool id+description catalog. It
 * never saw `tool-search-quality.eval.ts`'s `HELD_OUT_CASES` or any eval file, and was explicitly
 * instructed not to search for one.
 *
 * This replaces an earlier same-day attempt where the dispatching agent (having already read the
 * held-out set to build other canaries) wrote the questions itself and produced several
 * near-verbatim lifts of held-out query text — see the "Canary 1" section of
 * `ADS-memory/reports/analysis/2026-08-05-tool-search-canaries.md` for the full contamination
 * writeup. This file is the honest redo. Scored by `tool-search-doc2query-canary.eval.ts`.
 */
export const DOC2QUERY: Readonly<Record<string, readonly string[]>> = {
  collections_content_type_list: [
    "What content types do we have set up on the site?",
    "Where can I see all my content type schemas and their current version?",
    "Is the 'Recipe' content type still active or did someone retire it?",
    "I need the current version number for a content type before I edit it.",
    "Can you show me every content type, including old ones nobody uses anymore?",
  ],
  collections_content_type_define: [
    "How do I add a brand new content type to the CMS?",
    "We need a new kind of entry for 'Events' — how do I register that?",
    "Can you set up a new content model with its own fields?",
    "I want to create a custom content type from scratch.",
    "How do I register a new entry schema in the workspace?",
  ],
  collections_content_type_update_fields: [
    "I need to change the fields on an existing content type.",
    "How do I add a new field to the 'Product' content type?",
    "Can you replace the whole schema for this content type?",
    "The fields on our content type are wrong, how do I fix them?",
    "I want to overwrite the field list for a content type.",
  ],
  collections_content_type_deprecate: [
    "How do I stop people from creating new entries of a certain type?",
    "We don't want any more 'Legacy Post' entries made, can you retire that type?",
    "Can you mark this content type as deprecated?",
    "I want to phase out an old content type without deleting existing entries.",
    "How do I block new entries for a content type but keep the old ones?",
  ],
  collections_content_type_reactivate: [
    "I deprecated a content type by mistake, can you turn it back on?",
    "How do I bring back a retired content type?",
    "Can you make a deprecated content type active again?",
    "We need to start using that old content type again.",
    "How do I undo a content type deprecation?",
  ],
  collections_content_type_tombstone: [
    "How do I permanently get rid of a deprecated content type?",
    "Can you fully remove a content type and its indexes?",
    "We're done with this content type forever, how do I tear it down?",
    "How do I clean up the search indexes for an old content type?",
    "Is there a way to finalize deleting a content type that's already deprecated?",
  ],
  collections_entry_list: [
    "Show me all the entries for our 'Product' collection.",
    "What draft entries do we have in this collection type?",
    "Can I see a list of every entry, including unpublished ones?",
    "I want to browse the Collections list like the admin screen shows.",
    "What are the ids and slugs for entries under this content type?",
  ],
  collections_entry_create: [
    "How do I add a new entry to a collection?",
    "Can you create a draft record under the 'Testimonials' type?",
    "I need to add a new item with these field values.",
    "How do I make a new collection entry that isn't published yet?",
    "Can you create an entry but keep it as a draft for now?",
  ],
  collections_entry_update: [
    "How do I change the title on an existing collection entry?",
    "I need to update some fields on this entry without touching the rest.",
    "Can you fix the field values on this record?",
    "How do I edit an entry's data — will it fail if my version is out of date?",
    "I want to update just the fields I changed, not the whole entry.",
  ],
  collections_entry_publish: [
    "How do I make this draft entry go live?",
    "Can you publish this collection item?",
    "I want this entry visible on the site now.",
    "How do I flip a draft to published status?",
    "Can you set the publish date on this entry to right now?",
  ],
  collections_entry_unpublish: [
    "How do I take this entry down without deleting it?",
    "Can you pull this published item back to unpublished?",
    "I want to hide this entry from the site but keep it around.",
    "How do I revert something back to draft after publishing it?",
    "Can you unpublish this collection item temporarily?",
  ],
  comments_list_moderation_queue: [
    "What comments are waiting for me to approve?",
    "Show me the pending comments queue.",
    "Are there any comments stuck in moderation right now?",
    "I need the id of a comment before I can approve it.",
    "Can you list comments that were marked as spam so I can review them?",
  ],
  comments_get_settings: [
    "What are our current comment moderation settings?",
    "Is comment approval required before comments show up?",
    "How many comments can one visitor post per hour right now?",
    "What's our spam auto-reject threshold set to?",
    "Do we have comments closed after a certain number of days?",
  ],
  comments_update_settings: [
    "Can you turn on comment moderation for the site?",
    "I want to change how deep a nested reply thread can go.",
    "Can you raise the spam score threshold for auto-rejecting comments?",
    "How do I set comments to close automatically after 30 days?",
    "Can you limit how many comments one IP can post per hour?",
  ],
  comments_approve_comment: [
    "Can you approve this comment so it shows up publicly?",
    "This comment got flagged as spam but it's legit, can you approve it?",
    "How do I let this pending comment through?",
    "Can you make this comment visible to visitors?",
    "I want to unhide a trashed comment by approving it.",
  ],
  comments_mark_comment_spam: [
    "This comment looks like spam, can you hide it?",
    "How do I flag a comment as junk?",
    "Can you mark this as spam so it's not shown publicly?",
    "I need to hide an obviously fake comment.",
    "How do I mark a bad comment without deleting it permanently?",
  ],
  comments_trash_comment: [
    "Can you delete this comment?",
    "How do I remove a rude comment from the site?",
    "I want to trash a comment but be able to bring it back later.",
    "Can you soft-delete this comment?",
    "How do I hide a comment without permanently losing it?",
  ],
  comments_restore_comment: [
    "I trashed a comment by accident, can you bring it back?",
    "Can you undo marking this comment as spam?",
    "How do I restore a comment I deleted?",
    "Can you make a spam comment approved again?",
    "I want to recover a comment from the trash.",
  ],
  content_post_search: [
    "Where's the page about our pricing on the site?",
    "I don't know the exact URL, can you find the post that mentions refunds?",
    "Search our posts and pages for anything about shipping.",
    "Can you find a page by what it's about instead of its title?",
    "What page or post talks about our return policy?",
  ],
  content_post_list: [
    "Show me every post we have, drafts included.",
    "Can I get the full inventory of pages on the site?",
    "List every draft and published post.",
    "Give me the complete body text for all our pages.",
    "How many posts do we have total?",
  ],
  content_post_get: [
    "Can you open up this specific post's full content?",
    "I have the id, show me the whole page body.",
    "Show me the details of this one page including its current version.",
    "Can you pull up the full text of this post by its id?",
    "I want to read the complete content of one page, not a summary.",
  ],
  content_post_create: [
    "Can you draft a new blog post for me?",
    "How do I create a new page on the site?",
    "Can you make a new post that's published right away?",
    "I need a new page with this title, and can the URL be auto-generated?",
    "How do I add a brand-new post to the site?",
  ],
  content_post_update: [
    "Can you change the title of this page?",
    "I need to edit the whole content of this post.",
    "How do I publish this post by updating its status?",
    "Can you rewrite this page's body and slug at the same time?",
    "How do I take a live post back to draft?",
  ],
  content_post_delete: [
    "Can you delete this blog post?",
    "How do I remove a page from the site?",
    "I want to trash this post — will someone need to confirm it?",
    "Can you get rid of this old page for me?",
    "How do I delete a post that's cluttering the list?",
  ],
  database_query_timeline: [
    "What's the history of migrations and restores on our database?",
    "Can you show me a timeline of everything that's happened to the database?",
    "Was there an interrupted migration recently?",
    "I want to see the past database snapshots in order.",
    "What database events happened most recently?",
  ],
  database_list_restore_points: [
    "What restore points do we have for the database?",
    "When was the last database backup point taken?",
    "Can you list all the snapshots I could roll back to?",
    "How many restore points exist and what triggered them?",
    "Show me the database recovery points available.",
  ],
  database_get_health: [
    "Is the database okay right now?",
    "Are we running low on disk space for the database?",
    "Is there a stuck or pending migration I should worry about?",
    "Can you check if the database is connected and healthy?",
    "Is anything wrong with the database at the moment?",
  ],
  database_get_schema_state: [
    "Is our database schema out of sync with what it should be?",
    "Has the database schema drifted from the expected version?",
    "Is the database ahead or behind on schema changes?",
    "Can you check if our schema matches the saved snapshot?",
    "Do we need to run a migration to fix schema drift?",
  ],
  database_list_pending_migrations: [
    "Are there any database migrations waiting to be applied?",
    "What updates haven't been run on the database yet?",
    "Can you show me the migrations that are queued but not done?",
    "Is there pending schema work I need to apply?",
    "What migrations are outstanding right now?",
  ],
  database_plan_migrate_forward: [
    "What would happen if I ran the pending migrations right now?",
    "Can you preview the migration before actually running it?",
    "How much would it cost to migrate the schema forward?",
    "I want to see the plan for a forward migration without applying it.",
    "Can you dry-run the schema migration first?",
  ],
  forms_list_definitions: [
    "What forms do we have set up on the site?",
    "I need the id for our contact form before I can edit it.",
    "Show me all our form definitions and how many fields each has.",
    "Which forms are active versus disabled?",
    "Can you list every form by name and slug?",
  ],
  forms_create_definition: [
    "How do I build a new contact form?",
    "Can you set up a new form with a specific URL slug?",
    "I want to create a signup form with these fields.",
    "How do I add a brand-new form to the site?",
    "Can you make a new form definition — can the slug ever change later?",
  ],
  forms_update_definition: [
    "Can you add a new field to our existing form?",
    "I need to change who gets notified when this form is submitted.",
    "Can you rename this form without changing its URL?",
    "How do I edit the fields on a form I already made?",
    "Can I remove a field from a form, or does that get blocked?",
  ],
  forms_set_definition_status: [
    "How do I turn off a form so people can't submit it anymore?",
    "Can you disable this old form?",
    "Is there a way to delete a form, or just disable it?",
    "How do I re-enable a form I turned off earlier?",
    "Can you take this form out of service?",
  ],
  forms_list_submissions: [
    "What submissions have come in on our contact form?",
    "Can you show me the latest form entries, newest first?",
    "Who submitted this form and when?",
    "I want to see all the responses to our survey form.",
    "Show me the IP addresses on recent form submissions.",
  ],
  forms_get_submission: [
    "Can you pull up the full details of one specific form submission?",
    "I have a submission id, show me everything that was submitted.",
    "What did this particular visitor fill out on the form?",
    "Can you show me the exact time and IP for this one submission?",
    "I need to look at a single form response in detail.",
  ],
  identity_user_list: [
    "Who are the admin users on this site?",
    "Can you show me everyone with access to the admin panel?",
    "I need a user's id before I can change their role.",
    "What roles does each operator currently have?",
    "Show me which admin accounts are active versus disabled.",
  ],
  identity_role_list: [
    "What roles exist in our workspace?",
    "Can you show me the built-in roles plus any custom ones we made?",
    "I need the role id before I can assign it to someone.",
    "What are all the permission roles available?",
    "List the roles so I know what I can assign to a new hire.",
  ],
  identity_policy_list: [
    "What permission policies do we have set up?",
    "Can you show me which policies are frozen and can't be changed?",
    "I need a policy id before I can attach it to a user.",
    "What custom policies exist besides the built-in ones?",
    "List all the access policies in the workspace.",
  ],
  identity_user_create: [
    "How do I add a new admin user?",
    "Can you create a login for a new team member?",
    "I want to set up a new operator account — will they have any permissions right away?",
    "How do I make a new user account with a username and password?",
    "Can you create a brand new principal for someone joining the team?",
  ],
  identity_user_update_email: [
    "Can you update this admin's email address?",
    "How do I remove the email on file for a user?",
    "I need to change the contact email for one of our operators.",
    "Can you set a new email for this account? Can I also change their password here?",
    "How do I clear out a stored email address for a user?",
  ],
  identity_user_disable: [
    "How do I revoke someone's admin access?",
    "Can you lock out a former employee from the admin panel?",
    "I want to disable a user but not delete their account.",
    "Can you remove the owner's access? What if there's no other owner?",
    "How do I deactivate an admin account that's already inactive?",
  ],
  identity_user_enable: [
    "Can you turn a disabled admin account back on?",
    "How do I restore access for someone I locked out earlier?",
    "I need to re-enable a user I disabled by mistake.",
    "Can you reactivate this operator's login?",
    "How do I give a disabled user their access back?",
  ],
  identity_role_create: [
    "How do I make a custom role for our team?",
    "Can you create a new role called 'Editor'? Will it have any permissions right away?",
    "I want a new permission group that starts empty.",
    "How do I set up a brand-new custom role?",
    "Can you add a new role I can assign later?",
  ],
  identity_role_assign: [
    "Can you give this user the Editor role?",
    "How do I grant admin access to a new team member?",
    "I want to assign a role to a user — can I give them more power than I have myself?",
    "How do I actually grant permissions to someone by role?",
    "Can you assign the moderator role to this account?",
  ],
  identity_role_rename: [
    "Can you rename this custom role?",
    "How do I change the label on one of our roles?",
    "Can I rename the built-in 'Viewer' role to something else?",
    "I want to give a custom role a clearer name.",
    "How do I relabel a role we created?",
  ],
  identity_role_delete: [
    "Can you delete a custom role we don't use anymore?",
    "How do I remove a role, and what happens if someone still has it?",
    "Can I delete one of the built-in roles?",
    "I want to get rid of an unused permission role.",
    "Why can't I delete this role — is it still assigned to someone?",
  ],
  identity_policy_create: [
    "How do I create a new permission policy?",
    "Can you set up a custom policy — does it have any permissions to start?",
    "I want to make a new policy I can attach to users later.",
    "How do I add a brand-new access policy?",
    "Can you create an empty policy for me to configure?",
  ],
  identity_policy_update: [
    "Can you rename this policy?",
    "How do I update the description on a custom policy?",
    "Can I edit a built-in or frozen policy?",
    "I want to change the name and description of a policy.",
    "How do I edit the label on a policy I created?",
  ],
  identity_policy_delete: [
    "Can you delete this custom policy?",
    "Why can't I remove a policy that's still attached to someone?",
    "How do I get rid of an unused permission policy?",
    "Can I delete a built-in or frozen policy?",
    "I want to clean up a policy nobody needs anymore.",
  ],
  identity_policy_attach: [
    "Can you directly grant this policy to a user, no role needed?",
    "How do I attach a permission policy straight to someone's account?",
    "I want to give this user extra permissions from a policy — can I detach it later?",
    "Can I attach a policy that's more powerful than my own access?",
    "How do I grant a specific policy to one named user?",
  ],
  webhooks_list_subscriptions: [
    "What webhooks do we have set up?",
    "Can you show me our integration subscriptions and their last delivery?",
    "I need to see which webhooks are active.",
    "List all our outbound webhook connections.",
    "What integrations are currently configured?",
  ],
  webhooks_get_deliveries: [
    "Did our webhook actually fire successfully?",
    "Can you show me the delivery log for this webhook?",
    "Why did this integration fail — what was the last response?",
    "I want to see all the delivery attempts for one webhook subscription.",
    "How many times has this webhook retried?",
  ],
  webhooks_create_subscription: [
    "Can you set up a new webhook for us?",
    "How do I add an integration that starts active?",
    "I need a new webhook subscription — where do I get the signing secret?",
    "Can you create a new outbound webhook connection?",
    "How do I wire up a new integration endpoint?",
  ],
  webhooks_pause_subscription: [
    "Can you pause this webhook so it stops sending?",
    "How do I temporarily stop an integration from firing?",
    "Can you resume a webhook I paused earlier?",
    "I want to turn off deliveries for this subscription without deleting it.",
    "Can I pause and later resume the same webhook with one tool?",
  ],
  webhooks_delete_subscription: [
    "Can you remove this webhook subscription?",
    "How do I delete an integration we don't use anymore?",
    "I want to disable a webhook permanently.",
    "Can you deactivate this integration subscription?",
    "What happens if I try deleting a webhook that's already deleted?",
  ],
  media_list_assets: [
    "Show me all the images in our media library.",
    "I need the id of an image before I can edit its alt text.",
    "Can you list every uploaded file, including trashed ones?",
    "What media assets do we have and what are their checksums?",
    "Show me our full media library.",
  ],
  media_upload_asset: [
    "Can you upload this image to the media library?",
    "How do I add a new photo to our site's media?",
    "Can I upload an SVG file? What about a file that's too big?",
    "How do I add a new image from a base64 file?",
    "If I upload the same picture twice, does it create two entries?",
  ],
  media_update_metadata: [
    "Can you change the alt text on this image?",
    "How do I update the caption for a media file?",
    "Can I edit the credit line on this photo?",
    "I want to change the title of an uploaded image — can I replace the actual file this way?",
    "How do I fix the metadata on an existing media asset?",
  ],
  media_trash_asset: [
    "Can you delete this image from the media library?",
    "How do I remove a file I no longer need?",
    "Is there a way to permanently purge a media asset, or just trash it?",
    "I want to soft-delete this photo.",
    "What happens if I try to trash an image that's already trashed?",
  ],
  media_generate_asset: [
    "Can you generate an image of a red bicycle for me?",
    "I need a logo — can you create one with AI?",
    "Generate a hero banner image for the homepage.",
    "Draw me an illustration of a mountain landscape.",
    "Can you make an AI image and add it to the media library?",
  ],
  media_import_from_url: [
    "Can you save the image at this link into our media library?",
    "I have a URL for a picture — how do I get it into the CMS?",
    "Download this image from the web and add it to our media files.",
    "Another tool gave me a link to an image it made. Can you import it?",
    "How do I add a photo that lives on someone else's site or CDN?",
  ],
  members_list: [
    "Who are our site members right now?",
    "Can you show me pending, active, and disabled members?",
    "I need a member's id before I can look at their details.",
    "List everyone who's signed up as a member.",
    "Show me our member roster.",
  ],
  members_get_by_id: [
    "Can you pull up this one member's full details?",
    "I have the member id, show me their info.",
    "What does this specific member's record look like?",
    "Can you show me one member's account details?",
    "I want to check a single member's status.",
  ],
  members_disable: [
    "Can you revoke this member's access?",
    "How do I kick a member out and end their sessions?",
    "I want to disable a member's account.",
    "Can I re-enable a member after disabling them?",
    "What happens if I disable a member who's already disabled?",
  ],
  members_request_magic_link: [
    "Can you resend the sign-in link to this member?",
    "This member says they can't log in, can you send them a fresh link?",
    "How do I trigger a passwordless login email for a member?",
    "Can you resend a magic link even if I'm not sure the email is registered?",
    "Is there a rate limit on resending sign-in links?",
  ],
  menus_list_menus: [
    "What menus do we have set up on the site?",
    "Can you show me all our navigation menus and where they're placed?",
    "I need to see the current version of a menu before editing it.",
    "List every menu with its status and item tree.",
    "Show me the menus and what locations they're assigned to.",
  ],
  menus_get_menu: [
    "Can you show me the full item tree for this one menu?",
    "I have a menu id, pull up its details.",
    "What items are in this specific menu right now?",
    "Show me one menu's structure and version number.",
    "Can I see the current layout of our main navigation menu?",
  ],
  menus_create_menu: [
    "How do I create a new navigation menu?",
    "Can you make a new menu — will it show up on the site right away?",
    "I want to build a draft menu before assigning it anywhere.",
    "Can you create a menu with a unique slug?",
    "How do I start a brand-new menu from scratch?",
  ],
  menus_update_menu_tree: [
    "Can you rearrange the items in this menu?",
    "I need to replace the whole structure of a menu.",
    "How do I add a new link to an existing menu — do I need to list everything else too?",
    "Can you rename this menu while you're updating its items?",
    "How do I edit a menu's item tree?",
  ],
  menus_assign_location: [
    "How do I put this menu in the header?",
    "Can you assign this menu to the footer location?",
    "If another menu is already in that spot, what happens to it?",
    "How do I make a menu actually show up on the live site?",
    "Can you swap which menu is bound to the primary navigation slot?",
  ],
  newsletter_list_campaigns: [
    "What email campaigns do we have going?",
    "Can you show me our draft newsletters?",
    "I need a campaign's id before I can edit it.",
    "List all our newsletter campaigns by status.",
    "What campaigns have we sent or scheduled?",
  ],
  newsletter_get_campaign: [
    "Can you show me the full details of this one campaign?",
    "What's the current status and delivery count for this newsletter?",
    "I have a campaign id, pull up everything about it.",
    "How many emails has this campaign actually sent so far?",
    "Show me one campaign's full info.",
  ],
  newsletter_list_lists: [
    "What subscriber lists do we have?",
    "I need a list id before creating a new campaign.",
    "Can you show me all our newsletter lists?",
    "What are the names of our mailing lists?",
    "List every subscriber list in the workspace.",
  ],
  newsletter_list_subscriptions: [
    "Who's subscribed to this particular list?",
    "Can you show me the subscribers on our main mailing list?",
    "I want to see everyone signed up for a specific newsletter list.",
    "Show me the subscription records for one list.",
    "How many people are on this mailing list?",
  ],
  newsletter_list_send_log: [
    "Did everyone actually receive this newsletter?",
    "Can you show me the delivery log for this campaign, email by email?",
    "Who didn't get this newsletter and why?",
    "I want to see the per-recipient send status for a campaign.",
    "How many attempts did it take to deliver to each subscriber?",
  ],
  newsletter_create_campaign: [
    "Can you draft a new email newsletter?",
    "How do I start a new campaign — will it send automatically?",
    "I want to create a newsletter draft I can edit later.",
    "Can you set up a new campaign in draft status?",
    "How do I begin a new email blast without sending it yet?",
  ],
  newsletter_update_campaign: [
    "Can you change the subject line on this draft newsletter?",
    "I need to edit the from-email and reply-to on a campaign.",
    "Can I still edit this campaign once it's scheduled?",
    "How do I update the preheader text on a draft?",
    "Can you switch which list this campaign is going to?",
  ],
  newsletter_cancel_campaign: [
    "Can you cancel this newsletter before it sends?",
    "I want to stop a scheduled campaign from going out.",
    "Can I cancel a campaign that's already sending?",
    "How do I pull the plug on a draft campaign permanently?",
    "Can you take this campaign out of the send pipeline entirely?",
  ],
  newsletter_pause_campaign: [
    "Can you stop this newsletter that's currently sending?",
    "How do I halt an in-progress campaign send?",
    "Once I pause a campaign, can I resume it later?",
    "I need to stop outbound mail on this campaign right now.",
    "Can you pause a campaign that's already fully sent?",
  ],
  newsletter_create_list: [
    "Can you create a new subscriber list?",
    "How do I set up a new mailing list with its own slug?",
    "I want a fresh list for a specific audience segment.",
    "Can a brand-new list become the default one automatically?",
    "How do I make a new newsletter list?",
  ],
  newsletter_archive_list: [
    "Can you archive this old subscriber list?",
    "How do I retire a mailing list we don't use anymore?",
    "Can I archive our default 'all subscribers' list?",
    "I want to get rid of an unused list.",
    "How do I shelve a subscriber list?",
  ],
  newsletter_create_subscription: [
    "Can you add this member to our newsletter list?",
    "How do I subscribe an existing member — do they need to confirm it?",
    "I want to add someone to a mailing list and send them a confirmation.",
    "Can this also send them marketing content right away?",
    "How do I sign up an existing member for a specific list?",
  ],
  newsletter_remove_subscription: [
    "Can you unsubscribe this person from the list?",
    "How do I remove a subscription by its id?",
    "What happens if I try to unsubscribe someone who's already unsubscribed?",
    "I want to take someone off a mailing list.",
    "Can you cancel this subscriber's spot on the list?",
  ],
  newsletter_resend_confirmation: [
    "This subscriber never got their confirmation email, can you resend it?",
    "Can you send a fresh double opt-in link, invalidating the old one?",
    "How do I resend the confirmation for a pending subscription?",
    "What happens if I try resending confirmation for an unknown subscription?",
    "Can you re-trigger the opt-in email for someone who lost it?",
  ],
  plugins_list: [
    "What plugins are installed on the site?",
    "Can you show me which plugins are enabled versus disabled?",
    "Is there a plugin with a validation error I should know about?",
    "What's the trust tier on this third-party plugin?",
    "Show me every discovered plugin, built-in and site-installed.",
  ],
  plugins_set_enabled: [
    "Can you turn on this plugin?",
    "How do I disable a plugin we don't want running?",
    "Why won't this plugin enable — is it invalid or incompatible?",
    "Will enabling this plugin change our database schema?",
    "Can you toggle this plugin off?",
  ],
  recovery_get_status: [
    "Is there anything wrong with our database recovery state right now?",
    "Is a migration currently stuck or interrupted?",
    "What's our current restore-point cost class?",
    "Is there an operation already in progress I should wait for?",
    "Are we missing a baseline watermark for recovery?",
  ],
  recovery_resolve_deep_link: [
    "Is this restore-point link still valid, or was it faked?",
    "Can you double check this deep link actually points to a real restore point?",
    "Someone sent me a database timeline link, is it legit?",
    "How do I verify a restore point id from a link instead of trusting it blindly?",
    "Can you re-resolve this link server-side to make sure it's not stale?",
  ],
  redirects_list: [
    "What redirects do we have set up on the site?",
    "Can you show me only the active redirect rules?",
    "I need to see redirects filtered by source URL.",
    "List all our URL redirect rules.",
    "What redirects are currently disabled?",
  ],
  redirects_get: [
    "Can you show me the details of this one redirect rule?",
    "I have a redirect id, pull up its info.",
    "What does this specific redirect rule point to?",
    "Show me one redirect's source and target.",
    "Can you fetch a single redirect by id?",
  ],
  redirects_get_hits: [
    "How many times has this redirect actually been used?",
    "When was the last time someone hit this redirect?",
    "I want to see traffic stats for a specific redirect.",
    "Has anyone even used this redirect rule?",
    "Can you show me the hit count for this redirect?",
  ],
  redirects_create: [
    "Can you set up a new redirect from the old URL to the new one?",
    "How do I create a redirect — will it stop me from making a loop?",
    "Can you add a redirect rule, or will it reject an unsafe target?",
    "I need a new URL forwarding rule.",
    "What happens if I try to create a duplicate redirect for the same source?",
  ],
  redirects_update: [
    "Can you change where this redirect points to?",
    "I need to edit just the target URL on an existing redirect.",
    "How do I update a redirect rule's status?",
    "Can you fix a broken redirect without recreating it?",
    "How do I change one field on a redirect and leave the rest alone?",
  ],
  redirects_tombstone: [
    "Can you disable this redirect rule?",
    "How do I turn off a redirect without deleting its history?",
    "I want to soft-delete a redirect we don't need anymore.",
    "What happens if I try to disable a redirect that's already disabled?",
    "Can you retire an old redirect rule for audit purposes?",
  ],
  seo_get_entry_meta: [
    "What SEO title and description is actually showing for this page?",
    "Can you show me the effective meta tags for this entry?",
    "What's the resolved Open Graph and Twitter card data for this page?",
    "I want to see the final SEO values after overrides are applied.",
    "What does the JSON-LD look like for this specific entry?",
  ],
  seo_analyze_entry: [
    "How's this page's SEO score?",
    "What SEO issues does this page have, like a missing description?",
    "Can you audit this entry's search-engine metadata?",
    "Is this page missing anything important for SEO?",
    "Can you grade this page's SEO out of 100?",
  ],
  seo_set_entry_overrides: [
    "Can you set a custom SEO title for just this one page?",
    "I want to override the meta description on this entry.",
    "How do I mark this page as noindex?",
    "Can you set a canonical URL for this entry — does that also refresh the sitemap?",
    "How do I override SEO fields for one page without touching the site defaults?",
  ],
  seo_get_settings: [
    "What are our site-wide SEO defaults?",
    "What's our default Open Graph image set to?",
    "Is the sitemap toggle turned on for the whole site?",
    "What do our robots.txt custom rules look like?",
    "What's the title template applied across all pages?",
  ],
  seo_set_settings: [
    "Can you update our default meta description for the whole site?",
    "How do I change the site-wide title template?",
    "Can you turn off the sitemap for the whole site?",
    "I want to update our robots.txt rules — will it fail entirely if one field is wrong?",
    "How do I set a new default social share image sitewide?",
  ],
  seo_regenerate_sitemap: [
    "Can you force the sitemap to rebuild right now?",
    "Our sitemap seems stale, can you refresh it?",
    "How do I bypass the sitemap cache and regenerate it immediately?",
    "Can you rebuild the sitemap without losing any entries?",
    "I just changed a bunch of pages, can you regenerate the sitemap now?",
  ],
  settings_list_definitions: [
    "What settings are available in this workspace?",
    "Can you show me every setting definition, platform and site-owned?",
    "I want to see setting keys and their current status, not values.",
    "What namespace do our settings live under?",
    "List all the active setting definitions we can configure.",
  ],
  settings_get_effective: [
    "What's the actual value being used for this setting right now?",
    "Can you resolve the final setting value after all the overrides?",
    "What settings apply to me as a user versus the whole workspace?",
    "I want the effective, precedence-resolved values for a namespace.",
    "What's the value that actually wins between global, workspace, and user settings?",
  ],
  settings_get_raw: [
    "Can you show me the raw values for this setting at every layer?",
    "What's the workspace-level value versus the global default for this setting?",
    "I want to see all the unresolved layers for one setting key.",
    "Can you break down this setting by global, workspace, user, and default?",
    "Before precedence is applied, what does each layer say for this setting?",
  ],
  settings_set_ui_preference: [
    "Can you switch my admin panel to dark theme?",
    "How do I change my interface language in the admin UI?",
    "Can you turn off notification sounds for me?",
    "I want to change my own accent color in the admin panel.",
    "Can this change another operator's preferences, or just mine?",
  ],
  taxonomy_list: [
    "What categories and tags do we have?",
    "Can you show me all our taxonomies and their terms?",
    "I want to see the full category and tag structure.",
    "What terms exist under each taxonomy?",
    "Show me everything on the Categories and Tags screen.",
  ],
  taxonomy_create_taxonomy: [
    "Can you create a new tag group?",
    "How do I set up a new hierarchical category taxonomy?",
    "I want a flat taxonomy for simple tags, not a nested one.",
    "Can you add a brand-new taxonomy to the workspace?",
    "How do I create a new grouping system for content?",
  ],
  taxonomy_create_term: [
    "Can you add a new tag under this taxonomy?",
    "How do I create a subcategory under an existing category?",
    "Can you add a term with a parent — does it check the parent is in the same taxonomy?",
    "I want to add a new term to our category list.",
    "How do I create a new tag term?",
  ],
  taxonomy_rename_term: [
    "Can you rename this tag?",
    "How do I fix a typo in a category name?",
    "Can you relabel a term without changing its parent or taxonomy?",
    "I want to rename an existing term in place.",
    "How do I change the display name of a category?",
  ],
  taxonomy_assign_terms: [
    "Can you tag this post with a couple categories?",
    "How do I assign tags to a piece of content?",
    "If I assign the same tag twice, does it duplicate?",
    "Can this remove tags too, or only add them?",
    "How do I attach existing terms to a collection entry?",
  ],
  taxonomy_plan_merge_term: [
    "What would happen if I merged these two tags together?",
    "Can you preview a term merge before actually doing it?",
    "How much overlap is there between these two categories if I merge them?",
    "Can this tool actually perform the merge, or just show me what would happen?",
    "What content would lose its duplicate tag assignment if I merge these terms?",
  ],
  theme_list: [
    "What themes do we have installed?",
    "Is our current theme valid, or does it have errors?",
    "Can you show me the theme id I need for other theme tools?",
    "What's the validation status of each theme?",
    "List every theme available on the site.",
  ],
  theme_list_files: [
    "What files does this theme actually have?",
    "Can you show me the folder structure of a theme?",
    "I want to see what templates exist before I edit one.",
    "What's inside the theme's templates folder?",
    "Can you list the files in a theme without guessing filenames?",
  ],
  theme_read_file: [
    "Can you show me the contents of this theme file?",
    "I want to read the home template's Liquid code.",
    "Can you open theme.json for this theme?",
    "Show me the raw text of one file inside the theme.",
    "Can I read a file from outside the theme's own folder?",
  ],
  theme_write_file: [
    "Can you update this theme template for me?",
    "How do I edit a theme file — does it check for errors after saving?",
    "I want to overwrite a template file completely, not patch it.",
    "What happens to the live site if I write invalid code to a theme file?",
    "Can you create a new file inside the theme folder?",
  ],
  widgets_list_instances: [
    "What widgets do we have set up on the site?",
    "Can you show me only active widgets, not trashed ones?",
    "I want to filter widgets by type.",
    "Show me every widget instance and its current config.",
    "What widgets are currently active in the workspace?",
  ],
  widgets_get_instance: [
    "Where is this widget actually being used on the site?",
    "Can you show me one widget's config and everywhere it's placed?",
    "I want to see a widget's current state plus its region placements.",
    "Is this widget embedded inline anywhere?",
    "Can you show me the full details for a single widget instance?",
  ],
  widgets_list_regions: [
    "What widget regions are currently bound on the site?",
    "Can you show me each region and how many widgets are placed there?",
    "I want to see which theme areas have widgets assigned.",
    "Are there any regions that got orphaned after a theme switch?",
    "What widget slots exist right now?",
  ],
  widgets_get_region: [
    "What widgets are placed in this specific region?",
    "Can you show me if any widget in this region is broken?",
    "I need the current version of a region before I update its placements.",
    "What's actually filling the sidebar widget area right now?",
    "Is a widget in this region missing or the wrong type?",
  ],
  widgets_create_instance: [
    "Can you create a new widget?",
    "How do I make a new widget instance with a specific config?",
    "If I create a widget, does it automatically show up on the site?",
    "I want to set up a new widget of a certain type.",
    "Can you validate a widget's config against its schema when creating it?",
  ],
  widgets_update_instance: [
    "Can you change the settings on this existing widget?",
    "How do I edit a widget's config?",
    "Can I change what type this widget is?",
    "I want to replace a widget's configuration entirely.",
    "How do I update the content inside a widget instance?",
  ],
  widgets_trash_instance: [
    "Can you delete this widget?",
    "What happens to the places this widget is used if I trash it?",
    "How do I remove a widget instance — is it a hard delete?",
    "Can I trash a widget even if it's currently placed somewhere?",
    "Is there a way to permanently purge a widget, or just trash it?",
  ],
  widgets_bind_region: [
    "How do I set up a new widget area?",
    "Can you bind a new region key for widgets?",
    "If I bind a region that already exists, does it create a duplicate?",
    "I want to create an empty widget slot to fill later.",
    "How do I register a new widget region on the theme?",
  ],
  widgets_set_region_placements: [
    "How do I change which widgets show up in the sidebar?",
    "Can you replace the whole list of widgets in this region?",
    "What happens if I reference a widget that's trashed in the placement list?",
    "I need to see the current placements before I overwrite them, right?",
    "How do I reorder or swap out widgets in a region all at once?",
  ],
  widgets_insert_embed: [
    "Can you embed a widget inside this post's body?",
    "How do I add an inline widget to a page's content?",
    "Can I put a widget inside another widget?",
    "What happens if I try to embed too many widgets in one document?",
    "How do I insert a widget reference into the middle of a page?",
  ],
  widgets_remove_embed: [
    "Can you remove this inline widget from the page body?",
    "How do I delete one embedded widget without deleting the widget itself?",
    "I want to take out a widget embed by its placement id.",
    "Can you pull a widget out of the page content?",
    "How do I remove an inline widget slot from an entry?",
  ],
  widgets_reorder_embeds: [
    "Can you swap which widget shows in each embed slot?",
    "How do I change the widgets assigned to existing embed slots without changing the layout?",
    "I want to reassign what fills each inline widget spot in a document.",
    "Can this add new embed slots, or only reshuffle existing ones?",
    "Do I need to specify a widget for every single slot, or can I skip some?",
  ],
  workspace_get: [
    "What's our workspace's name and id?",
    "Can you show me when this workspace was created?",
    "What's our current workspace slug?",
    "I want basic info about our own workspace.",
    "Do we have more than one workspace here?",
  ],
  workspace_update: [
    "Can you rename our workspace?",
    "How do I change the workspace's URL slug?",
    "Will renaming the workspace affect anything else?",
    "Can I update just the name and leave the slug alone?",
    "How do I change our site's workspace name?",
  ],
  backup_create_restore_point: [
    "Can you create a manual backup point right now?",
    "I want a new restore point outside of any migration.",
    "Does creating a backup point require me to acknowledge a cost first?",
    "Can you snapshot the database state as it is now?",
    "How do I make a fresh restore point on demand?",
  ],
  backup_list_restore_points: [
    "What backup points do we have for this site?",
    "Can you list restore points newest first with what triggered them?",
    "How many restore points are there and what's their cost class?",
    "Show me all our site's snapshots.",
    "What restore points can I choose from?",
  ],
  backup_get_capabilities: [
    "How expensive would restoring from backup be for this site?",
    "What mechanism does our backup system use?",
    "What's the cost class for restore points on this site?",
    "Can you tell me what kind of restore capability we have?",
    "Before I restore anything, what would it cost?",
  ],
  backup_plan_restore: [
    "If I restore to this point, what would actually change?",
    "Can you preview a restore before I commit to it?",
    "How much data would I lose if I restored to this backup point?",
    "What's the discarded-write window if I roll back to this restore point?",
    "Can you show me what a restore would do without actually doing it?",
  ],

  // --- custom-credentials (2026-09-01) — added alongside the TOOL_SEARCH_KEYWORDS entries above, for
  // the same reason: `custom_credential_verify`/`custom_credential_make_request` shipped with no
  // search coverage at all and went unfound in a real session. See `tool-search-keywords.ts`'s own
  // entries for the full incident context.
  custom_credential_list: [
    "What credentials do I have saved?",
    "Do I have an API key or token saved for name.com?",
    "What did I save for fly.io — is there already a token for that?",
    "What third-party accounts or providers are connected to this site?",
    "Before I use curl for this, is there already a saved credential I should use instead?",
  ],
  custom_credential_verify: [
    "Is my fly.io token still valid?",
    "Can you check if this saved API key still works?",
    "Has my name.com credential expired or been revoked?",
    "Test whether this saved token is still good before I rely on it.",
    "Why did my last request through a saved credential fail — is the credential itself the problem?",
  ],
  custom_credential_make_request: [
    "Can you call the name.com API using my saved credential instead of curl?",
    "Make a request to my fly.io account using the token I already saved.",
    "I need to hit a third-party API with my saved credential — can you do that instead of shelling out?",
    "Can you check my domain's DNS records using the registrar credential I saved?",
    "Use my saved deployment provider token to make an authenticated request to their API.",
  ],

  // --- pages, bespoke HTML (2026-09-09) — added alongside the TOOL_SEARCH_KEYWORDS entries above.
  // The pages_* family shipped with NO doc2query coverage at all: this file was generated 2026-08-05
  // against the then-current catalog, and the tools postdate it. Written from what each tool IS, per
  // this file's own header, and — because the whole point of `pages_write_region` is to stop the
  // model reaching for the full rewriter — written to keep the pair APART: no "whole page" phrasing
  // in the region questions, no "just this section" phrasing in the rewrite questions.
  pages_read_html: [
    "What HTML is actually on our landing page right now?",
    "Show me the current markup for this page before I change anything.",
    "Which parts of this page can be edited separately?",
    "What are the editable section handles on this page?",
    "I need this page's current version number before I edit it.",
  ],
  pages_write_html: [
    "Build me a landing page for our new product.",
    "Replace this page's whole body with a completely new design.",
    "Start this page over from scratch — throw away what's there.",
    "I want to restructure the page and add two new sections.",
    "Create the full HTML for a bespoke page on our site.",
  ],
  pages_write_region: [
    "Just change the headline on our landing page, leave the rest alone.",
    "Update the pricing section of this page without touching anything else.",
    "Can you reword the call to action but keep the page as it is?",
    "Edit one section of a page instead of rewriting the whole thing.",
    "I want to swap out the hero copy on this page and nothing more.",
  ],
};
